### ISSUE TITLE
Fractional exponents are not being shown

### ISSUE THREAD

**Issue by TomasRiker** [andrejv/wxmaxima#1000]
I'm running the latest nightly wxMaxima on a 4K screen (150% UI scaling as recommended by Windows 10). Fractional exponents are not being shown any more, as can be seen in the screenshot below. It doesn't matter if I tick the two checkboxes regarding jsMath and Unicode symbols, the exponents are always missing. The fonts that ship with wxMaxima are installed. Any ideas? (please ignore the warning regarding the documentation - I'm running my own Maxima, not the one that comes with the wxMaxima bundle)

**Update 1:** I see now that the exponents are actually being rendered at the wrong position, namely in the top left corner of the window. If you look closely, you see some pixels there (see red arrow in the screenshot). That's the missing exponent.

**Update 2:** Switching to 100% UI scaling (no scaling, tiny pixels on my display) doesn't make a difference.

![image](https://user-images.githubusercontent.com/295205/40234674-05a1f918-5aa8-11e8-86ec-2018082e6240.png)

**Comment by gunterkoenigsmann** [comment]
Thanks for this bug report! The next nightly build will work again.
Kind regards,
  Gunter.
