### ISSUE TITLE
lmxchar and rmxchar cannot be changed in wxMaxima

### ISSUE THREAD

**Issue by RolandSalz** [andrejv/wxmaxima#1004]
This is something for the wish list: being able to display matrices in parentheses instead of square brackets. Maybe next Christmas?

**Comment by gunterkoenigsmann** [comment]
I guess I can make wxMaxima support the combination "[" and "]" and the combination "(" and ")". Don't know how much work this is, though => no ETA when it will work. ...but other combinations are hard to support even if I could imagine how they should look like.
