### ISSUE TITLE
Updating Spanish translation

### ISSUE THREAD

**Issue by cyphra** [andrejv/wxmaxima#1007]
[master[2018-0606].es.po.gz](https://github.com/andrejv/wxmaxima/files/2077673/master.2018-0606.es.po.gz)

**Comment by cyphra** [comment]
I tried to use the request, but I

**Comment by gunterkoenigsmann** [comment]
I have received the es.po.gz file that was attached to this ticket. If you want I commit it to the repo.

Kind regards,
 Gunter.
