### ISSUE TITLE
XDG basedir support, again

### ISSUE THREAD

**Issue by alexshpilkin** [andrejv/wxmaxima#1015]
This is a continuation of #869.

As of wxMaxima 18.02.0 (Arch Linux), I still see `wxmaxima` create `~/.wxMaxima` (and not something in `~/.config/wxMaxima`) each time it’s launched. It appears that the XDG support introduced in d02adbf got disabled in e05def7 (“This somehow didn’t work”) and later removed in 2cc62af (a code cleanup).

**Comment by gunterkoenigsmann** [comment]
Unfortunately the "didn't work" was correct: wxWidgets tried to introduce XDG_Basedir support. But it didn't work on half of the computers of our testers as it didn't check if the XDG directories did exist and were writable. Also wxWidgets didn't migrate the old config files to the new location loosing user data => currently there is no good way to make any of the several hundred? Thousand? wxWidgets applications support XDG. 

If you convince the wxWidgets guys to properly support XDG and to automatically migrate the configuration to the new location, though, all wxWidgets applications will automatically start supporting it => closing this bug as there is nothing wxMaxima can do about it. But I encourage you to talk to the wxWidgets guys to fix the actual problems that hinder wxMaxima from supporting XDG.

**Comment by alexshpilkin** [comment]
Ah, that makes more sense. OK, I’ll look at what they have on the wxWidgets side, although franky I don’t know a thing about it. (Do they have an issue or something about creating the directories there?)

**Comment by gunterkoenigsmann** [comment]
I guess that this was the case: with XDG enabled a few testers reported that settings no more were saved between sessions. But I didn't investigate the real reasons.

...and there were protests that all settings+recent files etc. were lost during switching to XDG.  My idea on migrating the settings to XDG would have been that if no XDG config file were found and an old config file would exist the old config file would be read. On leaving the application the new XDG config file is automatically created so the next time the program is started a XDG config file exists.

Until the config isn't automatically migrated switching to XDG looses user data and I don't want to loose user data.

**Comment by gunterkoenigsmann** [comment]
I think I *might* have found a way to resolve this issue for wxMaxima - even if that doesn't help the rest of the applications that use wxWidgets.
