### ISSUE TITLE
When Attempting to Change Mesh Line Colors, Results Fail (Linux and Windows 10)

### ISSUE THREAD

**Issue by mematusz** [andrejv/wxmaxima#1017]
I attempt to change the mesh_lines_color to black, blue, red, or other recognized colors but literally nothing changes it.

I tried this on multiple sample snippets given in the documentation, but with no luck.   The one I am working with now has issues (mesh lines always appear an unappealing yellow).  I can get rid of the mesh lines by setting the value to false, but no color values do anything.
plot3d ( 5, [theta, 0, %pi], [phi, 0, 2*%pi], same_xyz,
[transform_xy, spherical_to_xyz], [mesh_lines_color,blue],
[palette,[gradient,"#1b1b4e", "#8c8cf8"]], [legend, false])$

**Comment by gunterkoenigsmann** [comment]
Wow... ...a fairly enhanced plot example. Normally I just tell everyone to use draw as I am experienced with draw and normally can provide help. In this case I would ask you to ask the maxima developers (http://maxima.sourceforge.net) instead as plot is a command provided by maxima.

**Comment by gunterkoenigsmann** [comment]
Will close this ticket - not because it is invalid, but because it can be helped better in a different project.
