### ISSUE TITLE
wxMaxima: wrong output when printing WXMX-file to PDF

### ISSUE THREAD

**Issue by mirekslouf** [andrejv/wxmaxima#1019]
When I try to print a wxMaxima WXMX-file to PDF (using PDF Creator under Windows 7), the output PDF file shows several formatting errors:

1. If there are multiple outputs, the alignment of the 2nd, 3rd... output line is bad (shifted to left).
2. Even the 1st input and output in [input cells] are shifted to left with respect to the [text cells].
3. The font size and the plot size in the PDF output is quite small.

See attached files:
* [exp.wxmx.zip](https://github.com/andrejv/wxmaxima/files/2239015/exp.wxmx.zip) = zipped wxMaxima file
* [exp.wxmx.pdf](https://github.com/andrejv/wxmaxima/files/2239016/exp.wxmx.pdf) = corresponding PDF ouput

In my previous version of wxMaxima, this errors did not occur.

Versions of my programs:
wxMaxima version: 17.10.1
Maxima version: 5.41.0a_dirty
Maxima build date: 2017-10-24 09:10:11
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.206])

**Comment by gunterkoenigsmann** [comment]
II hope I have fixed this one in the current development version. Unfortunately the nightly build on launchpad is broken, currently...

**Comment by mirekslouf** [comment]
At first, let me thank you for your fast reply.

I have downloaded a nightly wxMaxima build (file wxmaxima-daily.zip from https://wolfgang.dautermann.at/maxima/) and unpacked it to my wxmaxima directory).

After uzipping the nightly built, the situation is as follows:

* cell alignment and font size in [math cells] seems to be Ok
* [text cells] do not work at all: I cannot see them, I cannot write into them
* wxMaxima is unstable, during saving WXMX file it usually crashes

Was my procedure correct? If the nightly built on launchpad is broken, does it mean that also Windows built is broken (sorry for the naive question)?

**Comment by gunterkoenigsmann** [comment]
Wow... ...will borrow a Windows PC tomorrow and have a look: until you wrote this I was convinced that I have resolved all Windows problems. Which windows version are you using and does wxMaxima output any additional information when crashing?

**Comment by gunterkoenigsmann** [comment]
As for the nightly launchpad build: this is a problem on launchpad's side: they can download the source code but cannot upload it in their computers any more.

**Comment by gunterkoenigsmann** [comment]
Found a big report on launchpad: https://bugs.launchpad.net/launchpad/+bug/1779572

**Comment by gunterkoenigsmann** [comment]
If my commit doesn't help with text cells my guess is that the text cells are either set to a font your computer doesn't provide or to a font size <= 0.

**Comment by mirekslouf** [comment]
Thanks again for fast response. I did the following:

1. Uninstall of Maxima.
2. Installation of [maxima-clisp-sbcl-current-win64.exe]
   from https://wolfgang.dautermann.at/maxima/nightlybuild/
3. Test of the installation.
4. Download of [wxmaxima-daily.zip]
    from https://wolfgang.dautermann.at/maxima/
   and unpacking the ZIP file in the maxima directory
5. Test of the installation.

The results of testing (both step 3 an 5 above) were the same:

* Writing in text cells does not work. Text is invisible, but after changing the cell type from [text cell] to [math cell] it appears. After changing back to [text cell] it disappears. I use font [Consolas 11]
* wxMaxima crashes when I try to save WXMX file. It just opens a small window, which says [wxMaxima has stopped working] and freezes. When I close the window with the error-message, wxMaxima main window closes as well.

Versions of my programs:
* Maxima: current built, see above
* Windows: Windows 7 Professional, Service pack 1

Should I test anything else?
(I am able to install prepared builts, but I have no experience with compiling maxima from source files)

**Comment by gunterkoenigsmann** [comment]
I hope in tomorrow's nightly build the saving issue is resolved.
---
In the configuration dialogue you can choose the text fonts. Does that help? On Windows there aren't many checks if invalid fonts overwrite unrelated memory which means that selecting a non-working font here might theoretically explain all the issues you are facing. The font issue might lie in the graphics driver, too, unfortunately, that I have no influence on...

**Comment by gunterkoenigsmann** [comment]
Wow... ...sorry for the capital letters. Seems I still have to learn more about MarkDown...

**Comment by mirekslouf** [comment]
The font should be Ok. I have been using a standard Windows font [Consolas]. To be 100% sure I switched to even more standard [Arial]. The behavior with [Arial] font is exactly the same, i.e. it seems that the font should not be the issue.

**Comment by gunterkoenigsmann** [comment]
Looks good => Next question: Is space reserved for the missing text? Is it possible to select the invisible text with the mouse, is the cursor of a plausible height and does the cursor move if you type in characters?

We once had an user whose system that for some reason changed the colour setting that characters by default have to be fully transparent black: Often users claim to have done something wrong as the computer doesn't lie. But often it does: Changing this setting this way would have been complicated and I assume the user would have remembered doing so.

**Comment by mirekslouf** [comment]
Answer to your question:
* if I select [text cell]
  * single line with cursor appears
  * the cursor is visible, but it does not move after pressing letters/numbers
  * [arrows] for moving do not work
  * the cursor goes down after pressing enter
  * but it is not possible to select the text neither with a mouse nor with [arrows]+[Shift]
  * see the attached file: ![second_cell_as_text](https://user-images.githubusercontent.com/22853864/43444838-11d51404-94a5-11e8-84f2-12002e71aafd.png)
 
* if the format of the input is changed from [text cell] to [math cell]
  * the text appears
  * see attached file: ![second_cell_as_math](https://user-images.githubusercontent.com/22853864/43444865-1d27c928-94a5-11e8-9ac2-b2387ecac95f.png)
  * if it is changed again to [text cell], the text disappears
  * if it is changed again to [math cell], the text appears again and so on...

**Comment by gunterkoenigsmann** [comment]
Wow... ...from your screenshot I can see:
 - you are definitively using the nightly build
 - but the toolbar buttons are displayed in the Win XP visual style, not in the Windows 7 one. Is wxMaxima executed in a weird compatibility mode?
 -  The cursor is moved a line down if you go into the 2nd line of a text cell, but
 - no additional space is reserved for the text cell even if it should be 2 lines long.

And since both calculations use the same variable for the font height both should not be possible at the same time.

  - and Text in text cells seems to have zero width.

all of that is positively weird.

**Comment by gunterkoenigsmann** [comment]
Another thing the screenshot shows: You had a very old version of wxMaxima installed on the same system once. I would be surprised if a leftover setting from an old version could confuse a new wxMaxima. But just in case: If you search for "wxcd" in regedit you should find a folder named "wxmaxima". If you close all instances of wxMaxima, delete this registry folder and open wxMaxima again: Does that resolve the problem?

**Comment by mirekslouf** [comment]
The method [Regedit - Search - Delete wxMaxima folder] solved the problem with the [text cells], at least partially:

* The text cells are visible (see attached PrintScreen below).
* The font in text cells cannot be set in current version of wxMaxima.
* I used Consolas for all both [math cells] and [text cells] in my previous version.
* Now it is Arial for [text cells] and this cannot be changed in Options (the button for font selection is inactive). Maybe this was the problem: wxMaxima tried to use font, which is no longer possible.
* Nevertheless, could you please activate the selection of font for [text cells again]? I know this is a minor problem, but the [Arial font] is really ugly. As a programmer, I am used to fixed-font width. Moreover, the font selection for [section] and [subsection] cells is still possible.

![test](https://user-images.githubusercontent.com/22853864/43489858-acb2aa62-951e-11e8-9561-9a7fd5b2448f.png)

The problem with saving has not been solved yet. My wxMaxima still freezes when I try to save a file. See the second PrintScreen:

![test2](https://user-images.githubusercontent.com/22853864/43489932-fb080248-951e-11e8-81c8-6e3e73c4b166.png)

**Comment by gunterkoenigsmann** [comment]
If you enable the debug messages (view/debug messages) wxMaxima should tell us at which point it has entered an endless loop. At least theoretically.

**Comment by mirekslouf** [comment]
Dear Gunter - a lot of news:

1. The first and the most important: Thanks a lot for all your help.
2. The second: **problem with saving solved** in the following way:

* complete uninstall of wxMaxima
* deletion of wxMaxima in regedit, as you suggested above
* installation of the recent stable version (file: maxima-clisp-sbcl-5.41.0a-win64.exe)
* installation of recent nightly built (file: wxmaxima-daily.zip)

3. The third **problem with disappearing text in [text cells] localized**:

* after the re-installation above, the text in the [text cells] is visible
* it disappears when I change: Edit - Configure - Worksheet - Autowrap long lines - No
* it appears back when I change it to: ... Autowrap long lines - Text only
* i.e. the option [No] seems to have caused all problems

4. [Ctrl+C] and [Ctrl+V] now works in a standard way.

5. The only remaining problem is the selection of font for [text cells]. From your notes above it seems that you have already repaired this, right? If yes, I suppose that I can download the nightly built as usual, correct?

With regards & thanks, Mirek

**Comment by gunterkoenigsmann** [comment]
You're welcome ;-)

...and thanks for all the testing: As I don't own a Windows and as even that wouldn't be a guarantee to encounter all problems found in the wild testing is most important and it is important to have a tester like you who  knows how to recognize which symptoms are important.

The nightly build really means nightly so the fixed bugs will only be fixed there tomorrow.

Will have a look at the setting that causes the leftover problems. But I cannot guarantee that I manage to do that before the next nightly build will take place. Kind regards,

Gunter.

**Comment by mirekslouf** [comment]
Everything seems to work, just one very minor formatting issue when printing WXMX to PDF:

* The current alignment of [text cells] and [math cells] to left is not exactly the same, but maybe this is intentional?
* See the attached PDF file: [el-rec_vs_time.wxmx.pdf](https://github.com/andrejv/wxmaxima/files/2253480/el-rec_vs_time.wxmx.pdf)

Now I am focusing to the formatting errors when converting WXMX - TEX - PDF (issue #1020). Nevertheless, the basic and direct output WXMX-PDF seems to me much more important than WXMX-PDF-TEX. Do not hesitate to stop me if you think that this is just a detail.

**Comment by mirekslouf** [comment]
A few other minor formatting errors when printing WXMX to PDF were found. They are illustrated in two attached files:

* [x1_konkretni_priklad.wxmx.zip](https://github.com/andrejv/wxmaxima/files/2274287/x1_konkretni_priklad.wxmx.zip) = ZIPed WXMX file
* [x1_konkretni_priklad.wxmx.pdf](https://github.com/andrejv/wxmaxima/files/2274291/x1_konkretni_priklad.wxmx.pdf) = corresponding PDF output (WXMX file printed to PDF)

Some of them have already been mentioned above, but I am listing them all together:

1. The current alignment of [text cells] and [math cells] to left is not exactly the same. Text cells seem to be aligned more to the right than the [math cells]. In previous version of wxMaxima the alignment of both [text cells] and [math cells] was the same.
2. For [Edit - Configure - Worksheet - Intelligently hide cell brackets - OFF] the cell brackets are visible in WXMX, but not printed in PDF. In previous version of wxMaxima the cell brackets were visible also in PDF, which was quite helpful and more readable in more complex files because it visually separated [math cells] and [text cells] with comments to the calculations.
3. Color background of the [text cells] is visible in WXMX file, but not in the PDF file.

**Comment by gunterkoenigsmann** [comment]
For 2.) In the config dialogue there should be a separate setting for printing the brackets: Some users want to see them on the screen but don't want to print them.

**Comment by gunterkoenigsmann** [comment]
I have now tried to resolve 3). But I remember that drawing a background on text cells used to trigger a bug in wxWidgets that caused half of the worksheet to disappear on printouts => I beg you to test this.

I have changed a lot today => cannot guarantee that the windows build will finish without an error, so there is no guarantee that tomorrow a new nightly build will exist. As I believe to have resolved all issues in this bug report I'll close it now. But please open new bugs or protest if I am wrong.
