### ISSUE TITLE
wxMaxima: Ctrl+C and Ctrl+X shortcuts do not work

### ISSUE THREAD

**Issue by mirekslouf** [andrejv/wxmaxima#1021]
In my version wxMaxima (see below), the behavior of [Ctrl+C] and [Ctrl+X] shortcuts is strange:

1. [Ctrl+C] and [Ctrl+X] do not work in neither [text cells] nor [input cells].
2. [Ctrl+V] works in both above-mentioned cell types.
3. The equivalent commands from Menu: [Edit-Copy] and [Edit-Cut] do work in a standard way.

Version of my programs:
wxMaxima version: 17.10.1
Maxima version: 5.41.0a_dirty
Maxima build date: 2017-10-24 09:10:11
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.206])

**Comment by gunterkoenigsmann** [comment]
This was my fault: Sometimes the "Copy" icon isn't enabled correctly - and with the icon the corresponding shortcut is disabled, too. In the current development version this should be corrected.

**Comment by gunterkoenigsmann** [comment]
Good news: the Ubuntu nightly build has started to work again: Launchpad's bzr import still is broken. But I've managed to setup a git import instead.
