### ISSUE TITLE
wxMaxima: yet another formatting error when printing WXMX to PDF

### ISSUE THREAD

**Issue by mirekslouf** [andrejv/wxmaxima#1023]
I am really sorry, but I have found yet another formatting error:
(originally noticed for long `if-then-else` statements, but it applies to all longer lines, as documented below)

* Long lines are correct in WXMX window...
![fig1](https://user-images.githubusercontent.com/22853864/44004298-a6ba7da6-9e60-11e8-9385-898d903657c6.png)

* But the same lines break too early when the WXMX is printed to PDF (note outputs %o2 and %o6):
![fig2](https://user-images.githubusercontent.com/22853864/44004322-23007578-9e61-11e8-92d3-6f82bab41ce4.png)

**Comment by mirekslouf** [comment]
Another issue, supplementing the above comment:

* If the output line breaks, I think that it should be aligned with the previous line, not with the leftmost margin.

**Comment by gunterkoenigsmann** [comment]
That will be a lot of work. But I think I have an idea how to both speed up wxMaxima and to indent the whole equation, not only the first line.

---

I almost never use a printer not pdf files so testers are always welcome.

**Comment by gunterkoenigsmann** [comment]
Ha! And I have found out how to draw a horizontal line without making the text before it a caption.

**Comment by mirekslouf** [comment]
Thanks for the patch, the output is improved, but still not perfect in my computer. The long lines in WXMX are Ok, but in WXMX printed to PDF they break too early. See the image below:

![if-then-else_linebreaks wxmx pdf](https://user-images.githubusercontent.com/22853864/44132230-8024689c-a058-11e8-9b03-ed971cd8be3c.png)
