### ISSUE TITLE
Exit without save still saves the file

### ISSUE THREAD

**Issue by christiankral** [andrejv/wxmaxima#1029]
Consider the following example, saved as `test.wxmx` (make sure the file is saved):

![image](https://user-images.githubusercontent.com/4184218/44988608-9468a100-af8b-11e8-8714-f73a525a8918.png)

Delete the second input (`y`): 

![image](https://user-images.githubusercontent.com/4184218/44988709-edd0d000-af8b-11e8-8f2c-e496653745f9.png)

In the window header `test.wxmx*` appears, so the `*` indicates that the file has changed. Now exit without saving (`ALT+F4`). No question is asked. Re-open `wxmaxima` and the assignment of `y` is lost. 

![image](https://user-images.githubusercontent.com/4184218/44988734-0640ea80-af8c-11e8-9501-5a4930c0f701.png)

Apparently changes are saved automatically. This is not good, since some changes shall NOT be save, e.g., when testing something without storing the changes.

Operating conditions: Linux Mint 18.3 64 bit, `wxmaxima 18.02.0`

**Comment by gunterkoenigsmann** [comment]
Looked at the code. Might it be that you have set "autosave interval" in the config dialogue to something > 0? In this case wxMaxima tries to keep the file saved all the time in the same way an ipad app would do. If not I will try to have another look at the code.

**Comment by christiankral** [comment]
I checked `/~.wxMaxima` and there I have the following settings:

```
autoSaveInterval=3
```

I changed the autosave interval to

```
autoSaveInterval=0
```

![image](https://user-images.githubusercontent.com/4184218/44999185-abbf8280-afbb-11e8-938b-766661dafca8.png)


and this changed the behavior to what I expected. OK so this is not a bug, it's a feature. I wasn't aware of this ipad app behavior which goes along with an autosave interval >0. So actually the 

`Autosave invterval (minutes, 0 means: off)` 

is 

`Autosave interval (minutes) plus save on exit (0 means: off)`. 

Thanks for clarifying this issue.

**Comment by christiankral** [comment]
One more interesting thing to note with `autosave > 0` here: If I keep only one line 
```
x:0;
```

Save the file, delete the `x` and exit (ALT+F4) and re-open the file: the `x` is still there... but it shouldn't, since autosave is on...

**Comment by christiankral** [comment]
But this may also not be a bug but a feature ;-)

**Comment by gunterkoenigsmann** [comment]
You are right: Not saving an empty (or almost empty) file was intended as a feature: If you instruct wxMaxima to automatically add an code cell every time maxima is ready for new input (as opposed to only when the user starts typing) wxMaxima always asked if the file is to be saved on exit. I tried to get rid of that.
