### ISSUE TITLE
wxMaxima crashes when saving a new workbook

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#1030]
When I open wxMaxima, start a new document, and what to save it, wxMaxima chrashes.
I also happens when I take an old workbook and make some large changes in it.
However, if I save the new file as a *.wxm it goes ok.
----------------------
wxMaxima version: 18.02.0.unofficial
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_41_base_485_g1859b47_dirty
Maxima build date: 2018-07-22 23:44:30
Host type: x86_64-w64-mingw32
System type: Win32 10.0.14393 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.2
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxxx/maxima/
Help dir: C:\maxima-current\wxMaxima/help
Maxima lisp dir: C:\maxima-current\bin/../share/maxima/branch_5_41_base_485_g1859b47_dirty

**Comment by ReneSci** [comment]
Seems to have been resolved with the next version - sorry. I could not delete this issue

wxMaxima version: 18.02.0.unofficial
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_41_base_525_gc4aa30a_dirty
Maxima build date: 2018-09-08 21:25:59

**Comment by gunterkoenigsmann** [comment]
No complaints from my side: saving is the worst place a program can crash so I expected a bug report to appear from the day it did and your bug report included the date. Sorry for not having had the possibility of replying you earlier!
