### ISSUE TITLE
conjugate should be displayed as "*"

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#158]
Converted from [SourceForge issue 2876331](http://sourceforge.net/support/tracker.php?aid=2876331), submitted by nobody

declare(%alpha, complex);

Then conjugate(%alpha) renders to conjugate(a),
this is anti-intuitive and results long expressions. it should be a* instead.

**Comment by gunterkoenigsmann** [comment]
Fixed in commit 6546a88ea10e1fd6193fb46ce9c2110e72eb5e42. Since this introduced a new tag to the wxxml format I did bump the format's minor version number after adding this feature.
