### ISSUE TITLE
Section jumper

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#160]
Converted from [SourceForge issue 2891466](http://sourceforge.net/support/tracker.php?aid=2891466), submitted by nobody

will be nice, if we can have a list of sections (sections, subsections, title, ...), then if we click on some section of the list, the active line jumps there. 
just like the function search of code's editors.

**Comment by gunterkoenigsmann** [comment]
A table-of-content-pane? Sounds practical.

**Comment by gunterkoenigsmann** [comment]
Closed with commit 9b3530a7379e487126d8c15b4a1c3654a1e330e3.

This is th 300th issue to be closed in the 10th yoear. There have been less important news about software that have been reported to the press than this one.
