### ISSUE TITLE
offset the minus sign in negative results

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#161]
Converted from [SourceForge issue 2950402](http://sourceforge.net/support/tracker.php?aid=2950402), submitted by machtfuernacht

Hi, especially when the result contains a negative fraction the leading minus sign conflates with the fraction line.
Is it possible to add a gap between the sign and the rest of the result?

**Comment by gunterkoenigsmann** [comment]
Resolved in commit 01c57cb70524e91ab8522060bb539f35434ad69b: Did cause an error in one of my calculatons and depending on the font fractions did collide with things like plus signs, too.
