### ISSUE TITLE
Select across different cells

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#168]
Converted from [SourceForge issue 2991143](http://sourceforge.net/support/tracker.php?aid=2991143), submitted by nobody

Can you add the possibility to select text across the borders of cells.
And I also miss the feature to just delete the current cell when it is empty. Instead you must move the cursor before the cell to delete it with del-key.

And how do I execute one cell after another? When I press Shift-Enter to execute one cell, my cursor is between the two cells, and when I press Shit-Eneter again (to execute the next one) nothing happens. So I have to move the cursor again before evaluation.
And is it possible to reverese Shift-Enter and Enter, because a lot of software does it the other way round. Like Word, Maple, ...

**Comment by gunterkoenigsmann** [comment]
Closed with commit 86dd9567570291451e14d4a50006f118de0a186c.
