### ISSUE TITLE
An option to "evaluate all cells" to consider errors.

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#172]
Converted from [SourceForge issue 3152383](http://sourceforge.net/support/tracker.php?aid=3152383), submitted by stefano_ferri

It would be useful to have a feature like the evaluation of all cells (Ctrl-R, Cell -> "Evaluate all cells" in the menu)  wich can consider errors.
Its behaviour should be like the "batch file" (or load) feature, when if an error occurs, the execution stops where the error is present. The present behaviour of Ctrl-R prevents a full write of a Maxima script in a wxMaxima sheet. In fact, it goes on until the end of the sheet is reached, even if there are errors.
I have written some interactive wxMaxima sheets, wich should be modified by users with their own input variables. If these variables are not valid, the execution must be interrupted, but this is not possible with the current behaviour of wxMaxima. For example, I have a call in the wxMaxima sheet to a .mac file that perform error checking and eventually stops the execution, but it is bypassed because wxMaxima goes anyway with the next cell to evaluate.
Therefore, I think it could be useful to have a real "script-like" function to evaluate all cells.

Stefano

**Comment by gunterkoenigsmann** [comment]
Do we get informed if a message from maxima is an error - or if it just is ordinary text? If not I expect this functionality to generate false positives/negatives.

**Comment by gunterkoenigsmann** [comment]
Fixed with commits c5cf98d04b1869d0417d48e293aa127e2f789fd8, ea8e5945041811ccd2912ff492b9389823000148 and d053de271a30784d3ae4ae1fddaf2233bdbf71c0.
