### ISSUE TITLE
"Maxima process terminated" in Windows.

### ISSUE THREAD

**Issue by dilijev** [andrejv/wxmaxima#193]
In Windows, when running 11.08.0 with maxima 5.25.0 in elevated privilege mode, wxMaxima is unable to make a connection with maxima (the status bar at the bottom reads: "Maxima process terminated." where it would normally read "ready for user input"). I am also unable to change the path to maxima in from the config dialog.

When I go Maxima > Restart Maxima, the status bar reads "Maxima started. Waiting for connection..." and never progresses.

Running without elevated privilege mode there is no problem.

**Comment by gunterkoenigsmann** [comment]
Maxima, wxMaxima and the complete build infrastructure have changed in the meantime => I assume whatever has caused the problem will have changed and close this ticket.
