### ISSUE TITLE
More aggressive "interrupt current computation" button.

### ISSUE THREAD

**Issue by dilijev** [andrejv/wxmaxima#225]
Presumably the button works fine if you want to interrupt long computations that are proceeding normally, however, if I have initiated an operation which causes a hang like in issue #204, the button does not cancel the operation.

Is it possible to implement a more aggressive interrupt of the computation? Currently the only workaround is to exit the program, which can cause loss of data or effort if computations so far are not saved.

Suggestion: force an exit of the current maxima session (possibly with saved state of variables from the session), and reconnect to maxima? It is not elegant, but would be an improvement over the indefinite hang.

**Comment by gunterkoenigsmann** [comment]
Issue #338 goes even farther than this ticket.

**Comment by gunterkoenigsmann** [comment]
The interrupt button should work in all cases now except for the issue https://sourceforge.net/p/maxima/bugs/3107/ => Closing this bug for wxMaxima.
