### ISSUE TITLE
Public Doxygen documentation of source code

### ISSUE THREAD

**Issue by dilijev** [andrejv/wxmaxima#238]
I noticed a while back that a Doxyfile was added to the project, but looking around, I don't see the HTML posted anywhere.

Perhaps the documentation pages should be added to the gh-pages website, so that there is an official documentation host for developers?

Perhaps add a section on the Develop tab of the website "Documentation" which has a link to that documentation?

For the moment, I have uploaded the documentation generated from the latest version of the master branch to:
http://doug.ilijev.com/wxmaxima/docs/

**Comment by gunterkoenigsmann** [comment]
Sounds like a great idea, that. But I have just written a script that uploads the documentation to the homepage and have been surprised that the result is about 300 Megabytes long. I can of course reduce the number of graphs doxygen generates - but then much information I feel as being useful gets lost.
I don't think we want *that* in our github repo.

On the other hand I could try to upload the documentation to my own homepage (which currently has no limit on the amount of data)... 
...don't know if that would be a feasible idea.

**Comment by dilijev** [comment]
Yes maybe gh-pages isn't the best option for the volume of documentation. I apologize that the version I was hosting was removed. My website has undergone some major maintenance in the last few years.

Any host for the documentation is better than no host :)

**Comment by gunterkoenigsmann** [comment]
Then it is decided that the Right Place to host the documentation is http://www.physikbuch.de/wxMaxima/html/index.xhtml 

Kind regards,

       Gunter.
