### ISSUE TITLE
For long documents, an outline view of the headings/subheadings would be helpful

### ISSUE THREAD

**Issue by dilijev** [andrejv/wxmaxima#239]
If I have a long document I would want to see all of the headings and subheadings in a side pane, whether or not they are folded, without any of the content cells.

I would also like such a pane to allow me to jump around in the document by clicking on the items there.

Displaying the headings indented by heading type / depth would also be a nice visual feature.

Perhaps the pane could also allow the user to fold/unfold the corresponding sections by clicking a button in the pane.

**Comment by gunterkoenigsmann** [comment]
wxMaxima 15.04 does contain the requested feature with exception of the fold commands that I didn't need..
