### ISSUE TITLE
ishow() Greek letters

### ISSUE THREAD

**Issue by murakamiriyugi** [andrejv/wxmaxima#261]
Type of Issue : Feature Request

Greek letters are not displayed as Greek letters
when displaying tensors using the function 

ishow()

For instance, the input

load(itensor)$
ishow(A([mu, nu],[])$

results to

A_{mu, nu}

in Wxmaxima. 

Is there a way or future plans for this feature (ie.,
displaying Greek letters as Greek letters under
ishow()) to be implemented?

This request may sound unreasonable since I can just
use Roman letters, but verifying very long expressions
written with Greek indices can be cumbersome (so to
speak) at times.

**Comment by gunterkoenigsmann** [comment]
Greek letters are supported in the upcoming version of wxMaxima.
