### ISSUE TITLE
Paste command problem!

### ISSUE THREAD

**Issue by DissidentPenguin** [andrejv/wxmaxima#277]
Hello!
First, thanks for the great work. It is a great addition to Maxima.

Second, the issue.

Seemingly wxmaxima simply ignores the paste command when the text being pasted begins with the string
/* [wxMaxima: input   start ] */

if the corresponding
/* [wxMaxima: input   end   ] */

is missing.

Just discovered by accident and it was driving me crazy because many of the files I am working on had the "input start" (which I didn't notice) and were missing the "input end". I usually work in a text editor and copy and paste in between it and wxmaxima, so some files that were working somehow didn't work any more. I probably selected the whole cell instead of only the text I wanted to copy, didn't notice those comments and somehow I lost the "input end" in one of the iterations.

Problem is present in windows and linux, and in versions 12.01.0 and 13.04.2

I have the latest version in mint-nadia and the older in windows. The behavior is a bit different between linux and windows, but I'm not sure if it is because of the different versions of wxmaxima. 

In both systems the problem only seems to arise only if the first text string in the text to be pasted is the "input start". However, in windows (12.01.0) the paste command only fails if both tags are present, and in Nadia only fails if the "input end" is missing.

Hope this is of any help.

Thanks again for the great gui!

All the best,..
DP

**Comment by gunterkoenigsmann** [comment]
Closing this bug due to a lack of inactivity.

**Comment by dilijev** [comment]
I'm not sure it's wise to close simply due to inactivity. There are still potential action items here that we may get to eventually.

**Comment by gunterkoenigsmann** [comment]
Since commit 776331fbbdc148ba95bde304025faec5f4641149 we now paste all intact cells.
