### ISSUE TITLE
High-DPI compatibility in Windows

### ISSUE THREAD

**Issue by dilijev** [andrejv/wxmaxima#282]
With many Windows systems coming out with high-DPI displays, it is important to support high-DPI mode for those resolutions.

On windows it might be as simple as declaring the application DPI-aware in the manifest, and updating the images in the app to higher resolution, or include higher-resolution alternatives for those images to be used in higher-DPI modes.

See guide on high DPI windows application programming:

http://msdn.microsoft.com/en-us/library/windows/desktop/dd464660(v=vs.85).aspx#declaring_dpi_awareness

It might not be completely obvious from this screenshot, but in-app fonts and images are blurred because of virtual dpi scaling. (Windows 8 Surface Pro)

![screenshot 3 - cropped](https://f.cloud.github.com/assets/494055/905097/a626cdda-fbfa-11e2-8690-af502082a933.png)

**Comment by gunterkoenigsmann** [comment]
The tango icons are available in SVG so I can create bitmaps from them in all resolutions. 
wxDC::GetPPI() or similar might provide us with the scaling factor we need. But I don't know enough about building on windows to find out how to change the manifest accordingly.

**Comment by gunterkoenigsmann** [comment]
Did add the icons in a resolution high enough that they are sharp on high-dpi screens. Likewise the plots are automatically scaled, if needed. The rest should already work now.
