### ISSUE TITLE
Add Text Wrap

### ISSUE THREAD

**Issue by ProfChoda** [andrejv/wxmaxima#286]
I use wxMaxima to make engineering documents. I would really like it if the program had text wrap so all written text would fit in the window. Also, it would help a lot if printing to PDF could also wrap the text based on the paper size. Currently when you print in PDF, any long text gets truncated and does not get displayed.  

Outputs currently have text wrap so hopefully it won't be too difficult to extend it to inputs and text.

Thanks!

**Comment by gunterkoenigsmann** [comment]
If the line wrapping would work for printing, too, that would resolve issue #402, as well.

**Comment by jonhp** [comment]
Here is one more vote for this issue having a higher priority. Thanks, Jon
