### ISSUE TITLE
Syntax Highlighting the input in the editor

### ISSUE THREAD

**Issue by mleoking** [andrejv/wxmaxima#288]
Is it possible to add the highlighting feature for the input field?

**Comment by gunterkoenigsmann** [comment]
Did document the starting point for implementing syntax highlighting in commit 85fb40ead334e59ae3c703f42a96031e77d072c3.

**Comment by gunterkoenigsmann** [comment]
Added syntax highlighting.

@ofurkusi: If you checkout the git version of wxMaxima Ctrl+Tab triggers a feature that might be what you want.
