### ISSUE TITLE
Can not select code using Shift and mouse click in an input cell.

### ISSUE THREAD

**Issue by mleoking** [andrejv/wxmaxima#291]
In most text editors, you would be able to select a block of text by the following steps:

1) Mouse click the beginning of the text block

2) Press Shift key and hold it

3) Mouse click the end of the text block.

Currently the wxMaxima input cell editor does not support selecting text by following the previous steps. 

The Shift and mouse click selection is very useful when the input code block is very long either in terms of the width or the height.

**Comment by gunterkoenigsmann** [comment]
Resolved with f4e72755ec352fd45bc54195926f1d0bac8f7db1
