### ISSUE TITLE
do not put double spaces when save and come back and open

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#292]
wxMaxima version: 13.4.0
Maxima version: 5.31.1
Maxima build date: 2013-09-24 09:49:12
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8

when i save a file my input typically does not have any spaces between my input lines on a single input cell  but the most irritating thing is when i open it again all the input lines have 2 or 3 spaces between them in every input cell. NOT the way it was when i saved it. Also bug in multinomial:

[multinomial(3,[1,1,1,0]),multinomial(3,[1,1,0]),multinomial(3,[0,1,1]),multinomial(3,[1,0,1])/*error*/,multinomial(3,[1,0,1,1])/*error*/];

(%o175) [6,6,6,3,3] 

the last 2 are obviously incorrect - seems to happen whenever have a 0 as the 2nd argument atleast in these examples.

**Comment by gunterkoenigsmann** [comment]
Did fix the thing with the extra newlines appearing on load in the git master (about three weeks ago): Was the \\r\n line ending win uses.
