### ISSUE TITLE
Curzor in Text Cell sometimes 2 positions misplaced

### ISSUE THREAD

**Issue by olddutch** [andrejv/wxmaxima#297]
wxMaxima version: 13.4.0
Maxima version: 5.31.2
Maxima build date: 2013-10-07 23:05:06
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8
OS: windows 7, Home Premium, 64 bit, SP1

As the title tells: the curzor in a Text Cell is sometimes 2 positions misplaced to the right of the position where the action really takes place.
It's quite annoying.

This is no criticism, I have deep respect for those who created (wx)Maxima!
Kind regards,
Olddutch

**Comment by gunterkoenigsmann** [comment]
Had the same problem and reported it as #385: A <TAB> character can be drag-and-dropped into wxMaxima but won't be handled kindly.
