### ISSUE TITLE
wxmx: Indentation of xml lines beginning with & is discarded on load

### ISSUE THREAD

**Issue by mleoking** [andrejv/wxmaxima#301]
I found wxmaxima changes the layout of the code after saving.

Here is a video showing wxmaxima eliminates the blanks I have inserted in the code after saving:

http://www.youtube.com/watch?v=R39V9q9tCC0&feature=youtu.be

Here is the test file: https://dl.dropboxusercontent.com/u/45318932/bug.wxmx

**Comment by gunterkoenigsmann** [comment]
OK... The file is saved correctly. But on loading the file again cells beginning with ' characters aren't interpreted right. Did mix that up with other bugs what was the reason why it took me so long to reach this point.

**Comment by gunterkoenigsmann** [comment]
Is corrected in the git master.
