### ISSUE TITLE
wxMaxima cause erors when excuted from command line.

### ISSUE THREAD

**Issue by mleoking** [andrejv/wxmaxima#302]
wxMaxima version: 13.4.0
Maxima version: 5.31.2
Maxima build date: 2013-10-07 23:05:06
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8

I am using Windows XP.

This problem only happens when you start wxMaxima from the command line in a directory that is not where wxMaxima.exe is located.

I set wxMaxima directory into the PATH of Windows, so that I can execute wxMaxima from any directory in the command.

wxMaxima reports an error after being loaded from command line:

![wxmaxima cmd error](https://f.cloud.github.com/assets/5763751/1759858/54cabf3a-66a5-11e3-9e29-17066ecf63bf.png)

The pictures in the GUI of wxMaxima are all missing.

**Comment by gunterkoenigsmann** [comment]
That is to be expected: On Windows (and on Mac) all files are stored in a directory that is relative to the executable file's path. A possible workaround would be storing things relative to
 - wxStandardPaths::GetExecutablePath() on windows
 - PREFIX+"/share/wxMaxima/" on Linux
 - wxStandardPaths::GetExecutablePath()+"/wxMaxima.app/Contents/Resources" on mac.

Am thinking if we could capsule all paths inside one object.

**Comment by gunterkoenigsmann** [comment]
Should be resolved by commit d3c0f716da5a1d5249a7e877f34afd118f2e91f6

**Comment by gunterkoenigsmann** [comment]
Ok... ...Seemignly it wasn't. Closing this ticket in favour of the new one (#454).
