### ISSUE TITLE
wxmaxima/broadcom-wl-dkms

### ISSUE THREAD

**Issue by meesu** [andrejv/wxmaxima#314]
Hi,

I use wl module (https://aur.archlinux.org/packages/broadcom-wl-dkms) for wireless.

if i have the wl module loaded and i am not connected to the internet then i get following error on console on executing wxmaxima:

Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #\<SB-THREAD:THREAD "main thread" RUNNING {10052E3773}\>

while the wxmaxima status bar displays "Maxima started: Waiting for connection"

If i rmmod the wl module then wxmaxima starts normally without any error. wxmaxima starts normally if i am connected to the net and wl module is loaded.

Other information:
i have the following line in my /etc/hosts:
127.0.0.1	 localhost.localdomain	localhost
the error persists with other variants like:
127.0.0.1	 localhost

**Comment by gunterkoenigsmann** [comment]
Did get hold of a similar laptop. Seems like changing the port fixes the problem.
