### ISSUE TITLE
ctensor stops

### ISSUE THREAD

**Issue by murakamiriyugi** [andrejv/wxmaxima#318]
The function csetup() stops with a wxmaxima message
"Reading Maxima output."

Steps to reproduce:
load(ctensor);
"/usr/share/maxima/5.32.1/share/tensor/ctensor.mac"

csetup();
"Enter the dimension of the coordinate system:"
3 <or any positive integer>
"Do you wish to change the coordinate names?"
n <or y>
"Do you want to1. Enter a new metric?2. Enter a metric from a file?3. Approximate a metric with a Taylor series?"
1 <or any other options>

Here it stops and does not display the statements for the next steps.
Actually, it does not stop per se. One can continue trying to enter the metric 
components. In the background, the system continues to display some
statements but is unable to get the user input. You will see the repititive 
statements after you clicked the interrupt button.

System setup:
Ubuntu 14.04 new install (64 bit)
AMD A10-4655M APU with Radeon(tm) HD Graphics × 4
AMD Radeon HD 7620G (proprietary driver installed)
Wxmaxima 13.04.2
Maxima 5.32.1

**Comment by gunterkoenigsmann** [comment]
Fixed in Commit 58e875afc5194db2b000f0c59bc4481a8940c9b6.
