### ISSUE TITLE
wxmaxima UI sluggish input with ibus

### ISSUE THREAD

**Issue by gregor-b** [andrejv/wxmaxima#334]
Reproduceable on freshly installed Lubuntu 14.04. The wxmaxima UI feels extremly sluggish and skips input if the key is not pressed long enough. However after "sudo pkill ibus" it runs like it used to, so I guess this is the culprit.

**Comment by gunterkoenigsmann** [comment]
I think I have it: Do the following in a terminal:

        sudo apt-get install ibus-gtk

After a reboot the input might work fine again. Reported this as ​https://bugs.launchpad.net/ubuntu/+source/wxwidgets3.0/+bug/1421558
