### ISSUE TITLE
pleases STOP putting in extra spaces when one pastes

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#341]
wxMaxima version: 13.4.0
Maxima version: 5.31.1
Maxima build date: 2013-09-24 09:49:12
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8

As anyone who has experimented with the built in editor it is useless and full of error etc. and one MUST use an external editor lest so even so should be able to do so. NOw when one pastes it puts in one or two extra spaces on every line depending upon whether it is .wxm or .wxmx. It is most troublesome for one to have to always go back in and delete all those extra spaces afterward for lines and lines of program code.

**Comment by gunterkoenigsmann** [comment]
I know what this is: On windows wxMaxima saved the \r\n windows line ending as \n\n in .wxmx files. Since this affected me, too I did fix it in the git master a few weeks ago.
