### ISSUE TITLE
/* forever calculating or forever outputting

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#342]
wxMaxima version: 13.4.0
Maxima version: 5.31.1
Maxima build date: 2013-09-24 09:49:12
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8

wherever 

/* 

appears anywhere in a program
then wxmaxima is either forever calculating or forever outputting one or the other instead of just giving a parsing error as it should. this can be quite frustrating when one forgets to enclose the other side of a comment when buried deep in a long program and does not know what is wrong

**Comment by gunterkoenigsmann** [comment]
With the git head of maxima we seem to have to watch out only for the following two things:
 - A /* that isn't ended by a */ and
 - in the rest of the text: Unmatched " signs. At least I couldn't find a third case involving brackets or parenthesis. wxMaxima might get confsed, though, if maxima produces unmatched parenthesis.

The question is what we have to do if we encounter such a cell. I hate excel always popping up some dialogs in this case. Would be a notification in the status bar and a clear of the evaluation queue would be a better alternative?

**Comment by gunterkoenigsmann** [comment]
Closed with commit 14ddd686375bcb988cb866c25cf6bc3d62ec80e6.
