### ISSUE TITLE
AltGr- and Strg-key do not works!

### ISSUE THREAD

**Issue by Bauhardt** [andrejv/wxmaxima#346]
Hallo,

AltGr- and Strg-key do not works in wxMaxima.
I use Ubuntu 14.04. 

Best Regards

Wolfgang

wxMaxima version: 13.4.0
Maxima version: 5.32.1
Maxima build date: 2014-01-10 01:52:55
Host type: x86_64-unknown-linux-gnu
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.10

**Comment by gunterkoenigsmann** [comment]
Now I can reproduce it again with the current git but am not sure if it is the problem we are searching for: For me the Ctrl key actually works when used as Ctrl+C, Ctrl+V or Ctrl+S. But Ctrl+1 no more adds a text Cell and Ctrl+2..4 fail, too.

**Comment by gunterkoenigsmann** [comment]
I think I finally got what triggers it: On my computer all hotkeys work that correspond to a string in wxMaximaFrame.cpp that begins with an &.
Hotkeys that correspond to strings that have the & somewhere in the middle won't work. Feels like being a wxWidgets bug, though, that.

**Comment by andrejv** [comment]
Do you build wxWidgets form source?

There is a samples/menu/menu.cpp example included. If you can reproduce the behaviour there, this should be reported to their bug tracker.

**Comment by gunterkoenigsmann** [comment]
Did use the version that came with Ubuntu. But will try to build it from source tomorrow.

**Comment by gunterkoenigsmann** [comment]
Good idea, that:
 - Built wxWidgets from source and compiled anew. Now wxMaxima works fine including all key combinations except of F1 and Ctrl+1. Ctrl+2 works, though.
 - Changedbuilt-in Ctrl+1 to Ctrl+q. It is definitively the key combination: For Ctrl+q the same code works. 
 - Changed a key combination in samples/menu/menu.cpp to Ctrl+1. Ctrl+1 doesn't work here, either.
 - Started emacs and typed Ctrl+h Ctrl+k Ctrl+1. Emacs tells that Ctrl+1 isn't currently bound to any function => my window manager seems to pass this key combination to the application. Weird.
 - Re-installed the version of wxWidgets Ubuntu provides and recompiled wxMaxima. All combinations except of F1 and Ctrl+1 work. Did Ubuntu leave out a vital file? Had the same thing once with MS Project.
 - Removed the i7n from the "insert text cell" menu item, just to be sure. No change this time.

Weird.

**Comment by gunterkoenigsmann** [comment]
Ok... ...got it: 

        sudo apt-get install ibus-gtk

solves this issue. Did report it to wxWidgets - and for a temporary workaround to Ubuntu so the experts for the framework can solve the problem.
