### ISSUE TITLE
Latex output uses \, instead of \cdot

### ISSUE THREAD

**Issue by lentzi90** [andrejv/wxmaxima#351]
Exported *.tex files have "\," insted of "\cdot" in output cells. This causes errors when trying to compile.

The minus signs also causes some problems since wxmaxima prints the "long minus" "–" instead of this "-", wich latex actualy prints as a long minus in math environments.

I'd **love** to fix these issues my self if someone can point me in the right direction. I have no idea as to where I should start looking!

**Comment by gunterkoenigsmann** [comment]
Did find a example where the new behavior does look strange:

        C_GD*diff(U_DS(t),t)

will be converted to LaTeX as a thing that looks slightly like the following ASCII art:

        d
      ---- * C_GD(t)
       d*t

dt (without the center dot) would have ben the better nominator. The question now is: I suspect that there isn't an ideal way to represent a multiplication and we now have chosen the better of the two possibilities. Or do we need to add additional logic in this case and there is actually a way of determining which representation of the multiplication operator is the best? Am not completely sure in this case.

**Comment by gunterkoenigsmann** [comment]
787f24b4e9d677b3637af2b79684c6b954a779c9 adds a heuristic that works around this case. Hope we have found the optimum way now.
