### ISSUE TITLE
Subscripts should be displayed inside exponents, not below them

### ISSUE THREAD

**Issue by endolith** [andrejv/wxmaxima#374]
In my example for https://github.com/andrejv/wxmaxima/issues/373, I noticed the subscript and superscript are on top of each other:

![subscript example](https://cloud.githubusercontent.com/assets/58611/5351866/ccfdd016-7f2a-11e4-9a6c-ab2f0592cb3a.png)

The LaTeX is `{G}_{0}^{2}`.  It would be better to use `{{G}_{0}}^{2}`, with exponent applied to entire variable and subscript:

![superscirpt subscript](https://cloud.githubusercontent.com/assets/58611/5351950/d78cf498-7f2b-11e4-9e29-a58c99b70bfb.png)

(Also why does Copy LaTeX always add `\[` and `\]` around the code?  These are not correct latex as far as I know.  `Undefined control sequence \[`.  Is this intentional or a separate bug?)

**Comment by gunterkoenigsmann** [comment]
Fixed in commit 2609416ce5a12ee3bf506fa4d5ebba19497872ca.
