### ISSUE TITLE
wx-cd bug

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#393]
Changing the directory with wx-cd to a drive different from c: breaks plotting.

**Comment by gunterkoenigsmann** [comment]
Added the workaround to the config menu in commit c3e2fc910a1fbe5d91037829dd4366bfb411f582. But after throughly looking into the issue I would call this a maxima bug: Maxima for some operations uses all components of the lisp representation of the path to a file. For some operations it drops the drive part instead. There were a few mails in maxima's mailing list about the fact that the help system does only work on c:. Robert Dodier fixed this part of the issue then.

**Comment by gunterkoenigsmann** [comment]
Maxima can now plot regardless of the drive and directory it is working in => Closing this issue. The option to make maxima not chdir() into the current directory is still necessary on some lisps, though, if the path contains unicode characters (see #674).
