### ISSUE TITLE
compiliation on Debian 7 fails

### ISSUE THREAD

**Issue by daute** [andrejv/wxmaxima#396]
Compilation of the current SVN fails on Debian 7 with messages like:

wxMaximaFrame.o: In function `~wxMaximaFrame':
wxMaximaFrame.cpp:73: undefined reference to `wxAuiManager::SavePerspective()'
wxMaximaFrame.cpp:82: undefined reference to `wxAuiManager::UnInit()'
wxMaximaFrame.cpp:71: undefined reference to `wxAuiManager::~wxAuiManager()'

(some more error messages follow...)

Adding "--libs all" instead of "--libs" in the wx-config call in configure solves that problem:

configure line 3846:
      WX_LIBS=`$WX_CONFIG_WITH_ARGS --libs all`

configure line 3850:
      WX_LIBS_STATIC=`$WX_CONFIG_WITH_ARGS --static --libs all 2>/dev/null`

(yes, I know, "configure" is generated by the GNU automake system, so the fix must probably be done somewhere else...)

Best regards, Wolfgang

**Comment by gunterkoenigsmann** [comment]
It is certainly the configure.ac file where additional modules have to be added to the following line:

AM_PATH_WXCONFIG([3.0.0], [wxWin=1], [wxWin=0], [xml,html,adv,aui,core,net,base])

**Comment by andrejv** [comment]
The wxAuiManager in defined in the aui library which is correctly included in configura.ac.

This looks like a misconfiguration on you system. Can you post the linking part of the build.

**Comment by daute** [comment]
You can find a typescript of my compiliation process at:
http://wolfgang.dautermann.at/maxima/wxmaxima-compileproblem-typescript.txt

First the script prints itself (so you can see what steps are done), then comes the compiliation of wxWidgets (rather long) and at the end the (failing) compiliation of wMaxima.

Best regards, Wolfgang

**Comment by andrejv** [comment]
The correct call to wx-config should be

    WX_LIBS=`$WX_CONFIG_WITH_ARGS --libs xml,html,adv,aui,core,net,base`

(these are the libs requested by configure.ac). Since you don't have them, you are probably picking up a wrong AM_PATH_WXCONFIG macro. Maybe you have some old wxwin.m4 somewhere?

Maybe you should change the line

    cp wxwin.m4 aclocal.m4 ..

to

    cp wxwin.m4 ../acinclude.m4

in your script.

**Comment by daute** [comment]
Oops. Thank you. 
My fault. 

Instead of "You will also need to copy the file wxwin.m4 to acinclude.m4 in the wxMaxima source directory." I 've read and implemented "You will also need to copy the file wxwin.m4 and acinclude.m4 to the wxMaxima source directory." (and it worked on Opensuse without problems...).

Sorry. It works now.
