### ISSUE TITLE
with_slider and with_slider_draw plots can't be loaded from .wxmx files

### ISSUE THREAD

**Issue by fsenese** [andrejv/wxmaxima#397]
To reproduce the problem, in a fresh wxMaxima window, type
   ` (%i1) with_slider(
              t, makelist(i/109, i, 0, 200),
              [cos(x)*sin(x*t)], [x,0,40]
          );`

Save as a .wxmx file. Close, and try to reload the .wxmx file. wxMaxima refuses to load the plot, saying "can't automatically determine the image format for non-seekable input"

**Comment by gunterkoenigsmann** [comment]
Did encounter this with two files on my win7 box. But other files worked fine so I thought I did break them myself.

On 9. Januar 2015 17:35:25 MEZ, fsenese <notifications@github.com> wrote:
>To reproduce the problem, in a fresh wxMaxima window, type
>   ` (%i1) with_slider(
>              t, makelist(i/109, i, 0, 200),
>              [cos(x)*sin(x*t)], [x,0,40]
>          );`
>
>Save as a .wxmx file. Close, and try to reload the .wxmx file. wxMaxima
>refuses to load the plot, saying "can't automatically determine the
>image format for non-seekable input"
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/397

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by andrejv** [comment]
Does loading normal plots work OK?

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On my linux box it does. And with the current trunk I am able to
reconstruct the slider problem on the same box.

Weird...
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJUsDtHAAoJEFyGwOQhHVuOouoQAJ8eFuqpevbxZ8IEekvDID5B
hDSefWZADYJwcf5kW9YvMXN4tqdIkfFK7g+dKfwqVaIVkGdyBwR6f67scIRwkslF
awL3kIaOQ4FM+mPMYH79tljPnzMHlgFE5zjmOv36wFu3peWLH1fZDGN6iRSaMTI9
Yq1FVW2P60c0e8tJEd/KJHKfVG751T60pi8Mvtu07b85/Wir7hTOt/zcQQ5mJfie
whiWciIGpcXI0CB1h9gf+940FbUNnRUXendk95ndvpLiL9gtCGplytOe1qcOQJuU
mMZTfTfWlepUEV4aYxYosX7m3JY2wzpYNAuazfbY0MHQhMacptoiQMtKqbdFoYhC
bhn/9nAsEEL8YHiYEMvPkAKfXOAwtjeFk2pzJU8EKX43naheb5C/4BVWEu1WQ2M9
Tw5JUIBKQzf6IZg3yrY8pI/udB4Jkrf+rrsHaMVET3yW8ctS+V8FUozMXiwHpbaL
CXpR44V7+8LKpvGiCqKLbapIPBNRQHYtI4tVPWBR3iKsYYAwh6Nc7vJ0CurQyEx3
0UycXnZuPqOpUfFb3i3VC9D5sIMCE0WtSMdI7f0/3M12lTrXPUqOamROJs5eXa4N
BaHpyaYwKpRuoU8e0KQF79L0z7r6yx9pPV+6mPO/+UneuvRYOF6QdQLkcJuNySAu
YVaC3/OUjU1W6+5mIPCx
=3I0K
-----END PGP SIGNATURE-----

**Comment by andrejv** [comment]
Fixed in 0ae44054a5250cd935d078ca7344dd9d12221399.
