### ISSUE TITLE
error in snippet

### ISSUE THREAD

**Issue by rchar4** [andrejv/wxmaxima#398]
this snippet gives an error in wxmaxima, but works fine in xmaxima
(%i1) load(to_poly_solve)$
 eq2 : sqrt(x-1) - sqrt(x+1) + 1 = 0$
 to_poly_solve(eq2, x);

seems to be an old bug as i am able to reproduce it in older version 5.34.1
i am running maxima on windows 7
the file grobner.lisp in my install is in:
C:\Program Files (x86)\Maxima-5.35.1.1\share\maxima\5.35.1.1\share\contrib\Grobner

Loading maxima-grobner $Revision: 1.6 $ $Date: 2009-06-02 07:49:49 $
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
loadfile: failed to load C:/Program Files (x86)/Maxima-5.35.1.1/share/maxima/5.35.1.1/share/contrib/Grobner/grobner.lisp
 -- an error. To debug this try: debugmode(true);
to_poly_solve: to_poly_solver.mac is obsolete; I'm loading to_poly_solve.mac instead.
Loading maxima-grobner $Revision: 1.6 $ $Date: 2009-06-02 07:49:49 $
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
loadfile: failed to load C:/Program Files (x86)/Maxima-5.35.1.1/share/maxima/5.35.1.1/share/contrib/Grobner/grobner.lisp
 -- an error. To debug this try: debugmode(true);

**Comment by andrejv** [comment]
This issue has been fixed in maxima git.
