### ISSUE TITLE
Make the slideshow speed configurable on a per-slideshowcell basis.

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#400]
I would be willing to write the C++ code to support that. But I don't have too much insight to the lisp code of the slider commands and therefore am not sure how to add such a graphics and draw option.

**Comment by andrejv** [comment]
The framerate can now be changed with the `wxanimate_framerate` option variable.

    wxanimate(a, 10,
        sin(a*x), [x,-5,5]), wxanimate_framerate=6$

**Comment by gunterkoenigsmann** [comment]
That was fast!
Added a few lines to the online manual (35d260de2a539e3ce214929d195c71199165d7bc) and think it is time to close this issue.
