### ISSUE TITLE
Trouble with ASCII-Codes above 127

### ISSUE THREAD

**Issue by SchnPa** [andrejv/wxmaxima#405]
wxMaxima seems to be in trouble with ASCII-Codes above 127.

The statement ascii(128); for Example produces a message, that the xml-file is incorrect.

In the opposite direction the statement cint("ü"); gives the following error message:

Maxima encountered a Lisp error: 
decoding error on stream
 #<SB-SYS:FD-STREAM for "socket 127.0.0.1:54159, peer: 127.0.0.1:4010"
   {13FAE991}>
 (:EXTERNAL-FORMAT :ASCII):
   the octet sequence (195) cannot be decoded.
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.

-------------------------------------------------------------
wxMaxima version: 13.4.0
Maxima version: 5.30.0
Maxima build date: 2013-04-22 13:48:12
Host type: i386-apple-darwin11.4.2
Lisp implementation type: SBCL
Lisp implementation version: 1.0.55.0-abb03f9

-------------------------------------------------------------

Thanks for looking at this.
Patrik

**Comment by andrejv** [comment]
Put this line into your ~/.sbclrc file (create it if it does not exist).

    (setf sb-impl::*default-external-format* :utf-8)

**Comment by SchnPa** [comment]
Now both statements have the expected behavior. Thanks for your help.

Patrik

**Comment by TufanSirin** [comment]
Where should I put this (setf sb-impl::*default-external-format* :utf-8) My OS is windows 7...
Can you tell me step by step please :))))

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512



On 14.02.2015 18:38, Tufan Şirin wrote:
> Where should I put this (setf sb-impl::/default-external-format/
> :utf-8) My OS is windows 7... Can you tell me step by step please
> :))))
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/andrejv/wxmaxima/issues/405#issuecomment-74384273>.
>
> 
That's a good question: I actually don't know where the sbcl packaged
with the maxima installer on windows does expect this file to be. So
two new ideas:

1.) Start the .wxmx file with the following math cell:

        :lisp (setf sb-impl::/default-external-format/ :utf-8)

...and make sure that this cell is evaluated before you try to save
the file. If that works let me know.

2.) If you right-click on a .wxmx file that gives this error in the
windows explorer, choose the "Properties" menu button, and tell what
is written in the "General" tab as "location" - I hope this will help
me to reconstruct the problem on a windows computer as soon as I get
hold of one. If the dialogues and buttons are named diversely on your
computer an image of the dialogue can be found at
http://www.comaroundfree.com/guides/4413/images/091204115209_1.png

Kind regards,

 Gunter.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQJ8BAEBCgBmBQJU37euXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOhEUQALPZ9WzpJkwEOXFSJK1DSh49
nUYgkHUPr10CVK8OD7OWN5BWXbsSqCPOSg4GRjOkytNHx8iNVcfeaQzaA9pVvxWp
xReNTPTJMr0x8i0485bKH3g12wl2DYJacjEdhWaoh74BhFIH85yWs6gIuFNbVBjZ
6gtbqBh8u7mK8hmrFqqdwqxsvgl/eGuvNGDrkI49DJPQYAPAjfZOdDiDxPlkvv3J
M/cEcJchMChmznXUT8NReomr1sZRMvq55TvVRh+5KSPPEvXFYX0Vt192FsMhICdT
8OYuj9NaxsbixM+/fl0j6f20spq8CB1rM2uojhCAfZvgfgchHXriPdE+FeNROrX4
BNk/RzF/RSnmAa9aYOw8zzuAh9w0cLcLk9LxB6MY+mBty4O7oF1NxmSPXP0Crw+H
U44Z7IYZ32BBSuuxkcn6QywuSaJ7WMKJNTZUr7vzOdVOgVDDrOhtHeKOamXjjQgQ
ef2dIUm0uw982vC0eF3X6ia2YCbVmrVf7kSYYirBTyAheLsCNB7GuAHFrFG1RSdG
OrFBb1K9y60i9CJgDyyEMNFqTL4P3z8cp97bNbAicIzqLWL82RyB7M711bJ0J6uu
gQ6jyvAaUmnB5QLazqbEWw/paBLiqueyp/o6enBgmcE584O3N6fsN89c3q3GKhm3
ESVqsfU629pPR6cdIzbk
=YOxu
-----END PGP SIGNATURE-----

**Comment by TufanSirin** [comment]
Again It is me. :)... I have another PC , OS is windows 7 (It is turkish,too). Maxima (sbcl) is working properly....
What is the difference between them... The PC in which Maxima gives error, I have installed on it TexMacs..... And I d tried to run Maxima through it.... The problem has occured after that... I have unistalled it but maxima was out of order.....Be aware this conflict... I think it will be helpfull for you...
(http://www.texmacs.org/Download/ftp/tmftp/windows/TeXmacs-1.99.2-installer.exe.)
What did I do the PC that Maxima does nt work properly... I have installed two 5.34.1 too .. It is working 
properly now :)) thanks for getting tried for me

**Comment by gunterkoenigsmann** [comment]
That's good thinking. But in my experience two win7 installations will behave differently even when installed from the same image and on identical machines so this could still be a false positive. Even if Emacs might be using sbcl and adding stuff to it's init files....

.... Did at least find out how to find out where the init file of sbcl is kept. http://stackoverflow.com/questions/2245854/sbcl-initialization-file claims it can be determined by typing:

        :lisp (SB-IMPL::USERINIT-PATHNAME)

If this works please tell us: I don't have an own windows machine that I am free to use.

Kind regards,
  Gunter.



Am 14. Februar 2015 23:21:43 MEZ, schrieb "Tufan Şirin" <notifications@github.com>:
>Again It is me. :)... I have another PC , OS is windows 7 (It is
>turkish,too). Maxima (sbcl) is working properly....
>What is the difference between them... The PC in which Maxima gives
>error, I have installed on it TexMacs..... And I d tried to run Maxima
>through it.... The problem has occured after that... I have unistalled
>it but maxima was out of order.....Be aware this conflict... I think it
>will be helpfull for you...
>(http://www.texmacs.org/Download/ftp/tmftp/windows/TeXmacs-1.99.2-installer.exe.)
>What did I do the PC that Maxima does nt work properly... I have
>installed two 5.34.1 too .. It is working 
>properly now :)) thanks for getting tried for me
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/405#issuecomment-74394515

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.
