### ISSUE TITLE
The slider functions don't substitute the slider value inside functions

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#411]
Not sure if this is a bug:

In the maxima mailing list there was a question about the following function (http://sourceforge.net/p/maxima/mailman/message/33373967/):

        T(n1,n2,n3,omega,c):=(4*n1^2)/((n1+n3)^2*(cos(n2*d*omega/c))^2+(n2+n3)^2*(sin(n2*d*omega/c))^2);

Directly with_slider_plotting it with d assigned to the slider fails:

        with_slider(
            /* first two arguments are the parameter and its range */
            d,makelist(10^(-4)*i,i,0,10),
            /* the following arguments are for plot2d command */
            T(1,2,1,omega,3*10^8),
            [omega,10^11,10^13],[y,.4,1.1]
        );

Substituting d by something else that is assigned to the slider works instead:

        with_slider(
            /* first two arguments are the parameter and its range */
            d_temp,makelist(10^(-4)*i,i,0,10),
            /* the following arguments are for plot2d command */
            at(T(1,2,1,omega,3*10^8),d=d_temp),
            [omega,10^11,10^13],[y,.4,1.1]
        );

There is a logic that determines that a variable isn't defined and this logic is new to maxima so I first suspected this to be the cause of the error message. But it seems like this is reproducible with old maxima versions, too.

Not sure, if this is a bug, though, or if there is a deeper truth behind it.

Kind regards,

     Gunter.

**Comment by andrejv** [comment]
I don't think this is a bug in wxmaxima. The issue is how maxima evaluates and whent in substitutes the expression. It first substitutes d and then evaluates.

You can fix this by forcing easly evaluation:

    with_slider(
            /* first two arguments are the parameter and its range */
            d,makelist(10^(-4)*i,i,0,10),
            /* the following arguments are for plot2d command */
            ''(T(1,2,1,omega,3*10^8)),
            [omega,10^11,10^13],[y,.4,1.1]
        );

or making the d explicit in the definition of T: `T(n1,n2,n3,omega,c,d):=...`

**Comment by gunterkoenigsmann** [comment]
The question is if we
 -  should somehow automatically force evaluation in these cases: All of my collegues managed to trigger this error in the first hour after getting to know that there is a with_slider command - and then were hopelessly lost with the error message thy got.
 - are even able to do so from the wxMaxima side
 - if this has some subtle side effects we don't want to deal with
 - or if we should at least add your solution to the documentation: It is actually a much better solution than the one I am using normally.

**Comment by andrejv** [comment]
This is acrually a very common issue for maxima commands. The same thing happens I think with

    makelist(T(...), d, 1, 10)

It is not something we should try to correct.

**Comment by gunterkoenigsmann** [comment]
Then this is another bug we can close. Will add a few lines to the documentation later. 
Kind regards,

     Gunter,
