### ISSUE TITLE
Input Problems

### ISSUE THREAD

**Issue by gonenc96** [andrejv/wxmaxima#415]
While I am typing in wxmaxima, it is not taking my input sometimes. For example when I am tring to write "come here" it shows "comehere" or "come hee" or whatever. My computer is a little bit old but it was working when I was using Lubuntu 13.10. After the upgrade to 14.10 I have been facing this problem.

-------------------------------------------------------------
wxMaxima version: 13.4.0
Maxima version: 5.33.0
Maxima build date: 2014-08-05 11:26:40
Host type: i686-pc-linux-gnu
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.10
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
Try to do the following on a terminal:

        killall ibus-daemon

When ibus was new to ubuntu it somehow had problems communicating with wxWidgets that does the I/O for wxMaxima.

Kind regards,

     Gunter.

**Comment by gunterkoenigsmann** [comment]
There might be a second thing that might work if this one fails:
        sudo apt-get install ibus-gtk

After a reboot the input might work fine again. Reported this as ​https://bugs.launchpad.net/ubuntu/+source/wxwidgets3.0/+bug/1421558
