### ISSUE TITLE
With wxplot_pngcairo:true, line styles are different

### ISSUE THREAD

**Issue by maedoc** [andrejv/wxmaxima#419]
I'm trying to plot several lines with the same style, black, 

```maxima
set_random_state(make_random_state(42)) $
n : 1000 $
t : makelist(i, i, n) $
x : random_normal(0.0, 1.0, n) $
wxplot2d([[discrete, t, x/3], [discrete, t, x/3 + 1], [discrete, t, x/3 + 2]],
    grid2d,
    [yx_ratio, 0.5],
    [box, false],
    [color, black]
);
```

Using `plot2d` or `wxplot_pngcairo: false;`, the result is correct, all lines have solid style and black, while with `wxplot_pngcairo: true;`, the resulting lines have different dash patterns.

**Comment by gunterkoenigsmann** [comment]
I think that is the intended behaviour: Gnuplot tries to mane the individual plots discernable from each other when it got the possibility to do so. With draw it is possible to manually select which line styles to use and therefore for exsmpke to make all curves solid. But I never use plot so I am not sure if that is the there, too 

Kind regards,

   Gunter

Am 12. Februar 2015 15:10:48 MEZ, schrieb maedoc <notifications@github.com>:
>I'm trying to plot several lines with the same style, black, 
>
>```maxima
>set_random_state(make_random_state(42)) $
>n : 1000 $
>t : makelist(i, i, n) $
>x : random_normal(0.0, 1.0, n) $
>wxplot2d([[discrete, t, x/3], [discrete, t, x/3 + 1], [discrete, t, x/3
>+ 2]],
>    grid2d,
>    [yx_ratio, 0.5],
>    [box, false],
>    [color, black]
>);
>```
>
>Using `plot2d` or `wxplot_pngcairo: false;`, the result is correct, all
>lines have solid style and black, while with `wxplot_pngcairo: true;`,
>the resulting lines have different dash patterns.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/419

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.
