### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by TufanSirin** [andrejv/wxmaxima#420]
I had a problem with saving the .wxm document in sbcl.maxima 
Maxima encontered a lisp error: CP1254 stream decoding error on #<SB-sys: FD-STREAM FOR
"SOCKET 127.0.0.1:52125,PEER:127.0.0.1:4010" {263DF679}>: THE OCTET SEQUENCE # (158) CANNOT BE CODED..

**Comment by gunterkoenigsmann** [comment]
I assume this might be related tp be the following bug: https://github.com/andrejv/wxmaxima/issues/405: There are many ways to express language-specific characters like umlaute, characters with a cedillia, the i without dot and similar. and sometimes it is non-trivial to make all routines of all programs agree on how to represent them.
If the error only happens on save (and perhaps on opening te file again) I would say that wxMaxima is trying to instruct maxima to change its working directory to the one the file is in - and it doesn't understand how to handle the file or the directory name. So Choosing other file and directory names would probably be a workaround.

Kind regards,

     Gunter.

**Comment by TufanSirin** [comment]
My problem still exists......

**Comment by gunterkoenigsmann** [comment]
Another idea: Windows in some countries saves the user's files, the desktop and similar in a folder containing strange characters even it will show "own files" or "desktop" as the location. Could you right-click on a file in the windows explorer, select the properties button in the menu that appears and tell us the whole path the file is in according to this dialogue: at least on win7 this dialogue still showed the real path to files.

Kind regards,

     Gunter.

Am 13. Februar 2015 10:05:24 MEZ, schrieb "Tufan Şirin" <notifications@github.com>:
>My problem still exists......
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/420#issuecomment-74224117

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by andrejv** [comment]
You probably need to change the external-encoding for sbcl.

Put his line in the file `.sbclrc` in your home directory:

    (setf sb-impl::*default-external-format* :utf-8)

Maybe the encoding needs to be changed to something other than `:utf-8` though.

**Comment by gunterkoenigsmann** [comment]
Finally found the error: wxWidgets wants the location of .zip files with unicode names to be url-encoded. If the new code is able to find all font issues we had, as well I hope we no more have language-specific bugs.
