### ISSUE TITLE
saves regular session files with no report of errors but cannot open them again

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#421]
Will try attach files. The ones that have 'err' somewhere in the title are the ones maxima saved from a session and one cannot bring back up. Same thing on two different computers. I did not put in any control characters or anything. Now for 

example the one titled 
untitled5.wxmx that will will load and as long as no code is executed then it can be saved and brought back up as original. BUT just run the top 2 cells of input in this file and save it and it truncates it to a very small 1kb such 

untitled5err.wxmx which cannot be brought back up so you lose everything. Maxima should never save a file with no error message or at all if it is going to save it in such a way as cannot be opened again. This is not specific to any 

computer as tried it on different computers.
Where can i attach the files.

**Comment by gunterkoenigsmann** [comment]
Didn't get the attachments. But you can send them to me as wxMaxima at Physikbuch.de. I am rather sure you encountered issue #405 (or its probable duplicate #420): The lisp shipped with the current maxima for windows does output special characters (like the µ) in a way that can be displayed - but won't result in a valid .wxmx file. Am currently adding this case to the test bench to avoid that it reappears in latter releases.

**Comment by gunterkoenigsmann** [comment]
If you want to research the problem yourself: wxMaxima normally tells which line of contents.xml it has a problem with. If you rename your .wxmx file to .zip after opening the file you will have access to content.xml and can see which line gives the problem.

**Comment by gunterkoenigsmann** [comment]
Did find the file at https://sourceforge.net/p/maxima/bugs/2906/attachment/untitlederr.wxmx. It unfortunately doesn't contain any real data.

**Comment by gunterkoenigsmann** [comment]
Am confident that this problem is solved by changing the recursive function calls into loops, the xml saving enhancements and the new way of saving via backup files => closing this bug for now.
