### ISSUE TITLE
does not ever return from ldisp.... or likely anything else when make this error

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#422]
does not ever return from ldisp....
  
 
wxMaxima version: 13.4.0
 Maxima version: 5.31.1
 Maxima build date: 2013-09-24 09:49:12
 Host type: i686-pc-mingw32
 Lisp implementation type: GNU Common Lisp (GCL)
 Lisp implementation version: GCL 2.6.8
 
ldisp(['n"])
 
maxima is forever calculating. NOrmally i make this type of error deep in some lengthy program file difficult to find and since maxima does NOT give me any syntax error but is just forever calculating it is most difficult to find and one thinks there is something else wrong. Also get the same type of error
using such as \* ............... where one forgot to close the comment.

**Comment by gunterkoenigsmann** [comment]
This looks to me like bug #342 and #358 and like being a fine example of the two.
Fixing them will be not trivial, though, I suppose: we talk to maxima through a network connection and have to analyze the contents of the packets we get to determine which is the last packet of of the current output of maxima. Currently this will fail on unmatched parenthesis (for supporting that we would have to update the display and export routines so they are able to support them, too, first). And it will fail on not-closed comments, too: maxima will actually wait forever in this case until it encounters a close comment sequence. 

Kind regards,

   Gunter.

Am 13. Februar 2015 18:42:31 MEZ, schrieb zmth <notifications@github.com>:
>does not ever return from ldisp....
>  
> 
>wxMaxima version: 13.4.0
> Maxima version: 5.31.1
> Maxima build date: 2013-09-24 09:49:12
> Host type: i686-pc-mingw32
> Lisp implementation type: GNU Common Lisp (GCL)
> Lisp implementation version: GCL 2.6.8
> 
>ldisp(['n"])
> 
>maxima is forever calculating. NOrmally i make this type of error deep
>in some lengthy program file difficult to find and since maxima does
>NOT give me any syntax error but is just forever calculating it is most
>difficult to find and one thinks there is something else wrong. Also
>get the same type of error
>using such as \* ............... where one forgot to close the comment.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/422

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by andrejv** [comment]
You have a syntax error and an unclosed `"`. If you send maxima another `"`, maxima returns with an error.

**Comment by gunterkoenigsmann** [comment]
That is right. But I sometimes wait for maxima to finish for a long time, too, before I find out that I made an error here even if I tend to enable the "matched parenthesis" feature. Did add the cases I encountered so far to issue #342 so they won't get lost.

**Comment by gunterkoenigsmann** [comment]
Fixed with commit 14ddd686375bcb988cb866c25cf6bc3d62ec80e6.
