### ISSUE TITLE
wxMaxima 14.12.1 freezes with simple input on windows

### ISSUE THREAD

**Issue by arbolis** [andrejv/wxmaxima#424]
As discussed there: https://sourceforge.net/p/maxima/bugs/2904/,
Input: a:sqrt(b^2-4c(d-e)); 
freezes wxMaxima 14.12.1 on windows 7 x64 edition.

**Comment by gunterkoenigsmann** [comment]
Did stumble upon that around new year => Is fixed in git.

**Comment by arbolis** [comment]
Thanks :)
