### ISSUE TITLE
Wrong operator precedence during Copy+Paste: (1-x)/x becomes 1-x/x

### ISSUE THREAD

**Issue by TomasRiker** [andrejv/wxmaxima#429]
Enter the following into wxMaxima:

    (1 - x) / x;

Now select the entire expression by clicking it with the mouse, and press `Ctrl+C`.
In a new line, press `Ctrl+V`. The expression will be wrongly pasted as:

    1 - x / x

It looks to me like the operator precedence is wrong, and wxMaxima thinks that there are no parenthes needed.

(running wxMaxima version 14.12.1)

**Comment by andrejv** [comment]
This has already been fixed in git.
