### ISSUE TITLE
Allow to add cells while maxima is running?

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#431]
Now that we have a button that allows to jump back to the cell that is currently being evaluated...

Since wxMaxima is working on events sequentially and there is no risk of the editor changing pointers to list items while the evaluation process tries to read them... ...would it be possible to allow adding new cells instead of only allowing to edit existing ones while maxima is still evaluating?

**Comment by andrejv** [comment]
The main concern with editing while maxima is computing is what should wxmaxima do when maxima asks a question. If you the user is editing a new cell then he must somehow be interrupted and asked to answer the question.

**Comment by gunterkoenigsmann** [comment]
Perhaps I have involuntarily added the first step of a solution: 
 - When the user scrolls away from the evaluation process MathCtrl::m_followEvaluation is set to false and the yellow button lights up that makes wxMaxima scroll to the currently evaluated cell again
 - When Maxima has a question the yellow button turns red to indicate that this is the case. When the user wants to answer the question all he has to do is to press this button and he is returned to the cell his attention is needed in.

...all we would need to do to enable that would be
 - to only use keypresses as an answer to maxima's questions when the currently selected group cell is the one with the question. 
 - to change the code so editing is enabled otherwise.
 - and to make sure that pressing the "follow" button actually selects the group cell pointed to by m_WorkingGroup instead of just scrolling to it.
 - And (I don't know when the next official release is planned) this looks like a big change that needs some testing. At least when an outsider to the project like me that surely has overlooked one or two obvious pitfalls would try to do this all. For example I haven't looked into the editing enabled" logic yet and still haven't found out how the vertical caret really works.

**Comment by gunterkoenigsmann** [comment]
Did add a branch named EditWhileEvaluating that tries to enable this mode. 

What I still haven't found out how to add was
 - If the button that tells that maxima has got a question is hit maxima returns to the right position. But if the user enters text it still doesn't end up in the output cell or in maxima.
 - If the user manually clicks on the cell the question is in this still doesn't happen, neither.

**Comment by gunterkoenigsmann** [comment]
I believe my branch works now. Will test it a little more before merging it.

**Comment by gunterkoenigsmann** [comment]
Fixed in commit f1b1dde5f9e8cc56a1fb750aff6691e85243516c.
