### ISSUE TITLE
wxWidgets asserts

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#434]
The following actions trigger wxWidgets asserts with the testbench:
 - Evaluate all cells
 - Export to HTML
 - Export to TeX

Perhaps this should be fixed prior to the next release.

wxbuild_info();
wxMaxima version: 14.12.0
Maxima version: branch_5_35_base_177_g95c186b
Maxima build date: 2015-02-21 09:35:53
Host type: x86_64-unknown-linux-gnu
System type: Linux 4.0.0-040000rc2-lowlatency X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.2.4.debian

**Comment by gunterkoenigsmann** [comment]
The "evaluate all cells" issue is fixed in commit 41f9be4a9305689a983e4be6c4ea4944c31c0d6a. But for the 2nd issue I am at loss what it is caused by.

**Comment by andrejv** [comment]
The HTML export is fixed with cef5f7e7.
