### ISSUE TITLE
Only partial display of a set with extra pair of ()

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#438]
The following expression gets truncated on my computer:

    ({acre = 4840*yard^2}(
     ));

This is bad since it hinders the following from working:

    load(ezunits);
    known_unit_conversions();

wxMaxima version: 14.12.0
Maxima version: branch_5_35_base_177_g95c186b
Maxima build date: 2015-02-21 09:35:53
Host type: x86_64-unknown-linux-gnu
System type: Linux 4.0.0-040000rc4-lowlatency X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.2.4.debian

**Comment by gunterkoenigsmann** [comment]
This is how far I got:
 - maxima gives the correct output if run from a console
 - wxMaxima doesn't only display only half of the cell. It does also only save the displayed part to .wxmx

=> a parser error? Might be a long shot, that, though.

**Comment by andrejv** [comment]
Why would you input `known_unit_conversions()`. `known_unit_conversions` is a constant, not a function.

**Comment by gunterkoenigsmann** [comment]
You are right => Removing the "release-critical" and am willing to remove the "bug", as well, if you decide so.

**Comment by gunterkoenigsmann** [comment]
This issue has been resolved in the meantime.
