### ISSUE TITLE
The "play" button stops on my windows PC

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#440]
When I press the "play" button for an animation on Windows it seems like the UI keeps updating with a high frequency, then the animation stops. Don't know if I have caused this with commit 22df7ea9afef9bfc03fd1cb2706e893c0f16fb40. But I seem unable to find the reason.

**Comment by gunterkoenigsmann** [comment]
I *think* I have fixed this with commit 66969b90c57acca479ed0fead0e52b860ee4e7d8. Will verify next week.

**Comment by gunterkoenigsmann** [comment]
Seems to me like MathCtrl::Refresh() does un-select the currently selected cell on windows while it doesn't do so on linux. 8cf29b322b40e1fc720ab01f7802643c9fc5f1ba is another go to awoid this problem.

**Comment by andrejv** [comment]
I'm guessing this is fixed now?

**Comment by gunterkoenigsmann** [comment]
You are right: It is.
