### ISSUE TITLE
  Hardcoded icon path in launcher for GNU/Linux systems

### ISSUE THREAD

**Issue by palob** [andrejv/wxmaxima#441]
Hi,

currently the icon path specified in the created launcher file is set to: 
*Icon=@prefix@/share/wxMaxima/wxmaxima.png* or
*Icon=wxmaxima.svg*

(see https://github.com/andrejv/wxmaxima/blob/11ba430a40787c5c2942f5c7e0dc4c88aa6d4291/data/wxMaxima.desktop.in      and      https://github.com/andrejv/wxmaxima/blob/840a33547ed8ee01a605affb64a9345bb6f71c94/wxmaxima.desktop)

This prevents icon theming without editing the launcher file.

I'd like to ask you to change the icon location as well as the icon path line in the launcher according to the freedesktop.org standards.

Please find more info here:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How

---------------------------------
According to the above resources standard icon locations are:

*/usr/share/icons/hicolor/[size]/apps/[icon name]*
*~/.local/share/icons/hicolor/[size]/apps/[icon name]*
*/usr/share/pixmaps/[icon name]*

The standard icon line in the .desktop launcher is:
*Icon=[icon name]*      (without full path, without file extension)

for instance
**Icon=wxmaxima**  
(for an icon *wxmaxima.svg* or *wxmaxima.png* stored in standard location)

Could you please move the icon to one of those locations and adjust the icon path in the .desktop file accordingly?

**Comment by gunterkoenigsmann** [comment]
Fixed with commit dbe86604a388aa4cf701cc6f29a115ab76b6488a.
