### ISSUE TITLE
Wrong answer for an integral ?

### ISSUE THREAD

**Issue by GFROGER** [andrejv/wxmaxima#443]
Hello

When some compute the following:
integrate((x-1)/((x+1)*sqrt(x^3+x^2+x)), x);
some obatin the following:
asinh((2*x)/sqrt(3)+1/sqrt(3))-2*asinh(x/(sqrt(3)*abs(x+1))-1/(sqrt(3)*abs(x+1)))
Wihich is wrong. Some can see it by derivating and simplifying the following way:
factor(ratsimp(diff(%,x,1)));
which gives:
x-1/((x+1)*sqrt(x^2+x+1))
Note that the correct result of the integral is:
2*atan(sqrt(x+1+1/x))
Which some can verify the following way:
radcan(ratsimp(diff(%,x,1)));

-------------------------------------------------------------
wxMaxima version: 14.12.1
Maxima version: 5.35.1.2
Maxima build date: 2015-01-15 21:27:01
Host type: i686-pc-mingw32
System type Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7
-------------------------------------------------------------

Best regards

**Comment by andrejv** [comment]
Please report maxima bugs to the bug-tracker at

http://sourceforge.net/p/maxima/bugs/
