### ISSUE TITLE
Slider gui element enable/disable logic broken on windows

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#444]
The logic that sets the slider in the toolbar to active or inactive seems to be slightly broken on windows, currently: The slider cannot be moved if a slideshow cell is selected until the play button has been pressed. It then keeps being active even after a different cell has been selected. Don't know if I have caused this or if it is a side-effect from repairing the play button after I broke it for win.

**Comment by gunterkoenigsmann** [comment]
If I am not totally mislead it is not the update logic but the Update_Toolbar() method is called much too often on Linux (#437) and too seldom on Win. Since there is only need to change the toolbar if the worksheet's state changed it would suffice to fix bothy issues by updating them then. I assume we could catch all worksheet state changes by
 - changing the names of MathCtrl::TreeUndo_CellLeft() and MathCtrl::TreeUndo_CellEntered() to CellLeft() and CellEntered() 
 - Telling these two functions to Update the toolbar and the menus as well as the undo buffers
 - updating the menus and toolbars on mouse clicks as well
 - updating them, too, on all key events we skip() because they look like they could be hotkeys
 - If maxima sends us data we normally leave a cell so the menu and toolbars are updated. If not the updated cell is far away from the caret and therefore doesn't matter for the toolbars and menus.
The last two times I did a thing that looked this logical it broke either the Mac Os or the Windows build so this time I thought, I'd better ask.

**Comment by andrejv** [comment]
I think it is pretty standard to update the GUI on idle events, which is what we do now. If it is called to often, that is OK. Why do you think it is not called often enough on windows?

Another idea is to simply remove the slider from the toolbar. It has a limited functionality which is covered better using other methods. I never use it myself for animations.

**Comment by gunterkoenigsmann** [comment]
Didn't find a flaw in the logic so I assumed the cause of the problem must be that on windows sometimes nobody calls the logic.

I personally like the slider: I normally use it to scroll through large sets of oscillograms showing the same measurement using different parameters and find this a quite helpful way for finding how a parameter affects the outcome of a measurement.

**Comment by gunterkoenigsmann** [comment]
If #460 isn't a bug we can close this one, too.
