### ISSUE TITLE
Dialog window is not refreshed properly if the backspace key has been pressed

### ISSUE THREAD

**Issue by arbolis** [andrejv/wxmaxima#450]
I have just downloaded, compiled, built and installed wxMaxima from git (because Ubuntu's default wxMaxima is so old that this bug: https://github.com/andrejv/wxmaxima/issues/340 is still not fixed). It was a bit of a pain to figure out every packages required but I've made it.

The bug I've found so far is extremely weird. For example when you go to "Plot -> Plot 2d ..." it opens a window where you can enter an expression to plot. There's a "%" sign by default. When you try to delete the percentage sign with the backspace key, the window doesn't refresh that you deleted the % sign. It still appears. You can enter more text in that window, but anything you try to delete will not show as deleted. Unless you minimize the window and restore it. 
That's very strange. I now retried it and even after restoring the window, the text still shows up even though I had supposedly deleted it. Now I can't even add text, even though the cursor is blinking as if I could enter text.

**Comment by gunterkoenigsmann** [comment]
That is a bug with the wxWidgets version shipped with ubuntu. In my 
case installing ibus-gtk has solved the problem. Others had to remove 
all the ibus stuff instead.
Am trying to contact the maintainers of the wxMaxima project on 
launchpad so they give me the necessary permissions to set up a nightly 
ppa.

Kind regards,

       Gunter.

**Comment by arbolis** [comment]
Thank you very much Gunter. I installed ibus-gtk (ibus-gtk3 didn't work), and it now works perfectly.
