### ISSUE TITLE
Show/hide toolbar does not work

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#452]
Show/hide toolbar does not work on Windows (and Linux?). The toolbar is always shown.

**Comment by gunterkoenigsmann** [comment]
Arrgh!
On my linux computer hiding the toolbar will work. Will test tomorrow with Wolfgang Dautermann's build. Not that this depends on the wxWidgets version.

**Comment by gunterkoenigsmann** [comment]
Fixed with commit be87d3ec917788d4335822e04604252d83e4bb0b.
