### ISSUE TITLE
Parenthesis issue in text mode

### ISSUE THREAD

**Issue by hesperion** [andrejv/wxmaxima#453]
Input :
solve(-x^2+x+1,x);

By copying and pasting the output :
[x=-sqrt(5)-1/2,x=(sqrt(5)+1)/2]
One can see a parenthesis issue in the first solution.

It's a simplified situation. I discovered it by solving this equation :
solve(b^2 * dcos(56)^2 / dcos(70)^2 = 54^2 + b^2 - 108 * b * dcos(146),b);
(where dcos is the cosine in degrees) and copying / pasting the 1st solution.

------
wxMaxima version: 14.12.1
Maxima version: 5.35.1.2
Maxima build date: 2015-01-15 21:27:01
Host type: i686-pc-mingw32
System type Win32 6.2.9200 X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7

**Comment by gunterkoenigsmann** [comment]
This is solved in wxMaxima 15.04 that can be downloaded as part of the maxima installer from http://maxima.sourceforge.net.

Kind regards,
   Gunter.
