### ISSUE TITLE
Double-clicking .wxm file causes wxMaxima loading failure

### ISSUE THREAD

**Issue by y-hiro** [andrejv/wxmaxima#454]
When double-click .wxm file to invoke wxMaxima on Windows 7 (64-bit) Japanese, the error shown below occurs.
![wxmaximaerr](https://cloud.githubusercontent.com/assets/12025525/7222402/e277c90c-e748-11e4-99d5-b51bdb8c9a93.png)

Here is also a log:

-- begin of log --
10:13:34: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-new.png' (error 0: この操作を正しく終了しました。)
10:13:34: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-new.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-open.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-open.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-save.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-save.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-print.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-print.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-preferences.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-preferences.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-cut.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-cut.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-copy.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-copy.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-paste.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-paste.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-select-all.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-select-all.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-find.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-find.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/view-refresh.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/view-refresh.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-stop.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-stop.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/weather-clear.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/weather-clear.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/software-update-urgent.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/software-update-urgent.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/media-playback-start.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/media-playback-start.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/media-playback-stop.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/media-playback-stop.png".
10:13:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-help.png' (error 0: この操作を正しく終了しました。)
10:13:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-help.png".
-- end of log --

My environment:
-------------------------------------------------------------
wxMaxima version: 15.4.0
Maxima version: 5.36.0
Maxima build date: 2015-04-16 09:44:01
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7
-------------------------------------------------------------

Regards.

**Comment by andrejv** [comment]
This is an issue with packaging. It is already fixed in maxima git ( http://sourceforge.net/p/maxima/code/ci/ada2fe972466e6b52225b819947df2ca7ed4536c/ ) and will be included in the final 5.36 release.
