### ISSUE TITLE
15.04.0 Toolbar will not load when .wxmx files are opened

### ISSUE THREAD

**Issue by fsenese** [andrejv/wxmaxima#457]
Opening wxMaxima 15.04.0 by clicking on a .wxmx file gives this:
![wxwidgets-error](https://cloud.githubusercontent.com/assets/10280442/7264583/fb64ec48-e85a-11e4-976a-7fd4fec952a7.png)

Cancel will load wxMaxima and the file, but the toolbar won't show.

**Comment by gunterkoenigsmann** [comment]
This may be a packaging issue. On my computer the icons from the art directory that can be found inside https:/ (which uses Wolfgang Dautermann's cross-built installer) the icons from the toolbar folder from https://github.com/andrejv/wxmaxima/archive/master.zip weren't shipped with the installer.  Alternatively I have seen that the file association for double-clicking might still be linked with an old, still half-installed version of wxMaxima.

**Comment by andrejv** [comment]
Fixed in maxima repository ( http://sourceforge.net/p/maxima/code/ci/ada2fe972466e6b52225b819947df2ca7ed4536c/ )
