### ISSUE TITLE
Loading old files error and language shifting

### ISSUE THREAD

**Issue by TufanSirin** [andrejv/wxmaxima#458]
I installed 15.04.0 and tried to open the files which are wirtten eith the previous version.. It says
"Loading error"....
Secondly (that is strange) I use the Turkish version... I tried to load a file it stopped I pushed the Cancel button and wxMaxima turned to English version .....

**Comment by gunterkoenigsmann** [comment]
What was the message that offered to cancel? And would it possible for you to send a us file that cannot be opened?
This somehow looks like the typical reaction of a non-unicode-aware wxWidgets to the request to convert a character that isn't in the current codepage wxWidgets guesses to be right for the computer.

**Comment by TufanSirin** [comment]
https://cloud.githubusercontent.com/assets/10280442/7264583/fb64ec48-e85a-11e4-976a-7fd4fec952a7.png

The message is this one.
After clicking the Cancel button wxMaxima turns to English version (this is a new problem)
 AND the file is not be opened. When i push the Ok button the previous coding problem still exists



Samsung Mobile tarafından gönderildi



-------- Orjinal mesaj --------
Kimden: Gunter Königsman <notifications@github.com>
Tarih: 22 04 2015 20:15 (GMT+02:00)
Alıcı: andrejv/wxmaxima <wxmaxima@noreply.github.com>
Cc: Tufan Şirin <tsirin@turgutozal.edu.tr>
Konu: Re: [wxmaxima] Loading old files error and language shifting (#458)



What was the message that offered to cancel? And would it possible for you to send a us file that cannot be opened?
This somehow looks like the typical reaction of a non-unicode-aware wxWidgets to the request to convert a character that isn't in the current codepage wxWidgets guesses to be right for the computer.

**Comment by gunterkoenigsmann** [comment]
Ok... ...this Message is a packaging problem. As far as I understand it works the following way:
 - Traditionally wxMaxima on Windows searched for its icon files in the current working directory. But sometimes the program wasn't started from the directory it was installed in and failed. So I modified it to ask wxWidgets where the .exe file can be found.
 - wxWidgets finds this path by asking windows where the program is installed and removing the "wxmaxima.exe" from this path.
 - Unfortunately wxMaxima upon double-clicking on a file is called as "wxMaxima.exe" and the search-and-replace that searchs for the icons fails.
I assume a similar thing might happen for the language files.
Starting wxMaxima and then opening a file from within the program should work, I hope.

Kind regards,

  Gunter.

**Comment by TufanSirin** [comment]
The message that I see on the screen is "../src/common/unichar.cpp(65): assert "Assert Failure" failed in ToHi8bit():character cannot be converted to single byte....
Do you wanto to stop the program?
You can also choose [Cancel] to suğress further warnings....
When I choose [Cancel] toolbar turns to english but and then it gives "loading error" I will send the one of the file (written with the previous version) that cannot be opened with the new version ...
I changed my PC windows language settings intoEnglish but it didnt help

**Comment by TufanSirin** [comment]
[cid:image001.png@01D07E73.FD521C20]

The problem that I have

Kimden: Gunter Königsman [mailto:notifications@github.com]
Tarih: Thursday, April 23, 2015 7:32 AM
Kime: andrejv/wxmaxima
Bilgi: Tufan Şirin
Konu: Re: [wxmaxima] Loading old files error and language shifting (#458)


Ok... ...this Message is a packaging problem. As far as I understand it works the following way:

  *   Traditionally wxMaxima on Windows searched for its icon files in the current working directory. But sometimes the program wasn't started from the directory it was installed in and failed. So I modified it to ask wxWidgets where the .exe file can be found.
  *   wxWidgets finds this path by asking windows where the program is installed and removing the "wxmaxima.exe" from this path.
  *   Unfortunately wxMaxima upon double-clicking on a file is called as "wxMaxima.exe" and the search-and-replace that searchs for the icons fails. I assume a similar thing might happen for the language files. Starting wxMaxima and then opening a file from within the program should work, I hope.

Kind regards,

Gunter.
