### ISSUE TITLE
Toolbar Error in turkish Version only?

### ISSUE THREAD

**Issue by TufanSirin** [andrejv/wxmaxima#459]
17:12:07: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-new.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:07: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-new.png".
17:12:34: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-open.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:34: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-open.png".
17:12:35: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-save.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:35: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-save.png".
17:12:35: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-print.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:35: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-print.png".
17:12:35: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-preferences.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:35: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-preferences.png".
17:12:35: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-cut.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:35: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-cut.png".
17:12:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-copy.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-copy.png".
17:12:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-paste.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-paste.png".
17:12:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-select-all.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-select-all.png".
17:12:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-find.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-find.png".
17:12:36: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/view-refresh.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:36: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/view-refresh.png".
17:12:37: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-stop.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:37: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-stop.png".
17:12:37: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/weather-clear.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:37: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/weather-clear.png".
17:12:37: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/software-update-urgent.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:37: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/software-update-urgent.png".
17:12:37: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/media-playback-start.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:37: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/media-playback-start.png".
17:12:37: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/media-playback-stop.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:37: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/media-playback-stop.png".
17:12:37: can't open file 'C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-help.png' (error 0: İşlem başarıyla tamamlandı.)
17:12:37: Failed to load image from file "C:\Program Files (x86)\Maxima-sbcl-5.36.0\wxMaxima\wxMaxima.exeart/toolbar/gtk-help.png".

**Comment by gunterkoenigsmann** [comment]
This should be issue #457 again. But how did you get this debug output on Windows? I had to go lengths for finding out what was going on; A temporary workaround would maybe be actually creating the folder the program currently expects.

**Comment by andrejv** [comment]
A new installer has been uploaded. The issue with packaging is fixed.

**Comment by TufanSirin** [comment]
The files that are not to be opened were on my "Desktop" (Windows 7- turkish)  and
 I moved them in to "Documents" folder. 
And they are being opened :) now…

**Comment by TufanSirin** [comment]
The files that are not to be opened were on my desktop (Windows 7)  and
I moved them in to documents folder.
And they are being opened ☺) now…


[cid:image001.jpg@01CEEF65.DFD0C6E0]


Yrd.Doç.Dr.Tufan ŞİRİN
Sağlık Bilimleri Meslek Yüksekokulu  Müdür Yardımcısı                          Ostim Kampüsü
1238 Sokak No:5 YENİMAHALLE ANKARA






[cid:image003.jpg@01CEEF65.DFD0C6E0]

Tel

:(+90) 312 3858100-1214

Faks

:(+90) 312 3851998


tsirin@turgutozal.edu.tr<mailto:tsirin@turgutozal.edu.tr>
www.turgutozal.edu.tr<http://www.turgutozal.edu.tr/>



Kimden: Andrej Vodopivec [mailto:notifications@github.com]
Tarih: Friday, April 24, 2015 2:24 PM
Kime: andrejv/wxmaxima
Bilgi: Tufan Şirin
Konu: Re: [wxmaxima] Toolbar Error in turkish Version only? (#459)


Closed #459<https://github.com/andrejv/wxmaxima/issues/459>.
