### ISSUE TITLE
F1 key deletes text after cursor

### ISSUE THREAD

**Issue by linuxdoesitbetter** [andrejv/wxmaxima#464]
Hello,

I built wxMaxima in debian 8 with libwx3.0 and have the problem that pressing function keys deletes the text after cursor. After this I can't enter text at the end of the input cell. This way I can, for example, do not use the online help. My keyboard layout is german with dead keys. I use wxmaxima under KDE.

wxMaxima version: 15.4.0
Maxima version: 5.36.0
Maxima build date: 2015-04-27 14:36:05
Host type: i686-pc-linux-gnu
System type: Linux 3.16.0-4-686-pae X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.4.debian

Regards, Andreas

PS:
After pressing F1 the remaining text of the cell does not seem to be missing entirely, parts of it are just invisible.

Another problem:
After executing "make distclean" a new "./configure && make" ends with:
>>
texi2html -split_chapter --lang=en --output=. \
          --css-include="manual.css" --init-file "texi2html.init" wxmaxima.texi
perl ./create_index
Can't open perl script "./create_index": Datei oder Verzeichnis nicht gefunden
<<(missing file)

**Comment by gunterkoenigsmann** [comment]
The create-index message is strange. Will look if I can reproduce it here. If nothing helps: I have removed this script and all calls to it from the current git version. For the F1 problem I hope it is the one I encountered: currently wxWidgets seems to have a bug that it only interprets function keys and the delete key correctly if ibus-gtk3 is installed.

**Comment by gunterkoenigsmann** [comment]
Did look for the script:

In the release tarball from github (https://github.com/andrejv/wxmaxima/releases/tag/Version-15.04.0) the script is included and "make distclean" doesn't delete it. At least on my computer.
The question now is if you have perl installed: The message seems to indicate that but - then perl should be able to find the script that is in its directory.

Or are you trying to do an out-of-tree-build? I am currently trying to make them work but am no expert on that. If all persists to refuse to work on your computer you can use the git version that no longer needs perl to work: https://github.com/andrejv/wxmaxima/archive/master.zip

**Comment by linuxdoesitbetter** [comment]
Hallo Gunter,

erst mal vielen Dank, für die schnelle Antwort. Ich hoffe, es ist in Ordnung wenn ich Deutsch schreibe. Mein Englisch ist, nicht so besonders.

Zuerst zu der Sache mit dem "make distclean". Ich benutzte den Tarball, den man von Sourceforge herunterladen kann und der Build-Vorgang läuft problemlos durch. Besagtes Script ist da und funktioniert, bis man "make distclean" aufruft. Danach ist es weg und der Buildvorgang bricht bei der Erstellung der Doku ab. Das stört mich aber nicht im Geringsten, da man den Tarball bei Bedarf einfach neu entpacken kann. Perl ist auf jeden Fall vorhanden.
Das Problem mit der F1-Taste ist viel lästiger. Das Paket "ibus-gtk3" war nicht installliert. Das habe ich jetzt nachinstalliert, aber das ändert nichts. Danach habe ich den ibus samt daemon installiert, gestartet und "ibus-setup" ausgeführt. In meine ~./bashrc habe ich folgende Zeilen angehängt:

#ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

Wenn ich mich am KDE anmelde und mit ps nachschaue, sehe ich Folgendes:

andi@jupiter:~$ ps -A | grep ibus
 5521 ?        00:00:03 ibus-daemon
 5527 ?        00:00:00 ibus-dconf
 5528 ?        00:00:00 ibus-ui-gtk3
 5532 ?        00:00:00 ibus-x11
 5574 ?        00:00:00 ibus-engine-sim

Aber auch das führt nicht zum Erfolg. Backspace und Delete sind übrigens nicht betroffen, die funktionieren wie erwartet. Nur wenn ich den Cursor auf ein Wort stelle, und F1 betätige, ist der Rest der Zeile weg oder unsichtbar und am (neuen) Ende der Zelle sind keine Eingabe mehr möglich, bis man den Inhalt löscht, wobei auch Teile des vermeintlich gelöschten Textes wieder auftauchen.

Ich habe jetzt zwei Debian 8 Systeme und beide verhalten sich gleich.

Es wäre echt super, wenn sich hier eine Lösung finden ließe, denn ich mag wxMaxima wirklich sehr. Notfalls nehme ich eben mit der gut abgehangenen Version von Debian (die der Größe nach zu urteilen statisch gegen wx2.8 linkt) vorlieb und hoffe darauf, dass der wx3-Kram irgendwann funktioniert. :-)

Wenn Du es schaffst, mir zu einer Lösung zu verhelfen, kaufe ich Dein Physikbuch - versprochen! ;-)

Viele Grüße,
Andreas

**Comment by gunterkoenigsmann** [comment]
Dann werde ich sehen, was ich tun kann ;-)

Wie weit ich bin ist:
 - Ich habe ein Setup gefunden, in dem ich das Problem reproduzieren 
kann. Ist oft das wichtigste bei der Fehlersuche.
 - Der Fehler scheint in EditorCell zu sein und dort in 
EditorCell::ProcessEvent: Das sollte bei der F1-Taste ein Event.Skip() 
ausführen.
Muss jetzt in die Arbeit und hab' meiner Freundin versprochen, das Auto 
warten zu lassen (was bedeutet, dass ich nicht in der Bahn arbeiten 
kann) - aber ich kümmer' mich drum.

Gruß,

     Gunter.

In English: The problem seems to reside in EditorCell::ProcessEvent(): 
This function should Event.Skip() the F1 key . Will find out why it 
doesn't do so.

**Comment by andrejv** [comment]
There is probably no special code for F1 handling in wxMaxima. The way it work is that F1 is a shortcut for Help->Menu entry (defined in wxMaximaFrame) which should be handled by wxWidgets/GTK. Pressing F1 probably inserts some unreadable character into the cell. WXK_F1 (and other functions keys) should probably added to ignored keys.

**Comment by gunterkoenigsmann** [comment]
Fixed with commit aa2a26c9483d998ece89c84b1afbe930d643913c and thanks for the bug report.

  Gunter.

**Comment by linuxdoesitbetter** [comment]
Hallo Gunter,

ich hatte vorhin den Code aus dem Master-Zweig als ZIP-Datei heruntergeladen und nach der Anleitung in README.md übersetzt und installiert. Dort könnte noch der Hinweis hinein, dass man zuerst das Skript 'bootstrap' ausführen muss.
Jetzt funktioniert die F1-Taste wie gewünscht. :-) Vielen lieben Dank dafür und für den Zeitaufwand, den Du damit hattest!
Die Erlaubnis, "Dein anderes Physikbuch" zu kaufen, habe ich bei meiner Frau eingeholt. Dazu habe ich noch eine Frage. Wäre es irgendwie möglich, ein von Dir signiertes Exemplar zu bekommen? Falls es einen Weg gäbe, könntest Du mich unter der Mail in meinem Profil erreichen.

Ich wünsche Dir und dem ganzen wxMaxima-Team ein schönes Wochenende!

Viele Grüße,
Andreas
