### ISSUE TITLE
wxmaxima -  with_slider_draw  bag?

### ISSUE THREAD

**Issue by lvch** [andrejv/wxmaxima#466]
In earlier versions of wxMaxima the behavior was like this:
It was possible to change the animation frame after selecting the result window with_slider_draw by the left mouse button WITH
1) Scrolling mouse wheel (the cursor was in the work window)
2) Scrolling mouse wheel (the cursor was at the scroll bar)
3) By pressing triangle on the toolbar
4) Moving animation icon with the left mouse button.

Now, in the current version: wxmaxima 15.04.0, wxWidgets: 3.0.2
Unicode: yes
Maxima version: 5.36.0.1  Lisp: SBCL 1.2.7, Windows 7

It is NOT possible to change the animation frame after selecting the result window with_slider_draw WITH
1) Scrolling mouse wheel (the cursor was in the work window)

It simply does not work. Instead of changing the animation frame, the whole content of the working window of wxmaxima is moving!

If it it a feature, it is very inconvenient!
If this is a bug - please, fix it.

So, is it bug or feature?

See example:
with_slider_draw(r,[1,3/2,2],
proportional_axes = xy, grid = true, xrange = [-2,2], yrange = [-2,2],
parametric(r*cos(t),r*sin(t),t,0,2*%pi))$

Best regards,

**Comment by gunterkoenigsmann** [comment]
After clicking on the slider the mouse wheel still seems to work on my computer. If the current behavior is a bug or intended I don't know, though.

Kind regards,
  Gunter.

**Comment by andrejv** [comment]
The scrolling through animations was removed in the last version because the behaviour of mouse scroll events was changed in wxwidgets 3.0 and I have not been able to reproduce the behaviour from 2.8.

Instead of mouse scrolling it is now possible to move through animation using the left and right arrow keys.

**Comment by lvch** [comment]
thank you very much
