### ISSUE TITLE
text copy of fraction bug

### ISSUE THREAD

**Issue by keeeeeeep** [andrejv/wxmaxima#468]
When I insert the following command
(a-b)/c;
and copy the result and paste it to notepad , the pasted text is following.
a-b/c
This is invalid.

-------------------------------------------------------------
wxMaxima version: 
Maxima version: 5.34.1
Maxima build date: 2014-11-11 09:57:09
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.11
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
This issue should be corrected in wxMaxima 15.04 which for windows is bundled with the newest installer. For linux until there is an official build the packages from https://code.launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies/+packages should work.
