### ISSUE TITLE
EditorCell.cpp: 2 * array index out of range ?

### ISSUE THREAD

**Issue by dcb314** [andrejv/wxmaxima#470]
[EditorCell.cpp:528]: (style) Array index 'm_positionOfCaret' is used before limits check.

      while((wxIsalnum(m_text[m_positionOfCaret]))&&(m_positionOfCaret<m_text.Length()))

[EditorCell.cpp:531]: (style) Array index 'm_positionOfCaret' is used before limits check.

Duplicate.

**Comment by gunterkoenigsmann** [comment]
Good find! Thanks!

Fixed in commit 21ab90e31ba0e8466e1f74cd4e1130580d2049ec.
