### ISSUE TITLE
Bug in wxMaxima Help menu

### ISSUE THREAD

**Issue by mardukbp** [andrejv/wxmaxima#476]
In wxMaxima 15.04 (either in Arch Linux or OS X 10.8) selecting **wxMaxima Help** in the Help menu brings up the Help browser showing only the wxMaxima manual. Closing the window and now selecting **Maxima help** in the Help menu shows both manuals. Closing the window and selecting **wxMaxima Help** now shows both manuals.

**Comment by gunterkoenigsmann** [comment]
This actually was intended: 
 - If you select a maxima command and press F1 the manual for this program is opened and the help browser is instructed to try and search the right page for it.
 - If you just press F1 in wxMaxima the manual for wxMaxima is opened instead as wxMaxima is a separate program - as are xmaxima, sage, emacs which can be used as front-ends to make work with maxima easier.
 - and there is a separate help menu entry for both of these programs so it is possible to open either help file this way.
Keeping the two programs in separate help menu items sounded logical at the time I wrote it.

**Comment by mardukbp** [comment]
I see. However, your first bullet point does not work quite well because of the problems with the help browser that I mentioned elsewhere.

**Comment by mardukbp** [comment]
Now I realize this is easy to fix. When pressing F1 with a Maxima command selected the help browser should open in the Index tab showing the help for the command in the right pane.

**Comment by mardukbp** [comment]
Never mind. I recompiled wxMaxima and now it works as intended. My apologies.

**Comment by gunterkoenigsmann** [comment]
No need to apologize. Even more if access to help could have been made slightly easier by automatically opening both tabs in the help browser at once so the user is automatically informed that there actually are two separate manuals. Did correct that in commit 09e38f3f609d2b8f68637c3a57a69b520e90b723.

**Comment by mardukbp** [comment]
Thanks. I think that's better.
