### ISSUE TITLE
Problem/error using plot2d/plot3d

### ISSUE THREAD

**Issue by zachilas** [andrejv/wxmaxima#477]
Dear Andrej,
I have just downloaded the new version of wxmaxima for Mac.
My configuration is:
wxMaxima version: 15.4.0
Maxima version: 5.36.1
Maxima build date: 2015-05-06 11:10:10
Host type: x86_64-apple-darwin14.3.0
System type: Darwin 14.3.0 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.2.10

When I try to plot something (using the menu Plot -> Plot 2d (or Plot 3d))
eg.
plot2d([x^2], [x,-5,5],
 [plot_format, gnuplot],
 [gnuplot_postamble, "set zeroaxis;"])$
The windows (both the terminal one and the gunplay_qt) close as soon as they open!!
So, I cannot plot anything. I see nothing!
Any ideas?

**Comment by andrejv** [comment]
Change plot_format from gnuplot to gnuplot_pipes.

**Comment by zachilas** [comment]
Perfect!! It worked fine.
Thanks Andrej.

**Comment by gunterkoenigsmann** [comment]
This should be resolved with the upcoming release of maxima.
