### ISSUE TITLE
Introduce a template file for generating the LaTeX from Maxima code

### ISSUE THREAD

**Issue by dossan** [andrejv/wxmaxima#481]
I was wondering if you could introduce a template file that generates the LaTeX code/version of the Maxima program, so that users can modify it when they need to change for example the style of the LaTeX code generated. This would really be a nice feature, and I hope you introduce it.

**Comment by gunterkoenigsmann** [comment]
The "Options" tab of the configuration dialog of wxMaxima 15.04 contains a field with additional lines for the TeX preamble. I don't know if this is what you need? My additional preamble lines are:

        \usepackage[a4paper,left=1cm,right=1cm,top=1.4cm,bottom=1.4cm]{geometry}
        \usepackage{auto-greek}

Kind regards, 
 Gunter.

**Comment by gunterkoenigsmann** [comment]
After commit 693aa93f444d6be401288ef607a75204c286f0dd you can choose the LaTeX document class, as well.
Kind regards,

    Gunter.
