### ISSUE TITLE
Fold and Unfold not working

### ISSUE THREAD

**Issue by mardukbp** [andrejv/wxmaxima#491]
I am using wxMaxima 14.12.0 in Arch Linux. In a cell I enter 

```
x;
y;
z;
```

and evaluate the cell, then I select *Fold All* in the Cell menu and nothing happens. Manually folding the cell by clicking on the triangle in the corner and then selecting *Unfold All* does nothing.

In Ubuntu 15.04 the version of wxMaxima in the repos is 13.04 and the same happens.

**Comment by gunterkoenigsmann** [comment]
Fixed with commit b92069d1c7d8fe471c779ac89c77950d3069b2a3.
