### ISSUE TITLE
integration is wrong

### ISSUE THREAD

**Issue by dossan** [andrejv/wxmaxima#493]
When I integrate using maxima using wxmaxima, for example:

    f(x) := x^3 * log(x);

    integrate(f(x), x);

I get 

![screen shot 2015-06-12 at 16 42 12](https://cloud.githubusercontent.com/assets/9349000/8132427/04d7ae2e-1122-11e5-94d5-65b77b9712c1.png)

Which is not correct, because it does not indicate the final constant. Remember that in this case we are asking for all possible functions that we can differentiate and get 

     f(x) := x^3 * log(x);

So, we need to indicate in the result some constant factor at the end, otherwise it seems that it simply returns an antiderivative instead of really integrating `f(x)`...

**Comment by gunterkoenigsmann** [comment]
Maxima shows this behaviour if wxMaxima isn't used to display the result => if it is a bug it has to be resolved in the maxima project. 
But you can ask their mailing list if that behaviour is somehow intended. 
Thinking about it I assume the rationale might be that if integrate would always add a obvious %r1 to its results this would require the user to filter these constants out in many cases or to resolve name clashes when dealing with other functions that might introduce new variables, too.

Am 12. Juni 2015 16:44:33 MESZ, schrieb Nelson Brochado <notifications@github.com>:
>When I integrate using maxima using wxmaxima, for example:
>
>    f(x) := x^3 * log(x);
>
>    integrate(f(x), x);
>
>I get 
>
>![screen shot 2015-06-12 at 16 42
>12](https://cloud.githubusercontent.com/assets/9349000/8132427/04d7ae2e-1122-11e5-94d5-65b77b9712c1.png)
>
>Which is not correct, because it does not indicate the final constant.
>Remember that in this case we are asking for all possible functions
>that we can differentiate and get 
>
>     f(x) := x^3 * log(x);
>
>So, we need to indicate in the result some constant factor at the end,
>otherwise it seems that it simply returns an antiderivative instead of
>really integrating `f(x)`...
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/493

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by gunterkoenigsmann** [comment]
Will close the bug here as it does not directly affect wxMaxima. But that doesn't mean that I am sure if it is a bug that should be fixed - or if it is a design decision.
