### ISSUE TITLE
Copying output expressions is flawed

### ISSUE THREAD

**Issue by jhkaiser** [andrejv/wxmaxima#504]
If I input the expression "(a-b)/(c-d);" and then choose "Copy Previous Output" from the menu, the result is "a−b/c−d" which is clearly wrong!  The same happens if I copy the output with the help of the context menu after selecting the displayed output.  However, the "Copy LaTeX" context menu item works.

This bug is especially annoying because I use this "feature" of the GUI to copy calculated results into program code.

PS: Anyway, great thanks for creating wxMaxima!

**Comment by andrejv** [comment]
Which version do you use? I believe this is fixed in the most recent version.

**Comment by jhkaiser** [comment]
wxMaxima 13.04.2
wxWidgets: 3.0.2
Maxima version: 5.34.1
Lisp: GNU Common Lisp (GCL) GCL 2.6.12 (a.k.a. GCL)

**Comment by gunterkoenigsmann** [comment]
It has been fixed. I assume you are running a debian-based system. If this is true you can find a working version of the program at https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies
If not please install the newest windows installer: It has many new features and stability fixes you might like.
