### ISSUE TITLE
copying/pasting error from output cell

### ISSUE THREAD

**Issue by dpgoldenberg** [andrejv/wxmaxima#532]
Hi,
    I think that I have found a small bug when copying certain output expressions into a new cell.  The example I stumbled on is:
−(sqrt(3)−2)/sqrt(8−4*sqrt(3));

If I evaluate this expression and copy it into a new cell, I get:
2−sqrt(3)/sqrt(8−4*sqrt(3))

Basically, the parentheses around the numerator terms are lost.

This happens whether I copy by selecting the output with the mouse or if I use the "Copy Previous Output" command in the Cell menu.

I am using wxMaxima 13.04.0 on a Mac with OS X 10.8.5.  (Installing the newer version, 15.04 has been problematic, but that's another story.)

Thanks,
David Goldenberg

**Comment by andrejv** [comment]
This has been fixed in 15.04.

Maybe you can open another issue for the problems with 15.04 on OS X. The binaries are compiled on 10.10 btw.
