### ISSUE TITLE
wxmaxima 15.04/gnuplot on OS X 10.4

### ISSUE THREAD

**Issue by dpgoldenberg** [andrejv/wxmaxima#533]
As mentioned in an earlier ticket, I have had difficulty using wxMaxima 15.04 on an OS X 10.8.5 system.  

Actually, the problem is really with the newly-modified gnuplot.app.  When I open gnuplot.app directly, change the term type to qt and then try to plot, I get:

gnuplot> set term qt
Terminal type set to 'qt'
Options are '0 font "Sans,9"'
gnuplot> plot sin(x)
dyld: lazy symbol binding failed: Symbol not found: ___exp10
  Referenced from: /Volumes/Maxima 5.36.1/Gnuplot.app/Contents/Resources/bin/gnuplot-5.0.0
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___exp10
  Referenced from: /Volumes/Maxima 5.36.1/Gnuplot.app/Contents/Resources/bin/gnuplot-5.0.0
  Expected in: /usr/lib/libSystem.B.dylib

/Volumes/Maxima 5.36.1/Gnuplot.app/Contents/Resources/bin/gnuplot: line 61: 38052 Trace/BPT trap: 5       GNUTERM="${GNUTERM}" GNUPLOT_HOME="${GNUPLOT_HOME}" PATH="${PATH}" DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}" HOME="${HOME}" GNUHELP="${GNUHELP}" DYLD_FRAMEWORK_PATH="${DYLD_FRAMEWORK_PATH}" GNUPLOT_PS_DIR="${GNUPLOT_PS_DIR}" DISPLAY="${DISPLAY}" GNUPLOT_DRIVER_DIR="${GNUPLOT_DRIVER_DIR}" "${ROOT}/bin/gnuplot-5.0.0" "$@"

This seems to reflect some sort of change to the libraries after OS X 10.8, and there are several references to it relating to other programs.  For instance:
https://github.com/USGS-R/glmtools/issues/80
http://stackoverflow.com/questions/22920497/git-mountain-lion-dyld-lazy-symbol-binding-failed-symbol-not-found-str

I was eventually able to work around this by installing gnuplot (5.0) from homebrew, and modifying maxima-init.mac appropriately.  

But, in order to get the homebrewed gnuplot to work with wxMaxima, I had to install it with the cairo terminal options.  This seemed odd, since the wxMaxima install instructions seem to indicate that the qt terminal is used.  But, with only qt available, I got errors in wxMaxima that indicated it wanted pngcairo.  In the end, I had both qt and the cairo options in gnuplot, and I don't know if qt is actually necessary.

It may also be worth noting that the wxMaxima installed with homebrew is still 13.04.2.

But, I know have 15.04 working, with plotting!  And the copy bug is fixed!

Thanks,
David

**Comment by gunterkoenigsmann** [comment]
If gnuplot is instructed to create a standalone plot it does do so with 
the qt terminal. Plots embedded into worksheets are drawn as png 
graphics instead.

Try

      wxplot_pngcairo:false$

before plotting. If this works there is a option in the configuration 
dialogue that disables cairo -
and I did find the original cause of the problem: The code contains a 
#ifdef that enables pngcairo depending on the system. But I seem to 
have enabled pngcairo per default only on mac computers - that are the 
only computers that don't support it.
Will fix it in the core and I have to appologize for the inconvenience 
this has caused.

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment]
Well... ...at least I did close half of the bug. Since the other half seems to be in gnuplot, though, I don't know if we can do anything about it. If you do think we can feel free to reopen the bug report.

Kind regards,

   Gunter.

**Comment by dpgoldenberg** [comment]
Gunter,
     Thanks very much for looking at this.  After I made my initial post, I discovered the cairo option in the preferences.  With versions of Maxima and gnuplot installed using homebrew, I now have things working well now.  One oddity, though, is that I no longer seem able to use the Maxima.app with wxMaxima.  I can launch the Maxima.app  and use it via a terminal window, but, when I try to choose it as the Maxima for wxMaxima to use, it hangs up waiting for the connection.  I suspect that I have messed up some configuration, but I haven't been able to figure it out.

I'm curious, where does the gnuplot distributed with wxMaxima for the Mac come from.  Digging around in the package contents, it looks like it is, or was, associated with the Octave project. 

Thanks again,
David
