### ISSUE TITLE
Panes on OS X

### ISSUE THREAD

**Issue by dpgoldenberg** [andrejv/wxmaxima#535]
This is a very minor bug in 15.04.0. .  On OS X, at least, the Maxima >> Panes >> Table of Contents menu command opens a pane with the history.  But, Maxima >> Panes >> Structure opens a table of contents. 

As an aside, the Table of Contents pane (or is it a structure pane?) is a very nice addition to the interface!

Thanks,
David

**Comment by gunterkoenigsmann** [comment]
Hey! Thanks for the report!
This explains an issue I had on a colleague's computer about a month ago.

**Comment by dpgoldenberg** [comment]
Glad to be of help! I'll look forward to the fix in the next compiled release.

David

On Aug 5, 2015, at 1:26 PM, Gunter K�nigsman <notifications@github.com> wrote:

> Hey! Thanks for the report!
> This explains an issue I had on a colleague's computer about a month ago.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

--
Department of Biology
University of Utah
257 South 1400 East
Salt Lake City, UT  84112-0840

Telephone: (801) 581-3885
Fax:  (801) 581-2174

E-mail: goldenberg@biology.utah.edu
Lab web page: http://bioweb.biology.utah.edu/goldenberg
