### ISSUE TITLE
wxMaxima got stuck when I tried to assign value to a variable

### ISSUE THREAD

**Issue by JohnHuang-China** [andrejv/wxmaxima#546]
A cell got stuck and all the buttons did so~~then all the wxMaxima went to no respond.
![bug](https://cloud.githubusercontent.com/assets/13872416/9361965/962a13ba-46d0-11e5-83fd-06adbec212e8.png)
I've seldom heard of such a problem from other users.That's strange and I guess there's something wrong when the .exe is going on with my computer.
However,if a matrix is assigned to,it goes well!

OS:Windows 10 Insider Preview 10525.
Maxima Testing:Maxima have been tested.

Could anybody give me a hand?Thanks!

**Comment by gunterkoenigsmann** [comment]
A fairly complete bug report. Thanks a lot for it!

...and I hope we can help: This looks like being a recurrence of Bug #486. I therefore assume installing the fonts from http://www.math.union.edu/~dpvc/jsmath/download/jsMath-fonts.html will solve the problem. If it does I will add the info that this can be the case to the FAQ section of the manual.

Kind regards,

      Gunter.

**Comment by JohnHuang-China** [comment]
![bug2](https://cloud.githubusercontent.com/assets/13872416/9373944/9fa98702-4722-11e5-9932-2b08bc455f71.png)

Thank you for helping me! How to correctly install the jsMath fonts? These fonts shows something wrong,and this operation did not solve my problem.

**Comment by JohnHuang-China** [comment]
It costs half of a two-core CPU!

**Comment by JohnHuang-China** [comment]
The "lisp.exe" stops working! I use Visual Studio 2015 to debug it,and it comes to wrong as former.I have caught some information here.

**Comment by JohnHuang-China** [comment]
![bug6](https://cloud.githubusercontent.com/assets/13872416/9375121/7b641814-472f-11e5-9836-de525c585675.png)

**Comment by JohnHuang-China** [comment]
![bug5](https://cloud.githubusercontent.com/assets/13872416/9375149/d4caa508-472f-11e5-9adc-b30012e01fba.png)

**Comment by gunterkoenigsmann** [comment]
Weird: Lisp.exe is the name of the maxima process - and you indicated maxima without wxmaxima is working fine...
...then it must be one of the commands wxMaxima sends to maxima on startup that makes maxima do this.

What we do on startup is:
 - in wxMaxima::InitSession() wxMaxima starts a server maxima will connect to to establish a communication between the two programs. By default it will use the first free port with a number > 4010 and the port is passed to the maxima process in a way specific to the lisp maxima runs with in wxMaxima::StartMaxima(). Cannot see what is wrong there.
 - in wxMaxima::SetupVariables we send a few assignments to maxima. But these are setting variables to int or bool values => they look insuspicious to me.
 - perhaps I got it: Then we send the name of the currently open file to maxima to inform it about the current working directory it has to chdir to.
 
My guess is that maxima somehow chokes on a non-ascii character in the full pathname to the current file or in the file name. On turkish computers we always had the problem that this didn't work if the path to the private folder of any user by default contains non-ascii characters. Perhaps the same is the case on your computer, as well. Could you try if a file that is placed in a path that only contains standard ascii characters works?

On windows the configuration dialogue contains a checkbox labelled "maxima's pwd is path to document". Did just push commit f9a3cfee8d6c09971f473172d673cb71964de542 to the source code repository of wxMaxima that disables sending the path to the current file to wxMaxima when this checkbox isn't checked. It will be included in the next nightly windows build which will be compiled in - well... ...about 20 hours. Information about how to install it on the local computer can be found here: http://andrejv.github.io/wxmaxima/develop.html

Let's hope this works.

**Comment by JohnHuang-China** [comment]
Thank you! I solve it in the same way.
 jsMath fonts must be installed from
http://www.math.union.edu/~dpvc/jsmath/download/jsMath-fonts.html
 and we must select "Use jsMath fonts".

I hope that the dear developer could solve this problem so that we could us wxMaxima without jsMath fonts using limit.That we will have a choice!
