### ISSUE TITLE
diff() no more working

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#548]
since commit c585cd6719962a3790c4f2d65e35ee3d51554c55 to the maxima, not the wxMaxima repo any use of diff() that returns an unevaluated diff leads to an error message in wxMaxima. Did send a mail to the maxima mailing list about this already.

**Comment by gunterkoenigsmann** [comment]
diff now no more returns an error message. But with the current maxima release the following still won't show a d(f(x))/d(x) but an empty line instead:
        diff(f(x),x);
=> Reopening this bug.

**Comment by andrejv** [comment]
Works for me. Which lisp are you using?

(%i1) 'diff(f(x), x);
(%o1) 'diff(f(x),x,1)
(%i2) diff(f(x), x);
(%o2) 'diff(f(x),x,1)
(%i3) wxbuild_info();
wxMaxima version: 15.8.0
Maxima version: 5.37.0_3_gd427843
Maxima build date: 2015-08-22 21:47:04
Host type: i386-apple-darwin14.5.0
System type: Darwin 14.5.0 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.2.10
(%o3)

**Comment by gunterkoenigsmann** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5041537/9427229/2d0b7466-4971-11e5-8bd7-d596f883d3f4.png)

**Comment by gunterkoenigsmann** [comment]
Perhaps one day I should implement an integrated wireshark-like tab for wxMaxima. The xml I get from maxima is:
![untitled](https://cloud.githubusercontent.com/assets/5041537/9427335/a0230002-4978-11e5-9250-25e3110e15eb.png)

**Comment by andrejv** [comment]
You don't have the latest wxmaxima from git?

**Comment by gunterkoenigsmann** [comment]
Only in /usr/bin, not in /usr/local/bin. Seems like I accidentally have run configure without a --prefix=/usr once. Thanks a lot,

Gunter.
