### ISSUE TITLE
:lisp sometimes halts if it is the first command 

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#551]
If I issue 

    :lisp
        (defun $sin (x)
        (sin x))

as the first command in a wxMaxima session the session halts. It this command is issued after a maxima command has been executed successfully the session doesn't halt, though.

**Comment by andrejv** [comment]
This is more likely a bug in maxima. There is no output from a :lisp command because we use some :lisp-quiet commands when maxima connects to wxmaxima.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!

Just moved this bug report to https://sourceforge.net/p/maxima/bugs/3007/

Kind regards,

    Gunter.
