### ISSUE TITLE
Strange symmetry of acoth(x), area cotangens hyperbolicus function

### ISSUE THREAD

**Issue by nolispnofun** [andrejv/wxmaxima#552]
Plugging the following into Maxima, 14.12.1

-acoth(-x);

gives me 

-acoth(x);

I think area cotangens hyperbolicus should be anti-symmetric, like f(-x) = - f(x)

**Comment by gunterkoenigsmann** [comment]
Thanks for the bug report!

And nice finding! Anyway since this is an error in maxima that does the maths, not in wxMaxima that only displays it - do you want to forward report this bug in the maxima project (either in their bugtracker at maxima.sf.net or in the mailing list that can be found there)? If no I would volunteer for doing it.

Kind regards,

    Gunter

**Comment by nolispnofun** [comment]
Hello Gunter!

Thanks a lot for your quick answer and your kind offer!

I tried first to report the thing at the address

    http://sourceforge.net/tracker/?atid=104933&group_id=4933&func=browse

which  I got from Maxima/wxMaxima

not really knowing what the difference between Maxima/wxMaxima was or is,

but this didn't work 

So if you could help, thanks a lot again!

By the way, wxMaxima/Maxima is really great!

Best regards
nolispnofun

**Comment by gunterkoenigsmann** [comment]
It is - and to be completely honest the last bug I reported against 
maxima in the end really was in wxMaxima.

> http://sourceforge.net/tracker/?atid=104933&group_id=4933&func=browse

This should have been the right bug tracker for maxima and it normally 
works. But sourceforge had a big server outage about two weeks ago. 
Perhaps they are still fine-tuning a few things...

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment]
Dear nolispnofun,


The mailing list already has sent two replies including a possible 
solution:


 >I believe this is caused by line 354 in "trigi.lisp":
 >
 >(setf (get '%acoth 'reflection-rule) #'even-function-reflect)
 >
 >change it to:
 >
 >(setf (get '%acoth 'reflection-rule) #'odd-function-reflect)

Kind regards,

  Gunter.

**Comment by gunterkoenigsmann** [comment]
Robert Dodier has pushed the fix to the current developer version of maxima.
I assume no commercial vendor would react this quickly to a bug report ;-)

Kind regards,

   Gunter.
