### ISSUE TITLE
bizarre eigenvalues of symmetric integer 3x3-matrix

### ISSUE THREAD

**Issue by nolispnofun** [andrejv/wxmaxima#553]
Eigenvalues of 
TT: matrix(
 [9,10,0], 
 [10,1,1],
 [0,1,1]
);

using eigenvalues(TT);
come out rather bizarre (see end of posting)

Since the matrix is so very small and symmetric, this strikes me as very odd indeed.
Maybe Maxima can or should be able to handle this sort of thing, I don't know.  

[[(-(sqrt(3)*%i)/2-1/2)*((sqrt(1226269)*%i)/3^(3/2)+4040/27)^(1/3)+(367*((sqrt(3)*%i)/2-1/2))/(9*((sqrt(1226269)*%i)/3^(3/2)+4040/27)^(1/3))+11/3,((sqrt(3)*%i)/2-1/2)*((sqrt(1226269)*%i)/3^(3/2)+4040/27)^(1/3)+(367*(-(sqrt(3)*%i)/2-1/2))/(9*((sqrt(1226269)*%i)/3^(3/2)+4040/27)^(1/3))+11/3,
((sqrt(1226269)*%i)/3^(3/2)+4040/27)^(1/3)+367/(9*((sqrt(1226269)*%i)/3^(3/2)+4040/27)^(1/3))+11/3],[1,1,1]]

**Comment by gunterkoenigsmann** [comment]
I am no expert in these things but - are you sure if these aren't the real eigenvalues? Normally maxima is one of the few programs that gets them right in any case. If not - or if you just want a second opinion - the maxima-discuss mailing list (http://maxima.sourceforge.net/maximalist.html) should be the right place to ask.

Kind regards,

  Gunter.

**Comment by gunterkoenigsmann** [comment]
Weird: As far as I know the eigenvalues of a matrix M are the values of lambda at which determinant(M-lambda*E) reads zero.

If I am not completely mislead I assume you found another bug - and I beg you to report it to maxima's mailing list or bug tracker - or to ask me to do this: Eigenvalues are important as trigonometrics is.

Thanks a lot and kind regards,

   Gunter

**Comment by nolispnofun** [comment]
Yes,  you are right: eigenvalues of a matrix M are the values of lambda at which determinant(M-lambda*E) reads zero.

I don't know if there really is a bug in the algorithm that computes the eigenvalues.
I think the eigenvalues can be made to appear as the real numbers they must be, 

maybe using  ratsimp(imagpart(eigenvalues(TT)));

but I wonder, why the output is so bizarre (or complicated).

I really would like to report this to the right place, but I didn't succeed.
So if you could help, 

lots of thanks!

(I obviously need time to get behind this.)

Best regards
nolispnofun

**Comment by gunterkoenigsmann** [comment]
Maxima always takes in account complex numbers, as well (just to make 
sure since it deviates from the normal nomenclature: %i stands for 
sqrt(-1)). But I think I found an easier example that I will forward to 
the mailing list:

M:matrix(
    [1,0,0],
    [0,1,0],
    [0,0,1]
);

seems to have two eigenvalues: 1 and 8. The 1 I can acknowledge. But I 
assume the 8 to be an error.

Verified it with the latest maxima version from the git repository, 
too. Let's see what the mailing list answers.

If you want to join the list (I would recommend you to join it: There 
is seldom a day I don't lean from what I read there) just fill in your 
mail address into the form at 
https://lists.sourceforge.net/lists/listinfo/maxima-discuss

You can optionally enter your name there, too, or pick a password for 
unsubscribing from the list later. But if you didn't pick a password 
the list program will still let you unsubscribe if you want to.


Kind regards,

     Gunter.

**Comment by nolispnofun** [comment]
Hello Gunter, 

one has to be careful with the example

M:matrix( [1,0,0], [0,1,0], [0,0,1] );

eigenvalues(M);

gives the list  [[1],[3]]

which means lambda = 1 is the eigenvalue of M, but with multiplicity m = 3
like the same eigenvalue  three times, the characteristic polynomial
being p = (1-lambda)^3

My concern is, why Maxima displays real eigenvalues in such a bizarre
way, showing the imaginary unit %i and stuff.

Maybe there's some good intention behind this, using Cardano's formulae,
or something, but I do not consider this helpful.

By the way, I tried to create an account on sourceforge.net but his failed
and I don't know why, so maybe I should just wait a few days and then
try again.

best regards
nolispnofun

**Comment by gunterkoenigsmann** [comment]
> My concern is, why Maxima displays real eigenvalues in such a bizarre
> way, showing the imaginary unit %i and stuff.
> 
> Maybe there's some good intention behind this, using Cardano's 
> formulae,
> or something, but I do not consider this helpful.
> 
I assume this matrix has complex eigenvalues. You can filter them out 
lateron if you want to - but I assume if they are there maxima has to 
display them for the sake of correctness. We sometimes get reports about

solve (x^(1/12),x)

returning too many solutions - which won't be changed for the same 
reason.

> By the way, I tried to create an account on sourceforge.net but his 
> failed
> and I don't know why, so maybe I should just wait a few days and then
> try again.
> 
I assume you will have to do so.

Kind regards,

    Gunter.
