### ISSUE TITLE
Restarting Maxima when there is a question pending makes wxMaxima crash

### ISSUE THREAD

**Issue by TomasRiker** [andrejv/wxmaxima#558]
Steps to reproduce:

Enter "integrate(x^n,x);" - Maxima will ask if n is -1 or not.

Don't answer the question, but instead click the "Maxima" / "Restart Maxima" menu item.

In my build (very recent Git version), this makes wxMaxima crash.

**Comment by andrejv** [comment]
I can't reproduce this from current git master on OSX.

**Comment by gunterkoenigsmann** [comment]
Neither can I on linux. Will try too reproduce it on windows tomorrow even if I don't have a debugger for this OS.

**Comment by TomasRiker** [comment]
I will rebuild the very latest version and give you the full error message
(looked like some assertion failed). Give me a couple of hours.
Am 06.09.2015 14:30 schrieb "Gunter Königsman" <notifications@github.com>:

**Comment by TomasRiker** [comment]
OK, here is a screenshot of what happens:

![assertionfailed](https://cloud.githubusercontent.com/assets/295205/9706079/0d8a4bde-54da-11e5-8f2d-417aa587771b.png)

Note that even though I did not type in any answer, it shows "Acceptable answers are yes, y, Y, no, n, N." and asks the question again, which it only does if you have entered a bogus answer. This happens as soon as I restart Maxima while the question is still open.

**Comment by andrejv** [comment]
Which lisp do you use to compile maxima?

**Comment by TomasRiker** [comment]
I'm using CCL 1.10.

**Comment by andrejv** [comment]
OK, what does ?getpid() return?

**Comment by TomasRiker** [comment]
A reasonable number - 2072 in my case, which is the PID of the CCL proccess.

**Comment by andrejv** [comment]
Does ccl has a negative pid?

**Comment by TomasRiker** [comment]
No, it's 2072.

**Comment by andrejv** [comment]
Is the Maxima->Interrupt menu entry enabled?

When wxmaxima decides to kill maxima, it seems that it does not know the pid of the maxima process (which is ccl). So it send quit(); over the socket. That is why you get the repeated question.

**Comment by andrejv** [comment]
Another thing which would be useful is to start wxmaxima with the xml inspector sidebar open. After maxima connects, you should see the pid info in the inspector.

**Comment by TomasRiker** [comment]
The "Interrupt" menu entry is disabled ...

How can I start wxMaxima with the XML inspection sidebar open? It doesn't seem to remember the setting. I enable it, quit, and the next time it's gone.

However, I restarted Maxima (using the menu) while the XML inspection sidebar was open, and it made wxMaxima crash - this time without a useful "assertion failed" dialog, though

**Comment by andrejv** [comment]
You need to enable the "Save the sidebar status" in the preferences dialog under the Options tab.

**Comment by TomasRiker** [comment]
This is what the XML monitor shows at startup:

	pid=7820
	Maxima 5.37post http://maxima.sourceforge.net
	using Lisp Clozure Common Lisp Version 1.10-r16196  (WindowsX8664)
	Distributed under the GNU Public License. See the file COPYING.
	Dedicated to the memory of William Schelter.
	The function bug_report() provides bug reporting information.
	(%i1) 

Restarting Maxima with the XML monitor opened crashes wxMaxima.

**Comment by andrejv** [comment]
OK, so one issue is that wxmaxima does not get the pid (the "Interrupt" menu is disabled), but this is not causing the crash.

Does it crash if the xml monitor is closed?

**Comment by TomasRiker** [comment]
Actually, now it crashes every time I restart Maxima, no matter if the XML monitor is open or not. This was not the case previously, I think. Each time it happens, it leaves a 100% CPU CCL process behind, plus another one that's doing nothing.

**Comment by TomasRiker** [comment]
Correction: It only crashes when I restart Maxima without having evaluated any expression before that.

**Comment by TomasRiker** [comment]
This seems to have fixed the issue indeed! Thanks!
