### ISSUE TITLE
string formatting

### ISSUE THREAD

**Issue by Mequin** [andrejv/wxmaxima#559]
I haven't got too much success with my previous attempt to rise this issue, so this is another try
At a wxMaxima prompt, suppose you enter the expression
             str : "hello world" ;     containing a character TAB between "hello" and "world"
for ch in charlist( str ) do print( cint( ch ) ) ;
104
101
108
111
32
32
etc ...
All the TAB characters WITHIN THE STRING have been replaced by spaces
The same thing is also true for CR, LF, etc ...
So, unlike the loading of an equivalent file, the interactive wxMaxima does remove the
formatting information embedded within the user strings
Such different behavior between interactive and batch is by itself questionable
But, for one of my application, is is a real issue
Regards,
     Jacques

```
Maxima version: 5.37.1 (sbcl)
```

wxMaxima version: 15.8.1

**Comment by gunterkoenigsmann** [comment]
I think I broke great parts of this:
 - wxMaxima didn't like TAB characters. For example they broke cursor movement and selection of text in the cells they were in
 - wxMaxima did handle LF characters correctly, but was unable to keep them through a save-load cycle
 - .wxmx files did get completely unusable on encountering some special characters including (but not limited to) ASCII code 27.

...so I decided to silently replace them by a thing that should be displayed, saved and loaded fine. Why do you want to keep them? Perhaps we can find a way to archive what you need without changing wxMaxima too much. If you need to pass them to an external application you could - for example - instruct maxima to write them to a file instead of transferring them using drag-and-drop.

**Comment by Mequin** [comment]
In fact, I told you about TAB but my application requires strings possibly spread on several lines
At some point those strings are finally forwarded by my application to an output file ( in fact a ".c" file )
If I am right until wxMaxima 5.31.2, wxMaxima (on windows) was transcoding any  line break in string as CR  (not LF nor CR-LF)
Yes, when loading those strings as part of  ".mac" file my application still works  (since it supports CR, LF, or even CR-LF in string) 
My only problem is when I have to do some interactive debug, that is interactive cut and paste of statements to wxMasima
During those debug phases, the multi-lines strings are squeezed to an unique line, and so unreadable
So, it is not for me a killer, I hope such silent special characters filtering will not create any more serious pain to anyone else
Regards,    Jacques
Date: Tue, 8 Sep 2015 08:48:39 -0700

**Comment by gunterkoenigsmann** [comment]
Imprementing a real Tab handling needs more time than I currently have. But wxMaxima should now at least handle correctly ASCII code 13.

**Comment by Mequin** [comment]
This is great ! 
ASCII code 13 is enough to detect the end of a line
In fact, digging my archives, I found a file that was already testing carriage-return apparently supported since, at least, 2013
I have never had the need to test TAB and, as I said, all this has never beena killer
Thanks
Regards,   Jacques Date: Fri, 15 Jan 2016 14:58:54 -0800

**Comment by Mequin** [comment]
I have downloaded Maxima  5.39.0  clisp/sbcl


I am glad to see that wxMaxima no longer have a hiccup

the  --open file is now executed only once


But I now see 2 new issues


1) I can no longer control-c text chunk on the screen (however input fields still allow it)


2) a new prompt does not automatically appear on the screen  (even when the open

     cell option is on for expected Maxima input)


Regards,

    Jacques

**Comment by gunterkoenigsmann** [comment]
Issue 1 should already be fixed in the current nightly build. Issue 2 I will investigate.

**Comment by gunterkoenigsmann** [comment]
Resolved by commit cbb3d95e6bb5db2d115b7dadbd551ba63500683d.
