### ISSUE TITLE
Lisp error after 2nd time reload of document

### ISSUE THREAD

**Issue by rend3r** [andrejv/wxmaxima#564]
Here is wxm document:
```
load(draw)$

draw3d(title          = "Sea shell",
             xu_grid        = 100,
             yv_grid        = 25,
             view           = [100,20],
             surface_hide   = true,
             parametric_surface(0.5*u*cos(u)*(cos(v)+1),
                           0.5*u*sin(u)*(cos(v)+1),
                           u*sin(v) - ((u+3)/8*%pi)^2 - 20,
                           u, 0, 13*%pi, v, -%pi, %pi) )$


R:5$

x(phi,t):=R*cos(phi)*sin(t);
y(phi,t):=R*sin(phi)*sin(t);
z(t):=R*cos(t);

u:[0,2*%pi];
v:[0,%pi];

sphere:parametric_surface(x(phi,t),y(phi,t),z(t),phi,u[1],u[2],t,v[1],v[2]);
draw3d(sphere)$
```
When evaluating all cells 2 time get error after 2 block:
```
Maxima encountered a Lisp error:
 The value 0 is not of the expected type LIST.
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
```
![max_err](https://cloud.githubusercontent.com/assets/12601181/9839098/904e5c52-5a77-11e5-91ca-67b92671974e.png)
Error is gone if restart maxima.

wxMaxima 15.08.1
wxWidgets: 3.0.2
Unicode Support: yes
Maxima version: 5.37.1 
Lisp: Clozure Common Lisp Version 1.9-r15764 (WindowsX8632)
Clisp or sbcl builds are affected too.

**Comment by gunterkoenigsmann** [comment]
This has happened to me, too:
The problem is that after assigning u and v values maxima uses the 
knowledge about these values for interpreting the draw3d line.
Starting the file with a kill(u,v) therefore solves the problem.

Kind regards,

 Gunter.

**Comment by rend3r** [comment]
Why doesn't just kill(all) internally before evaluating? Many people (ok, at least i am) assuming that previous calculations does not interfere next one after pressing ctrl+r in wxmaxima.

**Comment by gunterkoenigsmann** [comment]
kill(all) would not be sufficient since it doesn't affect all flags and functions. But I always wondered why on a "evaluate all cells" wxMaxima doesn't restart maxima, too.

Am 14. September 2015 19:47:13 MESZ, schrieb rend3r <notifications@github.com>:
>Why doesn't just kill(all) internally before evaluating? Many people
>(ok, at least i am) assuming that previous calculations does not
>interfere next one after pressing ctrl+r in wxmaxima.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/564#issuecomment-140157614

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by gunterkoenigsmann** [comment]
Now the "evaluate all cells" button completely restarts maxima before clearing the evaluation queue and scheduling the whole document for evaluation. Did change the "Evaluate all visible cells" and the "Evaluate document till here" commands, too. Hope, that this was a good idea. If it wasn't feel free to protest against it.
