### ISSUE TITLE
Plot error released with version version 5.37.0 - still present in version 5.37.2

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#567]
This error is occurred in version  5.37.0 but is  still present in the new version 5.37.2:
----------------------------------------------------------------------------------------------------------------------
1. It seems like wxMaxima looses the connection to maxima eftger having executed the set_draw_defaults(...) command, But only if this option is included: "set format y \"%0.3se%03S\""
2. That means this one:
--------------------------------------
set_draw_defaults(
dimensions = [1500, 800],
user_preamble = ["set xtics out", "set mxtics 10", "set ytics out", "set font \"Areal, 8 \"", "set zero 10^-100", "set format y \"%0.3se%03S\"", "unset clip", "set autoscale y", "set autoscale x" ],
font = "Times",
font_size = 12,
title = PlotTitle,
xlabel = PlotXlabel,
ylabel = PlotYlabel,
grid = true,
palette = gray,
point_type = 0,
point_size = 1,
points_joined = true);
--------------------------------------------
Goes ok - BUT ONLY IF I leave "set format y \"%0.3se%03S\"" out !

This have been working in all previous versions....
Any clue ?

PS: I sorry for the wrong formatiing - I can't figure out why it goes like this :-(

**Comment by gunterkoenigsmann** [comment]
I have no access to a computer right now so I cannot test this myself. But can you verify if the problem persists if you replace the \" by ' ?
Thanks a lot and kind regards,

   Gunter.

Am 19. September 2015 10:15:16 MESZ, schrieb Rene Hansen <notifications@github.com>:
>This error is occurred in version  5.37.0 but is  still present in the
>new version 5.37.2:
>----------------------------------------------------------------------------------------------------------------------
>1. It seems like wxMaxima looses the connection to maxima eftger having
>executed the set_draw_defaults(...) command, But only if this option is
>included: "set format y \"%0.3se%03S\""
>2. That means this one:
>--------------------------------------
>set_draw_defaults(
>dimensions = [1500, 800],
>user_preamble = ["set xtics out", "set mxtics 10", "set ytics out",
>"set font \"Areal, 8 \"", "set zero 10^-100", "set format y
>\"%0.3se%03S\"", "unset clip", "set autoscale y", "set autoscale x" ],
>font = "Times",
>font_size = 12,
>title = PlotTitle,
>xlabel = PlotXlabel,
>ylabel = PlotYlabel,
>grid = true,
>palette = gray,
>point_type = 0,
>point_size = 1,
>points_joined = true);
>--------------------------------------------
>Goes ok - BUT ONLY IF I leave "set format y \"%0.3se%03S\"" out !
>
>This have been working in all previous versions....
>Any clue ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/567

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ReneSci** [comment]
Just tried this:
user_preamble  = ["set xtics out", "set mxtics 10", "set ytics out", "set font \"Times, 8 \"", "set zero 10^-100", "set format y '%0.3s e%03S' ", "unset clip", "set autoscale y",  "set autoscale x" ], ....
It didn't make any difference.
best
Rene'

**Comment by ReneSci** [comment]
Maxima stucks at the next command. If I then press the button "Completely stop Maxima and restart" , I get the reply:

C:\Users\u265227\Applications\MAXIMA Math GNU\DEBUGGING\setFormaterror1.wxmx .gif

Then I maxima has restarted noamally.
kind regards
Rene'

![setformaterror1 wxmx](https://cloud.githubusercontent.com/assets/2638713/9975380/e4bc80d8-5eba-11e5-9454-ef9a94b36051.gif)

**Comment by ReneSci** [comment]
Hurray - found it:
When I changes both 

"set font \"Arial, 8 \""  to  'set font 'Arial, 8 ' "
and
"set format y \"%0.3se%03S\""   to  "set format y '%0.3se%03S' " 

It all works !
- it seems to be a change in what can be accepted from this version
Thanks a lot for your help.
Have a nice weekend
Rene'

**Comment by ReneSci** [comment]
However - now it dosen't seem to react on the option 
dimensions    = [1500, 800]
in the set_draw_defaults(...) anumore ??
- the plots are still small - it only changes the size if I change the "Default plot size" under the menu "Settings"
- but then the graph becomes quite blurry, and not as nice as previously.
/Rene'


![plotexample](https://cloud.githubusercontent.com/assets/2638713/9975588/0866216e-5ec1-11e5-8db5-5b034efaa715.gif)
 
/Rene'

**Comment by ReneSci** [comment]
And...
Previously {/symbol l}  - gave me nice lambda in the plot - now it don't ....
/Rene'

**Comment by gunterkoenigsmann** [comment]
For the size I can perhaps help you:

     wxplot_size:[1024,768]$

should do the trick.

If gnuplot can produce a lambda depends on the fonts the gnuplot 
bundled with your maxima was packaged with.
Here wxMaxima cannot help: This depends solely on the setting the 
installer was created with.
Will add the symbol to wxMaxima's manual testbench, though, so this 
gnuplot feature can be tested for.

Kind regards,

      Gunter.

**Comment by ReneSci** [comment]
Thank you again, for your prompt reply. It seems like maxima is not  able to print greek letters at all in this version - i know this dosen't belong to this forum.
kind regards
Rene'

**Comment by gunterkoenigsmann** [comment]
You're welcome!

There is a thread about Unicode support on the discussion mailing list on maxima.sf.net. perhaps this would be the right place to report it.

Kind regards 

  Gunter.

Am 19. September 2015 12:35:12 MESZ, schrieb Rene Hansen <notifications@github.com>:
>Thank you again, for your prompt reply. It seems like maxima is not 
>able to print greek letters at all in this version - i know this
>dosen't belong to this forum.
>kind regards
>Rene'
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/567#issuecomment-141643738

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ReneSci** [comment]
Did that already..

**Comment by gunterkoenigsmann** [comment]
The thread actually seems to contain a solution for half of the problem.
Would you be willing to test if it works out for you and if it does to 
answer my last question in this thread? This means: After downloading 
the code and doing a

      load("utf8-hack.lisp");

in a file that is in the directory the code lies in (and after telling 
wxMaxima in the "maxima" tab of the configuration that it should use 
the path to the current file as maxima's working directory) a

      g1:ü=1;

should no more hang but make ü accessible by


      at(ü,g1);

If maxima supports utf8 the next step: bundling it with a gnuplot that 
does do so, too - shouldn't be this big any more.

Thanks a lot,
and kind regards,

     Gunter.

**Comment by ReneSci** [comment]
Yes - of course - I will do it later today or tomorrow.
King regards
Rene'

**Comment by ReneSci** [comment]
Hmmm... downloaded the "utf8-hack-master" from https://github.com/leo-butler/utf8-hack
and copied the files into the directory:
C:\Program Files (x86)\Maxima-sbcl-5.37.2\share\maxima\5.37.2\src\
When i try to do load("utf8-hack.lisp"), i got an error message:
load("utf8-hack.lisp");
                             ; compilation unit aborted
                             ;   caught 1 fatal ERROR condition
loadfile: failed to load C:/Program Files (x86)/Maxima-sbcl-5.37.2/share/maxima/5.37.2/src/utf8-hack.lisp

Maybe I am doing it wrong..
best regards
Rene'

However, using greek in equations by using eg %lambda goes ok it is the greek letters in the plots that dosen't work anymore - it did back in version 5.28.0-2 but starting with 5.36.1 it stops working


![maxima 5_36_1](https://cloud.githubusercontent.com/assets/2638713/9982801/f79d71a2-5fe7-11e5-9f9b-f37c99c09079.gif)
![maxima 5_28_0_2](https://cloud.githubusercontent.com/assets/2638713/9982802/f7a1a826-5fe7-11e5-9d31-5972b754d72d.gif)

**Comment by gunterkoenigsmann** [comment]
Which of the installers did you use?
Perhaps I can get hold of a windows computer today.

Kind regards,

  Gunter.

Am 20. September 2015 22:36:55 MESZ, schrieb Rene Hansen <notifications@github.com>:
>Hmmm... downloaded the "utf8-hack-master" from
>https://github.com/leo-butler/utf8-hack
>and copied the files into the directory:
>C:\Program Files (x86)\Maxima-sbcl-5.37.2\share\maxima\5.37.2\src\
>When i try to do load("utf8-hack.lisp"), i got an error message:
>load("utf8-hack.lisp");
>                             ; compilation unit aborted
>                             ;   caught 1 fatal ERROR condition
>loadfile: failed to load C:/Program Files
>(x86)/Maxima-sbcl-5.37.2/share/maxima/5.37.2/src/utf8-hack.lisp
>
>Maybe I am doing it wrong..
>best regards
>Rene'
>
>However, using greek in equations by using eg %lambda goes ok it is the
>greek letters in the plots that dosen't work anymore - it did back in
>version 5.28.0-2 but starting with 5.36.1 it stops working
>
>
>![maxima
>5_36_1](https://cloud.githubusercontent.com/assets/2638713/9982801/f79d71a2-5fe7-11e5-9f9b-f37c99c09079.gif)
>![maxima
>5_28_0_2](https://cloud.githubusercontent.com/assets/2638713/9982802/f7a1a826-5fe7-11e5-9d31-5972b754d72d.gif)
>
>
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/567#issuecomment-141832047

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ReneSci** [comment]
This one:
maxima-sbcl-5.37.2.exe
Kind regards
Rene'
Is it easy to compile/build maxima?  I have unfortunately only experience with Delphi/pascal ....

**Comment by ReneSci** [comment]
Regarding the \" Setting \"  versus  ' Setting '   in the user_preamble:
Would it be possible in the next release to make wxMaxima/Maxima axept both and not freeze every time it meet a \"setting\" - it is bit annoying - have to correct 10's of wxMaxima-files :-(
Best regards
Rene

**Comment by gunterkoenigsmann** [comment]
It took a while to find out how to trigger this on my own machine but 
it seems you found a genuine bug.
The next nightly build of wxMaxima will contain a bugfix.


Kind regards,

  Gunter.

**Comment by ReneSci** [comment]
Always glad to help.
/Rene'
