### ISSUE TITLE
Menu: Configure/Worksheet/Show long expressions

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#568]
No matter what setting is chosen (no/yes/if not....) - long outputs are always terminated with the message: 
... [suppressed additional lines since the output is longer than allowed in the configuration] 

Before  I had been choosing "not if too long" and then vent back to "yes" - the setting "yes" completely eliminated all outputs, but "No" gave the above result.

Best regards
Rene'
wxbuild_info():
wxMaxima version: 15.8.2
Maxima version: 5.37.2
Maxima build date: 2015-09-18 21:03:17
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7

**Comment by gunterkoenigsmann** [comment]
Hey! Thanks!

Didn't find this one. But be warned: Now that this bug is fixed a "Show 
long output: yes" to a command that returns an infinite number of lines 
of output will completely hang wxMaxima until maxima is killed in the 
process manager.

**Comment by ReneSci** [comment]
Sorry - here's one more:
The title of the wxMaxima no longer reflects any chages in the filename
after been using e.g. "save as", nor does the * go away after having saved
the file. When ending, wxMaxima asks if I want to save the unsaved file
even though I just did.

/ I am afraid I give you quite some work /

Best regards
Rene'


2015-09-21 19:03 GMT+02:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
This one I can neither reproduce on Windows nor on Linux => In this 
case we have to hope that Andrej can fix it.


Kind regards,

     Gunter.

**Comment by gunterkoenigsmann** [comment]
Ok... This should be fixed in the next nightly build, too.

Kind regards,

    Gunter.

**Comment by ReneSci** [comment]
I got the nightly build from here.

http://wolfgang.dautermann.at/maxima/wxmaxima-daily-win.zip

the \" option \" now seems to work - good work.

However - now the command
wxfilename

dosen't give anything ?

Best regads
Rene'


2015-09-21 22:22 GMT+02:00 Gunter Königsman <notifications@github.com>:
