### ISSUE TITLE
Slow and blurry graphic with wxdraw

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#569]
in version maxima-sbcl-5.37.2.exe:
If I set a 
wxplot_size:[1500, 800];
The plot "image" becomes blurry, and scrolling a page with an image becomes quite slow. 
in the previous version maxima-sbcl-5.36.1.exe the plot "images" where sharp and the scrolling was fast. - why?
Kind regards
Rene'

**Comment by gunterkoenigsmann** [comment]
I actually did implement this as a new feature: I work with the same 
wxMaxima files on computers with vastly different screen resolutions: 
1024x768, 1920xsomething big and a high-DPI machine. Therefore very 
time I generated a graph on one computer it was either tiny on the 
other ones or way too big to fit on the screen => Added as auto-scaling 
mechanism that scales down images that are too big to fit on the screen 
to 90% of the screen size... ...and I chose a scaling method that uses 
a nice antialiassing algorithm that doesn't just drop pixels on scaling 
down (which tends to make text and sometimes the displayed curves, too 
unreadable) but rather keeps text and lines readable by keeping pixels 
visible even if they that happen to lie between the dots on the 
physical screen: A pixel whose one half is occupied by a black pixel 
and whose other half is occupied by white background will be displayed 
half-black (aka gray) instead. The disadvantage of this scaling 
approach is that these pixels appear to be blurred. If you export or 
save the image or view it on a large enough screen it will appear in 
its original sharpness again.

...found out only later that the scaling is real fast on some computers 
but not on others => The newest development version (Instructions on 
how to acquire it are here: 
http://andrejv.github.io/wxmaxima/develop.html) is fast again and still 
manages to save memory in respect to the previous versions.


If you really need this option I would be willing to add a checkbox to 
the configuration dialogue that turns off auto-scaling. But I don't 
want to clobber the options dialogue with too many items so I only will 
do this on an explicit request.

Kind regards,

  Gunter.

**Comment by ReneSci** [comment]
Maybe I should try the newest version before brother you more on this.
Still wish I could contribute more actively..
Kind regards
Rene'

**Comment by gunterkoenigsmann** [comment]
Unfortunately I don't know how hard it is to set up a compiler on 
windows. But - big parts of the code are documented and - we are always 
happy if we get a helping hand as does the maxima project.

On the other side you found a hard-to-trigger bug and if I am quite 
confident that thanks to your help I was able to resolve it => no 
complaints from my side.

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment]
In order to test the feature I advise you to try to make a wxMaxima window that contains diagrams smaller.
