### ISSUE TITLE
Malformed wxm sheet leads to alert/error

### ISSUE THREAD

**Issue by rend3r** [andrejv/wxmaxima#570]
Just removed from the end of file
/* [wxMaxima: input   end   ] */

/* Maxima can't load/batch files which end with a comment! */
"Created with wxMaxima"$

Then get warning window and hang up the wxmaxima

**Comment by gunterkoenigsmann** [comment]
I assume you tried to import a .mac file. Right? If this is true i assume this to be a maxima bug, not a wxMaxima one: Maxima will only process files right that don't end in a comment.

**Comment by rend3r** [comment]
No, just open malformed wxm as i said. Look the samples [dump](https://dl.dropboxusercontent.com/u/30953076/wmx.zip).
"Ugly" wxm was made somehow when copying it while wxmaxima running but i could not reproduce steps for now.

**Comment by gunterkoenigsmann** [comment]
If you would find out how to trigger the actual cause of the problem: How to trigger wxMaxima to create bad files that would be helpful.

I personally only use .wxmx files: They save more features and have grown stable enough for my use.
