### ISSUE TITLE
Printing is broken

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#572]
Original bugreport http://sourceforge.net/p/maxima/bugs/3018/.

**Comment by rweis66** [comment]
sorry, to bother you with this. But printing of text cells still not works properly.
Input Cells and *the first* text cell are printed.
But no further text cells or section titles
Only the first of these cells are printed.
I pulled the last git version and tested it.

**Comment by caoliver** [comment]
This is still broken as of commit 772ab8a

I don't know the code base at all, so my stabs at debugging have been futile.

**Comment by gunterkoenigsmann** [comment]
Did try to compile 6f01056a51bdd4921089a05a4b748626797a8a07 - which is far older than the last version known as having been able to print. Still I get the same result as with the current source => Seems like whatever caused printing to break was a change on wxWidget's side.
