### ISSUE TITLE
saves regular session .wxmx files with no report of errors but cannot open them again

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#575]
see the attached files. I did not put in anything extra or change files after they were saved.
Why don't you support that type of file .wxmx to attach here. See maxima bug 3001 where i attached an example file.

**Comment by gunterkoenigsmann** [comment]
Which version of wxMaxima are you using?

.wxmx files are ordinary .zip archives and can be opened with any .zip viewer if you rename them to end in .zip.
 Old versions of the program allowed to introduce illegal characters into the content.xml file inside this .zip file - but that should no more be possible with new versions.

You can fix them by hand, anyway or send them to me and I will do so.

Kind regards,

  Gunter.

Am 26. September 2015 00:02:16 MESZ, schrieb zmth <notifications@github.com>:
>see the attached files. I did not put in anything extra or change files
>after they were saved.
>Why don't you support that type of file .wxmx to attach here. See
>maxima bug 3001 where i attached an example file.
>
>
>
>
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/575

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by gunterkoenigsmann** [comment]
Your mail states that you attached some files to it. Seems like github 
wanted to protect us from them and hasn't forwarded them and did 
forward us only the text.

Kind regards,

  Gunter.

**Comment by zmth** [comment]
wxMaxima version: 13.4.0
 Maxima version: 5.31.1
 Maxima build date: 2013-09-24 09:49:12
 Host type: i686-pc-mingw32
 Lisp implementation type: GNU Common Lisp (GCL)
 Lisp implementation version: GCL 2.6.8

thought i put that in already but perhaps forgot. I am afraid to install a new version as don't know what will happen with all of the mess of directories and subdirectories nested galore. Also don't know if my existing .wxmx files will load and run properly.

**Comment by gunterkoenigsmann** [comment]
Dear Zmth,

 > thought i put that in already but perhaps forgot.
The cause might also be a over-eager malware protection from github 
that deletes attachments it doesn't know enough so it cannot prove them 
to be harmless. My private e-mail address is gunter (at) physikbuch.de 
so if github won't forward me files they can be sent to me using this 
means.

 >I am afraid to install a new version as don't know what will happen 
with all of the mess of directories and subdirectories nested galore.
Don't be afraid: We didn't change the directory structure in a long 
time.
 >Also don't know if my existing .wxmx files will load and run properly.
They will. The wxMaxima team is proud that they managed to keep the 
program both forward- and backwards-compatible:
The newest wxMaxima will still be able to read all files from 13.04. 
And 13.04 will ignore all new features introduced in the current 
wxMaxima, but will still load all text contained in .wxmx files from 
all new wxMaxima versions; Maxima (that does the actual maths) didn't 
change too much in the last two years.

If you are unsure you can even install several versions of wxMaxima at 
the same time on the same system and give them all a try. The windows 
installers will make sure that they are installed in separate 
directories and in the configuration dialogue you can even choose which 
of the installed maxima programs has to be used for doing the actual 
maths for the currently running version of wxMaxima.

Given that in the last two years many bug reporters and the wxMaxima 
developers did find many ways to crash wxMaxima and we managed to fix 
them all I always recommend to upgrade wxMaxima to its newest version.

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment]
Ok... ...the next nightly build will include commit 0ffe09cb7cd03d96de6b98b265801850fdfe82c9 that won't hinder wxMaxima from complaining about the error. But it will try to automatically correct the .wxmx file and to open it. Sorry that finding a way to do so did take this long.
