### ISSUE TITLE
fails to give parsing error - forever calculating

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#578]
wxMaxima version: 13.4.0
Maxima version: 5.31.1
Maxima build date: 2013-09-24 09:49:12
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8

(for i thru 9 do ldisp([i])/*end i);

Instead of giving a parsing error maxima is forever calculating with no display. This is most annoying when the error is the usual case in a program inside many do loops inside other loops ...

**Comment by gunterkoenigsmann** [comment]
This one is fixed in wxMaxima 15.08. An installer for this version can be found at http://maxima.sourceforge.net.

Kind regards,

     Gunter.
