### ISSUE TITLE
 wxMaxima crashs,when enters the following expression

### ISSUE THREAD

**Issue by cheny8907** [andrejv/wxmaxima#580]
When entering the following expression,wxMaxima crashs
a:e^(x^2)-e^(2-cos(x))

I test the same command in xmaxima,it works OK .So I think it may be a bug  with wxMaxima

wxMaxima version: 15.8.2
Maxima version: 5.37.2
Maxima build date: 2015-09-18 21:03:17
Host type: i686-pc-mingw32
System type: Win32 6.2.9200 X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7

**Comment by gunterkoenigsmann** [comment]
This isn't reproducible on my computer => I assume this to be another 
occurrence of https://github.com/andrejv/wxmaxima/issues/486 which also 
contains a local solution of the problem.

Kind regards,

  Gunter.

**Comment by cheny8907** [comment]
After install jsmath font here 
http://www.math.union.edu/~dpvc/jsmath/download/jsMath-fonts.html
it is solved.
