### ISSUE TITLE
Escape sequences for \partial and \int signs

### ISSUE THREAD

**Issue by aabalakin** [andrejv/wxmaxima#583]
Hi!
Can you add an escape sequences (like <ESC>diff<ESC> and <ESC>int<ESC>) for LaTeX symbols \partial ( ∂, U+2202 ) and \int ( ∫, U+222B )? Probably, these symbols can be used as synonyms of maxima commands diff() and integrate().

**Comment by gunterkoenigsmann** [comment]
Converting the symbols to diff() and integrate() on-the-fly would have meant writing a complex parser and I could not guarantee that it makes the right decisions if the user for example tries to solve a differential equation with the "separation of variables" method. But I assume you want to use the symbols mainly in text and you won't mind that I left out this part.

Did ask the maxima mailing list if it made sense to automatically convert a diff() in maxima's output to "partial" symbols for the 2d maths display.

Kind regards,

 Gunter.

**Comment by aabalakin** [comment]
Dear Gunter,

Thank you very much. Yes, I want to use these symbols in the text most of time.

I've just imagined that "∂(sin(x),x)" or "∂_x (sin(x))" will look shorter (more human readable) than "diff(sin(x),x)". But this is only negligible (minor) improvements in fact.

Kind regards,
Alexey Balakin
