### ISSUE TITLE
[Shift]+[Enter] no longer evaluates the selected cells (Today's Nightly Build)

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#588]
Just downloaded the Nightly Build:
When a number of cells are selected by selecting the cell-brackets, then [SHIFT]+[ENTER] no longer evaluates the cells - does nothing. The cells can only be evaluated by using the menu-"evaluate Cell(s)" - or by placing the cursor in the cells one-by-one and press  [SHIFT]+[ENTER] 
Best regards
Rene'

Edit: [CTRL]+[ENTER] evaluates the cells - a new definition ?

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!

Having good testers is an important thing.

**Comment by ReneSci** [comment]
Just glad to help :-)

2015-10-07 20:07 GMT+02:00 Gunter Königsman <notifications@github.com>:
