### ISSUE TITLE
Error introduced from nightly build date 2015-9-23 to 2015-10-07

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#589]
In the build 2015-10-07: When trying to make a new line in a text cell by pressing [ENTER], the cursor jumps to the end of the next cell - works ok in the 2015-9-23 build ??

Kind regards
Rene'

Windows 7

**Comment by gunterkoenigsmann** [comment]
What I originally was trying to do was to only change the behavior of 
the "evaluate" shortcut in the following way:
 - If a cell is active it evaluates this cell
 - if several cells are selected instead - we evaluate them instead
 - and if neither of this happens the cursor jumps to the next cell so 
pressing Ctrl+Enter for a long time evaluates many cells: Steve Job has 
taught us all that it isn't good to leave a shortcut around that does 
nothing if there would be a thing that would feel logical - if it would 
be implemented.

Seems like my attempt to do this didn't work at al I reverted the code 
to the old behavior. Today's nightly build should therefore work - and 
I will give my changes another try today.

Kind regards,

  Gunter

**Comment by ReneSci** [comment]
But you idea sounds good anyway.

In the same direction: Would it be possible to do this: If the user selects
a header or a sub-header [SHIFT][ENTER] evaluates all the cells belonging
to that header. I little like in Mathematica where several cells can be
grouped together in a sort of "super-cell" and selecting the "super-cell"
evaluates all the cells herein ?
Kind regards
Rene'


2015-10-08 7:16 GMT+02:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
Don't know if I would like Shift+Enter change its meaning drastically => we should ask andrejv before assigning the new pop-up-menu-entry to a shortcut. But at least the code to do so is there now.

**Comment by gunterkoenigsmann** [comment]
I could live with Shift+Ctrl+Enter meaning "evaluate this chapter/section/..." and would even be willing to write the code that if a cell isn't a sectioning command heading determines which section the current cell is in. Would this be OK for you instead?

**Comment by ReneSci** [comment]
Sounds wery good
 :-)


2015-10-10 16:37 GMT+02:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
Ok... ...Will commit the said code that will either do as I stated - or 
be completely broken on windows since I don't have a working windows 
installation to test it on => I advice you to better keep a backup copy 
of wxMaxima.exe at hand.

Kind regards,

   Gunter

**Comment by ReneSci** [comment]
I will do a test asap.
Kind regards
Rene'


2015-10-11 9:03 GMT+02:00 Gunter Königsman <notifications@github.com>:

**Comment by ReneSci** [comment]
Just did a test via today's nightly build,
The evaluate section/subsection etc. seems to work very well. As is
wxMaxime as a whole - it seems to be a god release.
And a especially nice feature is that, when evaluating a section, only
those subsections which are opened (expanded) are evaluated - thanks a lot.
A note for the user manual: selecting the bracket at a section header
doesn't give this option, the cursor has to be placed in the
section/subsection header text to make it available.

By the way gnuplot: you wrote that when doing a plot by draw2d, the zoom of
the plot went out in a strange (small) size. I get the same. If I then
opens the gnuplot command window and just press [Replot] - the plot goes
fine. Hope it gives you a clue.

Still the same about greek letters [esc]l[esc] gives a nice lambda in
wxdraw2d but have to use " {/symbol l}" to get a lambda in draw2d



2015-10-11 11:33 GMT+02:00 Rene Hansen <reneshansen@gmail.com>:

**Comment by gunterkoenigsmann** [comment]
Did file an issue for the strange border from gnuplot: https://sourceforge.net/p/gnuplot/support-requests/193/ Don't know if the greek letter issues originate in the packaging of the gnuplot version that is shipped with maxima, not in the source. But if you find a way to reproduce the strange size I assume you could file a ticket there, as well.

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment]
Right-clicking on the bracket should now work. And you did give a valuable hint even if I needed help by the gnuplot guys to see it: If a replot solves the problem it is likely to be caused by a "set" command in maxout_xxx.gnuplot being issued *after* it is needed. This would make it a maxima, not a wxmaxima problem, though => For the black border I already have handed in a patch that awaits approval. If you have a minimal working example for the gnuplot graph size issue you should report it at the maxima project.

Kind regards,

     Gunter.
