### ISSUE TITLE
hitting dot (.) on (french) keyboard produce strange Lisp error

### ISSUE THREAD

**Issue by puiseux** [andrejv/wxmaxima#592]
Hello,
I'm working on MacBookPro11,3, OS X El Capitan, Version 10.11
in maxima i have no problem: 
```maxima
(%i1) set_display(ascii)$

(%i2) a:1.0;
(%o2)                                 1.0
```
in wxmaxima : 

```maxima
(%i1) set_display('ascii)$

--> a:0/*just here i hit dot '.' on my (french) keyboard*/
```
I obtain this unexpected result (modifying last output):
```maxima
(%i1) set_display('ascii)$
Maxima encountered a Lisp error:
 Interactive interrupt at #x7FFF8B7DE222.
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
--> a:1/*no dot here*/
```
I can do with Cmd-C/Cmd-V but it's a pain !

**Comment by andrejv** [comment]
Are you sure that you are not pressing CMD+. which is a shortcut for the interruption command?

**Comment by puiseux** [comment]
I do not press Cmd+., i’m sure.
On french keyboard, the dot (.) is obtained with Shift+. 
There is no dot without Shift.

**Comment by puiseux** [comment]
I'm sure I do not press Cmd+.
On french keyboard, the dot (.) is obtained with Shift+.

**Comment by andrejv** [comment]
You need to replace the file wxMaxima.app/Contents/Resources/locale/fr/LC_MESSAGES/wxMaxima.mo with an updated translation (right click wxMaxima.app and select "Show Package Content" from the menu).

I copied the updated file here: https://www.dropbox.com/s/ozygoibfozblc4t/fr.mo?dl=0
