### ISSUE TITLE
Double-clicking to a table-of-contents-entry we never scrolled to doesn't scroll

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#594]
Don't seem to find the reason even if I have tried several times: In several cases we still fail to scroll to cells.

How to trigger this:
 - load a long file 
 - double-click on the table of contends entry of a cell that is below the currently visible portion of the file
 - wxMaxima will move the cursor there but won't scroll.

**Comment by gunterkoenigsmann** [comment]
This bug actually appears in many places:
 - sometimes wxMaxima doesn't scroll to the currently evaluated cell when evaluating a part of a document the user has never manually scrolled to before in the current wxMaxima session
 - search sometimes doesn't scroll to the cell it found something in.
 - and sometimes maxima still scrolls to the beginning of the document instead of scrolling to the point it is supposed to scroll to.

**Comment by andrejv** [comment]
When wxmaxima wants to show (scroll to) a cell, it checks the m_currentPoint to get the coordinates. But this is set when the cell is drawn to the screen MathCell::Draw. At least for group cells, maybe set the m_currentPoint in RecalculateSize?

**Comment by gunterkoenigsmann** [comment]
This approach sounds quite promising: Doing so should only need a neglectible amount of time at every refresh but should fix a bundle of scrolling-related bugs:
 - Scrolling for the search feature is sometimes broken
 - Scrolling to the cursor is sometimes broken as well if the cursor is moved outside of the screen during typing
 - Scrolling to the currently evaluated cell sometimes ends up in the wrong place after big output (like plots) has been added to the worksheet.
 - Scrolling to a given place sometimes is broken in newly-opened files.

Unfortunately I seem still to lack the knowledge about a vital part of the position calculations.

**Comment by gunterkoenigsmann** [comment]
Ok... ...Seems my changes did something. But scrolling to a given editor cell or a given cell within the output still fails for cells that have never been displayed or that have moved after being displayed. Seems like additional steps are necessary.

**Comment by andrejv** [comment]
How do you scroll to a cell which has not been displayed?

**Comment by gunterkoenigsmann** [comment]
A cell that not has been displayed in the current session.

How to reproduce:

Open the attached file, don't try to scroll anywhere and use the search
function in order to find the word "dog".


Kind regards,

   Gunter.

**Comment by andrejv** [comment]
Should be fixed with 63e04e1221a
