### ISSUE TITLE
Printing of text cells does not work

### ISSUE THREAD

**Issue by daute** [andrejv/wxmaxima#597]
Printing of text cells, title cells, etc. does not work in wxMaxima 15.08.2  (it did work in 15.04).

Best regards, Wolfgang

**Comment by gunterkoenigsmann** [comment]
Andrej has once mentioned in regards to a similar bug that he resolved an error in git. The same might be the case with this one.

**Comment by andrejv** [comment]
Yes, this has already been fixed (issue #572, fixed with commit 25753f2).
