### ISSUE TITLE
F1 doesn't open help

### ISSUE THREAD

**Issue by anddam** [andrejv/wxmaxima#598]
F1 function key on a MacBook Pro running os X 10.10.5 doesn't trigger the help as suggested at [in the reference manual](https://github.com/andrejv/wxmaxima/blob/b849a7a1693c475fdcd283f1b1a5864c3696422c/info/wxmaxima.texi#L120). Furthermore selecting text in a cell and then hitting F1 key deletes the text.

This happens either building with MacPorts or using provided 5.36.1 binary for OS X on the website.

**Comment by andrejv** [comment]
On OS X we use the standard shortcut to open the help dialog, which is CMD+?.
