### ISSUE TITLE
wxMaxima15.4.0 exit whenever w is pressed 

### ISSUE THREAD

**Issue by bobabu** [andrejv/wxmaxima#601]
Hi There;
WxMaxima Mac64 bit version has a bug, anytime press W will exit the program.
That's because the shortcut of exit is  "W" instead of command+W 
I had use the windows version it it good :)
I just want to know is there anyway to customize the shortcut? 

Thanks 
Albert

wxMaxima version: 15.4.0
Maxima version: 5.36.1
Maxima build date: 2015-05-06 11:10:10
Host type: x86_64-apple-darwin14.3.0
System type: Darwin 15.0.0 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.2.10

**Comment by andrejv** [comment]
This is probably a mistake in a translation. In which language are you using wxMaxima?

A temporary workaround is to switch to English.

**Comment by bobabu** [comment]
I set the Mac Default language to Chinese Simple but i could try as what you said and update soon 
Thanks for your reply

**Comment by bobabu** [comment]
Yes , As you said i change the language to English, problem is solved 

Thanks a lot
