### ISSUE TITLE
wxmaxima --open hello.mac

### ISSUE THREAD

**Issue by Mequin** [andrejv/wxmaxima#602]
wxmaxima 15.8.2

When calling the execution of "wxmaxima --open hello.mac" with a simple flie containing the line
                         print( "hello world" ) ; 
the wxmaxima windows popup by displaying 2 times "hello world" 
Is there an explanation or is it some kind of bug ? 

Regards, Jacques

**Comment by gunterkoenigsmann** [comment]
Found the reason for this bug and corrected it in the git master.
