### ISSUE TITLE
When I evaluate the gamma function. wxMaxima freezes.

### ISSUE THREAD

**Issue by gendaibushi** [andrejv/wxmaxima#607]
I'm using wxMaxima for windows.wxMaxima (version 15.08.2).
When I evaluate the gamma function. wxMaxima freezes.

examle.

When I evaluate the following as 'gamma(x);'
 => wxMaxima freezed.

When I evaluate the following as 'gamma(1);'
=> wxMaxima return 1  (it's correct.)

I'm sorry if it was if the wrong report.
And sorry my english.

**Comment by gunterkoenigsmann** [comment]
I *think* that this is another symptom of a bug that should be solved in the latest development version of wxMaxima. http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly contains instructions how to replace the wxMaxima directory of your installation by this nightly build.

If I am right a possible work-around for the current release of wxMaxima is described at https://github.com/andrejv/wxmaxima/issues/486#issuecomment-132890605.

**Comment by gendaibushi** [comment]
Thank you. I solved it by installing  Tex Font.
Thanks.
