### ISSUE TITLE
Input text isn't printed on last version of wxMaxima

### ISSUE THREAD

**Issue by epiparo** [andrejv/wxmaxima#610]
The last version of wxMaxima no more print texts of input cells on Windows PC.
-------------------------------------------------------------
wxMaxima version: 15.8.2
Maxima version: 5.37.2
Maxima build date: 2015-09-18 21:03:17
Host type: i686-pc-mingw32
System type: Win32 6.2.9200 X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
Andrej has resolved this one in the current development version that 
can be obtained following the instructions from here: 
http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly


Kind regards,

  Gunter.
