### ISSUE TITLE
Some issues on HTML exporting 

### ISSUE THREAD

**Issue by epiparo** [andrejv/wxmaxima#611]
HTML exporting would be nice and partly solving the printing issue on Windows systems (#610). However there are little bugs:
1. Output lines must be separed with a double backslash (\\)
2. String aren't correctly braced in mbox fields
3. Colored string obtained with dpart aren't  correctly red colored
An useful option will be that of hiding input cells.
-------------------------------------------------------------
wxMaxima version: 15.8.2
Maxima version: 5.37.2
Maxima build date: 2015-09-18 21:03:17
Host type: i686-pc-mingw32
System type: Win32 6.2.9200 X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7
-------------------------------------------------------------

**Comment by epiparo** [comment]
Moreover symbols aren't correctly exported (for instance "%rho" should become "\rho").
Hereby I enclose a sample file. If you export in html yu can see all the above issues.
[Compito1.pdf](https://github.com/andrejv/wxmaxima/files/34120/Compito1.pdf)

**Comment by gunterkoenigsmann** [comment]
Should be corrected by now.
