### ISSUE TITLE
factor function makes wxmaxima freeze

### ISSUE THREAD

**Issue by fanqo** [andrejv/wxmaxima#618]
I download maxima-sbcl-5.37.2.exe from sourceforge, and test "factor(x^3+y^3)" in wxMaxima, it freezed having no response, but in XMaxima factor function works well. "factor(x^2 + x -6)" also makes wxMaxima no response, and XMaxima working well, so maybe it's wxMaxima's faults.

By the way the OS is Windows 7 X86_64 version

**Comment by gunterkoenigsmann** [comment]
This most probably is a font issue: Maxima is determined to increase of parenthesis until they are big enough and to decrease the fontsize of labels until they are smaller than a given piece of text. If these characters happen to be of zero size in a font this won't work. Am still trying to find all places where this may happen.

The instructions found in https://github.com/andrejv/wxmaxima/issues/486#issuecomment-132890605 should make wxMaxima use a working font.

Kind regards,

       Gunter.

**Comment by fanqo** [comment]
Yes, Gunter is right. After installing jsMath fonts, the factor function works in wxMaxima. Thanks a lot.
