### ISSUE TITLE
MSW-only scroll issue

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#622]
How to reproduce:
- Open a large .wxmx file
- Press the left mouse button and select some text and move the mouse out of the bottom of the window
- The window starts scrolling
- Then release the left mouse button

What happens:
- The window keeps scrolling

What should happen?
- The window should stop scrolling once the left mouse key is released

Where is this reproducible?
- Only on windows

**Comment by ReneSci** [comment]
I have seen seen the same behavior.
Best regards
Rene'

Also - a long time ago: The user could select an cell, then scroll down the worksheet and press [SHIFT] and select another cell, then all the cells in between the two selected sells became selected. This one doesn't work anymore :-(
