### ISSUE TITLE
WxMaxima crashes at particular worksheet

### ISSUE THREAD

**Issue by bmes** [andrejv/wxmaxima#625]
I'm using new wxmaxima 15.08.1+git (installed as maxima-clisp-5.37.3.exe) under Windows-7.

My particular example (see the file in attachment) alweys crashes at attempts to execute it

**Comment by bmes** [comment]
Don't understand, how to include wxmx file ??
(zip also don't work:(( )

**Comment by gunterkoenigsmann** [comment]
github protects us all from files that aren's image files. But you can send the file to wxmaxima at physikbuch dot de: Am in a hurry now. But will read it this evening: Thanks to gdb crashes normally are astonishingly easy to fix.

Kind regards,

     Gunter.

**Comment by bmes** [comment]
Dear sirs,
I'm sending you this problem file: test1.wxmx, please, could you run all 
cells to see the problems.

Besides this, I'm attaching other file: test1.wxmx, which also gives 
unexpected result: when I input command
"evaluate all cells" using respective menu item, maxima stops before 
section 6 of this document (just after %o2, 1 cell above section 7). And 
at this point wxmaxima writes "maxima making calculations", but actually 
it doesn't. Moreover, if I press on the section 5 at that moment, to 
expand it,
wxmaxima  crushes.

Thank you for your attention.
Sincerely yours,
Mikhail Veysman

**Comment by gunterkoenigsmann** [comment]
Dear bmes,

Seems like github has confiscated the attachment.

If you send it to me via private mail I will test it, though.

Kind regars,

   Gunter.

**Comment by bmes** [comment]
Dear Gunter, please, could you indicate the proper mail to send the 
attachments ?

I'ts already my 3-d attempt to send the attachment...

Sincerely yours,
Mikhail

**Comment by bmes** [comment]
Dear sirs,
as long as it seems that the problem with attachments can't be resolved, 
I'm sending you the
reference to download them from fileserver sendspace.com:

https://www.sendspace.com/file/kb2znc
https://www.sendspace.com/file/wp0wrm

Mikhail

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Dear bmes,

Did manage to download the files - and I also can reproduce the crash
- - but only if the program is run from outside the debugger.

What I know is that some function is appending a cell to a list that
isn't part of the worksheet. But why?

Kind regards,

    Gunter.


On 13.12.2015 13:38, bmes wrote:
> Dear Gunter, please, could you indicate the proper mail to send
> the attachments ?
> 
> I'ts already my 3-d attempt to send the attachment...
> 
> Sincerely yours, Mikhail
>> Dear bmes,
>> 
>> Seems like github has confiscated the attachment.
>> 
>> If you send it to me via private mail I will test it, though.
>> 
>> Kind regars,
>> 
>> Gunter.
>> 
>> — Reply to this email directly or view it on GitHub 
>> <https://github.com/andrejv/wxmaxima/issues/625#issuecomment-16417541
5>.
>>
>
>> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/andrejv/wxmaxima/issues/625#issuecomment-164254647
>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWbYaxXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuO1E4P/i+Au1JepHNE63mVZ+bGFYCX
uIDcYed0wIsHPQTc4ekd8/8wTtCBeOu7RM6V/TZ/EBbeoQbKw1qsP132aU5wsVbu
pgNr5P+ZrmHYL6xINmQ+796SiD+lBgp2U/p8Evpxea+SgxC+/RCrtfJkL6DrkpzX
O5OG+DpAQdG6PSrEqV17gMxHIxt2BnXlw5aamyzUPq409q8pOn7BILMZORGsTwwB
DIk9pTU5RIlvQ5evmEObXdXByzZ+0oT4Ti68DJzb1FHohigACXxr8Dx0NyUpVFgv
5hIpRZtDX3btZjB++EbgnLRhQ0SgwxtcIPZWMscqTbPCIyDmn6vaxD2xOfZTjtga
6eJu24ICCWHAE9psqd9SOhWS6RTLNwXf4B+ExOOM5iOFq4CwIuKXY6glG82qKqDc
GLl7QkN+GbS94TKOxXnqxm0xpO1WBV36kBYH8ZyB0O7NIsteX6OttOoKWj0lonqo
tGqWJ45z6GjUa/Ss/1m60Kg28rpckvPyVemWzVtuXrKggBVPxIzXMUKGpH45gkB7
yfqo+jLgPOJ5ecH/YdfQAbXW/mDPmJzELRPpssdZb5VHCMLSDUlwcLCHeECJFIG7
wVvXhDONhcy7b64Dv93TewWrpguEng8wk8hYaxcvPK5jj1vE2Id9/1sbgOK+zB4T
64dsEr41Rwx95ZldM9bU
=8Apq
-----END PGP SIGNATURE-----

**Comment by gunterkoenigsmann** [comment]
The next nighlty build (http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly) should no more crash with the two worksheets you sent me.

Kind regards,

  Gunter.

**Comment by bmes** [comment]
Dear Gunter,
> Did manage to download the files - and I also can reproduce the crash
> - - but only if the program is run from outside the debugger.
>
> What I know is that some function is appending a cell to a list that
> isn't part of the worksheet. But why?
>
I know nothing about this, I'd only used standard features of the 
wxmaxima to make the example workshits ,
which crush wxmaxima. It seems (I guess) that this result is due to some 
operations with sections (1...6 in my example) of the document,
or due to some operations with mouse...

I hadn't find new version of the distributive of wxmaxima in you site, 
and simply replaced my old wxmaxima.exe file by your new ones (from
current build of wxMaxima 
<http://wolfgang.dautermann.at/maxima/wxmaxima-daily-win.zip>  from 
http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly ).
After I'd tried to run my test1.wxmx example: it didn't crushed after 
that, but when I'd pres "x" at the upper right corner of the window to 
close
the project an error had appeared: "can't save test1.wxmx~". After I'd 
managed to close the project (whmaxima had hunged) and had restarted the 
project, I'd recieved the message in the attachment. I'd answered Yes on 
the request (in the attached picture it is "Da" in my Russian version)
and just after wxmaxima had crushed ....

Also I'd tested test11.wxmx with new wxmaxima.exe file:  the result was 
the same as that I'd described in my previouse message.

So, it seems that there is seriouse bag in the current version...

Sincerely yours,
Mikhail

**Comment by gunterkoenigsmann** [comment]
Ok... ...gave it another try. Let's see if it works now.

**Comment by bmes** [comment]
Dear Gunter,
completely the same problems with the new version, which I'd downloaded.

and it's impossible to save changes (!) after evaluation of all cells at 
the project test1.wxmx: wxmaxima crushes during this.

Also the strange feature is that graphics, which should be plotted at 
section 1 of the test1.wxmx, actually are not plotted at the first run
(when I first open wxmaxima and than load the test1 project). At the 
second run, when I simply press at test1.wxmx, whey are plotted...

Mikhail

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Ok... ...ws able to reproduce the bug again and telling wxMaxima how to
deal with fractions with empty denominators fixes it again.

But why on earth would wxMaxima think that maxima has requested it to
draw such a thing? Was unable to find a suspicious fraction in your
document. Did you?

Kind regards,

   Gunter.
On 14.12.2015 23:45, bmes wrote:
> Dear Gunter, completely the same problems with the new version,
> which I'd downloaded.
> 
> and it's impossible to save changes (!) after evaluation of all
> cells at the project test1.wxmx: wxmaxima crushes during this.
> 
> Also the strange feature is that graphics, which should be plotted
> at section 1 of the test1.wxmx, actually are not plotted at the
> first run (when I first open wxmaxima and than load the test1
> project). At the second run, when I simply press at test1.wxmx,
> whey are plotted...
> 
> Mikhail
>> 
>> Ok... ...gave it another try. Let's see if it works now.
>> 
>> — Reply to this email directly or view it on GitHub 
>> <https://github.com/andrejv/wxmaxima/issues/625#issuecomment-16437462
1>.
>
>> 
> 
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/andrejv/wxmaxima/issues/625#issuecomment-164584019
>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWb7BZXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuO/p8P/1AAhGFhV+PnvQgVYIzC07jv
sPYYSXeDRaRqwB6BrMTKqXOz+TjZdP0M6K/Hw1rgWp5R2VPRaiyghT+nrHzUfFn4
L5q+Qe3a99h0nEPfWno6q3BCPWY8R1qeXrdt6EjGkkoFfAqQC6wt2aKPrNVLgjQn
SSXumYE/5gdLxugf4bNdXxAlcpl8fIx9c0uHbFr2Kq6Hy4p5rYlSnZYmCgZjEdE1
c6deYkL5NRS+DKI2KA1MNnpsOVdyAz3fQiEj6LW4HqFqkISZiuxouXj1OAFycdtt
41cf162jGS24JPPFl3EEovomezKjFRp1nFzBzd+dIRxkmb1Dq7fRxVBMJ16KjYHg
4K8CxFuOi/6yDiwGmkibVTcGZaYIyyfOWoLTdLeqLBhaoOysbla4nbifmp84cK/5
BzL415r6eEy+8sNhFrP4j8/lJVT54CrjD3D4ba6h94CzTlNdH4S0dUGG+ggGPCto
nP4Y9xH/v8uZ6l9D5O7fzEqCMALFLfhJF1aOHomeVsRCj7ZwGOVh9BfQDCPb6Xki
gaAWFKchNSNW07GKFEAp3A3n6+8K4qz/IpSIiNrPtkJNXTKs6mC6afuJ9OvH7LoG
BuL+5sUM/cBarZnBK/He3TqnqV/mK67bahST1+x1xL7bxwR/kgz32J4HdVGeqKW3
/O7JuFzX/xrwJt78WyiK
=/rSx
-----END PGP SIGNATURE-----

**Comment by bmes** [comment]
Dear Gunter,
I'd commented the suspicious parts of code in the test1.wxmx,
and had cheacked out, that when I run all visible (!) cells in the new 
file (I'd named corrected test1.wxmx as test10.wxmx),
than it works untill the end.

But(!):

1) I'd turned on the autosave in the wxmaxima, so the system had maide 
test10.wxmx~ .
When I tryed to save test10.wxmx myself, I'd got the error message, 
see   problem_test10_171215.png in the attachment
(the russian part of the text is: "error 0, operation is completed 
sucsessfully")

So, it was impossible to save test10.wxmx and I'd saved it as test100.wxmx

2) when I run all visible cells, it is OK. But the operation of 
evaluating of all cells give rise to error, see problem_test10_171215_2.png
in the attachment !

the problem file test100.wxmx with this error
  you can download from    https://www.sendspace.com/file/4ycqbt

Resume:
1) problem with autosave, conflict with *.wxmx~ files,
2) problem with cells included in sections, at least with evaluating of 
all of these cells if they are not visible.

Sincerely yours,
Mikhail

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Dear bmes,

> When I tryed to save test10.wxmx myself, I'd got the error
> message, see problem_test10_171215.png in the attachment (the
> russian part of the text is: "error 0, operation is completed 
> sucsessfully")

This half of the problem I can explain by now:
wxMaxima no more saves data directly into the file you invested much
work into because if anything crashed during the save you would risk
loosing the whole content of the file. Instead it writes all data into
a temporary file and then, when everything has worked fine, moves the
file to the intended place (which basically means: the operating
system changes the directory entry and everything is set).

Unfortunately windows has the habit to disallow moving files when
someone is still reading them and there might be several program that
routinely read new files:
 - A virus scanner is a good candidate for this
 - Dropbox starts reading every new file immediately - and needs loads
of time before the transfer is complete
 - The indexer for the search function.
It even is possible that the indexer triggers the virus scanner *again*.

What I already do is to wait a second and then to retry moving the
file. But sometimes this seems not to be enough...

> 
> So, it was impossible to save test10.wxmx and I'd saved it as
> test100.wxmx
> 
> 2) when I run all visible cells, it is OK. But the operation of 
> evaluating of all cells give rise to error, see
> problem_test10_171215_2.png in the attachment !
> 
> the problem file test100.wxmx with this error you can download from
> https://www.sendspace.com/file/4ycqbt
> 
This time github seems to have gotten scared by png images and try to
protect me from them (?!?) but this time I think I got a solution:

The function MathCtrl::Contains() is broken.

But I cannot seem to find what I did wrong there...

Will ask Andrej for help if I don't find an answer.

Thanks for doing all this debug work for wxMaxima -
and with any luck at all we will resolve the issue.

Kind regards,

     Gunter.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWceRbXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOFtsP/1hI3aetsi8pUpuM4I/4ZnsU
k7Q7UPl98wSNsE8remmKlmbXtoHriapcfrLLrSibtDJbd6yHjbN35Hh/iWlXkiFD
m6FSWOX6a78BeFC5bGbX/UQ93zP2oJ3RPyJyZ9pMOSUGT7QasVdZI/6HARrXflQB
wQ4o59k0RJIbaYvXQVczcBQxzyKh0c/kXrZm860n4LWevynbnlcsbuhyB7aAYu26
I75CbkXEpJ9KWv967BYZIpaRDY5a056w+cl2ElW3rLdXdusIJ4i6LE7Cq10SEeH5
54UfyN4LRg/8wftxyx11rVP0t8qdj6QbpCZ9fj5Coz75Q3W6ffC5arcNORphJR7B
38+Mp6beYyMkHtyavQ/XFwCqDqchS2MCfvejaBJvQjvcHwMRpwAoMhETpgldKgsC
MqWYXowVM7Q8jAPMIX2KdxRkYsQ2IvpapTfZDxbd49TCp62LFM7kxTEYCCrf6J2w
WyAplrpgyElvbW3oypjPR9+DZWzNrRxNfBxNDttGq7sEOCLUKGzmiIShKgN0fudr
8YkFrBo+JZT4uCOwtFJkZIJWUy2mlDBB/XU7i2y8FRz+vQ9nMm6KSX9IxwH5qely
r2yOzdfvtdNRLMmYOnKKFKpTBBtqT7yLeU1ye7GHgOfUsSOL5Ai0KRyTnR2Kih/o
pIu2VZGIZFIZRIpTImG8
=d4MR
-----END PGP SIGNATURE-----

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Dear bmes,

I think (again!) I found it:

 - I forgot to wait a second before retrying to move my temporary file a
nd
 - GroupCell::Contains() did traverse a list of GroupCells - but
didn't test the cell it was working on if it was folded but did test
the cell it started working on instead.

 These bugs would have haunted us for a long time if you hadn't found
them.

Thanks a lot,
and kind regards,

 Gunter.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWcefYXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOhaQP+gMo6ecqtvASpecO1VW7inZo
xRbaEZeqx9DeCvZewGsdeAiZS0YGp82+Sm8B4MZjlxiAdej3pCQRv9V2t4kaBGpQ
0kYRMlBtlIGo0rS5mIrgkoPVDIEwCLd0FZW3hKVQejCbe1iRAPAylnoqvEulTQjs
Kei86N07jcxt3DZ/oTFnbfp6n+6KTN/jPvIly/jPdkg+f4fy/xSOSWzISco1GUBz
2JXSDe0XaKXnwznnhlk5fPWDSctKu7wuisJybXB7c2Luxd1PBCRqtPJdxG7ndW8M
rjyMeQQsjSgyKTsPX64ZhMpV1FD9hAeMEABH48HxoWdp4hFJ506Jn6TK2KtA3kT+
gWW5Nld/LL9OLbDFlAsHc6gh28x6uoAcbHdGi/9+dDkzDGiXJXbbWFtTijchsr0h
s0LsegfAJyFH1uXyvJNdIAILa6OPhGg3Bot6LRPJq7kz0h2+L40q2KhclsShfTiD
AnFQSb0R5B84jG1tkhMFcZEMVxNCNPCG9uJ6E6Z5SjwiL0GLcg1BSTxWZ5zacRVc
i0M1kVHGKox+/BxizG6SNeQlGoMUEapSheoISMPBn/uJ7mDZaU6RkdNvHPq1YZx7
i+5zJZ4YKKglXdq5vp4vVnuF6vOsvt4ujyzuV6kZg/qzwLP4civnGgF3BSTT9Bix
XDgBdmGbsgXrqCEGX0qX
=ZA+l
-----END PGP SIGNATURE-----

**Comment by bmes** [comment]
Dear Gunter,
Thank you for your answer.

Please, take in mind also the following: in the lists of cells sometimes 
there are operators assuming interactive questions,
like "Is n equal to -1 ?" for integrals like  integrate(x^n,x); So it 
means, that when evaluating of folded lists of cells wxmaxima should
expand it.

Also I'd noticed, that in the case of evaluating of the group of cells 
with graphics (commands like plot2d (....);) wxmaxima
is wayting untill user will close the first graphical window to proceed 
to further operations, i.e. it stops at the first graphic
untill I'll close it. I think it would be better, it wxmaxima could open 
all graphics and make all operations in the group of cells indicated
by the user, or could permits  user to make a choice weather to stop at 
each graphic or not..

Sincerely yours,
Mikhail

**Comment by gunterkoenigsmann** [comment]
Am 17. Dezember 2015 11:42:39 MEZ, schrieb bmes <notifications@github.com>:
>Dear Gunter,
>Thank you for your answer.
>
>Please, take in mind also the following: in the lists of cells
>sometimes 
>there are operators assuming interactive questions,
>like "Is n equal to -1 ?" for integrals like  integrate(x^n,x); So it 
>means, that when evaluating of folded lists of cells wxmaxima should
>expand it.
>
This should already work.  Or did you find a glitch in this logic? 
>Also I'd noticed, that in the case of evaluating of the group of cells 
>with graphics (commands like plot2d (....);) wxmaxima
>is wayting untill user will close the first graphical window to proceed
>
>to further operations, i.e. it stops at the first graphic
>untill I'll close it. I think it would be better, it wxmaxima could
>open 
>all graphics and make all operations in the group of cells indicated
>by the user, or could permits  user to make a choice weather to stop at
>
>each graphic or not..

This is a gnuplot limitation on Windows. But you can replace "plot" by "wxplot".

Kind regards, 

   Gunter. 
>
>Sincerely yours,
>Mikhail
>
>> -----BEGIN PGP SIGNED MESSAGE-----
>> Hash: SHA512
>>
>> Dear bmes,
>>
>> I think (again!) I found it:
>>
>> - I forgot to wait a second before retrying to move my temporary file
>a
>> nd
>> - GroupCell::Contains() did traverse a list of GroupCells - but
>> didn't test the cell it was working on if it was folded but did test
>> the cell it started working on instead.
>>
>> These bugs would have haunted us for a long time if you hadn't found
>> them.
>>
>> Thanks a lot,
>> and kind regards,
>>
>> Gunter.
>> -----BEGIN PGP SIGNATURE-----
>> Version: GnuPG v2
>>
>> iQJ8BAEBCgBmBQJWcefYXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
>> ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
>> Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOhaQP+gMo6ecqtvASpecO1VW7inZo
>> xRbaEZeqx9DeCvZewGsdeAiZS0YGp82+Sm8B4MZjlxiAdej3pCQRv9V2t4kaBGpQ
>> 0kYRMlBtlIGo0rS5mIrgkoPVDIEwCLd0FZW3hKVQejCbe1iRAPAylnoqvEulTQjs
>> Kei86N07jcxt3DZ/oTFnbfp6n+6KTN/jPvIly/jPdkg+f4fy/xSOSWzISco1GUBz
>> 2JXSDe0XaKXnwznnhlk5fPWDSctKu7wuisJybXB7c2Luxd1PBCRqtPJdxG7ndW8M
>> rjyMeQQsjSgyKTsPX64ZhMpV1FD9hAeMEABH48HxoWdp4hFJ506Jn6TK2KtA3kT+
>> gWW5Nld/LL9OLbDFlAsHc6gh28x6uoAcbHdGi/9+dDkzDGiXJXbbWFtTijchsr0h
>> s0LsegfAJyFH1uXyvJNdIAILa6OPhGg3Bot6LRPJq7kz0h2+L40q2KhclsShfTiD
>> AnFQSb0R5B84jG1tkhMFcZEMVxNCNPCG9uJ6E6Z5SjwiL0GLcg1BSTxWZ5zacRVc
>> i0M1kVHGKox+/BxizG6SNeQlGoMUEapSheoISMPBn/uJ7mDZaU6RkdNvHPq1YZx7
>> i+5zJZ4YKKglXdq5vp4vVnuF6vOsvt4ujyzuV6kZg/qzwLP4civnGgF3BSTT9Bix
>> XDgBdmGbsgXrqCEGX0qX
>> =ZA+l
>> -----END PGP SIGNATURE-----
>>
>> —
>> Reply to this email directly or view it on GitHub 
>>
><https://github.com/andrejv/wxmaxima/issues/625#issuecomment-165275984>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/625#issuecomment-165417159

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
