### ISSUE TITLE
TeX input in comment cell broken

### ISSUE THREAD

**Issue by christianlupus** [andrejv/wxmaxima#626]
According to http://www.matrix44.net/blog/?p=1029 there seems to be a function to allow plain (?) TeX code to be set in a comment and when exported to (La)TeX this is not altered/parsed from wxmaxima.

Unfortunately this seems to be broken at time: The signalling token "TeX:\n" gets removed from the output as desired (can be verified from the outputted file) but the tokens relating to TeX are parsed. So every single '\' is translated to a "\ensuremath{\backslash}" leading to nonfunctional TeX codes.

This has been tested with the latest version of the master branch.

**Comment by christianlupus** [comment]
I just found a workaround. Preparing for a pull request. Please wait...

**Comment by christianlupus** [comment]
I just added a pull request for commit that solves the problem so far. I am unsure if this fits the desired architecture of software thus you might consider altering it.

**Comment by christianlupus** [comment]
I just saw there are multiple things to be addressed:
- Newlines in math cell input gets discarded resulting in correct syntax but without indentation and logical line structure
- Cells are not separated via \par
- Fractions at the start of equations (possible other locations too) get placed outside math resulting in LaTeX errors.

If I find time I might look into this later

**Comment by andrejv** [comment]
I think this is fixed by your pull request so I'm closing this report. If it is not, please reopen.

For issues not related to the original report, please open a new issue.
