### ISSUE TITLE
Printing still broken

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#630]
On my linux box the file test/testbench_simple.wxmx from the source tarball still doesn't print all input cells. No Idea why.

**Comment by gunterkoenigsmann** [comment]
cppcheck has some warnings about printing. Don't know if any of these is important:

[MathPrintout.cpp:169]: (style) The function 'GetPageInfo' is never used.
[MathPrintout.cpp:47]: (style) The function 'HasPage' is never used.
[MathPrintout.cpp:178]: (style) The function 'OnPreparePrinting' is never used.
[MathPrintout.cpp:54]: (style) The function 'OnPrintPage' is never used.
[MathPrintout.cpp:73]: (style) C-style pointer casting
[MathPrintout.cpp:79]: (style) C-style pointer casting
[MathPrintout.cpp:107]: (style) C-style pointer casting
[MathPrintout.cpp:139]: (style) C-style pointer casting
[MathPrintout.cpp:159]: (style) C-style pointer casting
[MathPrintout.cpp:237]: (style) C-style pointer casting
[MathPrintout.cpp:257]: (style) C-style pointer casting
[MathPrintout.cpp:300]: (style) The scope of the variable 'tmp1' can be reduced.
[MathPrintout.h:38]: (style) Class 'MathPrintout' has a constructor with 1 argument that is not explicit.

**Comment by andrejv** [comment]
The unused functions are called by the printing infrastructure from wxwidgets. Other warnings could be removed.

**Comment by gunterkoenigsmann** [comment]
Did try a "git bisect". To me it seems like printing has been broken by a change in wxWidgets: The Code from January 2013 is still able to read recent .wxmx files (Strike!) but printing with this version results in exactly the same missing text as does printing with the current version.

Giving up on this issue.

**Comment by andrejv** [comment]
Can you provide a minimal file which shows this bug. I think on OSX printing works as expected.

**Comment by gunterkoenigsmann** [comment]
On my computer the minimal example would be a .wxmx file containing nothing but two text cells. A single text cell normally works. Did send you such a file and the print result as a private mail as github won't allow me to attach them to a ticket.

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment]
One interesting detail is that the left bracket that allows folding text isn't printed out save of the triangle that when clicked at folds the cell.

**Comment by gunterkoenigsmann** [comment]
Commit 97b19bf seems to resolve this for me. But I have no idea why it does do so.

**Comment by munyari** [comment]
I downloaded wxmaxima today from the ArchLinux repositories and have the same issue. Attempted to print a file, only gnuplot and some ouptut cells show up. test/testbench_simple.wxmx from the source repo is almost completely blank when attempting to print, save a few red arrows in the margin. Running version 15.08.2-2, Linux Kernel version 4.4.3-1-ARCH

**Comment by gunterkoenigsmann** [comment]
Not again!

...but this time I managed to produce a printout that might contain a hint what is going wrong:
Seems like we are printing something with too big a white background. Don't know what to make out of it, though:

[output.pdf](https://github.com/andrejv/wxmaxima/files/201813/output.pdf)

**Comment by munyari** [comment]
Awesome how you guys are so responsive. Can't wait for your release to hit the arch repos so I can try it out!
