### ISSUE TITLE
Problem with set_plot_option 

### ISSUE THREAD

**Issue by mardukbp** [andrejv/wxmaxima#632]
The following command works in Maxima 5.36.1 but throws an error in wxMaxima 15.08.2

`set_plot_option([style, [lines, 2]]);`

**Comment by gunterkoenigsmann** [comment]
Weird: Looks clearly like a change in maxima. The error message is output by maxima - but the error appears only in wxMaxima. => Assuming it to be in wxMathml.lisp and am assuming it will affect other seemingly simple uses of maxima, too => adding the "release-critical" label.
