### ISSUE TITLE
Incorrectly translated TeX: from wxMaxima comment text.

### ISSUE THREAD

**Issue by ricardozimmer** [andrejv/wxmaxima#634]
My latest downloaded version:
wxMaxima version: 15.8.0
Maxima version: 5.37.3_5_g8106b41_dirty
Maxima build date: 2015-11-14 16:49:58
Host type: i686-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on 158234.vs.webtropia.com [127.12.34.56])

Using this two input line example:
/* [wxMaxima: input   start ] */
Y=F*G*Q+G;
matrix([1,1],[1,1]);
/* [wxMaxima: input   end   ] */
/* [wxMaxima: comment start ]
TeX:
\[Y=F\cdot \mathrm{G}\left( Q+G\right) \]
The same equation inline: $Y=F\cdot \mathrm{G}\left( Q+G\right) $.
   [wxMaxima: comment end   ] */

The exported output into a tex file looks like:

preamble ok.

\begin{document}
%%% OUTPUT:
\[\displaystyle
\printlabel{\mathrm{\tt (\%o1) }\quad  }
Y=F\cdot G\cdot Q+G\]
\[\displaystyle
\printlabel{\mathrm{\tt (\%o2) }\quad  }
\begin{pmatrix}1 & 1\cr 1 & 1\end{pmatrix}\mbox{}
\]
%%%%%%%%%%%%%%%
\ensuremath{\backslash}[Y=F\ensuremath{\backslash}cdot \ensuremath{\backslash}mathrm{G}\ensuremath{\backslash}left( Q+G\ensuremath{\backslash}right) \ensuremath{\backslash}]
The same equation inline: \$Y=F\ensuremath{\backslash}cdot \ensuremath{\backslash}mathrm{G}\ensuremath{\backslash}left( Q+G\ensuremath{\backslash}right) \$.
\end{document}

My comments:
1-The output from a wxMaxima cell is correctly translated, except for:
	a-The matrix end of row is translate to "\cr" as opposed to "\\". The "\cr" also appears in other environments, such as	\begin{align}......\end{align}.  Tex
	compiler does not complain.
2-The output from one text in a comment using the TeX: gives:
	a-Each \ in the math environment delimiters \[....\] and any \ inside the same environment gets translated to "\ensuremath{\backslash}"
	b-Each inline math delimiter $...$ gets translated to "\$....\$".
Thanks.
Zimmer

**Comment by gunterkoenigsmann** [comment]
Observation 2) is resolved now.
About the \\cr from observation 1) I don't have any opinion or experience.
