### ISSUE TITLE
No connected with maxima after an update with debian 8 testing

### ISSUE THREAD

**Issue by marecaca** [andrejv/wxmaxima#637]
After an update something wrong occurs because since then wxmaxima not work; the menssage is 
```
wxmaxima could not start the server.
Check if you have network support
enabled and try again!
```
maxima via console works fine; furthermore the command `maxima -s 4010` not work.

In the update in cuestion eliminates **ifupdown:amd64 0.7.54** and install **ifupdown2:amd64 1.0~git20151029-1** ... really not know if this has something to do, but the issue showed up after the upgrade, before worked fine.

the list of updates is:
```
[INSTALL, DEPENDS] ifupdown2:amd64 1.0~git20151029-1
[INSTALL, DEPENDS] python-argcomplete:amd64 0.8.1-1
[INSTALL, DEPENDS] python-ipaddr:amd64 2.1.11-2
[ELIMINATES, DEPENDS] ifupdown:amd64 0.7.54
[TO UPDATE] binfmt-support:amd64 2.1.5-1 -> 2.1.5-2

...

[TO UPDATE] gir1.2-soup-2.4:amd64 2.52.1-1 -> 2.52.2-1
[TO UPDATE] kbd:amd64 2.0.3-1 -> 2.0.3-2
[TO UPDATE] klibc-utils:amd64 2.0.4-4 -> 2.0.4-6
[TO UPDATE] libgraphite2-3:amd64 1.3.3-1 -> 1.3.4-2
[TO UPDATE] libklibc:amd64 2.0.4-4 -> 2.0.4-6
[TO UPDATE] liborcus-0.10-0v5:amd64 0.9.2-3 -> 0.9.2-4
[TO UPDATE] libpcre16-3:amd64 2:8.35-8 -> 2:8.38-1
[TO UPDATE] libpcre3:amd64 2:8.35-8 -> 2:8.38-1
[TO UPDATE] libpython3.4:amd64 3.4.4-1 -> 3.4.4-2
[TO UPDATE] libpython3.4-minimal:amd64 3.4.4-1 -> 3.4.4-2
[TO UPDATE] libpython3.4-stdlib:amd64 3.4.4-1 -> 3.4.4-2
[TO UPDATE] libsoup-gnome2.4-1:amd64 2.52.1-1 -> 2.52.2-1
[TO UPDATE] libsoup2.4-1:amd64 2.52.1-1 -> 2.52.2-1
[TO UPDATE] manpages:amd64 3.74-1 -> 4.04-0.1
[TO UPDATE] manpages-dev:amd64 3.74-1 -> 4.04-0.1
[TO UPDATE] nano:amd64 2.4.2-1+b1 -> 2.4.3-1
[TO UPDATE] openssh-client:amd64 1:7.1p1-5 -> 1:7.1p1-6
[TO UPDATE] publicsuffix:amd64 20151205-1 -> 20160104-1
[TO UPDATE] python3.4:amd64 3.4.4-1 -> 3.4.4-2
[TO UPDATE] python3.4-minimal:amd64 3.4.4-1 -> 3.4.4-2
```
wxmaxima: 15.08.2
maxima: 5.37.3
debian 8 testing amd64

thanyou and grettings!

**Comment by gunterkoenigsmann** [comment]
Could you give us the result of

     ifconfig

typed into a shell?

The symptom you describe looks like the update somehow broke the loopback network device whose only use is to allow a program on your local computer to talk to another one using a local network connection. One advantage of this approach is that the graphical user interface won't crash if the program that uses that does the actual maths does crash - which enables you to save the data and to restart maxima safely.

The error message you describe only is printed out if wxMaxima is unable to start a server maxima can be instructed to connect to over a local network connection.

Another possible reason for the error message is that the port wxmaxima's configuration dialog tells the program to use is actually in use as well as the 16 or similar port numbers directly above this one. Or that you have an overeager firewall that doesn't only disallow incoming connections from the outside but also network connections within the system. Or something like an selinux or apparmor rule that does disallow wxMaxima to establish a network connection to a different program.

**Comment by marecaca** [comment]
here the result of `ifconfig`:
```
enp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.36  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::fa32:e4ff:fe89:1897  prefixlen 64  scopeid 0x20<link>
        ether f8:32:e4:89:18:97  txqueuelen 1000  (Ethernet)
        RX packets 26050  bytes 15625863 (14.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22113  bytes 3281224 (3.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by gunterkoenigsmann** [comment]
Then I have guessed right: No loopback network device => no way for wxMaxima to offer maxima to open a connection.

Possible reasons might be:

/etc/network/interfaces might be lacking the line

|     # The loopback network interface
|||     |auto lo
|||     |iface lo inet loopback|


or you can try a

         ifup --force lo

The result of ifconfig should look like the following:

     lo        Link encap:Local Loopback 
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:25443 errors:0 dropped:0 overruns:0 frame:0
          TX packets:25443 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2638387 (2.6 MB)  TX bytes:2638387 (2.6 MB)

     wlan0     Link encap:Ethernet  HWaddr 68:94:23:49:1b:bb 
          inet addr:192.168.181.19  Bcast:192.168.181.255  Mask:255.255.255.0
          inet6 addr: 2003:86:8a05:c00:6a94:23ff:fe49:1bbb/64 Scope:Global
          inet6 addr: fd00::10c:1b68:6ea8:2da2/64 Scope:Global
          inet6 addr: fd00::6a94:23ff:fe49:1bbb/64 Scope:Global
          inet6 addr: fe80::6a94:23ff:fe49:1bbb/64 Scope:Link
          inet6 addr: 2003:86:8a05:c00:10c:1b68:6ea8:2da2/64 Scope:Global
          inet6 addr: 2003:86:8a05:1f00:10c:1b68:6ea8:2da2/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:233897 errors:0 dropped:0 overruns:0 frame:0
          TX packets:135568 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:286961187 (286.9 MB)  TX bytes:16846106 (16.8 MB)

...another possible reason might be a stale lock file in |/var/run/network/

Hope that at least one of them helps: Networks - if they don't work - are black magic.

Kind regards,

   Gunter.|

**Comment by marecaca** [comment]
Ok! its solve! :dart: 

In fact the loopback network interface not worked because that last update by a missing dependencies... the information are here:

[Bug#810844: ifupdown2: Unlisted dependencies] (https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1387402.html)

I have these packages installed:
```
python-gvgen
python-mako
```
and wxmaxima run fine.
Thankyou Gunter for the help!

**Comment by marecaca** [comment]
Sorry... my issues was resolved with: `ifup --force lo`

... every time to run wxmaxima.
I suppose that it will be fixed in nexts updates.
Grettings

**Comment by gunterkoenigsmann** [comment]
If not adding the line

     /sbin/ifup --force lo

between the

     #!/bin/sh -e

and the

     exit 0

of /etc/rc.local will execute the command for you at every start of the system.
