### ISSUE TITLE
Greek letters cannot be used within .mac files under windows

### ISSUE THREAD

**Issue by RolandSalz** [andrejv/wxmaxima#645]
Greek letters are represented by maxima/wxmaxima in a very strange way (as combinations of totally other special characters) when used from within .mac files under windows 7 and thus are not usable and result in error messages. See my message to the Maxima mailing list "Greek letters cannot be used within .mac files under windows" from Jan 6, 2016 for details.

**Comment by ricardozimmer** [comment]
I'm seeing the same behavior with Latin accented characters in comment lines from .mac files. 
Maxima encountered a Lisp error:
READ-CHAR-NO-HANG: Invalid byte sequence #xE7 #xE3 #x6F in CHARSET:UTF-8 conversion.
The same comment line in the spreadsheet works fine.

**Comment by RolandSalz** [comment]
Depending on what lisp you use, try inserting one of the lines of code into a file .sbclrc.lisp or .clisprc.lisp respectively as described here:

 

-----Original Message-----
