### ISSUE TITLE
Can't open files if the filepath contains diacritics

### ISSUE THREAD

**Issue by junrrein** [andrejv/wxmaxima#648]
Steps to reproduce:

1. Save a blank wxMaxima file to a directory without diacritics (e.g. ~/test/test.wxmx).

2. Close and reopen wxMaxima. The test file can be loaded normally through File->Open Recent.

3. Rename the "test" folder to "tést".

4. wxMaxima now refuses to load the file with the error message "wxMaxima encountered an error loading /home/julian/tést/test.wxmx".

5. Rename the folder back to "test". The test file can be opened normally again.

System info:

wxMaxima version: 15.8.2
Maxima version: 5.37.3
Maxima build date: 2015-11-12 21:01:59
Host type: x86_64-suse-linux-gnu
System type: 
gcc -g -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fno-strict-aliasing -fPIC -pipe -fno-gcse -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -O  -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -Wno-unused -Wno-uninitialized -DSAFETY=3 -O  -DENABLE_UNICODE -DDYNAMIC_FFI -DDYNAMIC_MODULES -I.  /usr/lib64/libreadline.so -lncurses -ldl /usr/lib64/libavcall.a /usr/lib64/libcallback.a  -L/usr/lib64 -lsigsegv libgnu_cl.a 
SAFETY=3 TYPECODES WIDE_HARD SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.10
libreadline 6.3
libffcall 1.11 GNU C 5.1.1 20150713 [gcc-5-branch revision 225736] X86_64
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on cloud121 [127.0.0.1])

**Comment by gunterkoenigsmann** [comment]
This bug did take long to hunt down. But it should be resolved in the latest nightly build (https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies).

**Comment by junrrein** [comment]
Thanks for the fast response!

I tested this under the current git snapshot (commit a128c4c2b05794daa65f7be2f713bbc381e0fd02) and this bug doesn't occur.

I should have tested this way before reporting, I will keep this in mind.

**Comment by gunterkoenigsmann** [comment]
No need to apologize: This (and many other) issues would never have been resolved if they hadn't been reported. And this time I'm really proud that I finally found it.
