### ISSUE TITLE
SendToMaxima called before a maxima client is up and running

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#652]
Don't know if this is intentional or a bug but we tend to call wxMaxima::SendToMaxima() before maxima is even running => reporting it in case it might prove to be important.

**Comment by ReneSci** [comment]
I have experienced this with one of the most recent nightly build. It claims no contact with Maxima.
Best regards
Rene

**Comment by gunterkoenigsmann** [comment]
Arrgh! That sounds like being a new issue - and I would beg you to file it as a new issue if it persists: The SendToMaxima() being called during the startup of maxima will only have subtle side effects - if it has any side effects at all.

Having said that the only time I personally experienced a maxima process that my wxMaxima could not connect with was when the parameters that have to be passed to maxima or the location of the binary were somehow broken.

**Comment by gunterkoenigsmann** [comment]
No way to debug windows. But I assume that this one might be related to #653.
