### ISSUE TITLE
Cannot change plot style from dashed to solid - dashed default setting for wxplot2d seems to be an error

### ISSUE THREAD

**Issue by MSoegtropIMC** [andrejv/wxmaxima#655]
Dear wxMaxmiam Team,

there is no (easy) way to change the plot style for wxplot2d from the default dashed to solid. According to a discussion with Jaime Villate on the maxima forum today, the dashed plot style is no longer default for maxima, because it cannot be changed to solid. So I think this should be changed for wxmaxima as well.

For wxMaxima the dashed setting is in

wxMaxima\data\wxmathml.lisp:

-           ($wxplot_pngcairo "set terminal pngcairo dashed background \"white\" enhanced font \"arial,10\" fontscale 1.0 size ~d,~d; set zeroaxis;")
+           ($wxplot_pngcairo "set terminal pngcairo background \"white\" enhanced font \"arial,10\" fontscale 1.0 size ~d,~d; set zeroaxis;")

Best regards,

Michael

**Comment by gunterkoenigsmann** [comment]
I never use plot. But if you can give me an example that uses a dashed
line instead of a solid one I can try to look if I can find the bug.

Kind regards,

 Gunter.

**Comment by gunterkoenigsmann** [comment]
After reading the list I am no more sure if plot supports setting the
line type after all...

Kind regards,

    Gunter.

**Comment by MSoegtropIMC** [comment]
Dear Gunter,

> After reading the list I am no more sure if plot supports setting the line type after all...

at least the manual doesn’t tell how. [style [lines ..]] cannot do this according to the manual.

Best regards,

Michael
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928
