### ISSUE TITLE
wxMaxima crashes when reading a .wxmx file saved with a folded (sub(sub))section(s).

### ISSUE THREAD

**Issue by ricardozimmer** [andrejv/wxmaxima#656]
Good evening,

Recently I noticed two behaviors with the "Nightly Build" version indicated at the end of this mail.

1) wxMaxima crashes when reading a .wxmx file saved with a folded (sub(sub))section.
If you unfold all (sub(sub))sections of the same file (with an older version), this version reads it ok.

2) wxMaxima flagging an "incorrect syntax" after executing a cell when only the 
last instruction is commented out. If you look again to the instructions lines
after execution of the cell, you see a semicolon added after the "end of comment" symbol.

Lines to execute:
(%i1)	Hi:matrix([V2],[I1])$
		/*print("The H matrix is:",Hi)$*/

After execution:
(%i1)	Hi:matrix([V2],[I1])$
		/*print("The H matrix is:",Hi)$*/;
incorrect syntax: Premature termination of input at ;.
;
Maxima encountered a Lisp error:
SYSTEM::FORMAT-TABULATE: argument -1 is not a nonnegative fixnum
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.

Thanks,

Zimmer

Version information (downloaded on 2/2/2016):
wxMaxima version: 15.8.0
Maxima version: 5.37.3_5_g8106b41_dirty
Maxima build date: 2015-11-14 16:49:58
Host type: i686-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on 158234.vs.webtropia.com [127.12.34.56])

**Comment by gunterkoenigsmann** [comment]
The first issue reported in this ticket should be resolved in the latest
nigtly build: http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly

The second one I can at least confirm.

**Comment by ricardozimmer** [comment]
Great, thanks.
Zimmer
