### ISSUE TITLE
File is not marked as saved after saving to .wxm

### ISSUE THREAD

**Issue by MSoegtropIMC** [andrejv/wxmaxima#659]
Dear wxMaxima Team,

when I save a .wxm file, the file is not marked as saved and when I close it, I am asked again if I want to save the file, but the file was actually saved before.

I am not sure if this intentional, like saving to a .csv file in Excel. I like the .wxmx format a lot, but for libraries I still use .wxm, because I can directly batchload these and the .wxm file can be nicely organized in sections. But for libraries it is quite confisuing if the save seems to not work.

Best regards,

Michael
-------------------------------------------------------------
wxMaxima version: 15.8.1
Maxima version: 5.37.1
Maxima build date: 2015-09-01 14:46:12
Host type: i686-pc-mingw32
System type: Microsoft Windows 6.1 Build 7601 (Workstation) x86
Lisp implementation type: Clozure Common Lisp
Lisp implementation version: Version 1.9-r15764  (WindowsX8632)
-------------------------------------------------------------

**Comment by rend3r** [comment]
Loading by double click is still affected - immediately get asterisk without any document changes.
