### ISSUE TITLE
wxmaxima crashes when loading old wxmx files

### ISSUE THREAD

**Issue by afettouhi** [andrejv/wxmaxima#662]
I recently updated my Maxima installation on my work Windows 7 PC. After after some problems getting my old scripts to run I settled on using maxima-5.37.2-sbcl with todays nightly build of wxmaxima. The scripts run fine but if I try to load a old wxmx file that has been generated with 5.36.1-sbcl, maxima crashes. The window pops up but I get a dialog window saying wxmaxima.exe has stopped working. Also newly generated wxmx files cannot be opened.

**Comment by gunterkoenigsmann** [comment]
One gcc team member once told me that a program should not crash nonetheless what one does try to do with it => would it be possible to send one of the files that causes the crash to wxmaxima at physikbuch.de? (The github bug tracker will filter out all .wxmx files before processing mails)? If the crash is reproducible on my computer the next nightly build will be free of this error.

**Comment by afettouhi** [comment]
Thanks for the quick fix. I needed that fixed ASAP. Since I use it exclusively for my work.
