### ISSUE TITLE
wxmaxima has issues with generating plots from network directories

### ISSUE THREAD

**Issue by afettouhi** [andrejv/wxmaxima#664]
My Documents folder is mirrored network directory that it is synced with a network drive at my workplace and I am forced to use it for backup purposes. I am running Windows 7 and maxima 5.37.2-sbcl with todays nightly build. My issue with wxmaxima is that it won't generate any plots when I run a wxm file from my network location like

"//danfoss.net/PersonalDrives/U321361/My Documents/Work/Andre Fettouhi/Fiber test/Test of fiber EOS-A1234217-2/Wavelength calibration test/Wavelength calibration versus temperature.wxm"
 
then I get an error 0 that find maxout_10968.png in C:/Users/U321361 but the data and gnuplot files are there and running gnuplot directly generates the png.

The mail issue seems like My Documents is mounted as a P: drive. If I go through that and then when I run my wxm file the plots are generated.

In the Windows Explorer I also have a Link called Libraries and under that, there is a link to My Documents there as well. If I go through that which is my usual way then the png generation fails. I tried to then set maxima_tempdir to a location on my network drive but it fails just the same.

With maxima-5.36.1-sbcl I had none of these issues. This is how I setup my work directories with every wxm

Set up work directories
 
wxfilename;

pathname_directory(wxfilename);

split(wxfilename, "/");

Reading directories - local storage

maxima_tempdir : "P:/My Documents/maxima";

workDrive : split(wxfilename, "/")[1];

workDir : concat(workDrive, pathname_directory(wxfilename));

ratprint : false;

Reading directories - network storage

maxima_tempdir : "//danfoss.net/PersonalDrives/U321361/My Documents/Work/maxima";

workDir : concat("/", pathname_directory(wxfilename));

ratprint : false;

**Comment by gunterkoenigsmann** [comment]
If you have access to a local drive you can store temporary files on one workaround might be setting the system's (or the user's environment variable) named HOME to this location: maxima will then store all data files there; If you want something executed by maxima on every startup you can put the respective lines into a file named maxima-init.mac in the maxima folder of your home directory.

**Comment by afettouhi** [comment]
maxima-init.mac where is that file on Windows? Is it under C:/Users/U321361/maxima?

**Comment by gunterkoenigsmann** [comment]
On my windows computer it was.
...and you could try using Wolfgang's nightly version of maxima http://wolfgang.dautermann.at/maxima/maxima-clisp-sbcl-current.exe: In the configuration dialogue of this wxMaxima version you can choose the command-line parameter

     -l sbcl

to use a reasonably fast maxima or

     -l clisp 

to use a maxima that is running in a slow but rather good-natured lisp. If the latter does work the error should be in maxima (maxima.sourceforge.net), not in wxmaxima (https://github.com/andrejv/wxmaxima). Alternatively you could try to do something like

           load("draw");draw2d(explicit(sin(x),x,0,10));

in a maxima started from the windows console (cmd.exe) instead of from wxMaxima in order to find out if maxima can plot: If maxima is able to plot and wxMaxima isn't and the .png file from the plot isn't generated we at least know that the error is in wxmathml.lisp that contains the wxplot and the wxdraw commands.

**Comment by afettouhi** [comment]
I have tried the latter suggestion running

load("draw");draw2d(explicit(sin(x),x,0,10));

from maxima running from cmd.exe and wxmaxima

both work some reason. wxMaxima fails though when I save

load("draw");draw2d(explicit(sin(x),x,0,10));

to a file and run it from my network drive goung through this path

\\danfoss.net\PersonalDrives\U321361\My Documents\Work\untitled.wmx

**Comment by gunterkoenigsmann** [comment]
That's positively weird. Unfortunately I don't have a windows to debug this on. Perhaps Andrej will have an idea. 

Anyway... ...when the drive is mapped as p: does saving the file somewhere on p: and then trying to plot work? 

Am 22. Februar 2016 08:30:00 MEZ, schrieb "André Fettouhi" <notifications@github.com>:
>I have tried the latter suggestion running
>
>load("draw");draw2d(explicit(sin(x),x,0,10));
>
>from maxima running from cmd.exe and wxmaxima
>
>both work some reason. wxMaxima fails though when I save
>
>load("draw");draw2d(explicit(sin(x),x,0,10));
>
>to a file and run it from my network drive goung through this path
>
>\\danfoss.net\PersonalDrives\U321361\My Documents\Work\untitled.wmx
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/664#issuecomment-187052417

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gunterkoenigsmann** [comment]
Half an idea I have perhaps: On saving the file to a network drive
wxMaxima tells maxima to cd to the drive and folder the file is saved
in. cd'ing to p:\someFolder is possible. cd'ing to a pure network path
might not.

But if a cd failed why does gnuplot fail? Unfortunately maxima doesn't
forward eventual debug output from gnuplot to wxMaxima.

Kind regards,

     Gunter.

**Comment by afettouhi** [comment]
Yes I save tempfiles to P:/My Documents/maxima but it works saving to the standard C:/Users/username/ but only if I go through the above mentioned route.

**Comment by afettouhi** [comment]
I have to mention that I didn't have any of these issues with maxima-5.36.1-sbcl. So something has changed...

**Comment by gunterkoenigsmann** [comment]
Many things have:
 - We now no more uncompress images on reading them from the disk but unompress and scale them once they hit the screen freeing unused memory when they leave the screen again.
 - wxWidgets (the library that handles file I/O for us and does the image handling) has evolved
 - and every installer is compiled on a slightly different system. Maybe one of these systems doesn't know how to make code network drive aware.
My guess would be that Andrej's 64-bit-sbcl installer that can be found on maxima.sf.net might solve the issue if the latter is the case.

**Comment by gunterkoenigsmann** [comment]
Resolved this problem with https://sourceforge.net/p/maxima/code/ci/48f31003d7475d1421560383d3cd807c1466df5c/tree/src/init-cl.lisp?diff=3fd2b4cf6c6fa7b36c9dd7da5609586ad01a0331
