### ISSUE TITLE
Setting --dynamic-space-size 999 doesn't work

### ISSUE THREAD

**Issue by afettouhi** [andrejv/wxmaxima#670]
I am using yesterdays nightly build of wxmaxima with 5.37.2-sbcl and I tried to set

--dynamic-space-size 999

in order to avoid running out of memory because I am reading a rather large file i need to plot with 86000 lines and 12 to 15 columns. But when sbcl reached 564 MB everything stopped sadly. I was hoping that with the above parameter I could go to 1 GB without issue.

**Comment by gunterkoenigsmann** [comment]
If you use Wolfgang's installer that incorporates both clisp and sbcl instead of --dynamic-space-size 999 you can tell wxMaxima in the configuration dialogue to pass the following command-line parrameter:

      -l clisp

Clisp has a way slower - but surprisingly efficient memory management. I personally always keep a linux box handy that being pure 64 bit doesn't have these 2GB problems. But I don't know if they would allow you to do so in your work place. Otherwise we can only hope that Wolfgang will find out how to make 64bit work on Windows - or that Wolfgang's nightly build of the maxima/wxMaxima installer (that incorporates Robert's work that makes maxima more memory-efficient) is already memory-efficient enough that it no more runs into this problem.

**Comment by afettouhi** [comment]
Thanks for the info. I would rather run maxima on Linux. But my
workplace doesn't allow Linux machines on their network plus I am not
allowed to move my data on to a non-certified machine. Hopefully you get
wxmaxima/maxima running on 64 bit windows.

Kind Regards

André Fettouhi

Den 27-02-2016 kl. 16:36 skrev Gunter Königsman:
>
> If you use Wolfgang's installer that incorporates both clisp and sbcl
> instead of --dynamic-space-size 999 you can tell wxMaxima in the
> configuration dialogue to pass the following command-line parrameter:
>
> |-l clisp |
>
> Clisp has a way slower - but surprisingly efficient memory management.
> I personally always keep a linux box handy that being pure 64 bit
> doesn't have these 2GB problems. But I don't know if they would allow
> you to do so in your work place. Otherwise we can only hope that
> Wolfgang will find out how to make 64bit work on Windows - or that
> Wolfgang's nightly build of the maxima/wxMaxima installer (that
> incorporates Robert's work that makes maxima more memory-efficient) is
> already memory-efficient enough that it no more runs into this problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrejv/wxmaxima/issues/670#issuecomment-189667673>.
>

-- 
-------------------------------------------
Dr. rer. nat. André Fettouhi
Mejerivej 40, Hjallese
DK-5260 Odense S
Denmark
Telephone: +45-65920808
Mobile Phone: +45-23269256
E-Mail: A.Fettouhi@gmail.com
-------------------------------------------

**Comment by afettouhi** [comment]
I tried setting -X '--dynamic-space-size 999' in the options menu of wxmaxima doesn't work. I just get a process terminated when runing anything now.

**Comment by andrejv** [comment]
It works for me on OSX with the git version of wxmaxima.

Can you tell me your `wxbuild_info()`.

**Comment by afettouhi** [comment]
wxMaxima version: 15.8.0
Maxima version: 5.37.2
Maxima build date: 2015-09-18 21:03:17
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7

**Comment by andrejv** [comment]
Looks like you need to replace single quotes with double qoutes on Windows. Try adding

    -X "--dynamic-space-size 999"

to the list of parameters.

**Comment by afettouhi** [comment]
I just tried your suggestion with the double quotes and I still get the same terminated process when I open wxmaxima.

**Comment by andrejv** [comment]
Maybe 999 is too ambitious. Try with a lower value, on my computer I could only get it to about 750.

Maybe switch to 64bit sbcl, it allows higher dynamic size.

**Comment by afettouhi** [comment]
Yes 750 is also the maximum I can set on my machine with yesterdays nightly build before I get the terminated process error. Testing it now.
