### ISSUE TITLE
autoindent

### ISSUE THREAD

**Issue by murakamiriyugi** [andrejv/wxmaxima#673]
For the sake of input readability and ease-of-use, 
it would be helpful to adopt the feature already present
in most IDE's for programming languages; that
is, auto-indentation. Some long expressions can
be easily inputted (and be read) with auto-indentation.

The problem readability is magnified the longer the 
expression is. One can of course, press the tab key 
(as much as you want) to indent the desired lines. 
But this can be really cumbersome.

**Comment by gunterkoenigsmann** [comment]
This is a reasonable request => The current nightly build (see http://andrejv.github.io/wxmaxima/develop.html) should contain the option to enable and disable autoindent at input.

Kind regards,

   Gunter.
