### ISSUE TITLE
Weird <TAB> issue

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#675]
Roland Salz found this:

If an input cell contains the string 
     
     <=> 
     
pressing the TAB key jumps to the position of the <=>, not to the position mod(x+4,4).

I can locate the reason in the following block in EditorCell::FindNextTemplate. Unfortunately I have no Idea what this function does do - so I don't dare to touch this part of the code.

       // First search in the direction of search
       if (varsRegex.Matches(first))
       {
         varsRegex.GetMatch(&start, &length, 1);
         if (left)
         {
           m_positionOfCaret = start;
           SetSelection(start,m_selectionEnd);
         }
         else
           m_positionOfCaret = m_selectionStart = positionOfCaret + start;
         SetSelection(m_selectionStart,m_selectionStart + length);
         return true;
       }

**Comment by andrejv** [comment]
This is expected. The template autocompletion will expand for instance

    integrate

into

    integrate(<expr>, <var>, <a>, <b>)

and TAB switches between expr, var, a and b.

**Comment by gunterkoenigsmann** [comment]
Then this is neither weird nor an issue. Thanks a lot!
