### ISSUE TITLE
Changing Default animation rate requires restart

### ISSUE THREAD

**Issue by afettouhi** [andrejv/wxmaxima#677]
I noticed that running a nightly build of wxmaxima that if I change the default animation framerate and then try to save an animation of a slide or plot in general. The right click menu doesn't show up anymore. One has to close wxmaxima and restart it for it to work again.

**Comment by gunterkoenigsmann** [comment]
Tomorrow's nightly build should fix this issue.
Thanks a lot,
and kind regards,

     Gunter.
