### ISSUE TITLE
Poor quality icons

### ISSUE THREAD

**Issue by rend3r** [andrejv/wxmaxima#680]
This one from Wolfgang Dautermann daily build
![wxm_new](https://cloud.githubusercontent.com/assets/12601181/13731004/789dab20-e970-11e5-817f-93669cc5cf9b.png)
And this one from official maxima-sbcl-5.37.2.exe installer
![wxm_old](https://cloud.githubusercontent.com/assets/12601181/13731003/789d4388-e970-11e5-8686-d10f154d4894.png)
As you can see something is broken now. Is it lowres images for icons at compile time or maybe some unnecessary interpolation in code?
wxMaxima\art\toolbar contains 32x32 pixels png's
Windows 7 x64

**Comment by gunterkoenigsmann** [comment]
That was me - and I honestly don't know if I took the right decision:

The icons the last release was equipped with look fine - but are way too
small for high-dpi screens like the one from the current microsoft
surface => added high-resolution icons instead and am automatically
scaling them down to a size that makes sense on the current screen.

An alternative would have been to include svg icons that are
indefinitely scalable without getting blurred - but that would have
added wxsvg to our dependencies.

Another alternative would have been providing maxima with icons of all
sizes - which works fine on windows. But for operating-systems that make
all icons themeable (for example gnome/linux) inventing your own way of
dealing with icons would break theming again. As the tango icons with
lower resolutions are created from high-resolution tango icons by
scaling them down I didn't expect there to be a difference between
downloading scaled icons and providing scaled icons. Actually the
scaled-down icons look exactly like the ones we provided with wxMaxima
on my computer...
... which leads me to an idea: perhaps scaling down works like magic -
if we don't encounter a screen resolution that makes us use an odd
scaling factor. If I round up/down the scaling factor to a sensible one
before scaling....

Will be quite busy this week so I cannot guarantee if I can make it in
the next few days. But will try if that works.

Kind regards,

 Gunter.

**Comment by andrejv** [comment]
In `Toolbar.cpp`  we are explicitly specifying the size of the icons to be 24x24. These is the standard size on Windows and OSX and we should use toolbar icons in this size on Windows and OSX. If the standard size is different on Linux/gtk, we can also provide icons in different sizes.

**Comment by gunterkoenigsmann** [comment]
> In |Toolbar.cpp| we are explicitly specifying the size of the icons to
> be 24x24. These is the standard size on Windows and OSX
24x2 is a sane resolution for most screens. But it is way too small is
no more true on the microsoft surface or on macbooks with retina
display... ...did just push commit 64dd4b2 that should get rid of weird
antialiassing decisions by limiting the pool of image sizes to 24, 48,
72 and 96 pixels for current displays.

That means: For some reason I seem to have placed images in the wrong
resolution into the toolbar folder which should also account for them
being blurred => Will do another push tomorrow that should completely
correct the issue.

**Comment by gunterkoenigsmann** [comment]
Ok.. ...tomorrow we should have sharp icons again that will autoscale,
when needed.

Kind regards,

 Gunter.

**Comment by andrejv** [comment]
I can confirm that the icons look much better on OSX.

**Comment by gunterkoenigsmann** [comment]
Then it is good that you insisted on the fact that their quality could be improved. Will see if I can get hold of a High-DPI device tomorrow.

Kind regards,

   Gunter.

**Comment by rend3r** [comment]
@gunterkoenigsmann 
Ok, main toolbar looks smooth again but when openning the preference i get following error
![wxm_up1](https://cloud.githubusercontent.com/assets/12601181/13818867/a19aec92-eba8-11e5-8f2c-c85e4f1b393c.png)

**Comment by pdiazs** [comment]
Hi i have been using wxmaxima last version for quite a lot now but suddenly i find that when i call edit preferences i find 
![2csnkfb](https://cloud.githubusercontent.com/assets/7243459/20759136/594c7bd2-b71c-11e6-90b0-14100b073add.png)

and program closes. It also happens when i close the wmx files

Any suggestion?

**Comment by pdiazs** [comment]
I have noticed now that if i close the window directly the preference windows emerges and works and after that everything works fine but happens again when i come back to maxima

**Comment by gunterkoenigsmann** [comment]
I *think* that the problem might be that in your operating system's language setting the decimal separator and the separator for 1000s is set to the same character making it impossible to convert strings to numbers and vice versa in a consistent way.

If this isn't the reason: Which Language is your system currently set to? Windows isn't language-friendly. But perhaps I can debug it.
