### ISSUE TITLE
Error using latest nightly build

### ISSUE THREAD

**Issue by afettouhi** [andrejv/wxmaxima#682]
I am testing the new release of maxima 5.37.3 with 64 bit sbcl on Windows 7. I updated wxmaxima to todays nightly build and when I open wxmaxima I get this error window:

wxwidgets debug alert

/home/dauti/maxima/daily/buildwxWidgets-prefix/src/wxWidgets/src/common/image.cpp(433): assert "(width > 0) && (height > 0)" failed in Scale(): invalid new image size
Do you want to stop the program?
You can also choose [Cancel] to surpress further warnings.

**Comment by rend3r** [comment]
I think https://github.com/andrejv/wxmaxima/issues/680 related

**Comment by afettouhi** [comment]
If I click No then I get another error window

wxwidgets debug alert

/home/dauti/maxima/daily/buildwxWidgets-prefix/src/wxWidgets/src/common/bitmap.cpp(922): assert "image.IsOk()" failed in CreateFromImage(): invalid image
Do you want to stop the program?
You can also choose [Cancel] to surpress further warnings.

Then it loops back to the other error and continues in an infinite loop. Until you either click Yes or Cancel

**Comment by afettouhi** [comment]
So this should be fixed in the latest nightly build then? I just downloaded the nightly build from Dautermann's that is now 5 hours old and I'm still getting this error.

**Comment by gunterkoenigsmann** [comment]
Weird. Will try to see what I did wrong this time.

Kind regards,

  Gunter.

**Comment by afettouhi** [comment]
Seems to be fixed now in todays nightly build. Many thanks!
