### ISSUE TITLE
verbatim in TeX export 

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#684]
Hi,

Using wxMaxima 5.36.1 sbcl on Windows 10 x64 and 5.37.3 clisp on Windows 10 x32

When exporting wxmaxima 5.36.1 input text into TeX the result was always in verbatim mode which makes a lot of sense.
5.36.1 TeX

%%%%%%%%%%%%%%%
%%% INPUT:
\begin{minipage}[t]{8ex}{\color{red}\bf
\begin{verbatim}
(%i1) 
\end{verbatim}}
\end{minipage}
\begin{minipage}[t]{\textwidth}{\color{blue}
\begin{verbatim}
info:build_info()$info@version;
\end{verbatim}}
\end{minipage}

Now in wxmaxima 5.37.3 it is not, which is causing me many problems with the TeX output. I have to change the code whenever there is an exponent or a dollar sign.

5.37.3 TeX
%%%%%%%%%%%%%%%
%%% INPUT:
\begin{minipage}[t]{8ex}\color{red}\bf
(\%i2) 
\end{minipage}
\begin{minipage}[t]{\textwidth}\color{blue}
info:build\_info()\$info@version;
\end{minipage}

Daniel Volinski

**Comment by gunterkoenigsmann** [comment]
The verbatim environment/command did frequently break export for me as sbcl tends to use the hash (#) quite frequently in its output and LaTeX's verbatim feature didn't support this character. Also support for greek letters and some mathematical symbols was broken => tried to emulate the verbatim feature on wxMaxima's side. During the last few days and with Roland's help I hope to have resolved all of the remaining bugs in the TeX export. I think the dollar ($) sign should work by now.

**Comment by danielvolinski** [comment]
What about the exponent, this also causes problems.
