### ISSUE TITLE
Restarting 5.38.0 maxima causes wxmaxima crash

### ISSUE THREAD

**Issue by afettouhi** [andrejv/wxmaxima#695]
Running 5.38.0 on Windows 7 with sbcl enabled in wxmaxima. If you try to restart maxima under the maxima section. wxmaxima crashes (one gets a wxmaxima has stopped working popup).

**Comment by gunterkoenigsmann** [comment]
I am afraid that was me trying to solve another way to crash wxMaxima. Commit c3ae7668729e635d32279fe23ce78ededeee7b47 which is included in the current nightly build resolves this problem.

**Comment by afettouhi** [comment]
Thanks for the info switched to todays nightly build and it works now.
