### ISSUE TITLE
Folding input cells sometimes broken

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#697]
Folding the following input cell sometimes fails:

     fef
     we
     ewcwe
     cewc
     cce

The folded cell doesn't end in "+ n suppressed lines". All of the other input cells I could think of worked. Don't know what causes this.

**Comment by andrejv** [comment]
Folding does not work for inputs which contain more that one line. It was probably broken when syntax highlighting was added.
