### ISSUE TITLE
32bit wxMaxima does not spawn 64bit sbcl

### ISSUE THREAD

**Issue by rend3r** [andrejv/wxmaxima#700]
I am playing with maxima-sbcl-5.38.0-win64  (sf installer by andrejv i suppose) now.
After starting wxMaxima i immediately get sad message "Maxima process terminated". Restarting Maxima from menu leads to infinite "waiting for connection".
Disabling DEP ( http://maxima.sourceforge.net/faq.html which is obsoleted even for 32bit sbcl builds )  does not solve the problem.
I think the cause is somehow related to File System Redirector https://msdn.microsoft.com/en-us/library/windows/desktop/aa384187(v=vs.85).aspx
32bit WxMaxima spawn 32bit command shell from %windir%\SysWOW64 due FSR -> 32bit cmd redirects C:\Program Files to C:\Program Files (x86) or just could not run 64bit sbcl.

Some [un]related links:
**%ProgramW6432%**
http://superuser.com/questions/766409/how-do-i-get-64-bit-programfiles-in-batch-file-that-is-run-from-32-bit-applica
**c:\Windows\Sysnative**
http://stackoverflow.com/questions/8453277/how-can-32-bit-cmd-exe-launch-64-bit-cmd-exe-in-windows-2003-x64
and batch voodoo if problem is related to maxima.bat
https://stackoverflow.com/questions/10071300/how-to-create-a-batch-file-which-work-for-both-program-files-and-program-filesx
https://stackoverflow.com/questions/12322308/batch-file-to-check-64bit-or-32bit-os
https://stackoverflow.com/questions/27090734/how-to-run-a-batch-file-in-64-bit-mode-from-a-batch-file-in-32-bit-mode
Clean command line maxima session works flawlessly.

**Comment by andrejv** [comment]
Does xmaxima work?

**Comment by rend3r** [comment]
Could not reproduce on another machine - xmaxima and wxmaxima work fine. The only difference last machine has disabled UAC.
Is it possible interference from old maxima installations, e.g. configuration files at the profile folder? I see some registry keys with preference in HKEY_CURRENT_USER\Software\wxMaxima

**Comment by rend3r** [comment]
>Does xmaxima work?

Ok, i'v tried to run xmaxima on 1st machine - no success.
Wolfgang Dautermann's build work fine btw. I have no clue now.

**Comment by rend3r** [comment]
```
C:\Program Files\Maxima-sbcl-5.38.0\bin>maxima.bat -r ":lisp (setup-server 4010)
"
Maxima 5.38.0 http://maxima.sourceforge.net
using Lisp SBCL 1.3.4
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1)
; in: PROGN (SETUP-SERVER 4010)
;     (MAXIMA::SETUP-SERVER 4010)
;
; caught STYLE-WARNING:
;   undefined function: SETUP-SERVER
;
; compilation unit finished
;   Undefined function:
;     SETUP-SERVER
;   caught 1 STYLE-WARNING condition

Maxima encountered a Lisp error:

 The function MAXIMA::SETUP-SERVER is undefined.

Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
(%i1)
C:\Program Files\Maxima-sbcl-5.38.0\bin>maxima.bat -s 4010
Connecting Maxima to server on port 4010

Unable to connect Maxima to port 4010.
Error: An exception occurred in context #.(SB-SYS:INT-SAP #X0022CD00): #.(SB-SYS
:INT-SAP #X0022DF10). (Exception code: 1722)

C:\Program Files\Maxima-sbcl-5.38.0\bin>maxima.bat -r ":lisp (setup-server 4010)
"
Maxima 5.38.0 http://maxima.sourceforge.net
using Lisp SBCL 1.3.4
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1)
; in: PROGN (SETUP-SERVER 4010)
;     (MAXIMA::SETUP-SERVER 4010)
;
; caught STYLE-WARNING:
;   undefined function: SETUP-SERVER
;
; compilation unit finished
;   Undefined function:
;     SETUP-SERVER
;   caught 1 STYLE-WARNING condition

Maxima encountered a Lisp error:

 The function MAXIMA::SETUP-SERVER is undefined.

Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
(%i1)
C:\Program Files\Maxima-sbcl-5.38.0\bin>
```

Is it any chance start maxima as server and connect to it manually?

**Comment by andrejv** [comment]
`maxima -s 4010` should do it.

**Comment by rend3r** [comment]
Output on 2nd machine: 
C:\Program Files\Maxima-sbcl-5.38.0\bin>maxima.bat -s 4010
Connecting Maxima to server on port 4010
Unable to connect Maxima to port 4010.
Error: Socket error in "connect": ECONNREFUSED
WARNING: DBG_PRINTEXCEPTION_C: DllMain: dll unloaded

**Comment by gunterkoenigsmann** [comment]
To me this looks like a firewall is blocking the applications from communicating with each other.

**Comment by rend3r** [comment]
Ok, exception occurred when dnscache service is stopped. sbcl x86 build is not affected by the way.
