### ISSUE TITLE
Text overlaping after undo changes

### ISSUE THREAD

**Issue by rend3r** [andrejv/wxmaxima#702]
1) Make simple sheet containing 1 cell with 3 line, for example:
a:5;
b:10;
c:15;
2) Evaluate document
![overlap1](https://cloud.githubusercontent.com/assets/12601181/14696625/66f8f590-0785-11e6-9f17-14350075f781.png)
3) Remove input line by line until cell disappears 
4) Undo, undo, undo changes
![overlap2](https://cloud.githubusercontent.com/assets/12601181/14696689/e88c5232-0785-11e6-92a9-c6cb0455a8cc.png)

**Comment by rend3r** [comment]
@gunterkoenigsmann 
I've tried latest trunk but bug is still presented.

wxbuild_info()$
wxMaxima version: 15.8.0
Maxima version: 5.38.0_dirty
Maxima build date: 2016-04-03 10:09:29
Host type: i686-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

That's one from about dialog:
wxMaxima 16.4.x-unofficial
System info
wxWidgets: 3.1.0
Unicode Support: yes
Maxima version: 5.38.0_dirty 
Lisp: SBCL 1.3.4

**Comment by gunterkoenigsmann** [comment]
Then there were at least 2 bugs in this functionality.

**Comment by gunterkoenigsmann** [comment]
Ok... ...I think I've found and corrected them when trying to improve wxMaxima's performance a little bit further. Feel free to re-open this ticket if there is a third case in which this could wrong.

**Comment by rend3r** [comment]
Can reproduce with current (d01ed90) master.

**Comment by gunterkoenigsmann** [comment]
I have managed to reduce the problem to the point that it disappears when the cursor leaves the cell after an undo. But why it happens is still a mystery to me.

**Comment by gunterkoenigsmann** [comment]
I think this time (and 2 bugs later) I really have found out what has been causing this issue. If it still occurs I have to apologize that this is necessary. But since this ticket has lead to resolving various bugs it seems to be important to fix this issue.

**Comment by rend3r** [comment]
Ok, seems to be fixed in 1c0e260
