### ISSUE TITLE
Search and replace cursor

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#709]
When searching and replacing, Wxmaxima highlights all the potential strings that could be replaced.
The problem is that the difference between the highlights and the one place in which the string is going to be replaced now, is very mild: almost the same color. The difference should be more pronounced.
Thanks.

**Comment by gunterkoenigsmann** [comment]
The "style" tab of the configuration dialogue should allow you to choose a color for "text that matches the selection". But you are right: The default color I chose isn't helpful to me, either.
