### ISSUE TITLE
Some windows build notes

### ISSUE THREAD

**Issue by rend3r** [andrejv/wxmaxima#715]
1) Updates for README.md
If you build WxWidgets with `./configure --disable-shared --enable-monolithic --disable-debug_flag --enable-unicode` wxconfig is `wxWidgets-3.1.0\lib\wx\config\inplace-msw-unicode-static-3.1` now.
This note is valid for wxWidgets 3.1.0 (does not check wxWidgets 3.0.2).
2) `./configure --with-wx-config=/path_to/wxWidgets-3.1.0/lib/wx/config/inplace-msw-unicode-static-3.1 --enable-fullystatic && make` build really fat unstripped binaries.
Maybe `configure` should provide `--enable-debug` like wxWidgets do and make stripped binaries by default?
3) `make wxMaxima.win.zip` creates zip archive but without msys libstdc++-6.dll, libgcc_s_sjlj-1.dll it's useless (especially if you update wxmaxima from sf maxima installers)

**Comment by gunterkoenigsmann** [comment]
About 2.) I have mixed feelings:
Stripped binaries will save a few megabytes. But megabytes aren't this costly anymore and if you include the debug symbols there always is the chance that someone who experiences a crash knows how to make a symbolic backtrace  that helps resolving the problem.
