### ISSUE TITLE
Greek letter π is not recognized as constant pi in a function loaded with a .mac file

### ISSUE THREAD

**Issue by RolandSalz** [andrejv/wxmaxima#719]
Generally, the Greek letter π is recognized as the constant pi, that is, float(π) evaluates to 3.14...
This, however, does not work, if I use π within a function that I load with a .mac file. Then π is just a symbol and float(π) does not evaluate to 3.14... This should be brought in line with the normal use of π in a worksheet: π should always be recognized as the constant pi.
(I use Windows 7 with Maxima 5.37post and wxmaxima 15.10.0 unofficial.)

**Comment by gunterkoenigsmann** [comment]
That a π isn't recognized by maxima on loading a file can only changed on the maxima side: wxMaxima has no access to the internals of maxima's load() function. But perhaps I could implement something like this:
 - If we are exporting to a .mac file
 - and we are inside a code cell
 - and if the current letter is a π
 - and if the letter before this letter and the one afterwards is not an alphanumeric character
 - then we replace the π by a %pi
Does this feel like it could make any sense?

**Comment by RolandSalz** [comment]
That seems better than nothing, although I for instance usually don’t export my .wxm files to .mac. Instead, I copy functions I wrote into an already existing .mac file. So the solution would not help here. 

 

Maybe, therefore, it would be better to make a change to Maxima in this case.

 

Thank you for looking at the problem.

**Comment by RolandSalz** [comment]
That seems better than nothing, although I for instance usually don’t export my .wxm files to .mac. Instead, I copy functions I wrote into an already existing .mac file. So the solution would not help here. 

Maybe, therefore, it would be better to make a change to Maxima in this case.

Thank you for looking at the problem.

**Comment by gunterkoenigsmann** [comment]
Implemented the wxMaxima half of the change in commit 248b010026fa0d50da59703910c1829bea822d44. Closing this bug for wxMaxima for now. But more unicode support in maxima is always welcome by me: I would like to use a λ in one of my libraries. But currently I cannot do so as long as the file is used on windows, too.
