### ISSUE TITLE
Evaluated output from maxima do not get plotted in order

### ISSUE THREAD

**Issue by christianlupus** [andrejv/wxmaxima#721]
Hello,

I have encountered the following problem: When I use the code in [Problem.zip](https://github.com/andrejv/wxmaxima/files/271948/Problem.zip) I expect to see alternating matrices and some (debugging) output. For plain maxima this works as expected (thus I am relatively sure this is not a maxima issue). However on wxMaxima the order of output get intermixed. On my machine the matrices I2 up to I4 are plotted straight after each other and then the corresponding text follow (see the wxmx file).

Can anybody confirm this behavior?

**Comment by gunterkoenigsmann** [comment]
Confirm.

...disp() tries to output stuff immediately (not waiting for the moment
the command has exited and the full maths can be output) - and printf
doesn't wait before outputting stuff, either.

Don't know if the result is to be expected, though, or if it is a bug.

Kind regards,

 Gunter.
