### ISSUE TITLE
Help not working inside wxMaxima

### ISSUE THREAD

**Issue by christianlupus** [andrejv/wxmaxima#722]
Hello again,
I have the problem found that wxmaxima no longer supports to enter `?? <topic>`. Normally one gets the possible help chapters and has to enter either a number or `none` or `all`. The text from maxima that asks the user to take action is not shown by wxmaxima. This is bad as the user might forget that such an invocation and maxima ignores any further input except for a number or one of the two keywords.

This might be related to some new code in wxmaxima which also was related to issue #721.

**Comment by andrejv** [comment]
Please include the output form `wxbuild_info()`.

**Comment by christianlupus** [comment]
The output of wxbuild_info():
> wxMaxima version: 16.4.x-unofficial
> Maxima version: branch_5_38_base_66_gcaae80f
> Maxima build date: 2016-05-18 13:25:29
> Host type: x86_64-unknown-linux-gnu
> System type: Linux 3.13.0-68-generic X86-64
> Lisp implementation type: SBCL
> Lisp implementation version: 1.1.14.debian

**Comment by andrejv** [comment]
This is caused by commits 7590b00 and fabf905.

@gunterkoenigsmann I think it would be better to stick to the old way of handling the prompts. I don't think many people want to change the input prompt anyway.

**Comment by gunterkoenigsmann** [comment]
> would be better to stick to the old way of handling the prompts. I don't
> think many people want to change the input prompt anyway.
Me neither. But there was a thread in the maxima mailing list that sounded like there is a need to do it for some reason.

On my computer (head of wxMaxima master) both the help system and changing the prompt work. Don't know if I did change anything that made this work or if it is reproducible on any other computer.

Kind regards,

  Gunter.

**Comment by gunterkoenigsmann** [comment]
Ok... ...Did misinterpret the bug report. But the next nightly should fix it. Thanks a lot, and kind regards,

    Gunter.
