### ISSUE TITLE
wxdraw should allow setting the file name

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#730]
Coma and a few other packages automagically switch their graphical output to wxdraw() if called from a maxima running within wxMaxima. This actually feels like a good idea. But if the user wants to keep the .png file afterwards it currently leaves no options to do so => We need a new feature:

If the scene description for wxdraw defines a file_name 
- wxdraw() should not specify its own filename
- and wxdraw() should add a del=no to the <img> tag it creates.

**Comment by andrejv** [comment]
I'm not familiar with the coma package. Can you provide an example of a call to wxdraw and describe what result you expect?

**Comment by gunterkoenigsmann** [comment]
The only working example I have would be:

     load(coma)$
     root_locus(1/(1+k*F(s)),xrange=[-5,0],yrange=[-2,2],
     file_name="12ClosedLoop3",terminal='png)$
     show_image("12ClosedLoop3.png")$

It can be worked around by adding an

     plot_defaults:delete(wx=true,plot_defaults);

But making wxdraw not adding wxMaxima's file_name command if the user provided one and not deleting the file after loading it in this case felt like it would make the user experience more seemless.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!
