### ISSUE TITLE
draw_graph fails if maxima_tempdir has extended ASCII characters

### ISSUE THREAD

**Issue by josemam** [andrejv/wxmaxima#732]
OS is Win8.1 64-bit. I run wxMaxima 16.04.2. This does not happen for wxMaxima 13.04.2 or when using Maxima from command line (Maxima version is 5.38.1_5_gdf93b7b_dirty). If I recall correctly it happened in a major release right after 13.04.2 as well.

If `maxima_tempdir` is set to a path with extended ASCII characters (such as `ó`, `è`, `ç`, `ñ`), then `draw_graph` will always fail to draw a graph, and will show this (if nothing fails before):

Message from maxima's stderr stream: 
set out '[Path in ASCII]/maxout\_[number]\_[another number].png'
                                        ^
cannot open file; output not changed
"[Path in Unicode (this is the correctly shown one)]/maxout\_[number].gnuplot", line 2: util.c: No such file or directory

As `maxima_tempdir` is set to the user path if `%MAXIMA_TEMPDIR%` is not set, any user with an extended ASCII character in their username will not be able to run `draw_graph` unless they change the value of `maxima_tempdir` or set `%MAXIMA_TEMPDIR%` to a proper path.

**Comment by gunterkoenigsmann** [comment]
Seems like the gnuplot version you are using refuses to write files if maxima instructs it to write data into its unicode path.

https://groups.google.com/forum/#!topic/comp.graphics.apps.gnuplot/mzO5yUiLYv4 indicates that this seems to be a general problem with gnuplot. Don't know if there can be a workaround on the maxima side. But if you convince the programmers from the maxima project to set %MAXIMA_TEMPDIR% to a "real" temp directory that might not be a bad thing, perhaps, neither.

**Comment by gunterkoenigsmann** [comment]
If you want to report this problem to the gnuplot guys they can be reached at http://www.gnuplot.info. If you didn't do so already, that is.

**Comment by gunterkoenigsmann** [comment]
Worked around this by choosing a (hopefully) more sane tempdir in https://sourceforge.net/p/maxima/code/ci/48f31003d7475d1421560383d3cd807c1466df5c/tree/src/init-cl.lisp?diff=3fd2b4cf6c6fa7b36c9dd7da5609586ad01a0331

**Comment by gunterkoenigsmann** [comment]
Will close this bug report for wxMaxima, not because it is invalid, bug since the real solution to this problem has to be done in a separate project (gnuplot). Seems like for some partition types this problem is already known there: https://groups.google.com/forum/#!topic/comp.graphics.apps.gnuplot/mzO5yUiLYv4
