### ISSUE TITLE
ctensor: csetup() cannot be completed in wxmaxima

### ISSUE THREAD

**Issue by RolandSalz** [andrejv/wxmaxima#739]
load(ctensor);
csetup();
Asks the usual questions to the user. However, after 
"Is the matrix 1. Diagonal, 2. Symmetric, ..." 
the dialog quits and the present wxmaxima cell is left. As a trial with the console shows, it should continue with 
"Answer 1, 2, ...:" 
Then the user should be able to enter the number and then enter the components of the metric.
All this is not possible under wxmaxima, so csetup() and ctensor cannot be used.

**Comment by RolandSalz** [comment]
PS: My dialogue so far was:
Dimension: 3 
Change coordinate names: no
1. Enter a new metric

**Comment by RolandSalz** [comment]
One more problem with csetup():
If to the question "Change coordinate names" I answer yes and want to enter the list of the new names, Greek letters are not accepted as list elements.

**Comment by gunterkoenigsmann** [comment]
The "Change coordinate names" problem isn't reproducible on my computer. I therefore believe it to be on maxima's (and not on wxMaxima's) side. If you are be willing to do so I wouldn't be too unhappy if you reported it to the maxima project: We seem to be 99% unicode compatible by now and it might be worth trying to arrive at a 100% and if problems aren't reported they cannot be fixed; If my diagnosis is inaccurate feel free to re-open this ticket.

**Comment by RolandSalz** [comment]
If it is not reproducible on Linux, couldn’t it then be another windows issue? If it were a maxima problem, then I would expect it to be reproducible on Linux. Or am I wrong? – Do you mean I should write a mail to the maxima list, or make a maxima bug report (the latter I never did so far)?

 

By the way, I discovered another unicode problem today. First of all, I still find it very sad that most of the wxmaxima mathematical symbols cannot be represented under windows, e.g. the ⊗ for the tensor product, they just give an empty box. (But I see the same thing happen if I use notepad++ under windows, so it does not seem to be wxmaxima-specifc. Also in notepad++ I see the ridiculously small representation of this symbol by the font. Remember, that is also an open issue in wxmaxima.) I tried it now with the combination ⊗→, which is visible. But wxmaxima hangs up on trying to load this from a .mac file (it does not connect to maxima at all). So what do you think of this: also a maxima issue?
