### ISSUE TITLE
User editing of the table of mathematical symbols

### ISSUE THREAD

**Issue by RolandSalz** [andrejv/wxmaxima#740]
It would be a nice feature if the user could add his own new symbols to the table of mathematical symbols.

**Comment by gunterkoenigsmann** [comment]
There actually is one way to do so - even if it doesn't seem to be in a place one expect it: We frequently get questions about this:

In the "Options" tab of the settings dialogue one can add "custom symbols sidebar glyphs": At some point it was predicable that there will be requests for more symbols than we could possibly fit into the sidebar.

This feature also adds more possibilities to issue #710.
