### ISSUE TITLE
Wrong visualization of small parentheses

### ISSUE THREAD

**Issue by Ninobr** [andrejv/wxmaxima#754]
I have just installed wxmaxima and tried
f(x,y):=x^2*(1-exp((y-sqrt(3*G)*x)^2*(L^2/x^2-0.5)*((R+y)/(R*(R-K+y)))/G) )/(R+y)^2;
and for the small parentheses the upper part is low and the lower part up (see image)
My computer is running Win10
OS Name	Microsoft Windows 10 Home
Version	10.0.14393 Build 14393
System Manufacturer	Dell Inc.
System Model	XPS 13 9350
System Type	x64-based PC
System SKU	0704
Processor	Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, 2592 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.4.4, 6/14/2016
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.

![image](https://cloud.githubusercontent.com/assets/20958105/17572606/b56ec254-5f55-11e6-8729-b182d4893e36.png)

wxMaxima version: 16.4.2
Maxima version: 5.38.1_5_gdf93b7b_dirty
Maxima build date: 2016-05-13 22:33:49
Host type: i686-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.3])

**Comment by gunterkoenigsmann** [comment]
Ok... ...found out parts of it: Big parenthesis are assembled by connecting a parenthesis top half sign and a parenthesis bottom half sign using a vertical line. In your case wxMaxima seems to try to create a Big Parenthesis that is smaller than a parenthesis top half sign and a parenthesis bottom half sign stacked one over the other.
