### ISSUE TITLE
Add text/html mime type for MathML

### ISSUE THREAD

**Issue by fred-wang** [andrejv/wxmaxima#758]
cc @gunterkoenigsmann

I see in d5a207b28e19e8f1dfa8df4b69d2887c322f61ce that application/mathml-presentation+xml was added for MathML. Would it be possible to do the same for text/html?

This is what is done for https://addons.mozilla.org/en-US/firefox/addon/mathml-copy/ and allows to paste equations into HTML editors such as contenteditable page loaded in Firefox (see http://html5demos.com/contenteditable) or the Thunderbird mail client.

**Comment by fred-wang** [comment]
See https://github.com/fred-wang/Mathzilla/blob/master/mathml-copy/lib/copy-mathml.js#L21

**Comment by gunterkoenigsmann** [comment]
Feels completely weird to add this. But you are right: MathML is a part of HTML5... ...The question is: Should I add this only to the "Copy as MathML" button or should I add it to the general "Copy" button, as well?

**Comment by gunterkoenigsmann** [comment]
I've added the MathML in both places. If this was a bad idea please tell me and I will revert the general copy button-half of the task.

**Comment by fred-wang** [comment]
I think it's good to have it in both places. Thanks

**Comment by fred-wang** [comment]
cc'ing @physikerwelt
