### ISSUE TITLE
wxmx files cannot be opened when path has # in it

### ISSUE THREAD

**Issue by afettouhi** [andrejv/wxmaxima#762]
As the title says. If the the path of wxmx file holds the # sign. Then opening the file on wxmaxima gives an error. You can save the wxmx file no problem. Removing the # sign from the path resolves the issue. This on Windows btw.

**Comment by gunterkoenigsmann** [comment]
Unfortunately this is true: wxmx files are zip archives and wxWidhets allows to open files inside them by trying to open something like "test.wxmx#contents.xml". As If the file name contains an # or other letters wxURL doesn't know how to encode for wxFileSystem this mechanism will fail.

**Comment by gunterkoenigsmann** [comment]
On the plus side I am convinced the next maxima release will handle network drives better than the current one.

**Comment by gunterkoenigsmann** [comment]
Found the bug report for wxWidgets: http://trac.wxwidgets.org/ticket/17024

**Comment by gunterkoenigsmann** [comment]
Should be resolved along with commit 94603c1d6847c59ef4c5d8d5f73f893f0ce419ab. But it seems like the wxWidgets guys still need to work a little bit on this before opening a file with a # in its name really works.

**Comment by gunterkoenigsmann** [comment]
Resolved with d87e238733d2872fdd4720c19f6f3ae1cff60fbd
