### ISSUE TITLE
Another failure in Export to TeX

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#764]
[Chapter01.zip](https://github.com/andrejv/wxmaxima/files/447531/Chapter01.zip)
What is the problem with this wxMaxima file?
I'm exporting to TeX but I get some errors with MikTeX I cant' solve.
MikTeX does not create the PDF file.
Additional lines in the TeX preamble
\usepackage{fullpage}
\usepackage{mdframed}
\usepackage{xcolor}
\usepackage[bookmarks=false,pdfstartview={FitH},colorlinks=true,urlcolor=blue]{hyperref}

Daniel

**Comment by gunterkoenigsmann** [comment]
When exported from the current nightly build my pdflatex seems to accept the .tex file. When I use your TeX file I get the same error message as you do - but I, too, cannot make any sense of the error message.

**Comment by danielvolinski** [comment]
Thanks.

**Comment by gunterkoenigsmann** [comment]
If you want: The nightly windows build of wxMaxima (http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly) should be quite stable, if it can find the right version of the two dll's you can download there, that is. ...it should fix your TeX problems. And I would be thankful to know if fixing them we have opened new ones.

**Comment by danielvolinski** [comment]
I'll wait for the next release.

**Comment by gunterkoenigsmann** [comment]
A wise decision! Will close this bug as I am convinced to have resolved it. But feel free to reopen it if I am wrong.
