### ISSUE TITLE
User experience: Typing is interrupted when a calculation finishes

### ISSUE THREAD

**Issue by TomasRiker** [andrejv/wxmaxima#768]
This often happens to me and is a bit annoying:

1. Start some calculation that takes a long time, e.g. `for i : 1 thru 1000000 do 'nothing;`
2. While the calculation is still in process, start typing the next command in a new cell
3. The first calculation finishes
4. Automatically, a new cell is inserted after the first one, and the cursor is placed there
5. You're suddenly typing into that new cell instead of the other one where you were typing your next command

**Proposal:** When a calculation finishes and the user has already started typing a new command, don't create a new cell.

**Comment by gunterkoenigsmann** [comment]
This happens only if "Open a new cell if maxima expects input" has been
selected in the preferences. So a quick workaround would be deactivating
this check box.

**Comment by gunterkoenigsmann** [comment]
The next nightly build will no more have this issue.

**Comment by TomasRiker** [comment]
Thanks, that's great!
