### ISSUE TITLE
Copy/paste stopped working in wxmaxima 16.04.0 in macOS Sierra.

### ISSUE THREAD

**Issue by cgo** [andrejv/wxmaxima#776]
Under macOS Sierra, copy/paste does not work in wxMaxima anymore.
I tried using cmd-c/x/v and the menus, none of them worked.
Cutting works, but not pasting.

System info:
wxWidgets: 3.1.1
Unicode Support: yes
Maxima version: 5.37.2 
Lisp: SBCL 1.3.10

**Comment by cgo** [comment]
Let me know if there is more information you need.

**Comment by gunterkoenigsmann** [comment]
This has happened with the official release?

...or did you use the nightly build. In the latter case it is me who
broke it.

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment]
I seem to remember that there was a request to change a few hotkeys so they are more in sync with the hotkeys other mac applications would use. Andrej resolved them. But CMD+C seems to look right to me.
...and a second question: Which language do you have selected for wxMaxima? Most hotkeys are taken from the menu texts which is a good thing as some standard hotkeys from one language are impossible to type on another language's keyboard. ...but a translation error will make some hotkeys weird or inaccessible.

**Comment by cgo** [comment]
I have been using 16.04.0, which I believe I have just downloaded from the sourceforge
page. Nothing that I have built myself.
I also tried to reproduce the problem with another wxmx file, but there it seemed to work (as of today) .
Also, it seems like a specific line I was trying to copy can not be pasted after copying it.
I can paste it in another window (such as a terminal), so copying appears to work. Very weird.

This is the line:
beta_3: rhs(solve(2+beta_1 + beta_2 + beta_3 − beta_1 * beta_2 * beta_3 = 0, beta_3)[1]);

Anything else I can provide to help fix this (if it is an issue)?

**Comment by cgo** [comment]
I am using English as language in wxMaxima.

**Comment by gunterkoenigsmann** [comment]
If the problem happens only for specific lines, tends to go away by themself in other cases (These bugs are seldom reported as most users feel guilty about having somehow caused the bug by themselves: Nobody expects a computer to lie or to make errors that only happen occasionally) and happens only if you drag-and-drop into specific programs I am convinced that you have found what I believe to b a wxWidgets bug: 

If I tell wxWidgets to put text on the clipboard sometimes strange things happen about once a day if I use the program for 8 hours. If  I append a "\0" to all text snippets I put on the clipboard (the current source code will do so) these things stop happening. As the clipboard tells everybody who wants to paste text how many characters it can offer and the text on the clipboard is terminated by an ASCII cod 0 the whole system is redundant. My theory now is that wxWidgets forgets to reserve space for the "\0" which means the string termination can be overwritten - which applications that use the length information from the clip board won't even notice. But others probably will if a non-zero-byte has been put in exactly the right place in the mean time.
valgrind tells me that drag-and-drop reads a byte that has not been reserved previously so my workaround might currently be the only way to go until the wxWidgets project fixes the problem on their side. But my theory might be utterly wrong and the error might be on wxMaxima's side...

**Comment by cgo** [comment]
Thanks -- so that means if I build the current HEAD and it works, you could be right, is that correct?
In that case I will try that tomorrow.

**Comment by gunterkoenigsmann** [comment]
On 05.10.2016 07:40, Christian Gosch wrote:
> Thanks -- so that means if I build the current HEAD and it works, you
> could be right, is that correct?
> In that case I will try that tomorrow.

If you are willing to do that this would be great!
In return I can promise that this version will contain many additional
bug fixes and new features.

Kind regards,

 Gunter.

**Comment by cgo** [comment]
What's the correct way to build wxmaxima in macos, and what do I need as prerequisites?

Thanks!

**Comment by gunterkoenigsmann** [comment]
The only prerequisite should be wxWidgets, the autotools and a c++
compiler. And perhaps ImageMagick in order to be able to export
animations. The main items of the rest of the build process are
documented at the bottom of the following page:

https://github.com/andrejv/wxmaxima

Don't know if this is any help: Unfortunately I don't own a mac.

I think, Andrej does, though. So if he currently has access to the
internet perhaps he will help for further questions.

**Comment by cgo** [comment]
I was able to build it, but it still does not work with the line I sent earlier.
It's now saying wxMaxima 16.4.x-unofficial, wxWidgets 3.0.2 (is that a 'bad' version?), Maxima 5.37.2, SBCL 1.3.10.

Any other idea?
The commit I was using is 42d0a747edac52de4ebdfef1c38acbd6ea5b7703.

I built with 
./bootstrap
./configure
make && make allmo
make wxMaxima.app

following the guide on https://github.com/andrejv/wxmaxima.

**Comment by gunterkoenigsmann** [comment]
Seems like you did everything right and that there still is a bug somewhere. But I currently don't seem to be able to find the offending code line => All we can hope for is a little bit of luck, for another of the developers being able to reproduce the bug or that one of us has a great idea. The good thing is: For many of the trickier bugs that have been reported one of these things actually has already happened. So there is a chance that we'll find how to fix it.

**Comment by gunterkoenigsmann** [comment]
Github has interpreted my commit as if I were completely sure that it resolves this issue. Please feel free to reopen it if this was wrong: I have changed a lot of things. But I might still have missed the actual error.
