### ISSUE TITLE
wxMaxima adds semicolon after the comment (and so .mac cannot be executed by maxima)

### ISSUE THREAD

**Issue by tigran123** [andrejv/wxmaxima#780]
I am using wxMaxima 16.04.2 with Maxima 5.38.1 compiled against the latest SBCL 1.3.10:

```
(%i1) build_info();
(%o1) 
Maxima version: "5.38.1"
Maxima build date: "2016-10-11 16:28:50"
Host type: "x86_64-unknown-linux-gnu"
Lisp implementation type: "SBCL"
Lisp implementation version: "1.3.10"
```

The problem is that wxMaxima is emitting a semicolon after the last line in a cell like this:

```
x:1; /* comment about x */
y:2; /* comment about y */
```

If the above two lines are typed into a cell and evaluated, then the input part of the cell becomes:

```
x:1; /* comment about x */
y:2; /* comment about y */;
```

Notice the semicolon added after the second comment. If you remain in wxMaxima this is fine (although annoying), but if you export it to a .mac file and then try to run it via command-line maxima you will get an error:

```
$ cat test.mac 
x:1; /* comment about x */
y:2; /* comment about y */;
$ maxima -l sbcl -b test.mac
Maxima 5.38.1 http://maxima.sourceforge.net
using Lisp SBCL 1.3.10
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) batch("test.mac")

read and interpret file: /home/tigran/python/qd/test.mac
(%i2) x:1
(%o2)                                  1
(%i3) y:2
(%o3)                                  2
/home/tigran/python/qd/test.mac:2:26:incorrect syntax: Premature termination of input at ;.
 comment about y */;
                  ^
(%o4)                   /home/tigran/python/qd/test.mac
```

If I remove the semicolon after the comment, then it runs fine, of course.

**Comment by gunterkoenigsmann** [comment]
In my experience in most cases Maxima tends to show most of its power if I calculate purely symbolical, keep the actual values of all variables in a central list and only introduce them when I really need numeric values:

     (%i1)		Values:[
          	    R_1=1, /* A test resistor */
           	    R_2=2  /* Another test resistor */
      	];
      (Values)	[R_1=1,R_2=2]
      
      (%i3)		rpar:R_Parallel=R_1*R_2/(R_1+R_2);
      (rpar)	R_Parallel=(R_1*R_2)/(R_2+R_1)

      
      (%i4)		at(rpar,Values);
      (%o4)		R_Parallel=2/3

I think this workflow was what made me not find this Phenomenon.

Kind regards,
Gunter.

**Comment by tigran123** [comment]
Thank you, Gunter for quickly fixing this.

**Comment by tigran123** [comment]
actually, speaking of "symbolic vs numeric" evaluation --- is there a way to somehow replace an operator intergrate with romberg without re-entering the expression? I.e. if I have something like `Z(x) = integrate(exp(-sqrt(1+x^2)),x,0,inf)` and discover that Maxima cannot calculate this integral symbolically, is there a way to do the equivalent of the naive `subst([integrate=romberg], Z(x))`? Of course I could re-enter the expression manually in this simple case, but in a more complex case it would be more preferable to do this without re-entering it?

I suppose questions like this should be asked on stackoverflow and not here, but I couldn't resist, sorry :)
Feel free to ignore my question if it doesn't belong here.

**Comment by gunterkoenigsmann** [comment]
Perhaps something like the following would work:

     eq:integrate(exp(-a*sqrt(1+x^2)),x,0,inf);
     args(eq);
     apply('romberg,%);

Kind regards,
    Gunter.

**Comment by tigran123** [comment]
Thank you!

**Comment by gunterkoenigsmann** [comment]
You are welcome!

     Gunter.
