### ISSUE TITLE
Running wxmaxima compiled from git source makes the system extremely slow (about 100x slower)

### ISSUE THREAD

**Issue by tigran123** [andrejv/wxmaxima#781]
I previously compiled wxMaxima 16.04.2 from sources and installed into /usr/local/bin and was running it with absolutely no problems (well, except the little one I raised yesterday and that was fixed by Gunter instantly).

So, today I decided to compile from the latest git sources. It compiled fine (with --prefix=$HOME/local) and so I installed it. To my horror, running it created an experience I have never had before (in my 20+ years of using and developing Linux). Namely, the entire X11 (Unity on Ubuntu 16.04.1) environment slowed down by a factor of about 100x or so, i.e. all the window animations etc (not just in wxMaxima, but system-wide --- in Google Chrome, gnome-terminal etc etc!) became unbearably slow. It looked as if X11 was put into what I vaguely remember to be called "synchronous mode" or something like that (the X11 debug mode, you know). Please let me know how to compile it from git sources properly, i.e. so that the resulting binary is usable (and the rest of the system is usable while wxMaxima is running). Thank you.

But running the "old" (16.04.2) wxMaxima from /usr/local/bin is fine, so I switched back to it, temporarily removing the one in $HOME/local until I figure out how to compile from git sources properly.

**Comment by gunterkoenigsmann** [comment]
Arrgh! Nomally the new version should be significantly faster, not slower...

As Slowness can have a few reasons I am afraid this time we'll need a lot of debugging:

If you open a terminal and type

     top

when the system is slow do you see any runaway process that uses up 100% of one cpu? (this should allow us to identify if X-Windows, unity, maxima or wxMaxima uses this many CPU that the system is slow.
Or is the system out of RAM and therefore constantly swapping? (top should show info about RAM, too).

Does the problem happen, too, with a wxMaxima version that can be downloaded from https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies ?

And does the slowness only happen if the "find" dialogue is open? (I have tried to add transparency to this dialogue if it is inactive)?

And which graphics card/chipset are you using?

Will try to setup a 16.04.2 system tomorrow in order to see if I can reproduce the issue there.

Thanks a lot,
and kind regards,
    Gunter.

**Comment by tigran123** [comment]
Here is the screenshot of htop running:

![Screenshot of htop](http://www.bibles.org.uk/screenshots/wxMaxima.png)

As you can see, wxmaxima process is only taking 8% CPU, I am not running out of RAM (almost all 16GB is free). The graphics card is built-in Intel HD, nothing fancy:

```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
```
The motherboard is Gigabyte H61M-S2PV, processor Core i3 2130, 16GB RAM. An old (2012) system, really, but in my hands it outperforms the fastest modern Core i7 setup with Linux installed "out of the box". Also, it is absolutely quiet which is why I still keep using it :)

I don't think this has anything to do with hardware. It looks like wxMaxima is putting X11 into some kind of "debug mode" or something like that. After exiting wxMaxima (normally, via File/Exit) the system is instantly back to normal. 

And no, I didn't open any find dialogs. Just started wxMaxima.

**Comment by gunterkoenigsmann** [comment]
The intel graphics driver is broken in the kernel they ship with 16.04, for me, too. In order to make my second laptop work I had to install a kernel from http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.8.1/

This one gives me a working graphics, at least. Have now to hurry to go to work. But will try to run wxMaxima under 16.04 this evening.

**Comment by tigran123** [comment]
The kernel they ship in 16.04 has changed about a dozen times since --- the last time two days ago. I run 4.4.0-43:

```
$ uname -a
Linux brave 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

And the i915 driver in it works absolutely fine. I also run exactly the same thing on the laptop. (I have binary identical rootfs image on laptop and desktop, regularly rsync'd).

**Comment by gunterkoenigsmann** [comment]
I perhaps have an idea: I changed wxMaxima to use the system's cursor blink rate. Not that your system tells it to use the blink rate "infinite"...

...will later today add a line that catches this case.

Am 14. Oktober 2016 07:33:07 MESZ, schrieb Tigran Aivazian <notifications@github.com>:
>The kernel they ship in 16.04 has changed about a dozen times since ---
>the last time two days ago. I run 4.4.0-43:
>
>```
>$ uname -a
>Linux brave 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC
>2016 x86_64 x86_64 x86_64 GNU/Linux
>```
>
>And the i915 driver in it works absolutely fine. I also run exactly the
>same thing on the laptop. (I have binary identical rootfs image on
>laptop and desktop, regularly rsync'd).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/781#issuecomment-253713351

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tigran123** [comment]
Aha, that sounds more like it...

**Comment by gunterkoenigsmann** [comment]
Ok... The current git head should refuse to set the cursor frequency to > 5 Hz. ...let's see if that helps.

**Comment by tigran123** [comment]
Unfortunately, no it doesn't. I did

```
$ git pull origin
$ make
$ make install
```

It did recompile MathCtrl.cpp and relinked the wxmaxima binary. I checked that $HOME/local/bin/wxmaxima is new and executed it --- exactly the same stuff happens, i.e. the GUI response is slowed down (I shouldn't say "system is slowed down" as the CPUs are all idle).

**Comment by tigran123** [comment]
Very interesting news: I have re-compiled it on my laptop and it runs much faster than on a desktop. There is still a very serious problem there, i.e. the GUI response becomes about 10x (TEN TIMES!) slower than usual, but it is about 10x faster than on the desktop. E.g. I am typing this on the laptop with wxmaxima running, which would be absolutely impossible on the desktop (i.e. the GUI was so slow on the desktop that even switching from one workspace area to another took something like 10-15 seconds).

Another difference: wxmaxima process on the laptop is taking up 60% CPU doing absolutely nothing, i.e. no files open and no cells being evaluated ---- just an empty screen. This in itself is a bug --- I should see 0% CPU here (except the blinking of cursor which shouldn't ever take more than 0.1% CPU). But on the desktop it is taking 8% CPU while doing nothing. Hmmm, maybe this is consistent behaviour because desktop has Core i3 3.6GHz and laptop has Pentium 2020M 2.4GHz processors.

This excessive CPU load in completely idle state may be a completely separate bug, I am just mentioning it here for completeness.

Also, as I said before, my laptop and desktop are binary identical in terms of software. Only the hardware (CPU) is different. Even the amount of RAM is the same 16GB.

**Comment by tigran123** [comment]
Some more debugging information.

If I strace attach to the running stable 16.04.2 wxmaxima process I see this:

```
$ strace -t -p 5501
strace: Process 5501 attached
09:33:01 restart_syscall(<... resuming interrupted restart_syscall ...>) = 1
09:33:04 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\241 \311\4\203\0\0\4K\1\0\0X\1\0\0009\1\0\0\203\0\0\4\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
09:33:04 recvmsg(3, 0x7fff5b8eeca0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:04 poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
09:33:04 writev(3, [{"\31\0\v\0\325\0\0\0\0\0\30\0! \0\0\325\0\0\0K\1\0\0X\1\0\0009\1\0\0"..., 44}, {NULL, 0}, {"", 0}], 3) = 44
09:33:04 recvmsg(3, 0x7fff5b8eeba0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:04 recvmsg(3, 0x7fff5b8eec80, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:04 poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=9, events=POLLIN}, {fd=11, events=POLLIN|POLLOUT}, {fd=12, events=POLLIN}, {fd=18, events=POLLIN|POLLPRI}], 6, -1) = 1 ([{fd=3, revents=POLLIN}])
09:33:09 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\241 \312\4\203\0\0\4K\1\0\0X\1\0\0:\1\0\0\203\0\0\4\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
09:33:09 recvmsg(3, 0x7fff5b8eeca0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:09 poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
09:33:09 writev(3, [{"\31\0\v\0\325\0\0\0\0\0\30\0! \0\0\325\0\0\0K\1\0\0X\1\0\0:\1\0\0"..., 44}, {NULL, 0}, {"", 0}], 3) = 44
09:33:09 recvmsg(3, 0x7fff5b8eeba0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:09 recvmsg(3, 0x7fff5b8eec80, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:09 poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=9, events=POLLIN}, {fd=11, events=POLLIN|POLLOUT}, {fd=12, events=POLLIN}, {fd=18, events=POLLIN|POLLPRI}], 6, -1) = 1 ([{fd=3, revents=POLLIN}])
09:33:14 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\241 \313\4\203\0\0\4K\1\0\0X\1\0\0;\1\0\0\203\0\0\4\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
09:33:14 recvmsg(3, 0x7fff5b8eeca0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:14 poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
09:33:14 writev(3, [{"\31\0\v\0\325\0\0\0\0\0\30\0! \0\0\325\0\0\0K\1\0\0X\1\0\0;\1\0\0"..., 44}, {NULL, 0}, {"", 0}], 3) = 44
09:33:14 recvmsg(3, 0x7fff5b8eeba0, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:14 recvmsg(3, 0x7fff5b8eec80, 0)  = -1 EAGAIN (Resource temporarily unavailable)
09:33:14 poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=9, events=POLLIN}, {fd=11, events=POLLIN|POLLOUT}, {fd=12, events=POLLIN}, {fd=18, events=POLLIN|POLLPRI}], 6, -1^Cstrace: Process 5501 detached
```

i.e. polling is done every 5 seconds. But if I do the same to the wxmaxima process compiled from the git sources I see a similar (but not identicall, because there are two calls to poll() per loop) polling but done **HUNDREDS** of times per second, i.e. continuously. This is where the high CPU load is coming from.

**Comment by tigran123** [comment]
Correction to the word HUNDREDS in the previous message. I actually counted the approximate number of polling calls by multiplying the number of rows in my terminal by the number of screens and got 71*49 = 3479, so it does almost 3500 calls per second --- no wonder it keeps the CPU busy!

**Comment by tigran123** [comment]
Presumably those polls coming from git sources were supposed to occur on a similar interval (like 5 seconds in 16.02.4 stable release) but for some reason they were called without timeout or with insanely small timeout like a few microseconds so that they managed to get 3500 calls/sec. So, we need to figure out where this timeout is set and make sure it is set correctly to a sane value.

**Comment by gunterkoenigsmann** [comment]
To me what you have done looks like an but excellent example of troubleshooting:

Something keeps sending events to wxMaxima. The next step will be finding out if it is timer events that were asked for from wxMaxima or if unity polls for something.

Am 14. Oktober 2016 18:16:19 MESZ, schrieb Tigran Aivazian <notifications@github.com>:
>Presumably those polls coming from git sources were supposed to occur
>on a similar interval (like 5 seconds in 16.02.4 stable release) but
>for some reason they were called without timeout or with insanely small
>timeout like a few microseconds so that they managed to get 3500
>calls/sec. So, we need to figure out where this timeout is set and make
>sure it is set correctly to a sane value.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/781#issuecomment-253848733

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tigran123** [comment]
Thank you. I forgot to do the most obvious thing --- to look at what file the descriptors 3,4,9,11,12,18 correspond to. And then I deleted the sources, so now I've re-cloned the git tree and am compiling it. I'll try a few more things after dinner :)

**Comment by gunterkoenigsmann** [comment]
I have just created a branch named CPULoadDebug that writes debug messages to the console every time a timer expires or wxWidgets runs out of tasks.

One way to get this branch would be to cd into the wxMaxima folder that was cloned from git and to type:

git pull
git checkout CPULoadDebug

Unfortunately my computer doesn't seem to be willing to run 16.04. But I will try to run unity under 16.10.

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment]
Seems like for me unity results in a blank screen with a "terminal" button on it. But if I press this button or double-click it nothing happens.

**Comment by tigran123** [comment]
If I run wxMaxima compiled from your CPULoadDebug branch then I get a continuous stream of `wxMaxima::OnIdle` lines plus `MathCtrl::OnTimer` after every 64 instances of `MathCtrl::OnTimer` events.

**Comment by tigran123** [comment]
The comments in the 16.04.2 version of the `src/wxMaxima.cpp:wxMaxima::OnIdle(wxIdleEvent& event)` function say:

```
 // and the idle loop is called
  //  - on every mouse movement
  //  - at each key press
  //  - and at each key release
```

But this assumption is not true --- this function is called very very frequently (probably thousands of times per second).

**Comment by gunterkoenigsmann** [comment]
> The comments in the 16.04.2 version of the
> |src/wxMaxima.cpp:wxMaxima::OnIdle(wxIdleEvent& event)| function say:
> 
> |// and the idle loop is called // - on every mouse movement // - at each
> key press // - and at each key release |
> 

What should happen is:
 - During drag-and-drop we need to be informed about the mouse pointer
position. So wxMaxima requests to be informed about that event
 - It is informed about a key press
 - and since events can happen faster than they can be processed they
will all be put into a queue and will be acted upon one by one.

As soon as the queue is empty (Many events don't need much time in order
to be processed, for example the mouse move event returns immediately if
we aren't currently doing drag-and-drop) OnIdle is called and will
redraw the wxMaxima window - if MathCtrl has set the flag that tells
that a keypress or a mouse click has changed something that has changed
something that is displayed by wxMaxima, that is. There also is a logic
that determines which elements actually need to be redrawn and which don't.


> But this assumption is not true --- this function is called very very
> frequently (probably thousands of times per second).
That means that wxMaxima is flooded by events (even if we still don't
know which nature they are of) and processes them faster than they occur
(or else onIdle wouldn't be called).

Since the events occur at a high rate and therefore slow down the system
significantly they seem to be events that don't need much processing.

Am still trying to get unity working in order to see if I can reproduce
the system here.

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment]
No unity. ...but if you switch to master again:

      git checkout master
      git pull

...and recompile wxMaxima with massive help from you doing all the debugging and with a little bit of luck the problem might be resolved now.

**Comment by tigran123** [comment]
Thank you, Gunter --- yes, I confirm that the issue is now fixed. I am very glad to see that this program is in very capable hands! :)

I am using wxMaxima from git sources and it works perfectly! So, I am closing this issue now.

**Comment by gunterkoenigsmann** [comment]
Says the one that did find the bug and did all the debugging needed to resolve it to the guy who actually introduced the bug while trying to make the program faster ;-)

Actually the reason why it is possible to add improvements in such a quick succession is that Andrej writes really write beautiful code that is highly maintainable and extendible. ...and even if he seems to be currently very busy - when he addresses the issues they are resolved astonishingly quick - which was one of the reasons I chose to help him working on this program.
