### ISSUE TITLE
Pressing Ctrl-S doesn't grey out the Save button (it did in wxMaxima 16.04.2)

### ISSUE THREAD

**Issue by tigran123** [andrejv/wxmaxima#784]
In the stable version of wxMaxima (16.04.2) if you press Ctrl-S, the Save button in the toolbox is greyed out, which is very useful, because you know you don't have any unsaved changes to your wxmx file. Having a visual indicator of unsaved changes is extremely useful, i.e. you can press Ctrl-S at some point if you are happy with the work or, alternatively, do NOT press Ctrl-S if you see you have made some changes and they are not quite working yet.

But in the latest git sources this functionality is broken: neither pressing Ctrl-S nor selecting "File/Save" from the menu nor even pressing the "Save" button directly --- none of these cause the "Save" button to grey out.

**Comment by tigran123** [comment]
UPDATE: The greying out "sort of" works, but it is not seen instantly --- you have to select some other cell and then the "Save" button is greyed out.

Well, it would be nicer if it was greyed out instantly. But now I would treat is as "cosmetic" rather than "serious bug" of course :)

**Comment by tigran123** [comment]
Thank you, I have tested it and confirm that your change fixed this issue.

**Comment by tigran123** [comment]
Actually, the "reciprocal" version of this bug still exists --- namely, if you _do_ modify the file, then the "Save" button remains greyed out until you click somewhere. It would be nice if this worked in both directions, i.e. when something is modified the "Save" button instantly becomes ungreyed.

**Comment by gunterkoenigsmann** [comment]
In old versions of wxMaxima the menus were update everytime the idle loop was entered - which meant on every mouse movement. Seems like I had eliminated a few too many menu update elements. Thanks for reporting this!
