### ISSUE TITLE
wxGTK: Changing the export file filter doesn't update the file extension.

### ISSUE THREAD

**Issue by tigran123** [andrejv/wxmaxima#785]
This small (almost cosmetic) bug is present in both stable 16.04.2 and the latest git. Namely, when exporting a file, the default filename is whatever was used for the previous export (or <base>.html if no exports were ever made). But if you select a different format (e.g. .mac for maxima batch files) then the default filename remains as is (e.g. with .html) and one has to manually correct it by deleting ".html" part and typing ".mac".

It's no big deal, but it would be nice if it was automatically updated when the user selects a specific format. Otherwise, the user may press ENTER and overwrite previously exported data in a different format (e.g. first exporting to .html and then to .mac)

**Comment by gunterkoenigsmann** [comment]
That would be http://trac.wxwidgets.org/ticket/16860. The  wxWidgets guys told me that this is a design decision made by gnome: The filter really is only a filter - and it doesn't affect the file name. If you want to file a bug against gnome so this behaviour can be changed I wouldn't object.

**Comment by gunterkoenigsmann** [comment]
Since that needs to be fixed in gnome I will close this issue for wxMaxima - even if I strongly agree with you that this would be a very handy feature. Let's hope that gnome will include this feature one day.

**Comment by gunterkoenigsmann** [comment]
Since that needs to be fixed in gnome I will close this issue for wxMaxima - even if I strongly agree with you that this would be a very handy feature. Let's hope that gnome will include this feature one day.
