### ISSUE TITLE
wxMaxima deletes parentheses without user's intention

### ISSUE THREAD

**Issue by tigran123** [andrejv/wxmaxima#787]
In the Settings I have disabled the option "Match parentheses in text control". However, wxMaxima is still trying to be "helpful" by deleting the parentheses which it thinks shouldn't be there. For example, consider the following cell

```
exp(-a*H(p));
```

Now place the cursor just after "H(p)" and try to change it into "H", i.e. do the following:

1. Press Backspace once. Now the cell shows "exp(-a*H(p)". This is correct. The closing parenthesis is from the exp() function, not from H(p).

2. Now press Backspace one more time. The cell shows "exp(-a*H()". This is correct.

3. Now press Backspace again. The cell now shows "exp(-a*H". Oops, wxMaxima has mistakingly decided that after deleting the opening parenthesis of "H(" it ought to delete also the nearest closing parenthesis and so has damaged the expression by making the "exp()" function lose its closing parenthesis. Clearly a bug.

Now, if I may express my humble opinion --- I think that even if this bug is fixed (i.e. wxMaxima is made to delete only the _correct_ parenthesis, not the one belonging to some other function), the more proper and desirable behaviour is to interpret the disabled setting of "Match parentheses in text control" as meaning "DO NOT touch my parentheses altogether --- just leave them up to me to decide whether they should be here or not". I.e. if the user disabled this setting it means not only he doesn't want wxMaxima to auto-insert the parentheses but also he doesn't want it to auto-remove them. Everything should be symmetric, imho.

Also, while we are on the subject of auto-matching parentheses --- it would be very useful if I could somehow disable highlighting matching parentheses. But this is not essential, whereas the above bug is serious.

**Comment by tigran123** [comment]
Actually, thinking about it --- at the step 2. it cannot possibly know which parenthesis is the "correct" one, so it really shouldn't delete any. Maybe it shouldn't delete anything even if the user did NOT disable "Match parentheses in text control" option. What do you think?

**Comment by gunterkoenigsmann** [comment]
The error definitively lies in EditorCell::HandleOrdinaryKey. But I still don't know where...

**Comment by tigran123** [comment]
Yes, thank you, your fix works fine. I've tested it just now.
