### ISSUE TITLE
Some shortcut keys not working at Xubuntu

### ISSUE THREAD

**Issue by msat-cont** [andrejv/wxmaxima#793]
Ctrl+1, Alt-* seem to not work at wxMaxima (tested 15.08.2, 16.04.2) under Linux Xubuntu 16.04LTS. Contrary to that, e.g. Ctrl+2 work for me.

Had these issues at earlier wxMaxima versions too; web search results were telling something about wxWidgets 2.x vs. 3.x, though am not sure if it is based on that.

**Comment by gunterkoenigsmann** [comment]
On my computer installing ibus-gtk and ibus-gtk3 has resolved this issue. See http://trac.wxwidgets.org/ticket/16840 for everything that is known about this phenomenon.

**Comment by gunterkoenigsmann** [comment]
The packets you can find at https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies should work with the hotkeys as they automatically make ubuntu install the said two packets.

**Comment by msat-cont** [comment]
Using wxMaxima 16.04.2, locally compiled (with wx3.0), having ibus-gtk and ibus-gtk3 installed. Found that it has two parts:
1) my wrong: Ctrl+1 works for me now, since this was caused by an old x-input-method (xim) set in .xinputrc;
2) Alt-* still not working, not sure why; I compiled an example wxWidget application (from wx3.0-examples) and it works there (though not at wxMaxima).

Can you please confirm that when you press e.g. "Alt+c" that it opens the "Calculus" menu?, since it writes "c" instead of that for me.

**Comment by gunterkoenigsmann** [comment]
On a german keyboard it isn't possible to type Alt-*. But the Alt+c results in a "c" on my computer, too. As the menu highlights the "C" of "Calculus" on pressing Alt I am quite sure that wxWidgets actually tries to assign a hotkey to Alt-c... ...and somehow fails. Perhaps it is the following:

> Tip: under Windows, if you discover that menu shortcuts (for example, Alt-F to show the file menu) are not working, check any EVT_CHAR events you are handling in child windows. If you are not calling event.Skip() for events that you don't process in these event handlers, menu shortcuts may cease to work.

I seem to remember that we removed the Skip() from MathCtrl() since on french keyboards some characters require to press Alt... ...don't know what we'll have to do here...

**Comment by msat-cont** [comment]
Thanks, it works for me now, tested the main git branch. And apologizing for the Alt-* since I meant Alt-with_any_key but wrote it unclear.

Regarding Alt+something for the French language, I've thought that the composed letters can have set the triggering key to whatever key, like to AltGr (right-hand Alt). The Alt-hotkeys is sort-of standard, thus I guess that the French use has to have something for that too. A quick web search gives e.g. this: <a href="https://en.wikibooks.org/wiki/French/Appendices/Typing_characters">French/Appendices/Typing characters</a>.
