### ISSUE TITLE
Deleting highlighted chars leave them shown

### ISSUE THREAD

**Issue by msat-cont** [andrejv/wxmaxima#795]
When I write e.g. 123 at input cell, highlight any part (e.g. 2) and use backspace, the highlighted part is taken out of evaluations, i.e. pressing (Shift+)Enter evaluates as 13 here; though the input cell still shows 123. The showing turns to 13 (as it should be) only when I start to type anything to that input cell then.

I use current git head, running current Xubuntu 16.04LTS with wx3.0 from Ubuntu packages. This seems to be introduced as a fix of parenthesis-related issue that is present at the Ubuntu wxMaxima package (where the reported highlighting issue is not present though).

**Comment by msat-cont** [comment]
Hi, sorry it seems this does not solve the issue yet.
1) after the backspace-based deletion of highlighted string, the string remains visible until Enter is hit.
2) when doing the same thing the second time, the deleted string remains visible even after hitting Enter (i.e. alike originally reported);
3) the feature of "putting quotations/brackets around highlighted string" seems to be vanished now; just a quotation/bracket is put in (deleting the string; instead of retaining the string and putting the quotations/brackets around it).

Notice that I have the "Enter evaluates cells" option set, and it may cause some behavior variations.
The original issue on auto-deleting parenthesis was not that severe for doing too fast changes. While I may look like pressing you to do it ASAP, I actually like this wxMaxima software a lot, and prefer a slower development with more thorough testing.

**Comment by gunterkoenigsmann** [comment]
Perhaps I shouldn't have committed my speed-up enhancements this fast. Sorry for that. But it seems like I have been able to resolve these two issues now, too. Let's hope that this time I didn't again open new issues in trying to resolve problems.

**Comment by msat-cont** [comment]
partially for me: while backspace-deleting itself (1, 2 above) look fixed for me, the part 3 above (i.e. vanished "putting quotations/brackets around highlighted string") is still vanished for me.
I guess it is about file EditorCell.cpp

```
bool EditorCell::HandleOrdinaryKey(wxKeyEvent& event)

if(m_matchParens)
    {
      switch (keyCode)
      {
      case '(':
```

write e.g. 1234 in input cell, highlight e.g. 23 and press e.g. "
it results in 1"23"4 on older wxMaxima versions, but it leads to 1"4 now.

**Comment by msat-cont** [comment]
apropos, writing 1"2 in input cell and trying to evaluate it, lead to
"Refusing to send cell to maxima: Unterminated string." message previously (that is correct);

by now, wxMaxima apparently sends it to Maxima, and the pipeline gets stalled; nothing happens and all the other (newly typed) correct expressions (e.g. 123) lead just to message at the bottom/message bar/frame-border:
"N cells in evaluation queue ..................... Maxima is calculating"
with N being the current count of typed (and waiting) expressions;
I have to interrupt or restart Maxima (from the Maxima menu) then to make it work again.

**Comment by gunterkoenigsmann** [comment]
Ok... ...I have opened a new issue for the parenthesis bug (#797). Let's hope we find what causes it.

**Comment by gunterkoenigsmann** [comment]
On 25.10.2016 22:14, msat-cont wrote:
> apropos, writing 1"2 in input cell and trying to evaluate it, lead to
> "Refusing to send cell to maxima: Unterminated string." message
> previously (that is correct);
> 
> by now, wxMaxima apparently sends it to Maxima, and the pipeline gets
> stalled; nothing happens and all the other (newly typed) correct
> expressions (e.g. 123) lead just to message at the bottom/message
> bar/frame-border:
> "N cells in evaluation queue ..................... Maxima is calculating"
> with N being the current count of typed (and waiting) expressions;
> I have to interrupt or restart Maxima (from the Maxima menu) then to
> make it work again.
> 

Good findm that!

Should be resolved with my last commit.

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment]
> 
> write e.g. 1234 in input cell, highlight e.g. 23 and press e.g. "
> it results in 1"23"4 on older wxMaxima versions, but it leads to 1"4 now.
>

Hmmm... ...Tried this with "Match parenthesis" enabled and disabled in
the configuration dialogue.

On my computer it does work => There seems another setting to be
involved. But which? Or how?

**Comment by msat-cont** [comment]
I had apparently never set the "Match parenthesis" option. And the enclosing-the-highlighted string always worked for me in the Ubuntu-based wxMaxima versions.
For the githead wxMaxima version, setting that "Match parenthesis" option enables the enclosing, while unsetting that option disables the enclosing-the-highlighted string work.

After testing it now, I would prefer the enclosing-the-highlighted working without "Match parenthesis" option being set. Since you've wrote that it works for you without that option being set, it probably gets allowed by something else too, though I do not know by what now.

**Comment by gunterkoenigsmann** [comment]
Ok... ...should be resolved in the git head.
