### ISSUE TITLE
The size of parentheses is wrong (ENORMOUS)

### ISSUE THREAD

**Issue by tigran123** [andrejv/wxmaxima#799]
Try to enter Gaussian wave packet in wxMaxima:

```
f_0(x,p):=(1/(2*π*σx*σp))*exp(-((x-x0)^2/(2*σx^2)+(p-p0)^2/(2*σp^2)));
```

And then evaluate it --- the resulting parentheses are so enormous that they overwrite the above cell and even go beyond it to the one before it. But in the stable wxMaxima 16.04.2 they are just fine --- the size of all parentheses (including the inner ones) is just right.

Actually, even the parentheses in `f_0(x,p)` part are wrong --- in the latest wxMaxima they sit on the baseline (and also stick way too far up), whereas in the stable wxMaxima they correctly drop below the baseline and are symmetric.

**Comment by tigran123** [comment]
Just wanted to add that if I export the worksheet into html (using latest wxMaxima) the output is absolutely gorgeous --- the parentheses are all the right size and everything is impeccable. So, at the moment html output looks better than the original :)

**Comment by gunterkoenigsmann** [comment]
Give me an hour of time. I think I know what I did wrong. What I tried to archive was to prevent that the lower half of parenthesis sometimes overlaps the upper one.

Kind regards,

  Gunter.

**Comment by gunterkoenigsmann** [comment]
Ok... ...then I have to apologize to you deeply... ...but at least can tell you that I have resolved the issue again.

**Comment by tigran123** [comment]
Thank you, your fix works perfectly, closing the issue now.
