### ISSUE TITLE
Maxima help with ?? is broken

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#802]
`?? solve`

should produce a list of functions which contain the word `solve` and ask the user for which function to display the documentation. The question is currently not handled correctly.

**Comment by gunterkoenigsmann** [comment]
Not again!

...but on my computer the question seems to be handled right:

 - The "Return to evaluation" Sun is replaced by a "User interaction needed" triangle
 - If I click into the cell with the question the cursor is put after the ":"
 - and if I input a number I get the help text article.

...that means: With a fresh maxima install maxima on the first try to do a ?? maxima did once output an endless stream of non-unicode chars. No idea what that was, though, as I cannot reproduce it any more. Don't know if that is the problem that occurred on your computer.


![solve](https://cloud.githubusercontent.com/assets/5041537/20055856/804fd170-a4e3-11e6-913b-e73984201d84.png)

**Comment by andrejv** [comment]
You are right, in the latest git help works as expected. I was using some older version I guess.

**Comment by gunterkoenigsmann** [comment]
No problem! This particular piece of code has caused more git revisions until now and you made me find another error in the code.
