### ISSUE TITLE
label strings not parseable by pdflatex (version 16.04.2)

### ISSUE THREAD

**Issue by antiskid56** [andrejv/wxmaxima#803]
Hi,

I have verified this issue on Windows and on Ubuntu with version 16.04.2.

If you do a Maxima assignment to a variable with an underscore at the end, say

x_1: y;

The pdflatex export will create a label string with

\label{x\\_ 1}

Note the space as well as the backslash escaped underscore in the label. This does not parse correctly by pdflatex, which is fussy about underscores in labels. The exported tex file will not compile.

Preceding each such \label{} statement is a similar \tag{} statement which does compile without issue. I do wonder, however, whether the extra space in the tag, following the underscore, is what is intended.

I'm not sure I understand exactly what the rules for characters in labels are, but underscores and spaces are not generally recommended for use in latex labels. I have been able to get the pdflatex file to compile by editing the label to look like

\label{x1}

and there are probably other reasonable approaches for fixing the issue in code.

I think the tag{} statement probably needs some fixing too, at least as regards the extra space character. Possibly a better tag would look like

\tag{${x}_{1}$}

because latex math is legal in a tag, but not legal in a label.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for this report!

For the next version of wxMaxima I have removed the \label command from the TeX export as it only seemed to cause trouble. Hope, this was the right decision...
