### ISSUE TITLE
plot fails with small x-range (1E-14) due to rounding 

### ISSUE THREAD

**Issue by Ukkoo** [andrejv/wxmaxima#805]
Following simple line fails to create a plottable file in gnuplot with wxMaxima 16.04.02 and 15.08.1+git, Windows7.:
`plot2d(t,[t,0,1E-14]);`
Obvious reason are line 8 and 11 in the maxout.gnuplot file, which both define a zero x-range for plotting:
```
set xrange [0.00000000 : 0.00000000]
...
plot [0.00000000 : 0.00000000] '-' notitle with lines lt rgb "#0000ff"
```
Maxima seems to write rounded numbers (zero instead of 1E-14), which is not sufficient here.

Same problem in version 16.04.02:

`Message from maxima's stderr stream: "C:/Users/Hi/maxout3384.gnuplot", line 128: Can't plot with an empty x range!`

I even checked a version in linux mint 17.1, which did not show this error.

Sorry, in case I should be wrong in this group, just let me know.

-------------------------------------------------------------
wxMaxima version: 16.4.2
Maxima version: 5.38.1_5_gdf93b7b_dirty
Maxima build date: 2016-05-13 22:33:49
Host type: i686-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.3])
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
As you already have guessed draw and plot are provided by the maxima project (https://maxima.sf.net). If you file a bug report there or write to the maxima-discuss mailing list perhaps they will find out about the reason of this problem.

But I can at least try to provide you with a workaround:

    wxdraw2d(
        explicit(
            at(
                sin(t*1e12),
                t=ps*1e-12
            ),
            ps,1,100
        ),
        xlabel="t [ps]",ylabel="U",grid=true
    );  

Kind regards,

   Gunter.

**Comment by ReneSci** [comment]
Hi 

Another workaround:

set_draw_defaults(
dimensions    = [1500, 800],
user_preamble  = ["set xtics out", "set mxtics 10", "set ytics out", "set font 'Areal, 8 '", "set zero 10^-100", "set format y '%0.3se%03S'", "unset clip", "set autoscale y",  "set autoscale x" ],
   font           = "Times",
 font_size      = 12,
     title          = PlotTitle,
xlabel         = PlotXlabel,
ylabel         = PlotYlabel,
    grid           = true,
    palette        = gray,
 point_type    = 0,
   point_size    = 1,
points_joined = true);

Kind regards
Rene'

**Comment by gunterkoenigsmann** [comment]
Forwarded this ticket to the maxima-discuss mailing list along with a proposed solution. Let's see what the real mathematicians will answer...

**Comment by gunterkoenigsmann** [comment]
Ok... ...they approved your solution => Maxima versions later than commit e2a6f507f7059488d9e212e224e584f9489139c1 no more have this issue. Thanks a lot for finding the bug and the fix for it!
