### ISSUE TITLE
Unnecessary "Do you want to save the changes ..." dialog when loading a package

### ISSUE THREAD

**Issue by TomasRiker** [andrejv/wxmaxima#806]
Steps to reproduce:

1. Enter something into wxMaxima so that the document is marked as "unsaved".
2. Click **File / Load Package** and load a `.mac` or `.lisp` file.
3. wxMaxima will ask "Do you want to save the changes you made (...)?".

The dialog implies that the content will be lost when you answer "Don't save". But this is not the case when loading a package file, therefore the question is unnecessary.

**Comment by gunterkoenigsmann** [comment]
Here i need more info since on my system I cannot reproduce this problem.

What is the outcome of

      wxbuild_info();

...and are there any other steps required?

**Comment by TomasRiker** [comment]
Checking it again, on a different computer. For some reason, I can't reproduce it using **File / Load Package** now, but it still happens when loading a package I previously loaded using **File / Open Recent**.

![image](https://cloud.githubusercontent.com/assets/295205/20299091/991ba698-ab19-11e6-8b7f-0a6dd904441e.png)
