### ISSUE TITLE
Error printed by "parse_string" confuses wxMaxima

### ISSUE THREAD

**Issue by TomasRiker** [andrejv/wxmaxima#808]
Evaluating `errcatch(parse_string("x+"))` confuses wxMaxima (latest nightly build) and messes up the formatting. The result, which is `[]`, is not printed.

![image](https://cloud.githubusercontent.com/assets/295205/20420186/2e83f232-ad5c-11e6-87d0-6aa1fc1170b9.png)

**Comment by gunterkoenigsmann** [comment]
This seems to be caused by a bug in wxMaxima that is triggered by a bug in wxMaxima => Thanks for finding two bugs at once ;-)

(I just have reported the maxima bug to the maxima mailing list already so the maxima team can determine if I interpreted the problem right.)
