### ISSUE TITLE
Re-evaluation of all cells (Ctrl+R) on Windows is much slower in recent versions of wxMaxima

### ISSUE THREAD

**Issue by dilijev** [andrejv/wxmaxima#809]
I'm not sure when this started since I haven't used this feature in a couple of years but it seems that when Ctrl+R is given, it takes a LONG time to evaluate all of the cells in whole document again.

It seems that for each cell, we are now doing something like opening a new connection to Maxima and evaluating that cell. Previously, re-evaluating a document with a couple dozen cells was nearly instantaneous, and now it takes at least half a second per cell on a very fast machine.

**Comment by gunterkoenigsmann** [comment]
Your diagnosis is correct: if we need to restart evaluation we now start a new Maxima progress for that: we got many complaints that re-evaluation tended to provide different results to the first one. In compensation I've spent much time on making the rest of wxMaxima faster...
If you want I'll add an option that allows to revert wxMaxima to the old behavior: wasn't sure if it would be just another option filling the preferences dialogue or if it would be useful.

**Comment by dilijev** [comment]
Considering that it's noticeably slow, an option would be helpful.

Though, it sounds like there's either a problem with the way those users are designing those documents (implicitly relying on variables set in the previous execution on the next execution or something) -- otherwise there's a bug somewhere because maxima should give the right results all the time, except for the current state of things.

Seems like the default behavior should *not* be to compensate for unexpected evaluations due to state and simply provide a workaround.

Restarting maxima when doing a new evaluation would make sense except that we're making a fresh connection to maxima for every evaluation? That's definitely excessive.

Another possible work-around for that issue would be to issue commands that reset things like variable assignments (I believe `killall;` does this).

**Comment by dilijev** [comment]
Thanks @gunterkoenigsmann!

**Comment by gunterkoenigsmann** [comment]
You are welcome!
