### ISSUE TITLE
Error in saving and opening files when the folder has Chinese name

### ISSUE THREAD

**Issue by zohooo** [andrejv/wxmaxima#810]
I have installed `maxima-sbcl-5.38.1-win64.exe` in my Chinese Windows 7. Then I tried to save `untitled.wxmx` to folder with Chinese name, e.g., 中文, I got the following error

    Maxima encountered a Lisp error:
     NIL c-string encoding error: the character with code 20013 cannot be encoded.
    Automatically continuing.
    To enable the Lisp debugger set *debugger-hook* to nil. 

When I tried to open the file from that folder again, I got the same error as the above.

**Comment by zohooo** [comment]
I have been using Maxima 5.31.2 with wxMaxima 13.04.2 for several years, and with this version I could open files from and save files to Chinese folders without any error messege.

**Comment by gunterkoenigsmann** [comment]
wxMaxima >13.04 by default tries to change maxima's path to the path of the current file so commands like load() and read_matrix() operate in the directory the .wxmx file lies on. Unfortunately most lisps seem not to like unicode chars too much - so they will output an error message on encountering them. The relevant code is as follows:


    (defun wx-cd (dir)
      (when $wxchangedir
        (let ((dir (cond ((pathnamep dir) dir)
                         ((stringp dir)
                          (make-pathname :directory (pathname-directory dir)
    				     :host (pathname-host dir)
                                         :device (pathname-device dir)))
                         (t (error "cd(dir): dir must be a string or pathname.")))))
           #+allegro (excl:chdir dir)
           #+clisp (ext:cd dir)
           #+cmu (setf (ext:default-directory) dir)
           #+cormanlisp (ccl:set-current-directory dir)
           #+gcl (si:chdir dir)
           #+lispworks (hcl:change-directory dir)
           #+lucid (lcl:working-directory dir)
           #+sbcl (sb-posix:chdir dir)
           #+sbcl (setf *default-pathname-defaults* (sb-ext:native-pathname (format nil "~A~A" (sb-posix:getcwd) "/")))
           #+ccl (ccl:cwd dir)
           #+ecl (si:chdir dir)
    
           (namestring dir))))

wxMaxima's configuration dialog contains a setting that allows to disable the code that changes maxima's pwd to the one of the .wxmx file which gets rid of the error message (but unfortunately of the feature, as well).

**Comment by zohooo** [comment]
Since the new feature causes some regressions, what about disabling it by default?

**Comment by gunterkoenigsmann** [comment]
Let's see if the sbcl programmers have an idea on how to resolve this problem: https://sourceforge.net/p/sbcl/mailman/message/35514857/

**Comment by gunterkoenigsmann** [comment]
Have forwarded this problem to the maxima-discuss mailing list. Perhaps they have ideas on how to really resolve it.

**Comment by gunterkoenigsmann** [comment]
For clisp the next nightly build at https://wolfgang.dautermann.at/maxima/nightlybuild/ will solve the problem (see Commit a7f03e2eb9b64cb85064ec57b206f5cf26f6c2e0)
