### ISSUE TITLE
*** - No more room for LISP objects*** - No more room for LISP objects

### ISSUE THREAD

**Issue by DrNo67** [andrejv/wxmaxima#813]
with this code:

/*condiciones inciales de partida*/
iceq_ant:0$
Vout_ant:0$ 

for i:1 step 1 thru n_samples do
(

    Vin:x[i],
    iceq: 2 * Vout_ant - iceq_ant,    
    Vout:1/(g+1)*(g*Vin+iceq),       
    iceq_ant:iceq,
    Vout_ant:Vout,     /*<--------error here!!!!!!!!!!!!!!!!!!!!!!!!!!*/

    out:append(out,[Vout])

)$

error: *** - No more room for LISP objects*** - 

what is happen within code?

**Comment by gunterkoenigsmann** [comment]
The program you are using is divided into two parts:
 - wxMaxima that displays the worksheet and
 - maxima that does do the actual mathematics and that is written in lisp.

This time it is maxima that ran out of memory so with a bit of luck the guys at https://maxima.sourceforge.net can help. What they will need is 
  - the output of 
     wxbuild_info()
 - how big is n_samples?
 - is x a list? Is x an undeclared array?
 - and does x consist of floating-point numbers (1.4 or 3.4) or of exact numbers (1, 10/47 or sqrt(33)*%pi)?

Possible reasons for an out-of-memory ar
 - something isn't as memory-efficient as it could be. Undeclared arrays aren't too memory-efficient
 - an algorithm created numbers that were longer than your computer's memory: floating-point numbers (1.3 or 43.6e5) are always only 32 or 64 bits long, but keeping them this short will introduce a little bit of rounding now or then. Exact numbrs (18233325/23432423+23423234/2423432) will never automatically be rounded by maxima. This might mean, though, that both the denominator and the numerator of a fraction can grow and in the end of a long algorithm might be millions of digits long using up many megabytes of space.
 - or you saved enough lisp objects (variables or array entries) that the amount of available memory was filled up.

If you replace

      Vin:x[i]

by 
     
     Vin:float(x[i])

does that help?

**Comment by DrNo67** [comment]
yes "float()" !
that is the answer.

x is declared so x:[]$  
Is it better to assign values x[] with float?
thanks.

**Comment by gunterkoenigsmann** [comment]
This is a complicated question: Numbers that contain a "." or that are marked as floating-point numbers by float() are guaranteed to use only a limited amount of memory. Your processor contains dedicated hardware that is astonishingly fast in handling floating-point numbers and most mathematics programs use only floating-point numbers.

The disadvantage of Floating-point numbers is that they can introduce small errors into the calculation:

     (%i14)	1+1e-14;
     	%-1;
     	%-1e-14;
     (%o12)	1.00000000000001
     (%o13)	9.992007221626409*10^-15
     (%o14)	-7.992778373591124*10^-18

Even a seemingly simple "0.1" cannot be expressed in binary floats like the computer would use them without adding some rounding error:

     (%i15)	rationalize(0.1);
     (%o15)	3602879701896397/36028797018963968

Normally this error is small enough so it doesn't matter, so for long lists using floating-point numbers is better. But see https://en.wikipedia.org/wiki/Wilkinson's_polynomial.

Also a discrete fourier transform might introduce surprisingly big errors with floating-point numbers while a fft will in most cases yield much accurate results.
