### ISSUE TITLE
wxMaxima: small graphs when printing to PDF

### ISSUE THREAD

**Issue by robert-dodier** [andrejv/wxmaxima#816]
Migrating this item from the Maxima bug tracker; copied verbatim from https://sourceforge.net/p/maxima/bugs/3252/ by Miroslav Siouf; see also the files attached to the Maxima bug tracker item:

If a file containing graphs created with wxplot2d or wxplot3d
is printed to PDF (using PDFCreator under Windows7),
the output PDF contains very small graphs.

See the attached file.

Version of my programs:

Windows 7, 64-bit; PDFCreator 2.4

wxMaxima version: 16.4.2
Maxima version: 5.38.1
Maxima build date: 2016-06-12 17:13:34
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

**Comment by gunterkoenigsmann** [comment]
Thanks for forwarding this issue: As I try to never use the printer the printing code tends to be tested to a lesser depth than the rest of the program.

The issue should be fixed in the current nighly build of wxMaxima. If it isn't please complain!
