### ISSUE TITLE
wxMaxima: errors when printing to PDF

### ISSUE THREAD

**Issue by mirekslouf** [andrejv/wxmaxima#817]
wxMaxima, comments and new problems connected with issues #816 and #815
(both issues are connected with printing to PDF
https://github.com/andrejv/wxmaxima/issues/816
https://github.com/andrejv/wxmaxima/issues/815

Robert Dodier repaired the bugs overnight (thank you!),
some problems were solved, some other remain,
and new small bugs were found.
See the description below.

(Versions of my programs are at the end of this file)

What has been done?

1) Installed recent version: maxima-sbcl-5.38.1-win64.exe
2) Downloaded NightlyBuild from http://andrejv.github.io/wxmaxima/develop.html

3) Replacement of [wxmaxima.exe] in WXMAXIMA subdirectory => does not run

4) Replacement of [wxmaxima + dll's] => works, but does not find all files (icons?)

- a) PDF output, size of graphs: Ok 
- b) PDF output, page breaks: original page breaks still present (pages 3,4,5,6)
- c) WXMX output: Ok
- d) WXM output: wrong; if I save as WXM, I can see only blank lines

5) Replacement of [wxmaxima + dll's + icons/subdiretory ART] => works

- a) the same as above in item (4a)
- b) the same as above in item (4b)
- c) the same as above in item (4c)
- d) the same as above in item (4d)

6) Please, see the test files:

- (WXMX file, with TXT extension) [3b_eln_v_krychli.wxmx.txt](https://github.com/andrejv/wxmaxima/files/616566/3b_eln_v_krychli.wxmx.txt)
- (PDF output from the WXMX file above) [3b_eln_v_krychli.wxmx.pdf](https://github.com/andrejv/wxmaxima/files/616567/3b_eln_v_krychli.wxmx.pdf)

Summary:

1) The problem with size of the graphs was resolved.
2) The problem with [page breaks] persists.
3) New bug in the current version:
   Saving to WXM file looses the data (after re-opening the WXM file is empty).
4) New bug: the first input line shows just (%i3) in both WXMX and PDF.
   i.e. the (%i1) and (%i2) prompts are missing.
   
Version of my programs:

Windows 7, 64-bit; PDFCreator 2.4

wxMaxima version: 16.4.2Maxima version: 5.38.1
Maxima build date: 2016-06-12 17:13:34
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

With best regards & thanks for your help, Mirek Slouf

**Comment by gunterkoenigsmann** [comment]
I still don't fully understand the .wxm bug. Hope it didn't cost you valuable work...
...but at least I can claim that the print problem you have reported will be fixed in the next nightly build. Thanks a lot for reporting it!

**Comment by mirekslouf** [comment]
1) Nightly build downloaded, wxmaxima.exe replaced, everything seems to work.
2) The two main issues (size of the images + page breaks) are resolved.
3) Also WXM files seem to be saved and re-opened correctly.
4) I found some other minor issues; these I will report later.

Thank you once again for your swift help. Best regards, Mirek Slouf

**Comment by gunterkoenigsmann** [comment]
Testers are always welcome: It is much better to find bugs before the a takes place than afterwards and - this time the wxm bug you found was actually 3 important bugs.

---

As you mention several issues: It is easier to handle them if they are in separate tickets. 

---

Tomorrow's nightly build will contain an attempt to fix how big parenthesis look like. I am quite sure that I've found the issue this time. But as I don't have access to a windows computer with a compiler on it please keep a backup of wxMaxima.exe handy before attempting to try tomorrow's build. The last time I thought to have resolved this issue the resulting parenthesis were monstrously large.

Kind regards,
Gunter.
