### ISSUE TITLE
wxMaxima: minor formatting errors

### ISSUE THREAD

**Issue by mirekslouf** [andrejv/wxmaxima#819]
I found two very minor errors in wxMaxima output. The errors are visible both in WXMX files and in the files printed to PDF. Both errors are shown in the image below:

![maxima_formatting_errors](https://cloud.githubusercontent.com/assets/22853864/20812234/1ac1c764-b811-11e6-8120-26872e1bfc50.png)

Thank you in advance for your help. With best regards, Mirek
 
Version of my programs:

Windows 7 64-bit, PDFCreator 2.4

wxMaxima version: 16.4.2Maxima version: 5.38.1
Maxima build date: 2016-06-12 17:13:34
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

wxMaxima = nightly build from 2016-11-30

**Comment by gunterkoenigsmann** [comment]
For the first issue: The problem with this is where to put the input labels for commands like the following:

      x:1;y:2;z:3;

---

Parenthesis are quite a beast on windows. But I still fail to find the reason why. The error definitively lies in ParenCell.cpp. Another parenthesis problem is that big parenthesis on certain zoom factors tend to be drawn with overlapping upper and lower half. Unfortunately I don't have access to a windows computer containing a compiler so I have no real machine to debug the issue on.

**Comment by mirekslouf** [comment]
Thank you for your fast reply.

ad 1) Would it be possible, if the numbering of multiple lines was like in the previous versions of wxMaxima?
- Now:   **(%i3) x:1; y:2; z:3;**
- In the past:   **(%i1) x:1; y:2; z:3;**

In my opinion, the previous version was more logical: ONE input line (%i1) produces three outputs (%o1, %o2, %o3). The current version looks strange, as if the first two input lines were missing.

Nevertheless, I admit that this is just a minor "easthetic" problem & I thank you once again for swift repair of all previous issues concerning PDF formatting. I use wxMaxima (among other things) for teaching students and if they see how fast the bugs are repaired, it is a great wxMaxima promo.

**Comment by gunterkoenigsmann** [comment]
For the parenthesis I perhaps have an idea on how to resolve this: By now all fonts we use contain unicode codepoints for 
 - normal-sized parenthesis
 - parenthesis that are double the normal text size
 - and extensions that make the parenthesis n times the text size.
Perhaps we should switch to them... ...but this time I will need a few week's time to rewrite the parenthesis code and test it extensively as this is a rather big change.

For the input labels I am unsure what to do: It feels logical to show the input label of the first command in a cell. But I rather liked the progress indicator we got for free by showing the input label of the cell being currently evaluated => keeping wxMaxima as it is feels right, but changing it to show the old behaviour feels right, too...

**Comment by gunterkoenigsmann** [comment]
Ok... ...the parenthesis part went easier than I thought and should be resolved in commit dd8aac37c44dc7cc1781d884499ea26c71837cb0.

**Comment by gunterkoenigsmann** [comment]
As the release is approaching I have temporarily reverted my parenthesis fixes as they haven't been tested enough for making it into a release and as my code failed spectacularily on windows.

Will keep trying over the next few weeks to find out how to make wxMaxima find out how the parenthesis are drawn using the windows font: 

It contains parts of big parenthesis that in theory could be assembled easily to form parenthesis. But these parts extend way beyond the baseline of the parenthesis characters and don't even remotely reach the character's top. Don't know what the canonical way is to determine their actual dimensions or if there is no such way and the dimensions are fixed by some standard.

**Comment by gunterkoenigsmann** [comment]
Ok... ...the parenthesis work fine by now => will be resolved in the upcoming release.
