### ISSUE TITLE
Can not select and copy the output/result anymore

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#831]
(%i1)	wxbuild_info()$
wxMaxima version: 16.12.0
	Maxima version: 5.39.0_2_g5a49f11_dirty
	Maxima build date: 2016-12-11 23:20:41
	Host type: i686-w64-mingw32
	System type: 
	gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
	SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
	libsigsegv 2.8
	libiconv 1.13
	libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
	Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on maxima [10.0.3.1])

**Comment by gunterkoenigsmann** [comment]
That was my fault.

In the current nightly build (http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly) it is corrected again - and the bugfix is marked for inclusion in the next minor release.

Thanks for reporting it!
   Gunter.

**Comment by ReneSci** [comment]
Thanks :-)

Merry Christmas and A Happy New Year
/Rene'


2016-12-22 13:07 GMT+01:00 Gunter Königsman <notifications@github.com>:

**Comment by ReneSci** [comment]
Now it works again.

Thanks :-)
Rene'

**Comment by segesdo** [comment]
Copy & paste for outputs in wxMaxima 16.12.0 in Linux does not work. Any solution?. Thanks!.

**Comment by endolith** [comment]
Same problem in maxima-clisp-sbcl-5.41.0a-win64

**Comment by gunterkoenigsmann** [comment]
Closing this bug as the upcoming version resolves this problem.
