### ISSUE TITLE
xml display not working on homebrew version on mac

### ISSUE THREAD

**Issue by neuwirthe** [andrejv/wxmaxima#833]
The attached image show that the default configuration of wxMaxima on a Mac
(installed with homebrew) has an issue with didplaying xml
`set_display('ascii)`
solves the problem.
Which startup file do I need and what exactly should I put in there
to have ascii display as the default.

And how can xml display made work?

![2017-01-05_15-19-20](https://cloud.githubusercontent.com/assets/157619/21683633/6950f030-d35a-11e6-8685-f7f66e2274c8.png)

**Comment by gunterkoenigsmann** [comment]
This is most likely a font issue. I seem to remember that changing fonts in the config dialogue has resolved a similar case. If it doesn't: Could it be that one of the text colors is set to "white"?

**Comment by neuwirthe** [comment]
This is a font issue!
In fact, clicking on any of the two Choose font buttons in the Fonts part of the dialog
will crash wxMaxima, he checkmark next diUse jsMath fonts cannot be changed,
and the Choose font button in the Styles part of the dialog simply does not work.

So I will use the native OSX version, but that one is a few version numbers back.

![2017-01-06_12-37-49](https://cloud.githubusercontent.com/assets/157619/21716798/27f1efc8-d40d-11e6-81a8-6a7e30b92e86.png)

**Comment by neuwirthe** [comment]
Just checked, there is exactly the same problem with the "native " wxMaxima binary from http://andrejv.github.io/wxmaxima/download.html

**Comment by gunterkoenigsmann** [comment]
I currently have an internet connection that is payed per kilobyte so this time I cannot search for it  But for this crash you will find a workaround in one of the closed tickets. I seem to remember that you have to remove the hidden file named .wxmaxima in your user's folder to ship around a bug in OS X. wxMaxima will create a new file in the next run.

**Comment by neuwirthe** [comment]
It turns out it was a case of missing jsMath fonts. Thery were mising on one of my machines. After installing them, things worked fine ;-)
One more point:
To make the `plot2d` command work, I had to install Gnuplot in the native binary (from the binary install of maxima). gnuplot + aquaterm from homebrow dod not show graphics in a separate window. This is, however, not needed for `wxplot2d`.

**Comment by andrejv** [comment]
Does wxMaxima still crash on "Choose font" button click after installing jsMath fonts?

**Comment by neuwirthe** [comment]
I still get the crash. And now I installed on a third machine. IMHO I think I installed it the same way (including jsMath fonts). But on that machine, the old problem (xml display not working) pops up again.

**Comment by neuwirthe** [comment]
Can you tell me where wxmaxima stores the info about the fonts it uses? Then I can compare on the working and the nonworking machines to locate the problem.

**Comment by andrejv** [comment]
Preferences are stored in `~/Library/Preferences/wxMaxima Preferences`.

Just for the record, the font dialog is displayed properly with the development version and wxWidgets 3.1.1.

**Comment by neuwirthe** [comment]
I noticed something in the preferences files.
On the machine where things work, there are entries
```
[Style/Variable]
color=rgb(0, 0, 0)
[Style/Function]
color=rgb(0, 0, 0)
```
On the machine where things do not work,
the entries are
`color=rgba(0, 0, 0, 0.000)`
I tried to change the entries, but it seems this file is written with the defaul values
each time wxMaxima is started.

**Comment by neuwirthe** [comment]
Problem solved! 
Using the preferences and manually setting opacity to 100% makes things visible. 
It is unclear to me why sometimes opacity is set to 0% by default.
