### ISSUE TITLE
Spanish Update

### ISSUE THREAD

**Issue by cyphra** [andrejv/wxmaxima#835]
[wxmaxima-16_04-es.po.zip](https://github.com/andrejv/wxmaxima/files/695503/wxmaxima-16_04-es.po.zip)

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!

I have added the .po file to the wxMaxima git master - and instructed the translation tool to add all the new strings that will part of the next major release to the file. The result was the following: [es.po.TXT](https://github.com/andrejv/wxmaxima/files/700809/es.po.TXT)

Kind regards,
Gunter.
