### ISSUE TITLE
cannot select and copy outputs wxmaxima 16.12.0

### ISSUE THREAD

**Issue by segesdo** [andrejv/wxmaxima#840]
Hi, I recently update to wxmaxima 16.12.0 in Ubuntu.
Now I cannot copy and edit the outputs. Does anyone else have this problem??.

Any solution would be highly appreciated!.
Thanks.

**Comment by gunterkoenigsmann** [comment]
Is this version already in Ubuntu? If yes I know which line to patch (it was me who introduced this error) but not how to make Ubuntu do so. If not compiling the git master will help until we make the next release - and I have to apologize to have caused that.

**Comment by segesdo** [comment]
Thanks for the prompt reply. 
Yes. I'm afraid the version is already in Ubuntu. When do you think you will have the next release?, If too late, then I would ask you the line to patch. Although I'm not sure if I will know how to change the line (I have never done that before).

**Comment by gunterkoenigsmann** [comment]
Then https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies might be useful for you: Somewhere on this page you can download a nightly build in which this error (along others) has been corrected.

**Comment by gunterkoenigsmann** [comment]
Andrej has just released a corrected wxMaxima version. How long it will need in order to enter the Ubuntu repositories I don't know, though.
