### ISSUE TITLE
wxmaxima 16.12.2: cannot select input

### ISSUE THREAD

**Issue by bigdevs** [andrejv/wxmaxima#846]
I have a wxmaxima file with a big first cell. When i try to select an input in the last cell by mouse,  the whole worksheet scrolls up to the top. It's almost impossible to work this way. Please unpack the attached .wxm and try to select the whole string in the last cell  by mouse. If you move mouse away from the string while selecting(up or down), the whole worksheet jumps up.
[untitled.wxm.zip](https://github.com/andrejv/wxmaxima/files/747764/untitled.wxm.zip)

**Comment by gunterkoenigsmann** [comment]
This is resolved in the current wxMaxima release.
