### ISSUE TITLE
Wrong language in GUI under Win

### ISSUE THREAD

**Issue by Hale812** [andrejv/wxmaxima#847]
Windows 7 x64. The location is Japan, BUT the "Display language" is defined as English.
Upon installing, GUI incorrectly takes UI language as Japanese. There is no way to change language for people not familiar with Japanese (because even "English" string is translated to "英語")

When changing the language to English, some elements stay in wrong language.
![bug](https://cloud.githubusercontent.com/assets/25519954/22577392/bedff166-ea04-11e6-92b7-056a73c037f2.PNG)

**Comment by gunterkoenigsmann** [comment]
Wolfgang and Andrej have found the problem in the meantime. It will be fixed in the next release.

**Comment by Hale812** [comment]
It is still not fixed

**Comment by gunterkoenigsmann** [comment]
That's completely weird: Some elements are provided by wxWidgets - and they should be in the correct language now. But the element your screenshot shows is provided by wxMaxima which should use the language selected in the config dialogue. ...and setting the display and the system language independently works fine for me...

**Comment by ciampix** [comment]
Under Linux (Ubuntu 16.04 64 wxmaxima from master github repo) some windows titles are always in English, no matter what the configuration is. For example: tip of the day or mathematical symbols...

**Comment by Hale812** [comment]
Gunter. In my case the wxMaxima is configured to English. And I don't know how to configure wxWidgets, or Maxima environment core locales.

I guess, it is again the problem of wrong understanding of windows conventions by API developers.
Even big developers like Intel, for instance, take the easiest to get parameter without thinking much.
In Windows, there are 4 languages:
1)Location, changed freely when you travel, without reboot.
2)Display language (Defined by installation for home/pro versions, or UI for Ultimate/server)
3)Core Language(nonunicode), defined on boot.
4)Format (currency, and calendar symbols, decimal symbols, other regional little things), changed freely when you travel, without reboot.
*)less obvious, but important: language of core libraries during installation - not a constant, but can be read from system .dll-s.
The correct answer is **2** ! The display language is how the things SHOULD be displayed (unless set different manually).
But most code monkeys never traveling abroad guess, that all are equal and take any option randomly.
That is very common in Japan. It became less common in software from US, but still happen.

**Comment by ciampix** [comment]
I do not know what you have done but now my (git master branch) wxmaxima works (Ubuntu 16.04-64)!!! Thanks!
Just another problem that probably is related but something completely different: I still see the English version of the "Tip of the day"...I see in English the dialog window "Tip of the day", inside the dialog "Did you know...", the option "Show tips at startup" and one (not all!!) buttons: "Next tip" ... the "Close" button _is_ (the only) translated thing ... weird...

**Comment by gunterkoenigsmann** [comment]
I have never found out how the Tip of the Day thingy works. Seems it currently doesn't. 
But the rest of your message is good news. Even if I am convinced that I didn't change anything in this part of wxMaxima after the failed attempt...

What I was expecting that text was enclosed in a `wxT()` macro (which allows to use unicode characters but doesn't translate) instead of a `_()` macro (which makes the string translatable).

**Comment by gunterkoenigsmann** [comment]
Weird:
- The tooltip window is created by wxWidgets so we don't have much influence on anything except of the text of the actual tooltip.
 - in the wxWidgets source code all pieces of the window text are enclosed in an _() macro which means that they turn up in the .po files and use the translations the .po files provide.
 - the .po files actually provide translations for the given pieces of text
 - the .mo files wxWidgets and the maxima installer are shipped with contain these translations.

...but on my system still only the dialogue contents is translated, not the rest of it.

**Comment by Hale812** [comment]
just updated to 17.10.1, uninstalled the older version before that. All the same...
![image](https://user-images.githubusercontent.com/25519954/37132583-b5ec5336-22d1-11e8-8895-6ccfd9a19d90.png)

**Comment by gunterkoenigsmann** [comment]
Wow... ...that seems to be an error in wxAUI which is provided by wxWidgets (http://wxwidgets.org). Let's see if I can tell wxAUI to replace pane titles manually.

Thanks for the screenshot - which was very helpful in locating the problem.

**Comment by gunterkoenigsmann** [comment]
Ok... ...found the reason: The name of each pane is saved in the registry along with the info where it is placed. On re-opening the program the panes are created with their new names - and then the info needed to restore them is loaded (along with the name they originally used). Will manually assign the panes the correct name after loading their position.

**Comment by gunterkoenigsmann** [comment]
Tomorrow's nightly build at https://wolfgang.dautermann.at/maxima/nightlybuild/ will use the correct pane titles.

**Comment by ciampix** [comment]
I do not know if this is related but the help dialog has similar issues... see screenshot
![wxmaxima-not-i18n](https://user-images.githubusercontent.com/372887/37137062-745297c8-22a4-11e8-9675-45ecb2256a1b.png)

**Comment by gunterkoenigsmann** [comment]
Ok... ...I am convinced both these problems should be resolved by now.
