### ISSUE TITLE
Faulty conversions in printing and PDF

### ISSUE THREAD

**Issue by herhin2015** [andrejv/wxmaxima#852]
Hello
Im using wxmaxima since many years for calculations in mechanics and machinery engineering. And until the version 15.04. it was a nearly perfect tool for technicians. Since this version, wxmaxima becomes more and more faulty. The biggest problem in daily work now, is the fault in printing and converting a worksheet to PDF Files. I tried many different platforms, but there's always the same result. Graphics and some signs are not displayed correctly! This is very bad for further using and spreading wxmaxima! You can not warm other fellows for maxima with this shown bugs!

My request to the developers is not to bring more new features but to increase the stability and quality of wxmaxima. Last i have a second question: why is there an OS-X version available but it does also not really work (not only one known friend got wxmaxima running on a mac)?

**Comment by gunterkoenigsmann** [comment]
I have to admit that I almost never use maxima's printing functionality - and that as I have no windows computer neither own a Mac I can only test if printing works on my own system. But I will correct all bugs that are reported - if I manage to find out what causes them and even if any change means the risk of breaking something in other places => Any help to find bugs is deeply appreciated.

What I would beg you would be to create a separate bug ticket for every bug you find: Else there is a probability that things get lost. ...and for the missing characters I need a minimal example in some way: Here I am completely lost on what causes them - as I am  in the inconsistent font sizes between code and output during printing, currently.

Thanks a lot, 
and kind regards,
Gunter.

**Comment by gunterkoenigsmann** [comment]
If you are on windows in less than 24 hours http://wolfgang.dautermann.at/maxima/nightlybuild/ will fix most of your printing bugs, if not at all. If you are using windows the same will be true for https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies/+packages. If any bug remains I would beg you to file a new bug with a minimal example attached.

For Mac OS my guess is that we would first need a developer who owns a recent mac and who is able to build packages: Mac OS tends to have compatibility problems if software isn't compiled with exactly the Mac OS version the user uses. But as I can be wrong in this aspect I would ask you to issue a separate bug report for the missing Mac OS build so this issue isn't lost.
