### ISSUE TITLE
Cells are sometimes not evaluated

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#854]
1. Enable "Open a cell when maxima expects input".
2. Enter load(solve_rec)
3. When a new cell is created, enter x. Shift+Enter does not evaluate.

**Comment by gunterkoenigsmann** [comment]
Weird: The 
       
      dynamic_cast<wxFrame*>(GetParent())->ProcessCommand(wxMaximaFrame::menu_evaluate);

is called in this case.

Tried to replace it by a

              wxMenuEvent *EvaluateEvent=new wxMenuEvent();
              EvaluateEvent->SetId(wxMaximaFrame::menu_evaluate);
              GetParent()->GetEventHandler()->QueueEvent(EvaluateEvent);

But I seem to be required the event type, as well... ...and I don't know which to use.

**Comment by gunterkoenigsmann** [comment]
Ok... ...the correct command was:

              wxMenuEvent *EvaluateEvent=new wxMenuEvent(wxEVT_MENU,wxMaximaFrame::menu_evaluate);
              GetParent()->GetEventHandler()->QueueEvent(EvaluateEvent);

As it was called three times throughout MathCtrl.cpp I will bundle these two lines in a new function.

**Comment by gunterkoenigsmann** [comment]
One drawback of using the official event queue exists, though: If one manages to type quicker than the computer understands the evaluation event is always inserted at the end of the evaluation queue, not directly after the Shift+Return. But I don't see any way around this and it is actually kind of hard to trigger this behavior, at least on Linux: The Shift state seems to be read out when the "Return" event is being processed, not when the "Return" key is pressed along with Shift.
