### ISSUE TITLE
Hiding the cell-markers and the labes for smarter look in printing (and PDF)

### ISSUE THREAD

**Issue by herhin2015** [andrejv/wxmaxima#857]
Hello
For smarter look in printing and PDF converting, it would be nice to have an opportunity to temporary hide all cell-markers and the input/ouput-labes. It could be simply set to white by a menu button (on/off). An increased look of a well textured calculation sheet is always a good argument for the validity in modern technical work and in education.

Thank you for your great work on this project!!

**Comment by gunterkoenigsmann** [comment]
This was quite big a change. If you find something I broke during doing this please tell me either by opening a new issue or by adding a comment to this one (which I will get per mail) - or per mail, of course. Will use this as starting point for additional improvements lateron.
