### ISSUE TITLE
Maxima is dead in the water on the MacOS after Apple security update. 

### ISSUE THREAD

**Issue by robert-dodier** [andrejv/wxmaxima#858]
(I (Robert Dodier) am migrating this issue from the Maxima bug tracker where it is item #3288. I'm quoting the original bug report in full. It appears to me that this issue is a wxMaxima crash so it is more suitable here. But if it turns out to be a Maxima bug after all, of course we can reopen #3288. Note that there are two files attached to #3288. Github won't let me attach the RTF to this issue so you'll have to go to #3288 to see it. See: https://sourceforge.net/p/maxima/bugs/3288/)

"I use Maxima almost every day. As of a week ago Maxima is dead in the water on the MacOS Platform running El Capitan. I have redownloaded most recent version, scrubbed and cleaned and I get a reproducible Maxima crash with the attached error log. and .wxm file that contains only two lines kill(all)$ and 2+2;
All other codes on this machine function properly. It is also stable otherwise. I downloaded Apple security updates and the problem started around the time of that update. Recent versions of MacOS have protected certain directories that were formerly available for install. My instinct is that some access to these formerly open directories is the cause of the crash."

"After each Maxima crash, a common lisp process 'sbcl' is left running on the machine and this process has very high CPU utilization. If not detected several of these processes taken together can overheat some machines, Stuxnet style. I have to keep on an icepack to keep the CPU temperature below 210 degrees. Bringing up the activity manager or doing a ps -au shows the zombie common lisps which can be killed one at a time."

**Comment by lvwarren** [comment]
Here is the crash file.
maxima works from the command line
2+2; works
anything else just crashes and produces the following crash log:
[maximaCrash.txt](https://github.com/andrejv/wxmaxima/files/815406/maximaCrash.txt)

**Comment by lvwarren** [comment]
Maxima is one of the few high quality and free repositories of mathematical knowledge. Because of its platform independence it is important for those who are reaching out to PC and Mac based centers of learning. For the MacOS version to be DOA is a serious loss of capability to the world.

**Comment by gunterkoenigsmann** [comment]
After quite a few tries I have managed to compile the current maxima+wxMaxima version for Mac OS: http://www.physikbuch.de/maxima/Maxima+wxMaxima.dmg. The crash seems to be resolved in the current version. There might a crash on closing wxMaxima, though (after saving the file, fortunately) that is resolved in wxMaxima's git head. But resolving it required many big changes to the program => I assume that should wait for the next major version => All that is now left should be uploading the .dmg to the maxima homepage.

**Comment by lvwarren** [comment]
You are fantastic Gunter. I will try it out.



________________________________

**Comment by lvwarren** [comment]
Just downloaded and checked on Mac #1:


It crashes and says there is a problem. Log is below


Also there is no icon on the maxima inside the .dmg.


Thanks for working on this.


- Van


just maxima:

exec '/Contents/Resources/maxima.sh'

-bash: /Contents/Resources/maxima.sh: No such file or directory

-bash: exec: /Contents/Resources/maxima.sh: cannot execute: No such file or directory


executing wxMaxima leads to immediate crash.

Process:               wxmaxima [1004]
Path:                  /Applications/wxMaxima.app/Contents/MacOS/wxmaxima
Identifier:            net.sf.wxMaxima
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           wxmaxima [1004]
User ID:               502

Date/Time:             2017-03-08 01:14:14.451 -0600
OS Version:            Mac OS X 10.11.6 (15G1421)
Report Version:        11
Anonymous UUID:        CBD23F19-0245-BDD6-6811-0DDDF29B6BE5


Time Awake Since Boot: 7500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/wxmac/lib/libwx_osx_cocoau_aui-3.0.dylib
  Referenced from: /Applications/wxMaxima.app/Contents/MacOS/wxmaxima
  Reason: image not found

Binary Images:
    0x7fff6a74a000 -     0x7fff6a781a47  dyld (360.22) <884763FC-CC0F-31CC-ACC4-75A805CE401D> /usr/lib/dyld
    0x7fff8dadc000 -     0x7fff8dadcfff  com.apple.Carbon (154 - 157) <8F6ED602-5943-3E29-A793-BC331E2C183D> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff8e3f6000 -     0x7fff8e3f7ffb  libSystem.B.dylib (1226.10.1) <012548CD-614D-3AF0-B3B1-676F427D2CD6> /usr/lib/libSystem.B.dylib
    0x7fff99bb5000 -     0x7fff99c2afff  com.apple.framework.IOKit (2.0.2 - 1179.50.2) <A509D3AE-9D48-31B7-89C7-326A7A2007B2> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff9aed4000 -     0x7fff9aed4fff  com.apple.Cocoa (6.11 - 22) <807787AB-D231-3F51-A99B-A9314623C571> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff9c35d000 -     0x7fff9c503ff7  com.apple.audio.toolbox.AudioToolbox (1.13 - 1.13) <370E95BC-956C-3962-86CC-0A14CF6A0389> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fffa0830000 -     0x7fffa083efff  com.apple.opengl (12.1.0 - 12.1.0) <62997B59-BCD2-3A71-BD16-DE75DBAFA7C2> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL

Model: MacBookPro5,2, BootROM MBP52.008E.B05, 2 processors, Intel Core 2 Duo, 3.06 GHz, 8 GB, SMC 1.42f4
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
Graphics: NVIDIA GeForce 9600M GT, NVIDIA GeForce 9600M GT, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x802C, 0x31364A5353353132363448592D3147314131
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x802C, 0x31364A5353353132363448592D3147314131
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE SSD TS256A, 251 GB
Serial ATA Device: MATSHITADVD-R   UJ-868
USB Device: USB Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: USB Bus
USB Device: USB Optical Mouse
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Built-in iSight
USB Device: USB 2.0 Bus





________________________________

**Comment by gunterkoenigsmann** [comment]
That would be great! I've tried to find testers on the Maxima Mailing List. But I assume it isn't easy to find someone there who doesn't build the programs from source or use homebrew or Mac Ports in order to install them.

**Comment by gunterkoenigsmann** [comment]
Arrgh!

It is always good to have testers...
...then I have to link wxMaxima statically. Will give it another try in a minute. Thanks a lot,

   Gunter.

**Comment by lvwarren** [comment]
I'm here for you! [😉]


[1479937485088_2016Signature.png]

wdv<http://wdv.com/>

<http://wdv.com/>amazon<https://www.amazon.com/L.-Van-Warren/e/B00E6W8WPI>
facebook<https://facebook.com/lvanwarren>
calculus<https://www.facebook.com/LearningCalculus/>

twitter<https://twitter.com/LVanWarren>



________________________________

**Comment by lvwarren** [comment]
perfect. I can do screen captures if they will help:


[cid:f341b32f-1221-41ae-a45d-3ab64b71e406]


[1479937485088_2016Signature.png]

wdv<http://wdv.com/>

<http://wdv.com/>amazon<https://www.amazon.com/L.-Van-Warren/e/B00E6W8WPI>
facebook<https://facebook.com/lvanwarren>
calculus<https://www.facebook.com/LearningCalculus/>

twitter<https://twitter.com/LVanWarren>



________________________________

**Comment by gunterkoenigsmann** [comment]
Ok... ...seems like I will have to build my own statically-linkable wxWidgets on a prehistoric Mac (that still can be updated to the latest Mac OS. No complaints here) => I am afraid my next build will need >1 hour. But it will be done.

Kind regards,

      Gunter.

**Comment by lvwarren** [comment]
No worries Gunter. It is 1:34 am here so I will go to bed for now and get up tomorrow and check it out. Thanks the world is hanging by a thread and this will help.


[1479937485088_2016Signature.png]

wdv<http://wdv.com/>

<http://wdv.com/>amazon<https://www.amazon.com/L.-Van-Warren/e/B00E6W8WPI>
facebook<https://facebook.com/lvanwarren>
calculus<https://www.facebook.com/LearningCalculus/>

twitter<https://twitter.com/LVanWarren>



________________________________

**Comment by gunterkoenigsmann** [comment]
It was several hours of compiling. And after a handful of compiler runs I have tested nearly all combinations of compilers (g++/clang), wxWidgets (current release/git head) and C standards (c++11? older C?) Dynamic linking seems to be tested but useless: In that case I have the needed libraries and the app won't work for anybody else. But a statically linkable wxWidgets on a mac can either not be compiled or not be linked to any program. Will have to give the mac back to its owner tomorrow. But it seems that programming on such a thing is - weird, at last.

**Comment by lvwarren** [comment]
where do we go from here?


[1479937485088_2016Signature.png]

wdv<http://wdv.com/>

<http://wdv.com/>amazon<https://www.amazon.com/L.-Van-Warren/e/B00E6W8WPI>
facebook<https://facebook.com/lvanwarren>
calculus<https://www.facebook.com/LearningCalculus/>

twitter<https://twitter.com/LVanWarren>



________________________________

**Comment by gunterkoenigsmann** [comment]
I am afraid that the only thing we can do is to wait that someone who has a mac and who knows how to compile wxMaxima on it in a way that it works on other computers, too steps forward and builds wxMaxima on it. If it is currently possible to compile wxWidgets applications in this way for mac computers, that is.

**Comment by lvwarren** [comment]
I may be willing to look at this I just got a new iMac and it is blazing fast. Is this an Xcode thing or can I do it in Netbeans or from a console with a Makefike?


________________________________

**Comment by gunterkoenigsmann** [comment]
That would be really 

great! What I have learned from discussions on the mailing list is that using homebrew was a bad idea on my side. What I know after all the discussion on the maxima mailing list is:

 - Install xcode
 - Install homebrew
 - Download the latest Release of Maxima and wxMaxima
 - download the source code of wxWidgets
 - open a console
 - cd into the directory wxWidgets is in
 - ./configure --disable-shared --disable-mediactrl
 - make
 - sudo make install

Now a wxWidgets version that doesn't need .dylib files should be installed on your system: Just using the one provided with MacPorts isn't possible as it can only be shipped as .dylib, not as part of an application. The next step is to compile wxMaxima:

 - Apply the following patch to wxMaxima (which makes plotting work): [0001-Istv-n-was-right-We-forgot-to-set-the-viewport-size-.patch.txt](https://github.com/andrejv/wxmaxima/files/833400/0001-Istv-n-was-right-We-forgot-to-set-the-viewport-size-.patch.txt)
 - cd into the directory wxMaxima is in
 - ./configure --enable-static-wx
 - make
 - make wxMaxima.app

This part has unfortunately failed for me

 - cd into the directory Maxima is in
 - follow the instructions found in macosx/Readme.md

On the maxima-discuss mailing is there are a few developers that use a mac. If there are problems - perhaps one of them can help.

**Comment by gunterkoenigsmann** [comment]
Arrgh! I meant: Install MacPorts, not Homebrew.

**Comment by lvwarren** [comment]
Lucid explanation, thank you. Does the final make include construction of the .dmg installation component? That would be my principle unfamiliarity.


________________________________

**Comment by gunterkoenigsmann** [comment]
And I forgot: For building maxima itself and the .dmg file the instructions found here work better than the ones from the release: https://sourceforge.net/p/maxima/code/ci/master/tree/macosx/

The instructions tell to create the .dmg by hand. But - I am no mac expert so if there are better ways feel free to do it in a better way...

**Comment by lvwarren** [comment]
Or write a shell script to do it. Ok I'll look into it and get back to you in a few days. Thanks!


________________________________

**Comment by gunterkoenigsmann** [comment]
A shell script would be great! Wolfgang has written a fully automatic Shell script that creates Windows Builds - and it has done real wonders as before that creating a new installer had proven an near-to-impossible.

...and a maxima release for the Mac would be extremely useful as many universities teach maxima - and as Mac computers were amongst the first that had accumulator runtimes fit for the device being useful at the university many students carry one of these devices.

**Comment by lvwarren** [comment]
Status: Downloads done, and your instructions have been codified.


There is a fatal error in wxWidgets due to the fact that <QuickTime/QuickTime.h> has been deprecated for MacOS Sierra and no longer exists.

[cid:cbd4f89d-7509-4ec8-b454-31656f9b0b9d]


A possible workaround is here<https://github.com/sass/libsass/issues/2326> and I am looking into it.


The wxWidgets compile takes a few minutes.


I have also created a clean directory for restarts and a README.txt checklist.


[cid:64b5238b-7d0d-4007-8ca4-71af6278027e]


[1479937485088_2016Signature.png]

wdv<http://wdv.com/>

<http://wdv.com/>amazon<https://www.amazon.com/L.-Van-Warren/e/B00E6W8WPI>
facebook<https://facebook.com/lvanwarren>
calculus<https://www.facebook.com/LearningCalculus/>

twitter<https://twitter.com/LVanWarren>



________________________________

**Comment by gunterkoenigsmann** [comment]
In the meantime I have found out that I wasn't far from succeeding:

http://stackoverflow.com/questions/20695805/using-dylibs-inside-app-bundle

tells that one can put the missing .dylib files into the Frameworks folder of the .apk.

I still don't know, though, what sense using a .dylib makes if it then is shipped along with an application.

**Comment by lvwarren** [comment]
After some fiddling I have the wxWidgets 3.10.0 compiled and installed, 3.0.2 does not work,
since <QuickTime/QuickTime.h> has been deprecated and no longer exists.
The ./configure steps take about a minute. The wxWidget compiles take about 15 minutes.
I need instructions on applying the plotting patch. Thanks.
Here's a summary transcript:

Install xcode: CHECK!
Install macports: CHECK!
Download the latest Release of Maxima and wxMaxima: CHECK!
Download the source code of wxWidgets: CHECK!
Open a console:
    cd into the directory wxWidgets is in: CHECK!
    ./configure --disable-shared --disable-mediactrl: CHECK!
make:
    FAILS with 1 error due to missing <QuickTime/QuickTime.h> deprecated in Sierra
    SOLUTION, retry using  wxWidgets latest dev release 3.1.0
make: CHECK!
sudo make install CHECK!

I'll pick up on Maxima proper next session.

**Comment by gunterkoenigsmann** [comment]
That sounds great!

There are tools that apply patches. But applying it by hand isn't hard, neither:

A patch is divided into several sections. Each begins with "@@" followed by the information where to change the code (in this case src/MathCtrl.cpp, left the line number in the original code, right the line number in the patched version:


```c++
@@ -219,6 +219,7 @@ void MathCtrl::OnPaint(wxPaintEvent& event)
```

The next 3 lines are a bit of context (the 3 lines above the line that is to be changed). Context is very helpful if the code has been changed since the patch has been created and the code that is to be patched has moved a line upwards or downwards since:
```c++
   }
   
   // Inform all cells how wide our display is
```
The next line starts with a "+" - which tells that text has to be added here:
```c++
           MathCell::SetCanvasSize(GetClientSize());
```
The text that is to be added is followed by another two lines of context
```
   wxMemoryDC dcm;
   wxPaintDC dc(this);
```
...and the next section containing another line to add in a different place.

Kind regards,
Gunter.

**Comment by lvwarren** [comment]
Hi Gunter -


The wxWidgets 3.10 is installed per specification.

The install terminates normally as sudo, and as regular user with the following message:



-----------------------------------------------------



 The installation of wxWidgets is finished.  On certain

 platforms (e.g. Linux) you'll now have to run ldconfig

 if you installed a shared library and also modify the

 LD_LIBRARY_PATH (or equivalent) environment variable.


skipping the viewport patch for a moment  we cd to the wxmaxima directory and run configure:


van wxmaxima-16.12.2 [580]: ./configure --enable-static-wx

BEGIN BASH OUTPUT


    checking for wx-config... /usr/local/bin/wx-config

    checking for wxWidgets version >= 3.0.0... yes (version 3.1.0)

    checking for wxWidgets static library... yes

    checking if we can compile a wxWidgets program...


    *** The test program failed to compile or link. See the file config.log for the

    *** exact error that occurred. This usually means that wxWidgets library was

    *** incorrectly installed.


    configure: error: Failed to compile a test program

END   BASH OUTPUT



So we check the config.log and find that an include file in for the wxWidgets test is missing:

BEGIN CONFIG.LOG EXCERPT


configure:4134: g++ -o conftest -g -O2

    -I/usr/local/lib/wx/include/osx_cocoa-unicode-static-3.1

    -I/usr/local/include/wx-3.1 -D_FILE_OFFSET_BITS=64

    -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__

    -I/usr/local/lib/wx/include/osx_cocoa-unicode-static-3.1

    -I/usr/local/include/wx-3.1

    -D_FILE_OFFSET_BITS=64 -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__

conftest.cpp  -L/usr/local/lib

    -framework IOKit

    -framework Carbon

    -framework Cocoa

    -framework AudioToolbox

    -framework System

    -framework OpenGL

        /usr/local/lib/libwx_osx_cocoau_aui-3.1.a

        /usr/local/lib/libwx_osx_cocoau_xrc-3.1.a

        /usr/local/lib/libwx_osx_cocoau_qa-3.1.a

        /usr/local/lib/libwx_baseu_net-3.1.a

        /usr/local/lib/libwx_osx_cocoau_html-3.1.a

        /usr/local/lib/libwx_osx_cocoau_adv-3.1.a

        /usr/local/lib/libwx_osx_cocoau_core-3.1.a

        /usr/local/lib/libwx_baseu_xml-3.1.a

        /usr/local/lib/libwx_baseu-3.1.a

        -lpng -ljpeg -ltiff

    -framework WebKit

        -lexpat -lwxregexu-3.1 -lz -lpthread -liconv  >&5


In file included from conftest.cpp:11:

In file included from /usr/local/include/wx-3.1/wx/wx.h:15:

In file included from /usr/local/include/wx-3.1/wx/object.h:19:

In file included from /usr/local/include/wx-3.1/wx/memory.h:15:

In file included from /usr/local/include/wx-3.1/wx/string.h:37:

/usr/local/include/wx-3.1/wx/strvararg.h:27:18: fatal error: 'tr1/type_traits' file not found

        #include <tr1/type_traits>

                 ^

1 error generated.


END CONFIG.LOG EXCERPT


The include directory /usr/local/include/wx-3.1 exists, and the file type_traits does exist on my system

[cid:e054a644-074a-4b7e-b217-59c7597aa0f5]


but not in a /usr/include/tr21 directory.


there are also type_traits folders that contain .cc files



So consequently wxWidget test cannot compile its test program in wxmaxima and it stops.

So the question is what is the minimal and portable change that makes type_traits[.h] visible?


- Van

PS Xcode is installed correctly and Xcode command line tools are installed correctly.

**Comment by gunterkoenigsmann** [comment]
All I was able to find out about that is that it is a symptom of apple switching from an old, but backwards compatible library to a new one: Your C compiler tries to use half of both which seems a common problem. https://forums.wxwidgets.org/viewtopic.php?f=19&t=41965&sid=4c9566c535a87d2f763a6cd715caee64&start=15 now tells that the problem can be solved, though. Let's hope they are right.

**Comment by lvwarren** [comment]
Ok, I have tried the --with-macos-version-min=10.11 switch. Here is the report:


wxMaxima still cannot create the test wxwidgets application in the configuration step.

Investigating:

I went into wxWidgets/demo directory and compiled the 5 demo programs.

All 5 compile and run without incident.

Then I went to the wxWidgets/samples directory and compiled the sample programs.

A random sample of 4 of the 87 programs each work.

The renderer sample works except when you try to load renderdll, which appears to be a fake stub.


 wxWidgets Preparation:

./config     - takes 19.8 seconds of clock time.

make         - takes 16 minutes and 4 seconds of clock time.

make install - takes 6.6 seconds


wxMaxima Preparation:

./config - will not run stating wxWidgets are not installed correctly.


None of several flag attempts including:

   --with-macos-version-min=10.11

fixed the include file missing problem:

/usr/local/include/wx-3.1/wx/strvararg.h:27:18: fatal error: 'tr1/type_traits' file not found

        #include <tr1/type_traits>


Curiously setting the macos-version-min flag to 10.11 ends up in the wxWidgets compile directives as:

    -mmacos-version-min=10.7

Here are some variations of flag configurations attempted:

For wxWidgets=wxWidgets-3.1.0

./configure

./configure --disable-shared --disable-mediactrl

./configure --disable-shared --disable-mediactrl --with-macos-version-min=10.11

./configure                  --disable-mediactrl --with-macos-version-min=10.12

make

make install (doesn't work)

sudo make install (does work)


For wxmMaxima=wxmaxima-16.12.2

./configure --enable-static-wx

./configure

sudo ./configure --enable-static-wx

(none of these solve the missing <tr1/type_traits> file problem)


but they are not addressing the underlying wxmaxima problem.


This is the current output of wxMaxima: ./configure --enable-static-wx

checking for wx-config... /usr/local/bin/wx-config

checking for wxWidgets version >= 3.0.0... yes (version 3.1.0)

checking for wxWidgets static library... yes

checking if we can compile a wxWidgets program...


*** The test program failed to compile or link. See the file config.log for the

*** exact error that occurred. This usually means that wxWidgets library was

*** incorrectly installed.


configure: error: Failed to compile a test program


All the best,

- Van

**Comment by gunterkoenigsmann** [comment]
No idea what Apple or the wxWidgets guys did do here. Tomio Arisaka from the maxima-discuss mailing list seems to have gotten a step further:

I have installed two sets of libraries (libpng, libjpeg, libtiff, etc.).
One is installed with MacPorts. The other is installed with Homebrew.
And so I misunderstood which libraries are linked to wxWidgets and wxMaxima.
(The default library search path is "/usr/lib" then "/usr/local/lib".)

The following note is the fixed version to compile wxWidgets and wxMaxima with MacPorts:
(It does not depend on Homebrew.)

[1] Make wxWidgets static libraries:
--------------------------------------------------------------------------------
$ bzip2 -dc ./wxWidgets-3.0.2.tar.bz2 | tar xf -
$ 
$ pushd ./wxWidgets-3.0.2
$ 
$ cp -ip ./configure ./configure.orig
$ open -e ./configure
$ diff -u ./configure.orig ./configure
--- ./configure.orig	2014-10-07 06:33:44.000000000 +0900
+++ ./configure	2017-03-15 00:42:14.000000000 +0900
@@ -21893,48 +21893,7 @@
 
 
 
-SEARCH_INCLUDE="\
-    /usr/local/include        \
-    /usr/local/X11/include    \
-    /usr/local/include/X11    \
-    /usr/local/X11R7/include  \
-    /usr/local/X11R6/include  \
-    /usr/local/include/X11R7  \
-    /usr/local/include/X11R6  \
-                              \
-    /usr/Motif-2.1/include    \
-    /usr/Motif-1.2/include    \
-    /usr/include/Motif1.2     \
-                              \
-    /usr/dt/include           \
-    /usr/openwin/include      \
-                              \
-    /usr/include/Xm           \
-                              \
-    /usr/X11R7/include        \
-    /usr/X11R6/include        \
-    /usr/X11R6.4/include      \
-                              \
-    /usr/include/X11R7        \
-    /usr/include/X11R6        \
-                              \
-    /usr/X11/include          \
-    /usr/include/X11          \
-                              \
-    /usr/XFree86/include/X11  \
-    /usr/pkg/include          \
-                              \
-    /usr/local/X1R5/include  \
-    /usr/local/include/X11R5  \
-    /usr/X11R5/include        \
-    /usr/include/X11R5        \
-                              \
-    /usr/local/X11R4/include  \
-    /usr/local/include/X11R4  \
-    /usr/X11R4/include        \
-    /usr/include/X11R4        \
-                              \
-    /usr/openwin/share/include"
+SEARCH_INCLUDE="/opt/local/include"
 
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for libraries directories" >&5
 $as_echo_n "checking for libraries directories... " >&6; }
$ 
$ patch -p0 </opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/graphics/wxWidgets-3.0/files/patch-upstream-src-stc-scintilla-src-Editor.cxx.diff
$ 
$ patch -p0 </opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/graphics/wxWidgets-3.0/files/patch-upstream-noquicktime.diff
$ 
$ patch -p0 </opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/graphics/wxWidgets-3.0/files/patch-upstream-src-osx-carbon-fontdlgosx.mm.diff
$ 
$ patch -p0 </opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/graphics/wxWidgets-3.0/files/patch-upstream-webkit-proper-types.diff
$ 
$ pushd ./build
$ 
$ arch_flags="-arch x86_64"
$ 
$ ../configure --with-macosx-version-min=10.9 --enable-unicode --with-opengl --with-osx_cocoa --with-libjpeg --with-libtiff --with-libpng --with-zlib --disable-mediactrl --enable-graphics_ctx --with-expat --disable-precomp-headers --disable-shared --with-libiconv-prefix="/opt/local"  CFLAGS="$arch_flags" CXXFLAGS="$arch_flags" CPPFLAGS="$arch_flags" OBJCFLAGS="$arch_flags" OBJCXXFLAGS="$arch_flags" LDFLAGS="$arch_flags -L/opt/local/lib"  CC="/usr/bin/gcc" CXX="/usr/bin/g++" CPP="/usr/bin/g++ -E" CXXCPP="/usr/bin/g++ -E"
$ 
$ make
$ 
$ ls -lt ./lib/
$ 
$ popd;popd
--------------------------------------------------------------------------------

[2] Make wxMaxima.app:
--------------------------------------------------------------------------------
$ tar xzf ./wxmaxima-15.08.2.tar.gz 
$ 
$ pushd ./wxmaxima-15.08.2
$ 
$ cp -i ../wxWidgets-3.0.2/wxwin.m4 ./acinclude.m4
$ 
$ ./configure --with-wx-config=../wxWidgets-3.0.2/build/wx-config --enable-fullystatic  LDFLAGS="-L/opt/local/lib" CC="/usr/bin/gcc -arch x86_64" CXX="/usr/bin/g++ -arch x86_64" CPP="/usr/bin/g++ -E" CXXCPP="/usr/bin/g++ -E"
$ 
$ make
$ 
$ make wxMaxima.app
$ 
$ ls -ltd ./wxMaxima.app
$ 
$ popd
--------------------------------------------------------------------------------
The result is that wxMaxima.app depends on seven shared libraries (libpng16, libjpeg, libtiff, libexpat, libz, libiconv, liblzma). Note: libtiff depends on liblzma.


By the way, You can make wxMaxima standalone.

[3] Make wxMaxima independent of the shared library which is not included in MacOS X:
    (1) Copy the shared library into the application bundle of wxMaxima.
    (2) Changes the dependent shared library install name old to new in the shared library of wxMaxima.
    (3) Changes the dependent shared library install name old to new in the executable file of wxMaxima.

(Note: I use "otool -L" to display the path name of the dependent shared library.)
--------------------------------------------------------------------------------
$ cp -iRp ./wxmaxima-15.08.2/wxMaxima.app ./
$ 
$ otool -L ./wxMaxima.app/Contents/MacOS/wxmaxima 
$ 
$ mkdir ./wxMaxima.app/Contents/MacOS/lib
$ 
$ pushd ./wxMaxima.app/Contents/MacOS/lib
$ 
$ cp -ip /opt/local/lib/libpng16.16.dylib ./
$ cp -ip /opt/local/lib/libjpeg.9.dylib ./
$ cp -ip /opt/local/lib/libtiff.5.dylib ./
$ cp -ip /opt/local/lib/libexpat.1.dylib ./
$ cp -ip /opt/local/lib/libz.1.dylib ./
$ cp -ip /opt/local/lib/libiconv.2.dylib ./
$ cp -ip /opt/local/lib/liblzma.5.dylib ./
$ 
$ otool -L ./libtiff.5.dylib 
$ 
$ install_name_tool -change /opt/local/lib/liblzma.5.dylib @executable_path/lib/liblzma.5.dylib libtiff.5.dylib
$ 
$ install_name_tool -change /opt/local/lib/libjpeg.9.dylib @executable_path/lib/libjpeg.9.dylib libtiff.5.dylib
$ 
$ install_name_tool -change /opt/local/lib/libz.1.dylib @executable_path/lib/libz.1.dylib libtiff.5.dylib
$ 
$ otool -L ./libtiff.5.dylib
$ 
$ otool -L ./liblzma.5.dylib 
$ 
$ install_name_tool -change /opt/local/lib/liblzma.5.dylib @executable_path/lib/liblzma.5.dylib liblzma.5.dylib
$ 
$ otool -L ./liblzma.5.dylib 
$ 
$ otool -L ./libpng16.16.dylib 
$ 
$ install_name_tool -change /opt/local/lib/libz.1.dylib @executable_path/lib/libz.1.dylib libpng16.16.dylib
$ 
$ otool -L ./libpng16.16.dylib 
$ 
$ pushd ..
$ 
$ install_name_tool -change /opt/local/lib/libpng16.16.dylib @executable_path/lib/libpng16.16.dylib wxmaxima
$ 
$ install_name_tool -change /opt/local/lib/libjpeg.9.dylib @executable_path/lib/libjpeg.9.dylib wxmaxima
$ 
$ install_name_tool -change /opt/local/lib/libtiff.5.dylib @executable_path/lib/libtiff.5.dylib wxmaxima
$ 
$ install_name_tool -change /opt/local/lib/libexpat.1.dylib @executable_path/lib/libexpat.1.dylib wxmaxima
$ 
$ install_name_tool -change /opt/local/lib/libz.1.dylib @executable_path/lib/libz.1.dylib wxmaxima
$ 
$ install_name_tool -change /opt/local/lib/libiconv.2.dylib @executable_path/lib/libiconv.2.dylib wxmaxima
$ 
$ popd;popd
$ 
$ otool -L ./wxMaxima.app/Contents/MacOS/wxmaxima 
--------------------------------------------------------------------------------

This wxMaxima works good on MacOS X (10.9.5 and 10.11.6).
I don't have any troubles with loading shared libraries.

Thanks,

Tomio Arisaka

**Comment by gunterkoenigsmann** [comment]
Thanks a lot! 
I've
 - updated the build instructions in README.md with these pieces of info
 - added the command-line switches to README.md that should allow to compile wxWidgets on a current Mac Os system without running into errors with type_traits.h
 - (hopefully) corrected the errors that prevent multi-window mode
 -  and added code to the makefile that (hopefully) generates a script that automatically bundles the needed .dylib files with wxMaxima.
All of this naturally is untested. But with really much luck it might all work.

**Comment by lvwarren** [comment]
Just Downloaded Big Sur on my iMac and here is what you have to do to fix maxima:
xattr -d com.apple.quarantine /Applications/Maxima.app
Also, there is a goofy new inset window appearing that is very distracting. See attached image.
<img width="297" alt="Screen Shot 2020-12-15 at 3 52 38 PM" src="https://user-images.githubusercontent.com/589358/102277265-a321ba80-3eed-11eb-88b6-41013464579f.png">
