### ISSUE TITLE
I noticed some weird results from solve.

### ISSUE THREAD

**Issue by ricardozimmer** [andrejv/wxmaxima#862]
Good evening,
Bellow is the simplest example I could find to show what I'm calling weird. Not sure if I'm missing something, or if solve is printing some intermediate result or if it's a bug. I have more complex examples were ALL solutions are not solutions for the set of equations, but are solutions for one or the other individually. I can make them available but this simpler one summarizes what I believe is a problem.

eq1:x^2/(2*y^2-2*y+2*x^2+1)=k;
eq2:-(2*x*(y-1)*(y-x-1))/(2*y^2-2*y+2*x^2+1)=0;
soln:solve([eq2,eq1],[x,y]);
(%o2) x^2/(2*y^2-2*y+2*x^2+1) = k
(%o3) -(2*x*(y-1)*(y-x-1))/(2*y^2-2*y+2*x^2+1) = 0
(%o4) [[x = 0,y = -(%i-1)/2],[x = 0,y = (%i+1)/2],
       [x = -(sqrt(k-3*k^2)+k)/(4*k-1),
        y = (3*k-sqrt(1-3*k)*sqrt(k)-1)/(4*k-1)],
       [x = (sqrt(k-3*k^2)-k)/(4*k-1),
        y = (3*k+sqrt(1-3*k)*sqrt(k)-1)/(4*k-1)],
       [x = -sqrt(-k/(2*k-1)),y = 1],[x = sqrt(-k/(2*k-1)),y = 1]]
ev([eq1,eq2],soln[1]),ratsimp;
(%o5) [0 = k,0 = 0] /*This solution, x=0 is not a solution for eq1, but is for eq2.*/

I'm seeing this behavior in 5.38.1 5.39.0 and on maxima-current.
Some files built in 5.37 and earlier fail when running on these versions.

Thanks a lot 
Rick Zimmer

wxbuild_info()
wxMaxima version: 16.4.2
Maxima version: 5.38.1_5_gdf93b7b_dirty
Maxima build date: 2016-05-13 22:35:09
Host type: i686-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.3.5
build_info();
(%o7) %build_info("5.38.1_5_gdf93b7b_dirty","2016-05-13 22:35:09",
                  "i686-w64-mingw32","SBCL","1.3.5"), 

wxbuild_info()
wxMaxima version: Version_16.12.x_164_gd22856d
Maxima version: branch_5_39_base_116_gcbe04cc_dirty
Maxima build date: 2017-02-26 20:50:12
Host type: x86_64-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.12
build_info();
 %build_info("branch_5_39_base_116_gcbe04cc_dirty","2017-02-26 20:50:12",
                  "x86_64-w64-mingw32","SBCL","1.3.12")

**Comment by gunterkoenigsmann** [comment]
The maxima team has improved solve a lot. As it is theoretically impossible to make an solve() that solves all equations perhaps you have found places where these changes backfire. If this is the case and you have minimal examples for that the maxima-discuss list on maxima.sourceforge.net might be interested in them. For the current case maybe I can help:

Each element of soln[1] has a left hand and a right hand side:

     [x=0 , y=-(%i-1)/2]

To get a suitable list of variables solve can find the correct values for you might want to do something like the following:

     ev([eq1,eq2],makelist(lhs(i),i,soln[1])),ratsimp;

A shorter version would be:

     ev([eq1,eq2],map('lhs,soln[1])),ratsimp;

Kind regards,
Gunter.

**Comment by ricardozimmer** [comment]
Thanks Gunter, for your comments. I'll try to better illustrate what I'm seeing, and post it on Maxima discuss list. The example I sent is a simple 1 section Pi matching network between two known loads.
Thanks again,
Zimmer   

    On Thursday, March 2, 2017 2:27 AM, Gunter Königsman <notifications@github.com> wrote:
 

 The maxima team has improved solve a lot. As it is theoretically impossible to make an solve() that solves all equations perhaps you have found places where these changes backfire. If this is the case and you have minimal examples for that the maxima-discuss list on maxima.sourceforge.net might be interested in them. For the current case maybe I can help:Each element of soln[1] has a left hand and a right hand side: [x=0 , y=-(%i-1)/2]
To get a suitable list of variables solve can find the correct values for you might want to do something like the following: ev([eq1,eq2],makelist(lhs(i),i,soln[1])),ratsimp;
A shorter version would be: ev([eq1,eq2],map('lhs,soln[1])),ratsimp;
Kind regards,
Gunter.—
