### ISSUE TITLE
wxplot2d: Tiny iniline plots

### ISSUE THREAD

**Issue by HiTuX** [andrejv/wxmaxima#868]
"wxplot2d" outputs a tiny inline plots (Screenshot). I could not find a way to change the size of embeded plots anywhere. I tried to change the "Default plot size of new Maxima session" but with no effect. 

```
wxbuild_info()$

wxMaxima version: 16.12.2
Maxima version: 5.39.0
Maxima build date: 2016-12-12 18:06:11
Host type: x86_64-unknown-linux-gnu
System type: Linux 4.4.52-1-MANJARO x86_64
Lisp implementation type: ECL
Lisp implementation version: 16.1.2
```
 ![screenshot](https://framapic.org/2ZesCA68vGf7/YvKbLEiHg1Xm)

**Comment by gunterkoenigsmann** [comment]
This will be fixed in the next release. The commit that solves this problem is already in the release branch.

**Comment by HiTuX** [comment]
Ahh! I'll use `plot2d` till next release comming to Manjaro.
Thanks for the clarification.
