### ISSUE TITLE
Enable XDG basedir support

### ISSUE THREAD

**Issue by alex-shpilkin** [andrejv/wxmaxima#869]
This is a continuation of #355.

wxWidgets added support for XDG Base Directory specification in wxWidgets/wxWidgets@3eda9023, but it requires manual intevention by the library user. This could now be implemented in wxMaxima.

**Comment by gunterkoenigsmann** [comment]
That is good news.

But wxWidgets doesn't provide us with a real way to find out if it supports the command that does the manual intervention => I've asked them if they could make the XDG path the default config file location and move the old file to the new place before reading the configuration - if the new file doesn't already exist.
