### ISSUE TITLE
 Can't enter Alt-Key combinations (e.g. square/curly brackets) on german keyboard 

### ISSUE THREAD

**Issue by jeanriemer** [andrejv/wxmaxima#872]
problem occurs under MacOS Sierra starting with wxMaxima 16.12.0 up to and including the current git Version,
V16.04.2 and older (15.8.2) work OK.
wxWidgets library is V3.0.2 (for all tested combinations)

wxMaxima version: 16.12.0
Maxima version: 5.39.0
Maxima build date: 2017-03-21 20:36:11
Host type: x86_64-apple-darwin16.4.0
System type: Darwin 16.4.0 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.15

**Comment by andrejv** [comment]
Which key combination exactly does not work.

I though this was fixed wit 988163dc81012281edf9a36a33408894447b86d7.

**Comment by jeanriemer** [comment]
Basically all Alt (also labeled "Option")-Key combinations were affected, it hurt most with the brackets though (e.g. for the plot commands).
Abovementioned patch 988163d indeed fixes this problem, thanks a lot. It's now included in current git version, and I could also successfully apply it to the downloadable source tar package 16.12.2 (here src/MathCtrl.cpp lines 3493..3497 need to be removed)
Thankx much for looking into this..
