### ISSUE TITLE
Label does not change

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#873]
In the following code:

reset()$kill(allbut(props))$
load(fourie)$
m:200$a:1$α:1$
foursin(a*x,x,1)$
FSin:foursimp(%)$
g(x):=sum(b[n]*sin(n*π*x),n,1,m),FSin;
u(t,x):=sum(b[n]*sin(n*π*x)*exp(-α*n²*π²*t),n,1,m),FSin;
with_slider(t,makelist(i,i,0,200)/1000,u(t,x),[x,0,1],[y,0,1],
            [label,[sconcat("t=",ev(t)," s"),0.2,0.8]])$

The label in the plot does not change.
How can make the label change with the time displayed?

Thanks,

Daniel Volinski

**Comment by gunterkoenigsmann** [comment]
with draw it works fine:

![image](https://user-images.githubusercontent.com/5041537/27768565-fac5ace8-5f16-11e7-9ee0-f42d369f68bc.png)

**Comment by gunterkoenigsmann** [comment]
`reset()$kill(allbut(props))$
load(fourie)$
m:200$a:1$α:1$
foursin(a*x,x,1)$
FSin:foursimp(%)$
g(x):=sum(b[n]*sin(n*π*x),n,1,m),FSin;
u(t,x):=sum(b[n]*sin(n*π*x)*exp(-α*n²*π²*t),n,1,m),FSin;
with_slider_draw(
    t,makelist(i,i,0,200)/1000,
    key=sconcat("t=",(t)," s"),
    explicit(u(t,x),x,0,1),
    yrange=[0,1]
);`
