### ISSUE TITLE
checksums for our downloads

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#884]
I honestly don't know what checksums for the downloads are good for:

- If someone can tamper with the download or with the files on the server one can do so with the checksums, as well.
- And if a download has failed... ...one finds that out without a checksum.

But lintian always warns that the download page doesn't offer them and cpack surely offers an option to add them => Adding a low-priority feature request to the wxMaxima bug tracker.

**Comment by daute** [comment]
Four different checksums (md5, sha1, sha256, sha512) of all binary and source packages can now be created using "make checksums" ("make package" / make "package_source" must be called before).

**Comment by gunterkoenigsmann** [comment]
That is perfect. Thanks!
