### ISSUE TITLE
wxplot2d shows a tiny plot

### ISSUE THREAD

**Issue by mobius-eng** [andrejv/wxmaxima#887]
When using `wxplot2d` the result shows as a tiny image in wxMaxima:

![wxmaxima-plot-issue](https://user-images.githubusercontent.com/11750374/27217911-29b48df0-527c-11e7-9454-68cd676c2e06.png)

If I do `plot2d` the gnuplot window pops-up with a normal size. Also, if I do right-click on the plot image and "Save image..." -- the saved image has a normal size. I've tried to manipulate `wxplot_size` but it didn't bring any changes to the image.

I have compiled wxMaxima from sources (sourceforge though, not directly from git). Versions:

- wxMaxima 16.12.2
- wxWidgets 3.0.2
- Maxima 5.40.0
- SBCL  1.3.2
- OS: Ubuntu 16.04

**Comment by gunterkoenigsmann** [comment]
This issue should be solved in the current release of wxMaxima.
Don't know if it ever was uploaded to sourceforge, though, as we are moving to GitHub.

Kind regards,

   Gunter
