### ISSUE TITLE
glitchy copying from complex formulas

### ISSUE THREAD

**Issue by cmrdt** [andrejv/wxmaxima#891]
i dont have exact examples ( from build older than a year ago)
but occasionally when dealing with huge formulas containing fractions and parenthesis in the denominator,
they are not always reliably tracked and copied, but when 

`display2d:false`, is set to false, the problem goes away, 
it seems that internally it oputputs a text-art formula atate before it re-converts into pretty formulas (?confirm?),
thus before internally parsed accurately but goes through a broken-telephone state in between

if could also pretty-parse the linear-mode and do that by default instead of the current clumsy-complex 2d-ascii legacy that the back-end does

**Comment by gunterkoenigsmann** [comment]
If you have a reproducible example we will try to find the problem. And I will watch out: Perhaps I stumble upon an example that allows reproducing it while working with the program.

There also is a chance that my last few commits happen to have resolved the problem => tomorrow's nightly build might already work for you.

In the meantime 

     set_display(none);

or

     set_display(ascii);

might be a feasible workaround.

Kind regards,
Gunter.

**Comment by gunterkoenigsmann** [comment]
Found a second place which might have caused this. Tomorrow's nightly build should resolve the problem. If it doesn't please re-open this bug ticket.
