### ISSUE TITLE
nested factor/expand/ratsimp seems to retain more internal-info than using commas

### ISSUE THREAD

**Issue by cmrdt** [andrejv/wxmaxima#892]
e.g. factor(fullratsimp(expand(...))) vs ...,factor,fullratsimp,expand
occasionally returns different results  , how to deal with this internally,
it is asif it builds list of facts and are lost when use comma notation

**Comment by gunterkoenigsmann** [comment]
This happens on maxima's command line, too => It seems to be a problem in maxima, not in wxMaxima => I would beg you to ask this on http://maxima.sourceforge.net instead. But as I have encountered the same phenomenon I am quite interested what the answer will be...
