### ISSUE TITLE
If a ParenCell is broken into two lines the parenthesis might be too small

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#901]
Example:
 
     sin(qdqwwqdqdqwdqdwdqwqdwqdwqwd+sin(a/(1+b/(1+c/(1+d/e))))+wlkwqjkqweweqjkqwejkqjwl);

![image](https://user-images.githubusercontent.com/5041537/27954541-bcd960b6-6310-11e7-926a-22dff9cafd0d.png)

The closing parenthesis should be high enough to accommodate the part of the parenthesis' argument that is left to it.

**Comment by LennartF22** [comment]
How should the parentheses actually look like? Should only (in this case) the closing parenthesis be bigger or should both parentheses be bigger? Should the two lines with "wlk..." and "qdq..." get extra padding so that these lines are as high as the other two parentheses, as they are also enclosed by them?

**Comment by gunterkoenigsmann** [comment]
Now as you ask it: Every of the three possibilities might look odd:

- Making the opening parenthesis big even if only only the closing parenthesis is in a line that contains much vertical space
- Making the closing parenthesis big even if only only the opening parenthesis is in a line that contains much vertical space
- keeping both parenthesis small if the equation contains a linebreak.

If you decide that the current situation already is the optimum method I'll close this ticket.

Kind regards,
 Gunter.

**Comment by LennartF22** [comment]
Actually I think the current version is the least awkward looking one, but you have to decide about that.
