### ISSUE TITLE
wxMaxima dies on Mac when using 'Evaluate all cells'

### ISSUE THREAD

**Issue by Wendyy999** [andrejv/wxmaxima#903]
Using the following commands makes wxMaxima quit:
  Cmd R; 
  Cell menu/Evaluate All Visible cells;
  Shift Cmd R; or
  Shift Cmd P;
Help?
-------------------------------------------------------------
wxMaxima version: 16.4.0
Maxima version: 5.38.0
Maxima build date: 2016-04-03 08:56:53
Host type: x86_64-apple-darwin15.4.0
System type: Darwin 16.6.0 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.2.10
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
After a security update of Mac Os X this version of wxMaxima ran into problems when trying to restart maxima. The current release of wxMaxima should fix that.
