### ISSUE TITLE
print output is shown in wrong cell on evaluate all (Ctrl+R)

### ISSUE THREAD

**Issue by MSoegtropIMC** [andrejv/wxmaxima#904]
I am using wxMaxima 17.05.0 / Maxima version="5.40.0",timestamp="2017-06-01 18:54:43",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="1.3.15"

A new issue not observed in 5.38.1 is that print output is assigned to wrong cells if Ctrl+R is pressed. Also the output cells are not shown in order to the input cells. Here is an example:

(%i1)	printtest():=block([],print("a"),print("b"),print("c"),print("d"));
(%o1)	printtest(Bug\: Missing contents):=block([],print("a"),print("b"),print("c"),print("d"))
(%i2)	printtest();
"a"" "
(%i3)	printtest();
"b"" "
"c"" "
"d"" "
(%o2)	"d"
"a"" "
(%i4)	printtest();
"b"" "
"c"" "
"d"" "
(%o3)	"d"
"a"" "
"b"" "
"c"" "
"d"" "
(%o4)	"d"

This works fine when each cell is evaluated individually. The issue is only observed with Ctrl+R.

Best regards,

Michael

**Comment by gunterkoenigsmann** [comment]
Thanks for the report!
I *think* I have fixed that for the current nightly build by disallowing wxMaxima to interpret tags in a different order than they arrive. But I am not completely sure if I have fixed it or merely changed the timing necessary to trigger it so if you are willing to test the nightly build I would be grateful.
