### ISSUE TITLE
[Debian/Ubuntu] wxMaxima toolbar icons folder is located in /usr

### ISSUE THREAD

**Issue by fthx** [andrejv/wxmaxima#905]
Hi,

When I was searching for some files, I noticed the subject of this thread.
It seems an unusual location to put an app folder.

If I'm right, the 'art' folder located in /usr/wxMaxima should land in /usr/share/wxMaxima ?

**Comment by daute** [comment]
Fixed by commit 6fce99e. Thank you for your bug report.
