### ISSUE TITLE
Problem with to_lisp() from wxmaxima 17.5.0: $-character seems not to be transmitted

### ISSUE THREAD

**Issue by RolandSalz** [andrejv/wxmaxima#906]
From wxMaxima 17.5.0 / Maxima 5.40/ sbcl on windows I create a Lisp-session, but from within I cannot access the value of a variable that I defined in wxMaxima previously:

a:1;
:lisp $a      -> 1             /* This works ok. */
to_lisp();   -> (Type (to-maxima)to restart,($quit)to quit Maxima.)
(+ 1 2)        -> 3           /* Here I am in the Lisp session. */
$a               -> “debugger invoked…: The variable A is unbound.“ The program hangs up.
(doing the same from the console, I get the answer “1”.)

When I look at the xml-editor, it tells me that “a” was sent to Maxima. But it should be “$a”, shouldn’t it? Getting only “a”, Maxima’s response would be understandable.
Another try was to input “$$a”. But again I get the same error message: variable A unbound. And the xml-editor again tells me that what was sent to Maxima was “a”. So my guess is that the $-sign is somehow lost in wxMaxima.

I checked that in my wxMaxima settings I have correctly set my installer’s Maxima 5.40.

**Comment by gunterkoenigsmann** [comment]
I'm convinced that T have resolved this problem in the meantime.
