### ISSUE TITLE
Updated Spanish wxmaxima 17.05-1 and 16.12-2

### ISSUE THREAD

**Issue by cyphra** [andrejv/wxmaxima#907]
[wxmaxima-17.05-1.es.po.gz](https://github.com/andrejv/wxmaxima/files/1170892/wxmaxima-17.05-1.es.po.gz)
[wxmaxima-16.12-2.es.po.gz](https://github.com/andrejv/wxmaxima/files/1170893/wxmaxima-16.12-2.es.po.gz)

**Comment by ciampix** [comment]
I think this can be closed since #925 (merged) already updated the same strings...

**Comment by gunterkoenigsmann** [comment]
I never dared to close this issue. ...and I thank you for working on the translations.

---

If you are willing to do this: In the last few weeks I have added many additional strings to https://github.com/andrejv/wxmaxima/tree/master/locales - and everything I had planned for the next wxMaxima release is now in place...

Kind regards,
 Gunter.
