### ISSUE TITLE
wxMaxima command line options

### ISSUE THREAD

**Issue by Mequin** [andrejv/wxmaxima#908]
I do have several issues with the command line options of  wxMaxima  17.05.0   
( for Maxima 5.40.0  SBCL 64 bits Windows 10 )

=======================================================

The -ini option crashes with a  ( Visual Studio ? ) message

=======================================================

The -open option hangs on the FIRST cell without executing the file content displayed 
on cells 2, 3, 4 etc ...

=======================================================

The -batch option does not QUIT and thus has a behavior similar to what --open should be 
except that the file is processed TWICE

In fact the --batch option should execute the file once and then QUIT

=======================================================

So, I need help 

Regards
   Jacques

**Comment by gunterkoenigsmann** [comment]
The -ini thing I cannot test for as I currently have no windows computer. But for the rest of the options I have changed many things since the release => Would you be willing to test if the current nightly build from http://wolfgang.dautermann.at/maxima/nightlybuild/ fixes the other 2 problems?

Thanks a lot,
and kind regards,

  Gunter

**Comment by Mequin** [comment]
Gunter ,


I have tried this morning your current release, all the 3 tested options are still broken


--ini    that  I do not really need, but is a legal option,  returns the following popup


[cid:048c29bf-e450-4f05-9e9e-5c60a0adc9e7]


--open   that is really the one I need, returns the following screen where you can see the 3 lines of my file

                   but that the cursor is waiting a user action on the top line



[cid:a3e4a2cd-5e6d-41d8-a392-78bdc883c34c]



--batch  does not quit  as it should (it is a batch), but behaves more or less like --open should be

                     however, the file is executed twice

                     Yes, there is only one "HELLO" but my file proves that the file has been executed twice  ( because of "second run" )


            print( "HELLO" ) $

            if run2_ready = true then print( "second run" ) $
            run2_ready : true ;


[cid:ff64e733-ae6a-4a54-8c50-68310e3778d7]


Regards,

   Jacques


________________________________
De : Gunter Königsman <notifications@github.com>
Envoyé : samedi 29 juillet 2017 00:43
À : andrejv/wxmaxima
Cc : Mequin; Author
Objet : Re: [andrejv/wxmaxima] wxMaxima command line options (#908)


The -ini thing I cannot test for as I currently have no windows computer. But for the rest of the options I have changed many things since the release => Would you be willing to test if the current nightly build from http://wolfgang.dautermann.at/maxima/nightlybuild/ fixes the other 2 problems?

Webseite von Wolfgang Dautermann<http://wolfgang.dautermann.at/maxima/nightlybuild/>
wolfgang.dautermann.at
Parent Directory - buildlog-win32: 24-Jul-2017 00:17 : 2.1M: Log of the 32 bit crosscompiled build: buildlog-win64: 24-Jul-2017 00:18 : 2.0M: Log of the 64 bit ...



Thanks a lot,
and kind regards,

Gunter

**Comment by Mequin** [comment]
I have downloaded the nightlybuild

maxima-clisp-sbcl-current-win64.exe  22-Aug-2017

The --open option still waits user actions in order to evalute the file content shown on the screen
The --batch options does not quit after file completion ( and still executes it twice )

Regards

PS:  I am using the following test file 

      nbexec : if integerp( nbexec ) then nbexec + 1 else 1 $
      print( "nbexec " , nbexec ) $

**Comment by Mequin** [comment]
I have tested the latest nightlybuild  maxima-clisp-sbcl-current-win64.exe  01-Sep-2017 00:32

Command line options  --ope n and  --batch  still broken 

Regards

**Comment by gunterkoenigsmann** [comment]
The good news is: Today I have found a way to reproduce the problem on my system => I am confident that in the next few days I will find the cause of the problem.

**Comment by Mequin** [comment]
Thanks a lot for your time solving this issue

Partly for the Nice University (France) I have developed a flow
for simulating LTI analog circuits 

Starting from a schematic editor (visual studio) that generates
a ".mac" file,  I am using wxMaxima to calculate symbolically the 
Laplace transforms of some user requested voltages, currents, ...
as well as the symbolic matrices ( A, B, C, D ) of the associated 
State Model

Then Maxima generates a C language ".h" file suitable for the
simulation of the circuit ( not through a convergence, but based
on matrix operations performing the Recursive Convolution of the 
State Model )

All this to explain that the command line options are necessary to
allow the making of an automated flow around Maxima

I will be happy to test any corrected version

Regards,
    Jacques
