### ISSUE TITLE
qdraw with wxmaxima not working

### ISSUE THREAD

**Issue by jhanly** [andrejv/wxmaxima#909]
I've been trying to use qdraw to make some plots.  qdraw does not work with wxmaxima.  If i use it in Maxima it works fine, When I call it in wxmaxima I get no output at all. No plot and no error message.  I'm running on an iMac with Sierra. I'm using Maxima 5.38 and wxmaxima 16.04.0

**Comment by gunterkoenigsmann** [comment]
On mac computers sometimes plots make problems if "use pngcairo" is enabled in the settings dialogue of wxMaxima. Alternatively you can try if the "plot/plot format" menu item allows to select a format that works better.

**Comment by gunterkoenigsmann** [comment]
The new version of wxMaxima will warn if a setting is selected that is known to give problems.
