### ISSUE TITLE
Need Some Help To Get The Result

### ISSUE THREAD

**Issue by unique33** [andrejv/wxmaxima#911]
In The Name Of GOD
----------------------------------------------------------------------
The Result Of The Following Expression Is :
1 

Please Help Me To Get The Result From The Bellow Expression :

```
set_display('none)$;
atan(floor(tan(%pi/2 - 0.01*10^-305)))/atan(tan(%pi/2 - 0.01*10^-305));
```

**Comment by gunterkoenigsmann** [comment]
Wow... what has happened that you need the result this urgently? 

I hope float(), eventually coupled with radcan() will help you. Also I believe the result not to be an exact 1. There is one caveat for radcan, though: if a trigonometric function has more than one result radcan will only pick one.

As wxMaxima only displays the math but doesn't actually do the calculations I expect you will get better help from http://maxima.sf.net 

Will close the request here for this reason. But I will read your answers so if with my limited mathematical knowledge I can be of any help I will try to.
