### ISSUE TITLE
Tensor.dem fails in tendemo.mac

### ISSUE THREAD

**Issue by richardgobeli** [andrejv/wxmaxima#914]
Xmaxima has reported that the tendemo.mac works in command line mode below.

When running in the Wxmaxima mode the long printing interferes with the read statements.  I needed to add delays before the reads can be executed.
I can't attach file, because you don't allow 7zip.
Example is below.

Thanks Richard

Also works for me using xmaxima (on the same box as before). I don't have wxmaxima available to test with right now.
Richard: Like Viktor said, this could be a problem in wxmaxima. If you are using wxmaxima, would it be possible for you to try this out in plain (text mode) Maxima and let us know whether or not you see the same behavior there?
________________________________________
[bugs:#3325] Tensor.dem fails in tendemo.mac
Status: open
Group: Includes_proposed_fix
Created: Tue Aug 15, 2017 04:42 AM UTC by Richard Gobeli
Last Updated: Sun Aug 20, 2017 08:29 PM UTC
Owner: Viktor Toth
Attachments:
•	tendemo.mac (6.2 kB; application/octet-stream)
tensor.dem loads tendemo.mac. The printing of the selectable options causes the read selection not to work. It is like the read is executed before the printing. is done. There are three positions in this file where the read selction does not work without the delay.
I got it to work if I run a for loop to delay the read selection unil after the printing is done.
Example is here in tendemo.mac.
print("A. Algebraic tensor manipulation"),
print("E. Complete examples"),
print("X. Exit this demo"),
print(""),
/ the following line is added so the read will work. /
for a: 1 thru 26000 step 1 do a*a,
sel:read("Select an option by its number followed by a semicolon (;)"),
if sel=1 then demo(itensor1)
else if sel=2 then demo(itensor2)
The modified file is attached.
________________________________________
Sent from sourceforge.net because you indicated interest in https://sourceforge.net/p/maxima/bugs/3325/
To unsubscribe from further messages, please visit https://sourceforge.net/auth/subscriptions/

**Comment by gunterkoenigsmann** [comment]
I believe this to be resolved in the current nightly build of wxMaxima.

**Comment by richardgobeli** [comment]
I think it still fails.  I ran it and I went to option 13 and it failed on this input %i13.
It also failed another time on line %i21 ricci(true).  attached is the spot.  both times I selected option 13.
![capture](https://user-images.githubusercontent.com/31253976/29591991-4f5c3eca-8767-11e7-9ec2-790d359b1b8a.PNG)

**Comment by richardgobeli** [comment]
It does work.  I made a mistake.  The demo was still calling the older version. I had to set config to call maxima.bat in the current folder.

**Comment by gunterkoenigsmann** [comment]
That's good news: Bugs that cannot be reproduced on my computer tend to be loads of work...
