### ISSUE TITLE
tex output wrong

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#917]
When using tex on an expression that contains Greek characters the output text contains the actual Greek characters which is not recognized by TeX, it should be translated to e.g. "\greek name"

Example: this is the output result
$$-{{e^{2\,α-2\,β}\,\left(r\,α_{r}\,β_{r}-r\,α_{r\,r}-r\,\left(α_{r}
 \right)^2-2\,α_{r}\right)}\over{r}}$$

It should be:
$$-{{e^{2\,\alpha-2\,\beta}\,\left(r\,\alpha_{r}\,\beta_{r}-r\,\alpha_{r\,r}-r\,\left(\alpha_{r}
 \right)^2-2\,\alpha_{r}\right)}\over{r}}$$

Now, I have to manually do the change.

Thanks,

Daniel Volinski

**Comment by gunterkoenigsmann** [comment]
On my computer this works fine. Which version are you using currently and could you verify if the problem persists with the nightly build?

Thanks a lot,

  Gunter.

**Comment by danielvolinski** [comment]
Hi Gunter,

I tried
build_info(version="5.38.1",timestamp="2016-06-12 17:13:34",host=
"i686-pc-mingw32",lisp_name="SBCL",lisp_version="1.3.4")

build_info(version="5.40.0",timestamp="2017-06-01 19:34:13",host=
"i686-pc-mingw32",lisp_name="SBCL",lisp_version="1.3.12")

with the same result.

I usually do not mess with intermediate builds.
My policy is to use only official releases.
If you tell me this bag has been solve, I will wait for the next official release.
For the time being I will do it manually.

Thanks,

Daniel Volinski

**Comment by gunterkoenigsmann** [comment]
The next question would be: Do you use wxMaxima's right-click menu for exporting to TeX or maxima's built-in TeX export?

**Comment by danielvolinski** [comment]
I use maxima's build-in TeX export

**Comment by gunterkoenigsmann** [comment]
Ok... ...on maxima's built-in TeX formatter wxMaxima has no influence. But you can ask the programmers at http://maxima.sourceforge.net if they know a way to support greek characters. As they work fine with the rest of maxima the TeX output should be able to deal with them, perhaps.

**Comment by danielvolinski** [comment]
Ok, thanks.
I will start to use the wxMaxima's right-click menu for exporting to TeX
