### ISSUE TITLE
assertion errors during startup

### ISSUE THREAD

**Issue by 0-wiz-0** [andrejv/wxmaxima#922]
I've just tried building wxmaxima 17.05.1 on NetBSD with cmake.
It built fine, but during startup I get lots of pop ups with assertion errors, and on the console I see:
````
./src/gtk/bitmap.cpp(814): assert "IsOk()" failed in ConvertToImage(): invalid bitmap
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
./src/common/image.cpp(1746): assert "IsOk()" failed in GetHeight(): invalid image
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
./src/common/image.cpp(429): assert "IsOk()" failed in Scale(): invalid image
./src/gtk/bitmap.cpp(627): assert "image.IsOk()" failed in wxBitmap(): invalid image
./src/gtk/bitmap.cpp(814): assert "IsOk()" failed in ConvertToImage(): invalid bitmap
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
./src/common/image.cpp(1746): assert "IsOk()" failed in GetHeight(): invalid image
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
./src/common/image.cpp(429): assert "IsOk()" failed in Scale(): invalid image
./src/gtk/bitmap.cpp(627): assert "image.IsOk()" failed in wxBitmap(): invalid image
./src/gtk/bitmap.cpp(814): assert "IsOk()" failed in ConvertToImage(): invalid bitmap
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
./src/common/image.cpp(1746): assert "IsOk()" failed in GetHeight(): invalid image
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
./src/common/image.cpp(429): assert "IsOk()" failed in Scale(): invalid image
./src/gtk/bitmap.cpp(627): assert "image.IsOk()" failed in wxBitmap(): invalid image
./src/gtk/bitmap.cpp(814): assert "IsOk()" failed in ConvertToImage(): invalid bitmap
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
./src/common/image.cpp(1746): assert "IsOk()" failed in GetHeight(): invalid image
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
./src/common/image.cpp(429): assert "IsOk()" failed in Scale(): invalid image
./src/gtk/bitmap.cpp(627): assert "image.IsOk()" failed in wxBitmap(): invalid image
./src/gtk/bitmap.cpp(814): assert "IsOk()" failed in ConvertToImage(): invalid bitmap

````
after which I gave up confirming the assertions.

Am I missing a dependency, or are some files missing from the
installation?
(From the error message, I guess perhaps icons?)

**Comment by gunterkoenigsmann** [comment]
That looks like being an accurate diagnosis. I assume you have started the program without installing it first - which means that the icons still aren't where the program assumes them to be. In this case the git head should work much better. Also it contains a few corrections to the logic that searches for the icons and fallbacks if icons the system should provide cannot be found. If that doesn't help do a

     gdb wxmaxima
     run

tell the assert dialogue to crash the program and then do a
    
     backtrace

in the gdb console which should lead to a stack trace showing where the problem resides.

In order to make that work sometimes a

      cmake -DCMAKE_BUILD_TYPE=debug;make;sudo make install

is necessary.

**Comment by 0-wiz-0** [comment]
I did install it in my first tries. Here is a list of all the png,
jpg, and xpm files that did install:

````
share/doc/wxmaxima/Autocomplete1.jpg
share/doc/wxmaxima/Autocomplete2.jpg
share/doc/wxmaxima/BatchImage.jpg
share/doc/wxmaxima/BatchImage.png
share/doc/wxmaxima/InputCell.jpg
share/doc/wxmaxima/Matrix table example.png
share/doc/wxmaxima/MatrixTableExample.png
share/doc/wxmaxima/NoiseFilter.jpg
share/doc/wxmaxima/Second table example.png
share/doc/wxmaxima/SecondTableExample.png
share/doc/wxmaxima/SidePanes.jpg
share/doc/wxmaxima/ezUnits.jpg
share/doc/wxmaxima/ezUnits.png
share/doc/wxmaxima/maxima_screenshot.png
share/doc/wxmaxima/sbclMemory.png
share/doc/wxmaxima/wxMaximaLogo.jpg
share/doc/wxmaxima/wxMaximaLogo.png
share/doc/wxmaxima/wxMaximaWindow.jpg
share/doc/wxmaxima/wxMaxima_configuration_001.jpg
share/doc/wxmaxima/wxMaxima_configuration_001.png
share/doc/wxmaxima/wxMaxima_configuration_002.jpg
share/doc/wxmaxima/wxMaxima_configuration_002.png
share/pixmaps/wxmaxima-16.xpm
share/pixmaps/wxmaxima-32.xpm
share/pixmaps/wxmaxima.png
share/wxMaxima/Document-export.png
share/wxMaxima/editing.png
share/wxMaxima/maxima.png
share/wxMaxima/network-error.png
share/wxMaxima/network-idle.png
share/wxMaxima/network-offline.png
share/wxMaxima/network-receive.png
share/wxMaxima/network-transmit-receive.png
share/wxMaxima/network-transmit.png
share/wxMaxima/options.png
share/wxMaxima/styles.png
share/wxMaxima/wxmaxima.png
````

Per your suggestion I tried the latest git head, both uninstalled and
installed, and got the same behaviour.

Then I wanted to run gdb on it, and here is where it gets confusing.
The test-installed wxmaxima binary does not find wxWidgets (missing rpath)
so I start it with `LD_LIBRARY_PATH=/usr/pkg/lib wxmaxima`. When I do
that, I get the assertions like before.

When I insert `gdb` in the middle, like this:
`LD_LIBRARY_PATH=/usr/pkg/lib gdb wxmaxima`, then wxmaxima starts up
fine. I don't understand this behaviour.

When I try the same thing on the uninstalled wxmaxima (i.e. with and without gdb), I see the assertions.

**Comment by krytarowski** [comment]
Please check PaX MPROTECT disabled. GDB disables it for a process.

**Comment by 0-wiz-0** [comment]
That is interesting. Turning off MPROTECT, either globally or with `paxctl +m wxmaxima`, fixes the problem.

**Comment by 0-wiz-0** [comment]
So, to summarize:
17.05.1 is broken (for me) because it doesn't install enough of its icons (even when turning off MPROTECT)
git head works fine when I turn off MPROTECT for the wxmaxima binary.

Please make a new release with the icon installation/search fixes. Thanks!

**Comment by gunterkoenigsmann** [comment]
One additional thing I would need to know: If you do a

    strace wxmaxima

with the git head and without mprotect... ...are the icon files then opened according to strace's output? Not that wxWidgets opens the files, but mprotect somehow hinders them from being decoded...

**Comment by krytarowski** [comment]
strace is under restoration on NetBSD, there is a native tool for similar purposes: ktruss(1).

PaX MPROTECT means that there is mmap(2) call for (R)WX allocation and we return EACCES. As we enforce W^X. There is an API to workaround it and support double mappings RW and RX of the same memory pages.

It may also fail for mprotect(2) calls, which attempt to grant more privileges for already mmap(2)ed memory pages. We have API for this too, to allow such scenarios.

From a quick look, I don't see mmap(2) or mprotect(2) in wxmaxima so it should be propagated from its dependencies.

**Comment by gunterkoenigsmann** [comment]
That's my guess, too: wxMaxima delegates file I/O, bitmap handling, drawing the gui elements as well as parts of the general memory management to wxWidgets so if MPROTECT affects mmap() and mmap() is mostly used for file I/O I expect the error to lie somewhere in wxWidgets.

**Comment by 0-wiz-0** [comment]
It's still slightly mysterious to me, since wxGTK 3.0.3 only has references to`mmap()` in the included expat and tiff sources, which should not be used in pkgsrc (where we use the packages for expat and tiff); and no references to `mprotect()` at all.

**Comment by gunterkoenigsmann** [comment]
Perhaps I found it: wxWidgets uses libpng, if it can and libpng once had mmap problems.

**Comment by 0-wiz-0** [comment]
`png-1.6.32` contains not a single call to `mmap()` nor `mprotect()`.

**Comment by gunterkoenigsmann** [comment]
Then maybe a library libpng uses calls one of these commands. Or these commands are called implicitely by something libpng does do...

...perhaps one could put a breakpoint on mmap() and mprotect() and see who calls them...

**Comment by 0-wiz-0** [comment]
I've tried reproducing/tracing with 17.10.1.
The problem with tracing `mmap()` and `mprotect()` is that it is heavily used by `ld.elf_so` itself.
I gave up after some time, only to find that 17.10.1 works without the paxctl settings.
So all fine now, thank you!
