### ISSUE TITLE
input area goes blank after printing to PDF 

### ISSUE THREAD

**Issue by OliverLew** [andrejv/wxmaxima#923]
The printed file is perfect, everything is in it. And I think actually all the cells still exist because I can still select & copy things into text editors, and right click on different place has different menus. The thing is, I can't see the cells after print to file.

There is one detail I found: after printing to file, the input area won't turn blank until some input(keyboard or mouse), in case this helps.

My Build info:
```maxima
(%i1)	wxbuild_info()$
wxMaxima version: 17.05.1
Maxima version: 5.40.0
Maxima build date: 2017-07-22 12:37:29
Host type: x86_64-unknown-linux-gnu
System type: Linux 4.9.47-1-MANJARO x86_64
Lisp implementation type: ECL
Lisp implementation version: 16.1.2
```
(And I am using the latest version of GNOME)

**Comment by gunterkoenigsmann** [comment]
Printing is quite a beast. Especially as I don't use it.

...but the error should already be resolved in the current source code and will be corrected in the next release. At least I hope so...

**Comment by OliverLew** [comment]
@gunterkoenigsmann Indeed! It is resolved in the git version. Thank you!
