### ISSUE TITLE
--open command line option

### ISSUE THREAD

**Issue by Mequin** [andrejv/wxmaxima#924]
I have downloaded the maxima-clisp-sbcl-current-win64.exe  14-Sep-2017  nightly build

Thanks you so much for solving the  --batch  option ( that now executes only once and then quit as it should )

There is still an issue with the  --open  option since it requires, from the user, to effectively call the GUI 
"Execute All Cells" to complete the file execution

![snapshot](https://user-images.githubusercontent.com/14158309/30438356-46ec600a-9971-11e7-907d-c685fd5532f5.png)

Regards,
  Jacques

**Comment by gunterkoenigsmann** [comment]
Traditionally the --open option just did, what it says: It opened files. --batch opens files, evaluates them and closes them afterwards.

...do I understand it right that you would need an option instead that opens, evaluates - but doesn't close afterwards? If this is correct I will write this option.

**Comment by Mequin** [comment]
Yes, this is perfectly right, an option that preload an user file before its interactive work
( so, like --batch but without quit )

By the way, the documentation is unclear, what is suppose to be the behavior of the --init option ???
( that also claims to **open** an input file )

Regards,
    Jacques

**Comment by gunterkoenigsmann** [comment]
Where did you find this documentation for the --init switch?

I guess the purpose of this switch is to tell wxMaxima to store the config in an text file whose name you can specify instead of in the registry.
