### ISSUE TITLE
Spanish translation update

### ISSUE THREAD

**Issue by cyphra** [andrejv/wxmaxima#925]
[wxmaxima-17.05-2.es.po.gz](https://github.com/andrejv/wxmaxima/files/1309385/wxmaxima-17.05-2.es.po.gz)

**Comment by gunterkoenigsmann** [comment]
We are currently preparing for a new release => If you translate additional strings from https://raw.githubusercontent.com/andrejv/wxmaxima/master/locales/es.po they will be included in the next version.

Thanks a lot,
 Gunter.

**Comment by ciampix** [comment]
Thanks for the heads-up ... I'm updating ... 
BTW:
1) in src/wxmaxima/src/wxMaxima.cpp:4979 I think there are some spaces missing...
2) still ./configure is not working any more (Ubuntu 16.04 here...)

**Comment by ciampix** [comment]
aaand typo here:
/home/gunter/src/wxmaxima/src/wxMaximaFrame.cpp:951

**Comment by gunterkoenigsmann** [comment]
Ok... ...the typos are fixed. And

     ./configure

 no more works since I didn't find out what has broken it and we have replaced it by

    cmake .

instead, anyway - which in theory is a way cooler build system that (besides others) should provide support for xcode, code::blocks and microsoft visual studio.

**Comment by ciampix** [comment]
Veeery good! I forgot to make a git clean...

Other typo/spaces missing (sorry I find these whenever I come across them when translating...):
/home/gunter/src/wxmaxima/src/wxMaxima.cpp:4922
and another space missing here:
src/wxmaxima/src/wxMaxima.cpp:4877

**Comment by gunterkoenigsmann** [comment]
I hope I found the right ones: The line numbers seem to have changed. But I found two missing spaces. And no need to be sorry at all: Translating is the only time one finds such a thing. And spaces are important.
