### ISSUE TITLE
On macosX brew upgrade [or install] wxmaxima; wxmaxima does not work

### ISSUE THREAD

**Issue by puiseux** [andrejv/wxmaxima#930]
My os is OSX El Capitan-10.11.6
here are the command lines and messages:

mac-pro-de-pierre:Documents puiseux$ brew uninstall --force wxmaxima
Uninstalling wxmaxima... (187 files, 15.2MB)
mac-pro-de-pierre:Documents puiseux$ brew install wxmaxima
==> Downloading https://homebrew.bintray.com/bottles/wxmaxima-17.10.0.el_capitan.bottle.tar.gz
Already downloaded: /Users/puiseux/Library/Caches/Homebrew/wxmaxima-17.10.0.el_capitan.bottle.tar.gz
==> Pouring wxmaxima-17.10.0.el_capitan.bottle.tar.gz
==> Caveats
When you start wxMaxima the first time, set the path to Maxima
(e.g. /usr/local/bin/maxima) in the Preferences.

Enable gnuplot functionality by setting the following variables
in ~/.maxima/maxima-init.mac:
  gnuplot_command:"/usr/local/bin/gnuplot"$
  draw_command:"/usr/local/bin/gnuplot"$
==> Summary
🍺  /usr/local/Cellar/wxmaxima/17.10.0: 214 files, 29.4MB
mac-pro-de-pierre:Documents puiseux$ wxmaxima
08:52:20: Debug: Unknown accel modifier: 'maj'
08:52:20: Debug: Unknown accel modifier: 'maj'
08:52:20: Debug: Unknown accel modifier: 'maj'
08:52:20: Debug: Unknown accel modifier: 'maj'
08:52:20: Debug: Unknown accel modifier: 'maj'
08:52:20: Debug: Unrecognized accel key 'entrée', accel string ignored.
08:52:20: Debug: Unknown accel modifier: 'maj'
./src/common/image.cpp(1739): assert "IsOk()" failed in GetWidth(): invalid image
Collecting stack trace information, please wait...Trace/BPT trap: 5

**Comment by gunterkoenigsmann** [comment]
The warnings you got seem to indicate that the .po file containing the translation for your language has errors: The accellerators and hotkeys are taken from there. 

For the error itself: Seems like wxMaxima cannot find an image file. If you tell the assert dialogue not to crash the program in order to enter the debugger: Can you see which image is missing? Thanks a lot,
Gunter.
