### ISSUE TITLE
Wrong language in GUI under Win (Closed bug is still there)

### ISSUE THREAD

**Issue by Hale812** [andrejv/wxmaxima#931]
After clear reinstalling the newest version of Maxima (version: 17.05.0), I see the same old bug in wxMaxima, which should have been resolved half a year ago.
https://github.com/andrejv/wxmaxima/issues/847
Some elements in wxMaxima take incorrectly "windows location" as a guide for language selection, but not the "windows display language", or config-defined language. 
![image](https://cloud.githubusercontent.com/assets/25519954/22577392/bedff166-ea04-11e6-92b7-056a73c037f2.PNG)
That is a common mistake made by English-speaking programmers not familiar with windows machines operating in eastern Europe and Asian countries. Should be fixed to comply with "windows display language" or Maxima config.

**Comment by gunterkoenigsmann** [comment]
I think I understand now what you mean: 

Tektronix Oscilloscopes 
- either use english as GUI language or 
- speak german, but also output numbers that use a "," as a decimal dot which means that "1.29,1.35" is saved as "1,29,1,35" which makes all CSV files basically useless.

There is no way to make them speak german, but use english numbers.

...but normally the locale should affect the numbers the program outputs and all the text (including the pane titles) should be defined by the "language" setting. Is that correct? If this is true: What pieces of text are in the wrong language? Perhaps I can find a pattern.

**Comment by gunterkoenigsmann** [comment]
I maybe have found the problem: Along with the position of all floatable windows  wxWidgets saves their names. And restores their name again along with the translations of their title replacing any newly selected translations. Unfortunately wxWidgets doesn't seem to provide a way to replace the name of an already-placed pane.

**Comment by ciampix** [comment]
I wonder how other xwwindows programs have solved this issue then ... because for example audacity does not have these issues, nor KiCad and both are wxwindows programs...

**Comment by gunterkoenigsmann** [comment]
Good point! Will try to find this out.

**Comment by ciampix** [comment]
Luckily that could mean that if you have found the potential source of the problem you should be nearer to a solution or a workaround. I am just sorry to be mere translator and not a wxwindows programmer and therefore unable to lend you a hand...

**Comment by gunterkoenigsmann** [comment]
If you were a wxWindows programmer I would ask you if you could help with finding out why the accessibility for the blind in MathCtrl isn't working. Which I am completely lost at. For the rest we need loads of translators and testers - and this time we needed two testers for finding the reason for this bug. At least I am convinced that tomorrow's nightly build will finally resolve it. Please protest if it doesn't.

**Comment by ciampix** [comment]
I use to compile from git master. If the master is already updated I am sorry to say that I still see untranslated dialog titles...
