### ISSUE TITLE
Unexpected formatting

### ISSUE THREAD

**Issue by oakleaflr** [andrejv/wxmaxima#937]
(%i1)	wxbuild_info();
wxMaxima version: 17.10.1
Maxima version: 5.41.0a_dirty
Maxima build date: 2017-10-24 09:10:11
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.206])
(%o1)	
(%i2)	%/* Test */
	a:5;
incorrect syntax: a is not an infix operator
a:
 ^
(%i2)	/* Test */
	a:5;
(a)	5

In i2 above I typed /* Test */ but get something else.  Copy and paste to i2 and remove the % and the cell is ok.
This is a brand new install and I am just trying to enter a comment in a cell. Don't see this in older version of wxMaxima.

**Comment by gunterkoenigsmann** [comment]
You have checked "Insert % before an operator at the beginning of the cell" in the config dialogue. This makes wxMaxima to prefix  the "/" with an "%". What do you think? Does it make sense to catch this case and to change "%/*" to "/*" again hoping that nobody actually wants to input "%/*"?
Or would this add complexity to the code while merely moving the strange behavior from one place to another?
Thanks a lot,
Gunter.

**Comment by oakleaflr** [comment]
Gunter,

I don't vote for more complex code.  This behavior just surprised me since
I often add some comments in a cell when  I try  something new in Maxima
and if my memory is correct (which it may well not be) this didn't happen
before in an earlier version of wxMaxima.

I do have a follow on question.  Should the same behavior happen in a
WxMaxima "text cell"?

In any event thanks for your interest.

Larry

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Mon, Nov 13, 2017 at 12:14 AM, Gunter Königsman <notifications@github.com

**Comment by gunterkoenigsmann** [comment]
I will make the "Insert % before an operator" checkbox in the config dialogue default to "off": The idea behind this setting is that if you just want to divide the last equation maxima has output by 2 you just have to type "/2" and wxMaxima understands that you wanted to type a "%/2". Which saves one key press but surprises most Users I know. If you turn this setting off on your computer manually the program should do exactly what you want it to.

---

If an EditorCell that isn't used for code it doesn't make sense to add an "%" to the beginning of the cell if its first letter looks like being an operator.
