### ISSUE TITLE
Problem with "Ctrl-C"

### ISSUE THREAD

**Issue by RolandSalz** [andrejv/wxmaxima#940]
Habe in der Version17.10.0 unter Windows ein Problem mit dem Kopieren. Wenn ich einen Bereich aus einer wxMaxima-Eingabe markiere, so kann ich ihn zwar mit dem Befehl „Kopieren“ aus dem Menü „Bearbeiten“ in die Zwischenablage befördern, nicht jedoch mit der Tastenkombination „Ctrl-C“. Ich bekommen in diesem Fall dann mit Ctrl-V nicht diesen zuletzt markierten Bereich zurück, sondern den zu vorletzt markierten.

**Comment by gunterkoenigsmann** [comment]
War kompiziert, das: Hatte wxMaxima gesagt, es solle nicht mehr bei jedem Ereignis den gesamten Bildschirm neuzeichnen - sondern nur, wenn alle Tastendrücke und Mouseclicks abgearbeitet sind, die Teile, die sich geändert haben.

...und, wenn Text mit der mouse markiert worden ist, hab' ich die Toolbar vergessen, neuzuzeichnen. Dadurch war das "Copy"-Wekzeug inaktiv und Ctrl+C drückt auf dieses Werkzeug.

Ist im aktuellen Nightly Build behoben

Vielen Dank,
und Gruß,

  Gunter.
