### ISSUE TITLE
read_matrix from csv file gives a list [ , value] as the first element[1,1].

### ISSUE THREAD

**Issue by richardgobeli** [andrejv/wxmaxima#944]
I am using the latest released version.

The elements should all be values.

Here is the result of reading a csv file:
![capture](https://user-images.githubusercontent.com/31253976/34075154-6e62407c-e283-11e7-893e-948f865bb6ed.PNG)
work around is to use this after the read_matrix.
m[1,1] : m[1,1][2];   /* replace first element with the second value in the first element list.
I think this is in numericalio.lisp.

A similar thing happens when reading as a nested list.
read_nested_list has the same bug, because it uses the same read sub function.
![capture](https://user-images.githubusercontent.com/31253976/34075368-78493a1c-e28a-11e7-994e-1eef994b5f55.PNG)

Richard

**Comment by gunterkoenigsmann** [comment]
Weird: I'm using read_matrix all the time. But I've never experienced anything like this. Could you send me an example .csv file?

---

read_matrix is a maxima command. wxMaxima is merely the program that displays maxima's results and sends commands to maxima => If there is really a bug in read_matrix we'll have to ask the programmers at http://maxima.sourceforge.net to fix it.

**Comment by richardgobeli** [comment]
It does not let me reply to your e-mail.  I can't load a file here.

**Comment by gunterkoenigsmann** [comment]
You can reach me per e-mail as wxmaxima (at) physikbuch (dot) de.

**Comment by gunterkoenigsmann** [comment]
Ok... ...I've forwarded the bug report to https://sourceforge.net/p/maxima/bugs/3371/ and will close this ticket here as the problem needs to be addressed in another project.
Thanks for reporting it,
Gunter.
