### ISSUE TITLE
Spanish localization update

### ISSUE THREAD

**Issue by cyphra** [andrejv/wxmaxima#946]
[wxmaxima-17.05.1.es.po.gz](https://github.com/andrejv/wxmaxima/files/1583650/wxmaxima-17.05.1.es.po.gz)

**Comment by gunterkoenigsmann** [comment]
For the next version of wxMaxima many new translatable strings have been added, see: https://raw.githubusercontent.com/andrejv/wxmaxima/master/locales/es.po 

If you would be willing to translate them, too, that would be nice.

Kind regards,
 Gunter.

**Comment by ciampix** [comment]
On Sat, Dec 23, 2017 at 01:57:01PM -0800, Gunter Königsman wrote:
> For the next version of wxMaxima many new translatable strings have been added, see: https://raw.githubusercontent.com/andrejv/wxmaxima/master/locales/es.po 
> 
> If you would be willing to translate them, too, that would be nice.

Please note that here:

/home/gunter/src/wxmaxima/src/MathCtrl.cpp:1207

there is a small typo... (Restict -> Restrict?)

Regards

-- 


Marco Ciampa
