### ISSUE TITLE
Autocomplete command testing on windows 10.

### ISSUE THREAD

**Issue by richardgobeli** [andrejv/wxmaxima#948]
I think is partially working.  It will pull down the drop down list with the command CTL-k.
It will except a new character.  It is always a capital character that goes to the input line and the drop down list disappears.
This is after the new character is typed:

![capture](https://user-images.githubusercontent.com/31253976/34464762-c3e626a8-ee54-11e7-97ee-d87ae89649a8.PNG)

The mouse click does not work in the drop down list.  I can only select the correct command with the down arrow and then press enter. I can't use the mouse to select a correct command.
The capital letter stops the CTL-k from making a new drop down list.
Happy New Year!
Richard

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!

What I have learned is:

- On MSW key presses for a wxListBox in a pop-up menu don't arrive in the wxListBox but in the top-level window.
- wxWidgets provides two ways of handling keys: One callback that gets the uppercase version of what you get when you press the Key without Shift, Alt or Ctrl and one that gets the keycode you get with thes modifiers being pressed.
- and a wxListBox in a popup menu doesn't get mouse events. But the popup menu seems to get them => perhaps we have to forward them.
Let's see if commit 9a24aed8ea561fcf607c56ee9f3f28b59d4f1228 fixes all of these problems.

**Comment by richardgobeli** [comment]
I does not look like there was any change on this build from 1/1/18.  The files from 12/31/17 and now are the same.

**Comment by gunterkoenigsmann** [comment]
The Build server is a private computer => there is no guarantee that it is on at midnight and even if it is the build process might have crashed. But I will write the owner of the computer a Mail.

**Comment by gunterkoenigsmann** [comment]
Ok... ...it was my fault: On windows the new dialog needed a variable that wasn't needed on Linux and that I therefore commented out => Tomorrow's nightly build should work again.

**Comment by richardgobeli** [comment]
Typing CTL-TAB or CTL-k or CTL-SPACE the first time gives this error message:
![capture](https://user-images.githubusercontent.com/31253976/34505337-430f5152-efea-11e7-9d3b-51f47c54c1db.PNG)


I typed "so" then used CTL-TAB or CTL-k or CTL-SPACE, then the drop down list appears.
I continue to type "lve_"  and the drop down list shows only the current valid items. Example here:

![screenshot 1](https://user-images.githubusercontent.com/31253976/34505208-51785a8c-efe9-11e7-9459-968214691054.png)
When the drop down list has only one valid item, the list disappears and the command is auto-completed in the input line.

The down arrow can be used the select the command you want and typing enter will auto-complete the command in the input line.
It looks like it is working  without the mouse control.
Richard

**Comment by gunterkoenigsmann** [comment]
That's great news.

On Linux the letters that are typed are visible when the autocompletion window is active => will close this issue when I have a good idea on making it work on every OS.
