### ISSUE TITLE
Subscript and superscript swapped on load, but not after execute

### ISSUE THREAD

**Issue by moakanoni** [andrejv/wxmaxima#955]
The following image represents the state of part of a workbook immediately after being loaded:

![image](https://user-images.githubusercontent.com/11376129/35196158-2d8fd38e-fec6-11e7-8794-42f790eee5d8.png)

Notice in the first term of the first parenthesized term we have g_2^1.

After execution it looks like this:

![image](https://user-images.githubusercontent.com/11376129/35196171-5a058792-fec6-11e7-82f7-f2531ee9efcb.png)

The subscript and superscript are now the correct way round: g_1^2.

The same issue afflicts the first term just after the second opening parenthesis.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for reporting this!
