### ISSUE TITLE
Suggestion show %i and %e as symbols i and e in italics

### ISSUE THREAD

**Issue by richardgobeli** [andrejv/wxmaxima#963]
Macsyma converts all of these to symbols.  It makes it easier to read.
![capture](https://user-images.githubusercontent.com/31253976/35344547-09e752b6-00f3-11e8-9c22-a6b3c4faceb7.PNG)

**Comment by richardgobeli** [comment]
I see the config box for not keeping % sign with %i and %e.  The symbols are just normal i and e.  italic symbols would make them stand out in a equation.

**Comment by gunterkoenigsmann** [comment]
Still working on this. My first try misteriously failed to work.

**Comment by richardgobeli** [comment]
The description for h-bar should read horizontal bar or with stroke and not vertical bar.
Definition of h-bar is H with stroke, a Latin letter H with a doubled horizontal stroke (Ħ ħ)

**Comment by richardgobeli** [comment]
![capture](https://user-images.githubusercontent.com/31253976/35474869-fb28fc84-0359-11e8-9eb4-cfe3f871bcdd.PNG)

I don't think the italics worked for the i and e, but I think the other symbols are OK.
Some of the math symbols from the symbol table don't show.
When adding some more symbols some of the previous symbol now look OK.

**Comment by gunterkoenigsmann** [comment]
My guess is: You have configured wxMaxima to show all variable names in italic => the only way to make %e and %i special is to invert the "italic" flag again making them upright.

**Comment by richardgobeli** [comment]
How would I configure to show variable names in italic?  I don't think I have changed anything.  Now I can't get into configure, because of a crash.  I can do normal operations in math and there is no crash.

**Comment by gunterkoenigsmann** [comment]
If you hadn't reported that your configuration dialogue crashes I would say: Open the Config dialogue, go to "Styles" and select "Variables".

The change may be on my side: The worksheet now reads the configuration correctly. One day I will unify the code that reads the configuration for the worksheet and for the config dialogue. Currently they are (for big parts) separate code paths.

**Comment by richardgobeli** [comment]
Thanks,  I can go back to the last version where it did not crash and look at the styles and variables.

**Comment by richardgobeli** [comment]
I found that all my computers had the variables italic flag set already.   The changes you made do work when I have the italic flag unchecked.  Is this info stored in the register or somewhere not connected with wxMaxima and Maxima, because I changed the flag in the working version.  I uninstalled it and then installed your new version from today to my desktop.   I could get the %i to show the italic i.    I could not get to the configure page to verify the the italic flag was still unchecked.

**Comment by richardgobeli** [comment]
![capture](https://user-images.githubusercontent.com/31253976/35485534-0400b6e4-0459-11e8-861f-019109f08cac.PNG)
This is in ConfigDialogue.cpp
Does this show that the default for variables is italics true?

**Comment by gunterkoenigsmann** [comment]
This is the default for the config dialogue. The worksheet currently has its own default in Configuration.cpp. Hope they match.

Am 28. Januar 2018 19:30:20 MEZ schrieb richardgobeli <notifications@github.com>:
>
>![capture](https://user-images.githubusercontent.com/31253976/35485534-0400b6e4-0459-11e8-861f-019109f08cac.PNG)
>This is in ConfigDialogue.cpp
>Does this show that the default for variables is italics true?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/963#issuecomment-361084404

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
