### ISSUE TITLE
wxMaxima crashes when going to configure page.

### ISSUE THREAD

**Issue by richardgobeli** [andrejv/wxmaxima#965]
[crash.txt](https://github.com/andrejv/wxmaxima/files/1670349/crash.txt)
attached is the crash file and here is my build info
![capture](https://user-images.githubusercontent.com/31253976/35474665-24623276-0357-11e8-87be-ddd3682c8af5.PNG)
The init files are empty.

**Comment by gunterkoenigsmann** [comment]
On Linux crashes are simple-to-fix:
 - Start the program in gdb
 - make it crash
 - and type in "backtrace".
The result is a list which function has called which function with what
parameters finally leading to the crash => Easy debugging.

This time I cannot reproduce the crash on my computer. And the crash log
shows at what address in the memory the crash has happened. But I have
no way of telling what actually is to be found at this address =>

Is there any additional information I can start detective work with?

Thanks a lot,
and kind regards,

    Gunter.

**Comment by richardgobeli** [comment]
This is weird the same version from today runs on my laptop.  I can access the configure page.  The install version from today on my desktop runs OK, but it still crashes when trying to go to configure page.   I had to go back to 1-22-2018 to get a version that will allow my to start the configure page on my desktop computer.

**Comment by gunterkoenigsmann** [comment]
Microsoft requires the settings to be stored in the registry. If you search in regedit for ConfigDialogTab you'll find the storage for wxMaxima's settings.

As on 1-22-2018 nothing in the config dialogue code was changed I guess in order to trigger the problem the wrong value has to be in a variable being used without filling it with a value first by accident. Which a totally unrelated change makes sure. This kind of problem I only like if I have a debugger *and* if the debugger doesn't make the problem disappear ;-(

**Comment by richardgobeli** [comment]
I deleted all of the settings except my recent files.  I can now load the configure page.

I did noticed that the old setting had the ConfigDialogTab setting set to 1 and on the laptop and now the new settings that work are set to zero.  Would this be an indication the it thought the page was already loaded?

**Comment by richardgobeli** [comment]
[diff1.txt](https://github.com/andrejv/wxmaxima/files/1671357/diff1.txt)
This is the difference between the setting that did not work and the new settings that work.

**Comment by gunterkoenigsmann** [comment]
ConfigDialogTab is the info which tab of the config dialogue was open when the dialogue was closed the last time. In theory wxWidgets should catch the case is an invalid tab is selected. If it doesn't tomorrow's nightly build does do that, too.

Am 28. Januar 2018 18:35:11 MEZ schrieb richardgobeli <notifications@github.com>:
>I deleted all of the settings except my recent files.  I can now load
>the configure page.
>
>I did noticed that the old setting had the ConfigDialogTab setting set
>to 1 and on the laptop and now the new settings that work are set to
>zero.  Would this be an indication the it thought the page was already
>loaded?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/965#issuecomment-361080352

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gunterkoenigsmann** [comment]
Diffing the registry was an excellent idea! 
One setting tells to resume editing styles at the 33th style (0x20; the enumeration begins with 0).

My computer has killed Wayland in order to free memory for a big task => will count the styles tomorrow and see if it caused the problem. Tomorrow's nightly build should catch this case, if that is the problem...

Am 28. Januar 2018 18:38:29 MEZ schrieb richardgobeli <notifications@github.com>:
>[diff1.txt](https://github.com/andrejv/wxmaxima/files/1671357/diff1.txt)
>This is the difference between the setting that did not work and the
>new settings that work.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/965#issuecomment-361080610

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by richardgobeli** [comment]
I'll try reloading the saved wxMaxima register settings to see if your corrections will take care of this config crash.   I can also try deleting items in the register to find the area of error.

**Comment by gunterkoenigsmann** [comment]
That would be great! I've tried to covert the registry dump to a .wxMaxima file for my linux computer. But here I wasn't able to reproduce the crash.

If this night the nightly build compiles I perhaps have fixed something that might cause a crash under odd circumstances. But I am not sure.

**Comment by richardgobeli** [comment]
I found what causes the configure page to crash.  I had set the default font to Arial.
![capture](https://user-images.githubusercontent.com/31253976/35605975-129b86ba-0612-11e8-9b78-25473c8120c3.PNG)
![capture](https://user-images.githubusercontent.com/31253976/35605992-38c55fa0-0612-11e8-91a3-9b0796ce147e.PNG)
If I close the configure screen now, it will crash when I try to open it.
This is the setting in the registry.
![capture](https://user-images.githubusercontent.com/31253976/35606050-a953d18e-0612-11e8-822e-7f594684c51e.PNG)

**Comment by gunterkoenigsmann** [comment]
This font name is used only in ConfigDialogue::ExamplePanel::OnPaint - let's see what we can find here...

**Comment by richardgobeli** [comment]
It crashes also if I set the math font to Arial.

**Comment by gunterkoenigsmann** [comment]
I cannot confirm this on my computer but thanks to that information I have found out hat causes it. Thanks a lot!

**Comment by gunterkoenigsmann** [comment]
Actually this *should* have crashed on my computer, too ?!?

**Comment by richardgobeli** [comment]
Thanks to you too.

**Comment by richardgobeli** [comment]
I noticed that once you have selected a font, you have no way to go back to the default font.

**Comment by gunterkoenigsmann** [comment]
There is no "reset to default" button in wxFontSelector (which is the dialogue we use for asking for a font). But the font dialogue should offer the font wxWidgets chooses if no font is set. At least I hope so. If this isn't the case that would be a bug wxWidgets has to resolve.

**Comment by richardgobeli** [comment]
All you need to do is clear the font string and it will then use the default font.
