### ISSUE TITLE
Copy works only from left to right

### ISSUE THREAD

**Issue by DanteCpp** [andrejv/wxmaxima#968]
wxMaxima 17.10.1 on windows 10. 
The edit commands work only if I select the text from left to right, otherwise the text is unselected while performing the right click.

PS. the key combinations do not work as well but the text is not unselected during the keys pressing.

**Comment by gunterkoenigsmann** [comment]
Should be corrected in the current wxMaxima release. The Windows installer will still take a week. But the Nightly Build is fully functional in the meantime.
