### ISSUE TITLE
wxplot2d problem in 18.02.0: can't find .png file

### ISSUE THREAD

**Issue by jpcusumano** [andrejv/wxmaxima#973]
This occurs with successfully compiled wxmaxima 18.02 on Mint 17.3, Mint 18.3, and crunchbang++ (Debian 9), using maxima 5.41.0. 

Trying to use `wxplot2d`, on the worksheet I see
```
Message from maxima's stderr stream: 
set terminal png picsize 600 400; set zeroaxis;; 
"/tmp/maxout30857.gnuplot", line 1: unrecognized terminal option
```
and a popup error window that says:
```
can't open file '/tmp/maxout_30857_2.png' 
(error 2: No such file or directory)
```
Using just `plot2d` works fine in all cases. Inline plots work fine up to 17.10.1. The `/tmp` folder has permissions of 777. 

Seems that wxmaxima is failing to create the `.png` file because of a failed terminal setting. This happens with or without the "use cairo" box checked. 

Here's the head of `maxout30857.gnuplot`:
```
set terminal png picsize 600 400; set zeroaxis;; 
set zero 0.0
set term pngcairo
set output "/tmp/maxout_30857_2.png"
unset colorbox
set xlabel "x"
set ylabel "sin(x)"
set grid front
unset grid
set size ratio 0.75
set xrange [-10.00000000 : 10.00000000]
set zeroaxiset datafile missing "NaN"
plot [-10.00000000 : 10.00000000] '-' notitle with lines lt rgb "#0000ff"
-10. 0.5440211108893698 
-9.97844827586207 0.525812734914041 
-9.956896551724139 0.5073601405682313 
-9.935344827586207 0.48867189832241866 
-9.913793103448276 0.46975668809583467 
-9.892241379310346 0.4506232952249904 
-9.870689655172413 0.4312806063832537
```

**Comment by gunterkoenigsmann** [comment]
Temporary workaround: Put

     wxplot_old_gnuplot:false;

in wxMaxima's startup file (that can be found in the configuration dialogue).

**Comment by jpcusumano** [comment]
Well, that was an easy fix. Thanks!
