### ISSUE TITLE
possible false order on definite integration

### ISSUE THREAD

**Issue by jimishol** [andrejv/wxmaxima#974]
(%i3)	wxbug_report()$
The Maxima bug database is available at
	    http://sourceforge.net/p/maxima/bugs
	Submit bug reports by following the 'Create Ticket' link on that page.
	To report a Maxima bug, you must have a Sourceforge account.
	The wxMaxima bug database is available at
	    https://github.com/andrejv/wxmaxima/issues?direction=desc&sort=created&state=open
	Submit bug reports by following the 'New issue' link on that page.
	Please include the following information with your bug report:
	-------------------------------------------------------------
	wxMaxima version: 16.12.2
	Maxima version: 5.41.0
	Maxima build date: 2017-12-27 09:20:45
	Host type: x86_64-pc-linux-gnu
	System type: Linux 4.13.2-gentoo X86-64
	Lisp implementation type: SBCL
	Lisp implementation version: 1.4.2
-------------------------------------------------------------
(%i4)	integrate(2*r*y/(x^2+y^2), x);
(%o4)	2*r*atan(x/y)
So i expect integration from minf to inf to give 2*r*(pi/2-(-pi/2)=2*pi*r But i get for y>0
(%i5)	integrate(2*r*y/(x^2+y^2), x,minf,inf);
"Is "y" zero or nonzero?"n;
(%o5)	-2*%pi*r

**Comment by jimishol** [comment]
for the question "Is "y" zero or nonzero?" i answered, n assuming for nonzero.
If i give p for positive, i get the right answer
thank you

**Comment by gunterkoenigsmann** [comment]
I never knew that you can answer "y" here, too. But somehow the result for "n" not convinces meif the one for "p" should be right => Forwarded the question to the maxima-discuss mailing list hoping to learn something new about mathematics (often I do): wxMaxima is only the program that displays the worksheet. The actual work is done by the program that is to be found at http://maxima.sourceforge.net

Kind regards,
  Gunter.

**Comment by gunterkoenigsmann** [comment]
Will close the ticket here as it affects a different project.
