### ISSUE TITLE
legacy support for function array()

### ISSUE THREAD

**Issue by stephenathel** [andrejv/wxmaxima#975]
My program gives multiple instances of a message...
"ARRSTORE: use_fast_arrays=false; allocate a new property hash table for $EVARG"
even though the code works OK.
I have already tried all combinations of use_fast_arrays and translate_fast_arrays.
Could we make the display of the message an option, please?

**Comment by gunterkoenigsmann** [comment]
I hope this message will be gone with the next maxima release: It was introduced as a debug message and should be gone in the current nightly build. At least I hope so.

Tried in the nightly build. Seems I cannot reproduce the message here. If you still can please protest against me having closed the ticket or report the problem to http://maxima.sourceforge.net
