### ISSUE TITLE
18.02.0 / master About dialog no longer reports maxima/lisp versions on MacOS

### ISSUE THREAD

**Issue by jeanriemer** [andrejv/wxmaxima#976]
it seems the problem comes from incorrectly parsing the maxima process output rather than the socket output fed into the builtin TCP server. This used to be \_\_WXMSW\_\_ only before (up to V17.10) but now seems to be the case for all platforms - probably linux is also affected by this, due to the #ifdef \_\_WXMSW\_\_ protection the bug doesn't show up for Windows builds.
affected files: wxMaxima.cpp only.
Suggestion: remove abovementioned #ifdefs in ReadFirstPrompt, get rid of ReadProcessOutput altogether (for a maxima in TCP client mode it doesn't output anything we don't know already) and remove the call to ReadProcessOutput in ServerEvent. (see attached patch file for master branch)

[noRdProcOut.patch.TXT](https://github.com/andrejv/wxmaxima/files/1764025/noRdProcOut.patch.TXT)

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for the patch!

Am currently thinking if we should read out the lisp variables *autoconf-version* and autoconf-host* instead of relying on maxima's output as this might be more portable without any #ifdef...

**Comment by jeanriemer** [comment]
Not sure if I understand that (I might speak too few lisp for that, and I thought autoconf is sadly gone to favour cmake with V18+?)
but I think with this patch you get rid of a couple of #ifdef’s on the way and that’s surely a good thing…

Glad you found it useful.

Cheers,
  Jean

**Comment by gunterkoenigsmann** [comment]
cmake is very easy to configure and extremely powerful. For example it can automatically generate a Xcode project for wxMaxima. But I don't have a mac to test these features on so I don't know the details, unfortunately.

**Comment by jeanriemer** [comment]
Yeah, I know, but somehow I still prefer Makefiles, and thus use the "Unix Makefiles" generator instead (must be due to all the fuzz I went through with older cmake version a few years ago when Apple changed C-Compilers and SDKs at 3 times the pace as the cmake authors could follow..).
