### ISSUE TITLE
Just installed Windows version via the link in andrejv.github.io and got 16.04.2 (old version?)

### ISSUE THREAD

**Issue by dilijev** [andrejv/wxmaxima#977]
Is this really the most recent release?

**Comment by gunterkoenigsmann** [comment]
I get the following link: https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.41.0-Windows/

Which page did you find an older one on?

**Comment by dilijev** [comment]
Same page but I clicked on download latest which was apparently not latest.

![image](https://user-images.githubusercontent.com/494055/36817028-86ebea76-1c94-11e8-8938-e62d6bbfc1d3.png)

**Comment by dilijev** [comment]
Looks like many people are still downloading 5.38.1

https://sourceforge.net/projects/maxima/files/Maxima-Windows/
https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.38.1-Windows/

**Comment by gunterkoenigsmann** [comment]
I believe this problem could be resolved by changing the order of the folders on the sf.net download page: 5.38.1/Maxima-Windows. But I am not completely sure...
