### ISSUE TITLE
WxMaxima 17.10.1 crashes on CTRL+SHIFT+Z (Un-undo/Redo)

### ISSUE THREAD

**Issue by Hale812** [andrejv/wxmaxima#981]
WxMaxima 17.10.1 crashes on CTRL+SHIFT+Z (Un-undo/Redo)

"wxmaxima.exe has stopped working"

Windows 7 x64, latest x6x maxima for win. package.

**Comment by gunterkoenigsmann** [comment]
That is resolved in the nightly build at https://wolfgang.dautermann.at/maxima/nightlybuild/.
As soon as the new release of Maxima has taken place the installer will be updated with the newest wxMaxima release, as well.
