### ISSUE TITLE
Please don't include non-Linux screenshots in AppStream metadata

### ISSUE THREAD

**Issue by jbicha** [andrejv/wxmaxima#982]
As far as I'm aware, AppStream metadata is only used in *nix systems (Linux and presumably BSDs).

Therefore, please don't include the Windows and OS X screenshots in
https://github.com/andrejv/wxmaxima/blob/master/data/wxMaxima.appdata.xml

Thanks @ikeydoherty for noticing.

**Comment by jbicha** [comment]
(or credit to whoever wrote this [post](https://plus.google.com/+Solus-Project/posts/aSoqHPJxa1r))

**Comment by ikeydoherty** [comment]
Heh yeah that post was me xD
