### ISSUE TITLE
Can't make xmaxima plots under Windows: path error

### ISSUE THREAD

**Issue by Hale812** [andrejv/wxmaxima#990]
When plotting with xmaxima engine, wxMaxima is confused by paths with spaces, particularly "X:/Program Files/...". Therefore attempt to plot anything fails.

![image](https://user-images.githubusercontent.com/25519954/38850337-f1361c6c-424b-11e8-8e6e-a3613f5eb3fb.png)

wxMaxima version: 17.10.1
Maxima version: 5.41.0a_dirty
Maxima build date: 2017-10-24 09:10:11
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.206])

**Comment by gunterkoenigsmann** [comment]
That seems to be an error in maxima - and this error seems to be limited to plot: In draw it seems to work. I am no plot expert. But perhaps I can fix it.

Setting the environment variable MAXIMA_TEMPDIR in the control panel (I seem to remember it can be added in System/Advanced/Environment Variables) and rebooting the computer (Windows always wants a reboot) to something not containing a space should be a workaround until then.

**Comment by gunterkoenigsmann** [comment]
Unfortunately it seems like both plot and draw correctly quote the string containing the file name to plot to:

The beginning of maxout.gnuplot on my system reads:

    set terminal pngcairo solid background "white" enhanced font "arial,10" fontscale 1.0 size 600,400; set zeroaxis;; 
    set zero 0.0
    set term pngcairo
    set output "/tmp/maxout_9830_2.png"

But still gnuplot believes that every space ends a file name => If you are willing to report that problem to gnuplot you could improve the overall experience with many programs in the wild.

Closing this ticket for wxMaxima not because it isn't valid (it definitively is), but because I cannot do something for it in wxMaxima.

**Comment by gunterkoenigsmann** [comment]
That means: in xmaxima gnuplot isn't involved => will forward this bug report to the maxima developers.

**Comment by Hale812** [comment]
gunterkoenigsmann, I believe, there is a wrong title. The title is "xMaxima: MAXIMA_TEMPDIR isn't quoted "
well... but it does not look so.

just looking at maxima.bat, we can see
if not defined MAXIMA_TEMPDIR set "MAXIMA_TEMPDIR=%TEMP:\=/%"
if not exist "%MAXIMA_TEMPDIR%"/ set "MAXIMA_TEMPDIR=%USERPROFILE:\=/%"

In my case, TEMP resides in the disk-root (yeah, its windows, you know), and the userpath does not contain spaces, or special characters.

**Comment by gunterkoenigsmann** [comment]
wxMaxima isn't involved here: all it does is to forward you Xmaxima's error message and to tell you that xmaxima didn't generate a bitmap file that wxMaxima can load.

**Comment by Hale812** [comment]
no.. I mean, you created the ticket, that for some reason mentions %MAXIMA_TEMPDIR%, which does not look related to the problem, or did I miss something. May it be related to wxMaxima environment, which feeds system constants to Maxima? Why do you think, it is TEMP?
