### ISSUE TITLE
File / Open Recent should remember whether files were opened as a package

### ISSUE THREAD

**Issue by TomasRiker** [andrejv/wxmaxima#991]
I'm working on a big Maxima package. I load it using `File / Load Package...`. Next time I start wxMaxima, I want to open it again. But when I load the file using `File / Open Recent`, it is being opened in the "normal" way, i.e. its entire content is loaded into the window, which makes wxMaxima totally unresponsive because the file is so large.
I think in earlier wxMaxima versions, this didn't happen. `File / Open Recent` seemed to remember how I opened the file previously. It would be nice to get this behavior back.

**Comment by gunterkoenigsmann** [comment]
I never use the "File/Load Package" button. But I will find a solution.

**Comment by TomasRiker** [comment]
Hi!
Thanks for implementing this.
However, there is a bug in the new feature. When loading the package initially using `File / Load Package...`, backslashes are properly converted to forward slashes.
When loading the same package again using the new menu `Load Recent Package`, the path contains backslashes, and loading fails.
