### ISSUE TITLE
No scroll bars in configuration dialog

### ISSUE THREAD

**Issue by guraga** [andrejv/wxmaxima#994]
wxMaxima 18.02.0 in ubuntu 16.04 from ppa http://ppa.launchpad.net/blahota/wxmaxima/ubuntu.

Content of "edit -> configure" dialog partially not visible (so, changing options not possible), and dialog is not resizeable. Please, allow resize dialog and add scroll bars to it.

**Comment by gunterkoenigsmann** [comment]
Seems like my gtk install is still broken so I still cannot compile the wxWidgets samples.

**Comment by gunterkoenigsmann** [comment]
Ok... ...seems like the "enable the scrollbars" command and the "create the dialog" command need to be executed in the Right Order in order to make this work and seems like the global setting is ignored here.

In the nightly build this should finally work now.
