### ISSUE TITLE
Menu cannot be used.

### ISSUE THREAD

**Issue by guraga** [andrejv/wxmaxima#995]
wxMaxima 18.02.0 in ubuntu 16.04 from ppa http://ppa.launchpad.net/blahota/wxmaxima/ubuntu.

Press "alt + f".
Expected behavior: display "file" menu.
Actual behavior: type character "f".

**Comment by gunterkoenigsmann** [comment]
This I can reproduce. Seems like I still have to find out how to make "Alt+e" produce an "€" symbol and still pass the other letters to the menu. And what to do on Alt+F which could be an "open the file menu" and an "đ" on my keyboard...

**Comment by gunterkoenigsmann** [comment]
Forwarded the question to the wx-users group: https://groups.google.com/forum/?fromgroups#!topic/wx-users/aDnWi8U3e6E. Let's hope that they have an answer.
